////////////////////////////////////////////////////////////////////////////
//
// UDP Producer 
// by  Arsenij Vodjanov
//
////////////////////////////////////////////////////////////////////////////

#include "../../C/alisp.h"
#include "../../C/storage.h"

#include "udp_common.h"
#include "udp_producer.h"

#include "udp_streams.h"
#include "udp_hashtab.h"
#include "ddc_cw.h"


// debug output
static int udp_producer_debug = 1;

// logging macros
#define DBG(x) if (udp_producer_debug) udp_log_message x
#define ERR(x) udp_log_error x



////////////////////////////////////////////////////////////////////////////
//
// Registers foreign ALisp functions for Producer manipulation
//
void udp_register_producer_functions(void)
{
  extfunction1("PRODUCER-DEBUG", udp_producer_debugfn);
  extfunction0("PRODUCER-START", udp_producer_startfn);
  extfunction0("PRODUCER-STOP", udp_producer_stopfn);
  extfunction5("PRODUCER-HANDLE-COMMAND", udp_producer_handle_commandfn);
  extfunction2("PRODUCER-SEND-PACKET", udp_producer_send_packetfn);
}
//
////////////////////////////////////////////////////////////////////////////




// Port on which to listen for connections
#define MYPORT 4096

// Producer status values
#define PSTATUS_OFF 0
#define PSTATUS_ON  1

// Client status values
#define CSTATUS_STOPPED 0
#define CSTATUS_RECEIVING 1


////////////////////////////////////////////////////////////////////////////
//
// visualization client descriptor
//
struct udp_client {
  struct udp_client *prev;
  struct udp_client *next;
  int id;                  // id (auto generated by the hashtable functions)

  int key;                 // hash key based on the hostname & port
  int status;              // running or paused?
  char hostname[32];
  int port;

// This is filled in, but not used:
  struct sockaddr_in addr; // resolved host address of the vis-client

// These are not even filled in:
  // parameters that the client has requested so far, decoded from CWs
  float freq;
  float red;               // defines signal bandwidth, BW = fs/(4*2^red)
  float gain;
};

typedef struct udp_client udp_client_t;


////////////////////////////////////////////////////////////////////////////
//
// Some nasty globals
// ------------------
//

// This macro declares a hashtable for udp_client_t * type, and
// functions to access/create/delete elements in the table.
//
// TODO: This must be replaced with a different table implementation,
// because the hashtable created by this macro is not optimized for
// how udp_client_t objects are accessed.
MM_DEF_HASHTABLE( udp_clients,  udp_client_t,  64 )

// Producer status: on/off
//
static int udp_producer_status = PSTATUS_OFF;

// Numeric ID of the udp-stream through which producer talks to clients
//
static int udp_producer_stream_id = -1;

//
// End of nasty globals
//
////////////////////////////////////////////////////////////////////////////




////////////////////////////////////////////////////////////////////////////
//
//
//
//               Internal functions start here
//
//
//
////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////
//
// Resolves canonical hostname:port pair into a socket address struct.
// Used internally by producer to resolve the inet address of a newly
// connecting vis-client.
//
// Returns:
//   On success: 1
//   On failure: 0
//
static int udp_producer_initaddr(char *hostname, int port, struct sockaddr_in *target_addr)
{
  struct hostent *he = gethostbyname(hostname); // returns pointer to static data

  if (he != NULL) {
    target_addr->sin_family = AF_INET;
    target_addr->sin_port = htons(port);
    target_addr->sin_addr = *((struct in_addr *)he->h_addr);
    memset(&(target_addr->sin_zero), '\0', 8);  // zero the rest of the struct
    return 1; // 1-ok
  } else {
    return 0;
  }
}
//
////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////
// simple hash from ip:port to integer
INLINE int make_client_key(char *hostname, int port)
{
  unsigned int k = (unsigned int)port * 7;
  while (*hostname)
    k += (unsigned int)128 * k + (unsigned int)((char)*(hostname++));
  return (int)k;
}



////////////////////////////////////////////////////////////////////////////
// brute-force "find", traverses entire table like a linked list
static udp_client_t * udp_producer_find_client(char *hostname, int port)
{
  int key = make_client_key(hostname, port);
  udp_client_t *client = udp_clients_first_elem();
  int i=0;
  while( i<udp_clients_num_elements && client != NULL ) {
    if (key==client->key)
      return client;
    i++;
    client = udp_clients_next_elem( client );
  }
  return NULL;
}



////////////////////////////////////////////////////////////////////////////
// Adds a new vis-client descriptor to the list/table
static int udp_producer_client_ID( char *hostname, int port )
{
  udp_client_t *client = udp_clients_create_elem();

  if (client==NULL)
    return 0;

  if ( udp_producer_initaddr(hostname, port, 
			     (struct sockaddr_in *)&(client->addr)) == 0) {
    udp_clients_delete_elem( client );
    DBG(("Warning! Vis-client connect attempt canceled: can't resolve client's host\n"));
    return 0; // 0 - ignored
  }

  client->key = make_client_key(hostname, port);
  client->status = CSTATUS_STOPPED;
  strncpy(client->hostname, hostname, 32);
  client->port = port;

  DBG(("UDP Producer: client (%s:%u) identified itself\n", hostname, port));
  return 1; // 1 - handled
}



////////////////////////////////////////////////////////////////////////////
// Enables data streaming to a vis-client
static int udp_producer_client_SA( udp_client_t *client )
{
  client->status = CSTATUS_RECEIVING;
  DBG(("UDP Producer: client asked to start streaming\n"));
  return 1; // 1 - handled
}


////////////////////////////////////////////////////////////////////////////
// Disables data streaming to a vis-client
static int udp_producer_client_SC( udp_client_t *client )
{
  client->status = CSTATUS_STOPPED;
  DBG(("UDP Producer: client asked to stop streaming\n"));
  return 1; // 1 - handled
}


// NOTE: This function is not used now.  
//       All MS packets are forwarded to radio 'as is'
////////////////////////////////////////////////////////////////////////////
// Attempts by vis-clients to set mixer register are ignored,
//
// TODO: extract the parameters that the vis-client was trying to set
static int udp_producer_client_MS( udp_client_t *client, ddc_cw_t *cw )
{
  DBG(("UDP Producer: client asked to set mixer reg: ignoring command\n"));
  return 0; // 0 - ignored
}




////////////////////////////////////////////////////////////////////////////
//
//
//
//               Lisp interface functions start here
//
//
//
////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////
// enable/disable debug print-outs
//
// Returns: 
//
//   On debug printing enabled: 1
//   On disabled: 0
//
oidtype udp_producer_debugfn(bindtype env, oidtype toggle)
{
  int iToggle;
  DBG(("%s()\n", __FUNCTION__));
  IntoInteger(toggle, iToggle, env);
  udp_producer_debug = (iToggle>0);
  return mkinteger(iToggle);
}
//
////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////
// Get ready to produce radio streams
//
// Returns: 
//
//   On success:  id number of the producer's udp-stream 
//   On failure:  nil
//
oidtype udp_producer_startfn(bindtype env)
{
  DBG(("%s()\n", __FUNCTION__));

  if (udp_producer_status == PSTATUS_ON) {
    DBG(("Producer already started!\n"));
    return nil;
  }

  // Create a read/write udp stream listening on port MYPORT
  udp_producer_stream_id = udp_stream_open( MYPORT, "", 0, 1, 1 );

  if (udp_producer_stream_id != -1) {
    udp_producer_status = PSTATUS_ON;
    return mkinteger(udp_producer_stream_id);
  } 

  // errors
  return nil;
}
//
////////////////////////////////////////////////////////////////////////////




////////////////////////////////////////////////////////////////////////////
// Stop streaming udp data, delete info about all connected vis-clients
//
// Returns: 
//
//   On success: Number of clients with unique hosts that have been
//                "served" during the session
//
//   On failure: nil
//
oidtype udp_producer_stopfn(bindtype env)
{
  udp_client_t *client;
  int i=0;

  DBG(("%s()\n", __FUNCTION__));
  if (udp_producer_status == PSTATUS_OFF) {
    DBG(("Producer not started!\n"));
    return nil;
  }

  // Close down udp stream
  udp_stream_close( udp_producer_stream_id );
  udp_producer_stream_id = -1;
  udp_producer_status = PSTATUS_OFF;

  // Delete all client infos
  client = udp_clients_first_elem();
  while( i<udp_clients_num_elements && client != NULL ) {
    udp_client_t *next = udp_clients_next_elem( client );
    udp_clients_delete_elem( client );
    client = next;
    i++;
  }

  return mkinteger(i);
}
//
////////////////////////////////////////////////////////////////////////////




////////////////////////////////////////////////////////////////////////////
//
// Handles and dispatches a command from a vis-client.
//
// Returns:
//
//   On success:  1      (command valid & handled)
//                0      (command valid, but ignored)
//
//   On error:    nil    (invalid command)
oidtype udp_producer_handle_commandfn( bindtype env,
				       oidtype host,
				       oidtype port,
				       oidtype data,
				       oidtype datasize,
                                       oidtype rstreamid )
{
  udp_client_t *client = NULL;
  udp_cwpacket_t *cwp;
  char *pHost = NULL;
  int iPort, iDatasize, iRSID, res = -1;

  DBG(("%s()\n", __FUNCTION__));
  if (udp_producer_status==PSTATUS_OFF) {
    DBG(("%s: udp producer is not started!\n", __FUNCTION__));
    return nil;
  }

  // Check arguments
  IntoString(host, pHost, env);
  IntoInteger(port, iPort, env);
  OfType(data, BINARYTYPE, env);
  IntoInteger( datasize, iDatasize, env );
  IntoInteger( rstreamid, iRSID, env );

  cwp = (udp_cwpacket_t *)&(dr(data,binarycell)->cont);
  if (!cwp) return lerror( ILLEGAL_ARGUMENT, data, env );

  // If this client has already identified itself with us, we already have its
  // descriptor in our table.  Find descriptor by client's ip:port
  client = udp_producer_find_client( pHost, iPort );

  // Determine what kind of command this is.
  
  // Identify user?
  if (cwp->type[0]=='I' && cwp->type[1]=='D') {

    // Only bother to add this new client if this is the first time it
    // tries to ident itself.
    if (client==NULL)
      res = udp_producer_client_ID( pHost, iPort );
    else
      res = 0;

    return mkinteger(res);
  } 

  // At this point, if we don't have a client descriptor, then we
  // ignore the command packet.  Clients must always ident themselves.
  if (client==NULL)
    return nil;

  // Ok, client had identified itself before.

  // Start or stop streaming?
  if (cwp->type[0]=='S') {
    if (cwp->type[1]=='A') {
      // 'SA' == start
      res = udp_producer_client_SA( client );
    } else if (cwp->type[1]=='C') {
      // 'SC' == stop
      res = udp_producer_client_SC( client );
    }
  }

  // Mixer-register setting?
  if (cwp->type[0]=='M') {
    if (cwp->type[1]=='S') {

      // res = udp_producer_client_MS( client, &(cwp->cw) );

      // Quick fix to allow *ALL* clients to configure radio
      // settings.
      // TODO: user hierarchy, low rank user can't change higher rank
      // user's settings

      udp_stream_put( iRSID, (char *) cwp, sizeof(udp_cwpacket_t) );
      res = 1;
      // end of quick and dirty fix
    }
  }

  return (res==-1) ? nil : mkinteger(res);
}



////////////////////////////////////////////////////////////////////////////
// 
// Sends udp radio packet to all connected (i.e. clients that have
// identified themselves & requested that streaming starts)
// visualization clients.  Current implementation uses high-level
// udp-streams functions, which is relatively slow.
//
// TODO: The obvious optimization is to obtain a (struct sockaddr*)
// for each vis-client at connection & identification time, and then
// use the low-level internal function udp_stream_senddata_to()
// directly.  That way we wouldn't need to manually "redirect" the udp
// stream and only need to resolve the vis-client address once.
//
oidtype udp_producer_send_packetfn( bindtype env,
				    oidtype data,
				    oidtype datasize)
{
  udp_client_t *client;
  int iDatasize, i=0;
  char *pData;

  //  DBG(("%s()\n", __FUNCTION__));
  if (udp_producer_status==PSTATUS_OFF) {
    DBG(("%s: udp producer is not started!\n", __FUNCTION__));
    return nil;
  }

  OfType(data, BINARYTYPE, env);
  IntoInteger( datasize, iDatasize, env );

  // get pointer to data
  pData = (char *)&(dr(data,binarycell)->cont);
  if (!pData) return lerror( ILLEGAL_ARGUMENT, data, env );

  // Dispatch to every client using the same UDP stream
  client = udp_clients_first_elem();

  while( i<udp_clients_num_elements && client != NULL ) {

    int res = 0;
    if ( client->status == CSTATUS_RECEIVING ) {
      if (udp_stream_redirect( udp_producer_stream_id, client->hostname, client->port )) {
	if (udp_stream_put( udp_producer_stream_id, pData, iDatasize ))
	  res = 1;
      }
    }

    client = udp_clients_next_elem( client );
    i++;
  }

  return nil;
}

