////////////////////////////////////////////////////////////////////////////
//
// UDP Producer for "house keeping" status stream
// by  Arsenij Vodjanov
//
////////////////////////////////////////////////////////////////////////////

#include "../../C/alisp.h"
#include "../../C/storage.h"

#include "udp_common.h"
#include "udp_housekeep.h"

#include "udp_streams.h"
#include "udp_hashtab.h"
#include "ddc_cw.h"
#include "udp_hk_packet.h"

// debug output
static int udp_housekeep_debug = 1;

// logging macros
#define DBG(x) if (udp_housekeep_debug) udp_log_message x
#define ERR(x) udp_log_error x



////////////////////////////////////////////////////////////////////////////
//
// Registers foreign ALisp functions for Housekeep manipulation
//
void udp_register_housekeep_functions(void)
{
  extfunction1("HOUSEKEEP-DEBUG", udp_housekeep_debugfn);
  extfunction0("HOUSEKEEP-START", udp_housekeep_startfn);
  extfunction0("HOUSEKEEP-STOP", udp_housekeep_stopfn);
  extfunction4("HOUSEKEEP-HANDLE-COMMAND", udp_housekeep_handle_commandfn);
  extfunction2("HOUSEKEEP-SEND-PACKET", udp_housekeep_send_packetfn);
}
//
////////////////////////////////////////////////////////////////////////////


// Port on which to listen for connections
#define MYPORT 4097
#define UDP_HKP_QUEUE_SIZE 64

// Housekeep status values
#define PSTATUS_OFF 0
#define PSTATUS_ON  1

// Client status values
#define CSTATUS_STOPPED 0
#define CSTATUS_RECEIVING 1


////////////////////////////////////////////////////////////////////////////
//
// visualization client descriptor
//
struct udp_hk_client {
  struct udp_hk_client *prev;
  struct udp_hk_client *next;
  int id;                  // id (auto generated by the hashtable functions)

  int key;                 // hash key based on the hostname & port
  int status;              // running or paused?
  char hostname[32];
  int port;

  // This is filled in, but not used:
  struct sockaddr_in addr; // resolved host address of the vis-client

  // Client-requested options
  // Flags
  unsigned int si_autosend  : 1;    // 1 = always send serverinfo packets automatically (at si_rate)
  unsigned int ts_autosend  : 1;    // 1 = always send timestamp packets automatically (at ts_rate)
  unsigned int si_onchange  : 1;    // 1 = send serverinfo when radio settings (freq, bw) change
  unsigned int reserved     : 5;
  // Rates:  once for every 2^rate radio-packets
  unsigned long si_rate;            // serverinfo packets rate (autosend_si must be set)
  unsigned long ts_rate;            // timestamp packets rate (autosend_ts must be set)

  // Fail-safe packet delivery: important packets are queued and
  // re-sent until delivery has been confirmed or UDP_MAX_RETRIES
  // exceeded.  If the outgoing queue becomes full, client is
  // disconnected (flow control would be useful here)
  udp_hk_packet_t hkp_queue[UDP_HKP_QUEUE_SIZE]; // outgoing packets FIFO queue
  unsigned short qhead; // first element to send
  unsigned short qtail; // first free location where to store a new queued packet
};

typedef struct udp_hk_client udp_hk_client_t;


////////////////////////////////////////////////////////////////////////////
//
// Some nasty globals
// ------------------
//

// This macro declares a hashtable for udp_hk_client_t * type, and
// functions to access/create/delete elements in the table.
//
// TODO: This should be replaced with a different table implementation,
// because the hashtable created by this macro is not optimized for
// how udp_hk_client_t objects are accessed.
MM_DEF_HASHTABLE( udp_hk_clients,  udp_hk_client_t,  128 )

// Housekeeper status: on/off
//
static int udp_housekeep_status = PSTATUS_OFF;

// Numeric ID of the udp-stream through which housekeeper talks to clients
//
static int udp_housekeep_stream_id = -1;

//
// End of nasty globals
//
////////////////////////////////////////////////////////////////////////////




////////////////////////////////////////////////////////////////////////////
//
//
//
//               Internal functions start here
//
//
//
////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////
//
// Resolves canonical hostname:port pair into a socket address struct.
// Used internally by housekeep to resolve the inet address of a newly
// connecting client.
//
// Returns:
//   On success: 1
//   On failure: 0
//
static int udp_housekeep_initaddr(char *hostname, int port, struct sockaddr_in *target_addr)
{
  struct hostent *he = gethostbyname(hostname); // returns pointer to static data

  if (he != NULL) {
    target_addr->sin_family = AF_INET;
    target_addr->sin_port = htons(port);
    target_addr->sin_addr = *((struct in_addr *)he->h_addr);
    memset(&(target_addr->sin_zero), '\0', 8);  // zero the rest of the struct
    return 1; // 1-ok
  } else {
    return 0;
  }
}
//
////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////
// simple hash from ip:port to integer
inline int make_hk_client_key(char *hostname, int port)
{
  unsigned int k = (unsigned int)port * 7;
  while (*hostname)
    k += (unsigned int)128 * k + (unsigned int)((char)*(hostname++));
  return (int)k;
}



////////////////////////////////////////////////////////////////////////////
// brute-force "find", traverses entire table like a linked list
static udp_hk_client_t * udp_housekeep_find_client(char *hostname, int port)
{
  int key = make_hk_client_key(hostname, port);
  udp_hk_client_t *client = udp_hk_clients_first_elem();
  int i=0;
  while( i<udp_hk_clients_num_elements && client != NULL ) {
    if (key==client->key)
      return client;
    i++;
    client = udp_hk_clients_next_elem( client );
  }
  return NULL;
}



////////////////////////////////////////////////////////////////////////////
// Handle client ID command.
// Creates a new client descriptor.
//
static int udp_housekeep_client_ID( char *hostname, int port )
{
  udp_hk_client_t *client = udp_hk_clients_create_elem();

  if (client==NULL)
    return 0;

  if ( udp_housekeep_initaddr(hostname, port, 
			     (struct sockaddr_in *)&(client->addr)) == 0) {
    udp_hk_clients_delete_elem( client );
    DBG(("Warning! Client connect attempt canceled: can't resolve client's host\n"));
    return 0; // 0 - ignored
  }

  client->key = make_client_key(hostname, port);
  client->status = CSTATUS_STOPPED;
  strncpy(client->hostname, hostname, 32);
  client->port = port;

  DBG(("UDP Housekeep: client (%s:%u) identified itself\n", hostname, port));
  return 1; // 1 - handled
}



////////////////////////////////////////////////////////////////////////////
// Handle Client Options command
// This sets streaming options and enables/disables several streams at once.
//
static int udp_housekeep_client_CO( udp_hk_client_t *client, hkp_clientopt_t *opt )
{
  client->status = CSTATUS_RECEIVING;
  DBG(("UDP Housekeep: client (%s:%i) sets options\n", client->hostname, client->port));
  return 1; // 1 - handled
}



////////////////////////////////////////////////////////////////////////////
//
//
//
//               Lisp interface functions start here
//
//
//
////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////
// enable/disable debug print-outs
//
// Returns: 
//
//   On debug printing enabled: 1
//   On disabled: 0
//
oidtype udp_housekeep_debugfn(bindtype env, oidtype toggle)
{
  int iToggle;
  DBG(("%s()\n", __FUNCTION__));
  IntoInteger(toggle, iToggle, env);
  udp_housekeep_debug = (iToggle>0);
  return mkinteger(iToggle);
}
//
////////////////////////////////////////////////////////////////////////////



////////////////////////////////////////////////////////////////////////////
// Get ready to produce housekeeping packets (opens new UDP stream)
//
// Returns: 
//
//   On success:  id number of the housekeep's udp-stream 
//   On failure:  nil
//
oidtype udp_housekeep_startfn(bindtype env)
{
  DBG(("%s()\n", __FUNCTION__));

  if (udp_housekeep_status == PSTATUS_ON) {
    ERR(("%s(): Housekeep already started\n", __FUNCTION__));
    return nil;
  }

  // Create a read/write udp stream listening on port MYPORT
  udp_housekeep_stream_id = udp_stream_open( MYPORT, "", 0, 1, 1 );

  if (udp_housekeep_stream_id != -1) {
    udp_housekeep_status = PSTATUS_ON;
    return mkinteger(udp_housekeep_stream_id);
  } 

  // errors
  return nil;
}
//
////////////////////////////////////////////////////////////////////////////




////////////////////////////////////////////////////////////////////////////
// Stop streaming udp data, delete info about all connected vis-clients
//
// Returns: 
//
//   On success: Number of clients with unique hosts that have been
//                "served" during the session
//
//   On failure: nil
//
oidtype udp_housekeep_stopfn(bindtype env)
{
  udp_hk_client_t *client;
  int i=0;

  DBG(("%s()\n", __FUNCTION__));
  if (udp_housekeep_status == PSTATUS_OFF) {
    ERR(("%s(): Housekeep not running\n", __FUNCTION__));
    return nil;
  }

  // Remove clients
  client = udp_hk_clients_first_elem();
  while( i<udp_hk_clients_num_elements && client != NULL ) {
    udp_hk_client_t *next = udp_hk_clients_next_elem( client );

    // Send 'end session' packet

    udp_hk_clients_delete_elem( client );
    client = next;
    i++;
  }

  // Close down udp stream
  udp_stream_close( udp_housekeep_stream_id );
  udp_housekeep_stream_id = -1;
  udp_housekeep_status = PSTATUS_OFF;

  return mkinteger(i);
}
//
////////////////////////////////////////////////////////////////////////////




////////////////////////////////////////////////////////////////////////////
//
// Handles and dispatches a command from a client.
//
// Returns:
//
//   On success:  1      (command valid & handled)
//                0      (command valid, but ignored)
//
//   On error:    nil    (invalid command)
oidtype udp_housekeep_handle_commandfn( bindtype env,
					oidtype host,
					oidtype port,
					oidtype data,
					oidtype datasize )
{
  udp_hk_client_t *client = NULL;
  udp_hk_packet_t *hkp;
  char *pHost = NULL;
  int iPort, iDatasize, res = -1;

  DBG(("%s()\n", __FUNCTION__));
  if (udp_housekeep_status==PSTATUS_OFF) {
    DBG(("%s: udp housekeeping service is not started!\n", __FUNCTION__));
    return nil;
  }

  // Check arguments
  IntoString(host, pHost, env);
  IntoInteger(port, iPort, env);
  OfType(data, BINARYTYPE, env);
  IntoInteger( datasize, iDatasize, env );

  hkp = (udp_hk_packet_t *)&(dr(data,binarycell)->cont);
  if (!hkp) return lerror( ILLEGAL_ARGUMENT, data, env );


  // Determine what kind of command this is.
  
  // Identify 
  // If duplicate ID messagess are received, we respond 
  // to each message anyway with the client's ID.
  if (hkp->type[0]=='I' && hkp->type[1]=='D') {
    res = udp_housekeep_client_ID( pHost, iPort );  
    return mkinteger(res);
  } 

  // If this client has identified itself with us, we have its
  // descriptor in our table.  Find descriptor by client's ip:port
  client = udp_housekeep_find_client( pHost, iPort );

  // At this point, if we don't have a client descriptor, then we
  // ignore the command packet.  Clients must always ident themselves.
  if (client==NULL)
    return nil;

  // Ok, client had identified itself before.

  // Client options
  if (hkp->type[0]=='C') {
    if (hkp->type[1]=='O') {
      // 'CO' == client options
      // res = udp_housekeep_client_CO( client );
    }
  }

  if (hkp->type[0]=='A') {
    if (hkp->type[1]=='C') {
      // 'AC' == acknowledge 
      // res = udp_housekeep_client_CO( client,  );
    }
  }

  

  return (res==-1) ? nil : mkinteger(res);
}



////////////////////////////////////////////////////////////////////////////
// 
// Sends udp radio packet to all connected clients (i.e. clients that
// have identified themselves & requested that streaming starts).
// Current implementation uses high-level udp-streams functions, which
// is relatively slow.
//
// TODO: The obvious optimization is to obtain a (struct sockaddr*)
// for each vis-client at connection & identification time, and then
// use the low-level internal function udp_stream_senddata_to()
// directly.  That way we wouldn't need to manually "redirect" the udp
// stream and only need to resolve the vis-client address once.
//
oidtype udp_housekeep_send_packetfn( bindtype env,
				     oidtype data,
				     oidtype datasize)
{
  udp_hk_client_t *client;
  int iDatasize, i=0;
  char *pData;

  //  DBG(("%s()\n", __FUNCTION__));
  if (udp_housekeep_status==PSTATUS_OFF) {
    DBG(("%s: udp housekeep is not started!\n", __FUNCTION__));
    return nil;
  }

  OfType(data, BINARYTYPE, env);
  IntoInteger( datasize, iDatasize, env );

  // get pointer to data
  pData = (char *)&(dr(data,binarycell)->cont);
  if (!pData) return lerror( ILLEGAL_ARGUMENT, data, env );

  // Dispatch to every client using the same UDP stream
  client = udp_hk_clients_first_elem();

  while( i<udp_hk_clients_num_elements && client != NULL ) {

    int res = 0;
    if ( client->status == CSTATUS_RECEIVING ) {
      if (udp_stream_redirect( udp_housekeep_stream_id, client->hostname, client->port )) {
	if (udp_stream_put( udp_housekeep_stream_id, pData, iDatasize ))
	  res = 1;
      }
    }

    client = udp_hk_clients_next_elem( client );
    i++;
  }

  return nil;
}

