/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class callin_Connection */

#ifndef _Included_callin_Connection
#define _Included_callin_Connection
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     callin_Connection
 * Method:    AmosError
 * Signature: (ILjava/lang/String;Lcallin/Oid;)V
 */
JNIEXPORT void JNICALL Java_callin_Connection_AmosError
  (JNIEnv *, jclass, jint, jstring, jobject);

/*
 * Class:     callin_Connection
 * Method:    initializeAmos0
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_callin_Connection_initializeAmos0
  (JNIEnv *, jclass, jstring);

/*
 * Class:     callin_Connection
 * Method:    amosInit
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_callin_Connection_amosInit
  (JNIEnv *, jclass, jstring, jobjectArray);
 
/*
 * Class:     callin_Connection
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Connection_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     callin_Connection
 * Method:    initJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Connection_initJava
  (JNIEnv *, jobject);

/*
 * Class:     callin_Connection
 * Method:    execute
 * Signature: (Ljava/lang/String;)Lcallin/Scan;
 */
JNIEXPORT jobject JNICALL Java_callin_Connection_execute__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     callin_Connection
 * Method:    execute
 * Signature: (Ljava/lang/String;I)Lcallin/Scan;
 */
JNIEXPORT jobject JNICALL Java_callin_Connection_execute__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     callin_Connection
 * Method:    execute_custom
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lcallin/Scan;
 */
JNIEXPORT jobject JNICALL Java_callin_Connection_executeCustom
  (JNIEnv *, jobject , jstring, jstring);

/*
 * Class:     callin_Connection
 * Method:    amosTopLoop
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_callin_Connection_amosTopLoop
  (JNIEnv *, jobject, jstring);

/*
 * Class:     callin_Connection
 * Method:    openScan
 * Signature: ()Lcallin/Scan;
 */
JNIEXPORT jobject JNICALL Java_callin_Connection_openScan
  (JNIEnv *, jobject);

/*
 * Class:     callin_Connection
 * Method:    commit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Connection_commit
  (JNIEnv *, jobject);

/*
 * Class:     callin_Connection
 * Method:    rollback
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Connection_rollback
  (JNIEnv *, jobject);

/*
 * Class:     callin_Connection
 * Method:    getFunctionInternal
 * Signature: (Ljava/lang/String;)Lcallin/Oid;
 */
JNIEXPORT jobject JNICALL Java_callin_Connection_getFunctionInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     callin_Connection
 * Method:    callFunction
 * Signature: (Lcallin/Oid;Lcallin/Tuple;)Lcallin/Scan;
 */
JNIEXPORT jobject JNICALL Java_callin_Connection_callFunction__Lcallin_Oid_2Lcallin_Tuple_2
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     callin_Connection
 * Method:    callFunction
 * Signature: (Lcallin/Oid;Lcallin/Tuple;I)Lcallin/Scan;
 */
JNIEXPORT jobject JNICALL Java_callin_Connection_callFunction__Lcallin_Oid_2Lcallin_Tuple_2I
  (JNIEnv *, jobject, jobject, jobject, jint);

/*
 * Class:     callin_Connection
 * Method:    callFunction_custom
 * Signature: (Lcallin/Oid;Lcallin/Tuple;Ljava/lang/string;)Lcallin/Scan;
 */
JNIEXPORT jobject JNICALL Java_callin_Connection_callFunctionCustom
(JNIEnv *, jobject, jobject, jobject, jstring);

/*
 * Class:     callin_Connection
 * Method:    createObject
 * Signature: (Lcallin/Oid;)Lcallin/Oid;
 */
JNIEXPORT jobject JNICALL Java_callin_Connection_createObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     callin_Connection
 * Method:    getType
 * Signature: (Ljava/lang/String;)Lcallin/Oid;
 */
JNIEXPORT jobject JNICALL Java_callin_Connection_getType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     callin_Connection
 * Method:    deleteObject
 * Signature: (Lcallin/Oid;)V
 */
JNIEXPORT void JNICALL Java_callin_Connection_deleteObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     callin_Connection
 * Method:    setFunction
 * Signature: (Lcallin/Oid;Lcallin/Tuple;Lcallin/Tuple;)V
 */
JNIEXPORT void JNICALL Java_callin_Connection_setFunction
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     callin_Connection
 * Method:    addFunction
 * Signature: (Lcallin/Oid;Lcallin/Tuple;Lcallin/Tuple;)V
 */
JNIEXPORT void JNICALL Java_callin_Connection_addFunction
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     callin_Connection
 * Method:    remFunction
 * Signature: (Lcallin/Oid;Lcallin/Tuple;Lcallin/Tuple;)V
 */
JNIEXPORT void JNICALL Java_callin_Connection_remFunction
  (JNIEnv *, jobject, jobject, jobject, jobject);

/*
 * Class:     callin_Connection
 * Method:    getObjectNumbered
 * Signature: (I)Lcallin/Oid;
 */
JNIEXPORT jobject JNICALL Java_callin_Connection_getObjectNumbered
  (JNIEnv *, jobject, jint);

/*
 * Class:     callin_Connection
 * Method:    printErrForm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Connection_printErrForm
  (JNIEnv *, jobject);

/*
 * Class:     callin_Connection
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_callin_Connection_init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     callin_Connection
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Connection_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
