/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class callin_Oid */

#ifndef _Included_callin_Oid
#define _Included_callin_Oid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     callin_Oid
 * Method:    getType
 * Signature: ()Lcallin/Oid;
 */
JNIEXPORT jobject JNICALL Java_callin_Oid_getType
  (JNIEnv *, jobject);

/*
 * Class:     callin_Oid
 * Method:    getID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_callin_Oid_getID
  (JNIEnv *, jobject);

/*
 * Class:     callin_Oid
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Oid_print
  (JNIEnv *, jobject);

/*
 * Class:     callin_Oid
 * Method:    deleteObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Oid_delete
  (JNIEnv *, jobject);

/*
 * Class:     callin_Oid
 * Method:    init
 * Signature: (Lcallin/Oid;)V
 */
JNIEXPORT void JNICALL Java_callin_Oid_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     callin_Oid
 * Method:    toAmosString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_callin_Oid_toAmosString
  (JNIEnv *, jobject);

  /*
 * Class:     callin_Oid
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Oid_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
