/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class callin_Scan */

#ifndef _Included_callin_Scan
#define _Included_callin_Scan
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     callin_Scan
 * Method:    getRow
 * Signature: ()Lcallin/Tuple;
 */
JNIEXPORT jobject JNICALL Java_callin_Scan_getRow__
  (JNIEnv *, jobject);

/*
 * Class:     callin_Scan
 * Method:    getRow
 * Signature: (Lcallin/Tuple;)V
 */
JNIEXPORT void JNICALL Java_callin_Scan_getRow__Lcallin_Tuple_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     callin_Scan
 * Method:    nextRow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Scan_nextRow
  (JNIEnv *, jobject);

/*
 * Class:     callin_Scan
 * Method:    eos
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_callin_Scan_eos
  (JNIEnv *, jobject);

/*
 * Class:     callin_Scan
 * Method:    closeScan
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Scan_closeScan
  (JNIEnv *, jobject);

/*
 * Class:     callin_Scan
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_callin_Scan_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
