package callout;

/**
  * This class is used for throwing a very special type of "exception". It is
  * used to jump out of a foreign function when the system doesn't want more
  * data. For example: The query notany(jsqrt(2.0)); This query asks if there
  * isn't any elements in the set of values generated by the jsqrt(2.0) foreign
  * function. This set has two elements, so when the system finds the first
  * element it already knows the value of the whole query, so there is no need
  * to calculate the second element. This is where the NoMoreData-"exception" is
  * used. The C-code throws this "exception" causing the Java foreign-function
  * to stop executing and return control to the system. The user is can catch
  * this exception and do some cleanup if needed. This exception is not required
  * to be declared or caught in foreign functions.
  *
  * @author Daniel Elin
  * @version 1.1 (Last modified 990506)
  */
public class NoMoreData extends RuntimeException {

  NoMoreData() {
    super();
  }

  NoMoreData(String s) {
    super(s);
  }

  // No members or methods.

}
