ArchiveType=2
OutputFile=E:\\AmosNT\\bin\\javaamos.jar
ManifestFile=<auto generate>
ExtractManifest=false
DisabledNodeKeys=1
DisabledNodes0=file:///E:\\AmosNT\\Java\\Goovi\\delete.gif;
ExtraClassKeys=0
ExtraFileKeys=0
ExcludedDirKeys=0
ExcludedClassKeys=0
ExcludedFileKeys=0
