;;; ============================================================
;;; AMOS2
;;; 
;;; Author: (c) <year>2012  <author>Minpeng Zhu, Tore Risch UDBL
;;; $RCSfile: absorbmng.lsp,v $
;;; $Revision: 1.17 $ $Date: 2013/06/05 11:38:27 $
;;; $State: Exp $ $Locker:  $
;;;
;;; Description: The absorber manager takes the Datalog query and, 
;;; for each source predicate referenced in the query, calls the 
;;; corresponding absorber of its wrapper.
;;; =============================================================

(defvar *absorbedpreds* nil "list of abosorbed predicates")

(defvar *allSPsvarlist* nil "list of all source predicates variables")

(defun absorber-rewrite-block (pred)
  "Run the absorber on a query block generated by AND-BLOCKS"
  (selectq (car pred)
	   (and (absorber-rewritel 'and (cdr pred)))
	   (optional (absorber-rewritel 'optional (cdr pred)))
	   (error "Not a predicate block" pred)))

(defun absorber-rewritel (tag predl)
  "Heling function to ABSORBER-REWRITE-BLOCK"
  (cons tag (absorb-predicates 
	     (mapcar (f/l (pred)
			  (if (compound-p pred)(absorber-rewrite pred)
			    pred))
		     predl))))

(defun absorber-rewrite (pred) 
  "Run the absorber on an aritrary predicate"
  (cond ((osql-variablep pred) pred)
	((osql-constantp pred) pred) 
        ((compound-p pred)
         (selectq (car pred)
		  ((and optional)
		   (let ((bdy (andify 
			       (mapcar (f/l (p) (absorber-rewrite-block p))
				       (and-blocks (cdr pred))))))
                     (cons (car pred)(argsof 'and bdy))))
		  (or (orify (mapcar (function absorber-rewrite) (cdr pred))))
		  (error "Cannot absorb compund predicate" pred)))
        (t (andify (absorb-predicates (list pred))))))

(defun wrapper-of (dsinst)
  "get the wrapper of a data source instance"
  (let ((w (arg-type dsinst)))
    (cond ((osql-subtypep w _datasource_) w)
	  (t (error "Not a data source" dsinst)))))

(defun sourcepred? (pred)
  (if (leaf-predicate-p pred)
      (getobject (car pred) 'cclusterfct?)))

(defun datasource-of (pred)
  "get datasource from a source predicate"
  (if (sourcepred? pred)
      (let ((dsinst (getfunction 'datasource (list (car pred))))
	    )
	(cond ((eq (length dsinst) 1);;just one dsinst
	       (caar dsinst));;return the only dsinst
	      ((> (length dsinst) 1);;more than one dsinst
	       (mapcar (f/l (dsinstl) (car dsinstl)) dsinst)))))
  )

(defun get-absorber (dsinst)
  "dsinst can be a single datasource instance and can be a list of datasource
   instances (e.g in multisql) and this function gets wrapper's absorber"
  (if dsinst
      (cond ((consp dsinst);;list of dsinsts, get first dsinst's absorber
	     (mksymbol (caar (getfunction 'get_absorber 
				   (list (wrapper-of (car dsinst)))))))
	    (t;;just one dsinst
	     (mksymbol (caar (getfunction 'get_absorber 
					  (list (wrapper-of dsinst)))))))))

(defun get-finalizer2 (dsinst)
  "get wrapper's finalizer"
  (if dsinst
      (cond ((consp dsinst);;list of dsinsts, get first dsinst's absorber
	     (mksymbol (caar (getfunction 'get_finalizer
				   (list (wrapper-of (car dsinst)))))))
	    (t;;just one dsinst
	     (mksymbol (caar (getfunction 'get_finalizer
					  (list (wrapper-of dsinst)))))))))

(defun absorb-predicates (l)
  "go through conjunction L and absorb the possible predicates
   for source predicates" 
  (let ((changed t)
	(*absorbedpreds* nil)
	(*allSPsvarlist* (allsp-varlist l))
	)
    (while changed
      (setq changed nil)
      (dolist (pred l)
	(let* ((dsinst (datasource-of pred));;only source predicate has dsinst
	       (absorber (get-absorber dsinst));;wrapper's absorber
	       )
	  (if absorber
	      (let ((finalizer (get-finalizer2 dsinst))
		    absorbedpredl accessfilter genexpression newrest res
		    accessfiltervarlist transformed varpredassnlst)
		(setq res (funcall absorber pred (remove pred l)))
		(setq absorbedpredl (absorberresult-absorbedpreds res))
		;;remove preds in *absorbedpreds* after absorbation is done
		(setq *absorbedpreds* (append *absorbedpreds* absorbedpredl))
		(setq newrest (absorberresult-newrest res))
		(setq genexpression (make-expression 
				     absorbedpredl;;filter
				     dsinst;;data source instance
				     finalizer;;finalizer to finalize filter
				     ))
		(setq accessfiltervarlist 
		      (absorberresult-accessfiltervarlist res))
		;;create access filter
		(setq accessfilter (gen-accessfilter genexpression 
						     accessfiltervarlist))
		(setq transformed (cons accessfilter newrest))
		(cond ((null transformed))
		      (t (setq changed t) 
			 (setq l transformed)
			 (return nil)))))))) 
    ;;after absorbation, l is a collection of access filter pred and non SP 
    ;;preds, remove absorbed non SP preds in *absorbedpreds* after 
    ;;absorbation is done
    (if *absorbedpreds*
	(remove-absorbedpreds *absorbedpreds* l)
      l)
    ))

(defun remove-absorbedpreds (absorbedPreds l)
  "remove the absorbed predicates before heading to the optimizer"
  (let ((newlist l))
    (mapc (f/l (pred)
	       (if (member pred newlist)
		   (setq newlist (remove pred newlist))))
	  (unique absorbedPreds))
    newlist))