#Load Turtle file with data:
load('talk.ttl');

#URI prefix used during session:
prefix : <http://udbl.uu.se/pop#>;

#Select array element:
SELECT (?a[1,1] AS ?res)
 WHERE { ?g :pop ?a .
         ?g :species "A" };

#Select array element using SPARQL collections:
SELECT ?elt11
 WHERE { ?g :pop ?a .
         ?g :species "A" .
         ?a rdf:rest ?t1 .
         ?t1 rdf:first ?t2 .
         ?t2 rdf:rest ?t3 .
         ?t3 rdf:first ?elt11 };

#Select array slice:
SELECT (?a[:,1:3] AS ?res)
 WHERE { ?g :pop ?a .
         ?g :species "A" };

#Select first row in matrix:
SELECT ?res
 WHERE { ?g :pop ?a .
         ?g :species "A" .
         ?a rdf:first ?res };

#Select rows in matrix excluding the first one:
SELECT ?res
 WHERE { ?g :pop ?a .
         ?g :species "A" .
         ?a rdf:rest ?res };

#Select transposed matrix:
SELECT (permute(?a,1,0) AS ?res)
 WHERE { ?g :pop ?a .
         ?g :species "A" };

#Select average value of every second column, together with column index:
SELECT (?i*2 AS ?idx)
       (mean(?a[:,::2][:,?i]) AS ?avg)
 WHERE { ?g :pop ?a .
         ?g :species "A" };

#Select average value of the array:
SELECT (mean(?a) AS ?res)
 WHERE { ?g :pop ?a .
         ?g :species "A" };

#Select array of average values (aggregation across several arrays):
SELECT (AVG(?a) AS ?res)
 WHERE { ?g :pop ?a };

SELECT (sum(mean(?a)) as ?res)
 WHERE { ?g :pop ?a };

SELECT (mean(?a) as ?res)
 WHERE { ?g :pop ?a };

#Define functional view of total population per species type:
DEFINE FUNCTION totalPop(?species) AS
SELECT (array_sum(?a) AS ?res)
WHERE { ?g :pop ?a .
        ?g :species ?species };

#Using the view for species "A":
totalPop("A");

#The remaining statements require the Python engine. See readme.txt!

#Define and test foreign function calling built-in Python function:
DEFINE FUNCTION abs(?a) 
 AS PYTHON 'abs';

abs(-1.5);

#Define and test user-defined foreign function in Python:
DEFINE FUNCTION pyplus(?a ?b) 
 AS PYTHON 'foreign.plus';

pyplus(1,2);

#Define and test foreign aggregate function in Python:
DEFINE AGGREGATE pysum(?b) 
 AS PYTHON 'foreign.mysum';

SELECT (pysum(mean(?a)) as ?res)
 WHERE { ?g :pop ?a };
