;;; SLR1-parser generated by GRM Parser Builder
;;; (C) 2001-2010, Andrej Andrejev

;;; INPUT-FN is a function returning (terminal . value) pairs
;;; or NIL when input is exhausted

(defun slr1-parser (input-fn)
  (let ((stack '((^))) ; contains pairs (key . value), ^ is bottom-marker
        (input (funcall input-fn)) (delayed-input nil))
    (labels ((shift (key) ; SHIFT op
               (push (cons key (cdr input)) stack) ; push new key with input value
               (if delayed-input (progn (setq input delayed-input)
                                        (setq delayed-input nil)) ; restore input after REDUCE
                 (setq input (funcall input-fn)))) ; feed input
             (reduce (n) ; REDUCE op: returns list of n top values from stack
               (let ((values nil))
                 (dotimes (i n) (push (cdr (pop stack)) values))
                 (setq delayed-input input) ; non-terminal will be put into INPUT
                 values)))
      (do () (nil t) ; main cycle - no stop condition
       (unless input (setq input (cons '-! nil))) ; end-marker
       (selectq (caar stack) ; outer KEY switch
         (<CONDS>-10.1
           (selectq (car input)
            ((RIGHT-BRACE) ; REDUCE(10) op
              (setq input (cons '<CONDS> (apply #'(LAMBDA (A B C) (CONS A C)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE) (car input)))))
         (<IRI-REF>-15.1
           (selectq (car input)
            ((IRI ID STRING NUMBER TRUE FALSE LEFT-PAR VAR NOT MINUS) ; REDUCE(15) op
              (setq input (cons '<IRI-OR-VAR> (apply #'(LAMBDA (A) A) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI ID STRING NUMBER TRUE FALSE LEFT-PAR VAR NOT MINUS) (car input)))))
         (VAR-16.1
           (selectq (car input)
            ((IRI ID STRING NUMBER TRUE FALSE LEFT-PAR VAR NOT MINUS) ; REDUCE(16) op
              (setq input (cons '<IRI-OR-VAR> (apply #'(LAMBDA (A) (CONS (QUOTE VAR) A)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI ID STRING NUMBER TRUE FALSE LEFT-PAR VAR NOT MINUS) (car input)))))
         (LOCALNAME-48.1
           (selectq (car input)
            ((WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) ; REDUCE(48) op
              (setq input (cons '<IRI-REF> (apply #'(LAMBDA (A B) (LIST (QUOTE PREFIXED) A B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) (car input)))))
         (IRI-47.1
           (selectq (car input)
            ((WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) ; REDUCE(47) op
              (setq input (cons '<IRI-REF> (apply #'(LAMBDA (A) (CONS (QUOTE IRI) A)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) (car input)))))
         (RIGHT-BRACE-14.1
           (selectq (car input)
            ((DOT RIGHT-BRACE) ; REDUCE(14) op
              (setq input (cons '<COND> (apply #'(LAMBDA (A B C D) (CONS (QUOTE OPTIONAL) C)) (reduce 4)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(DOT RIGHT-BRACE) (car input)))))
         (RIGHT-PAR-13.1
           (selectq (car input)
            ((DOT RIGHT-BRACE) ; REDUCE(13) op
              (setq input (cons '<COND> (apply #'(LAMBDA (A B C D E F G) (LIST (QUOTE REGEX) (CONS (QUOTE VAR) D) F)) (reduce 7)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(DOT RIGHT-BRACE) (car input)))))
         (<REL-EXPR>-19.1
           (selectq (car input)
            ((AND OR RIGHT-PAR) ; REDUCE(19) op
              (setq input (cons '<CONJUNCTION> (apply #'(LAMBDA (A B C) (LIST (QUOTE AND) A C)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(AND OR RIGHT-PAR) (car input)))))
         (RIGHT-PAR-12.1
           (selectq (car input)
            ((DOT RIGHT-BRACE) ; REDUCE(12) op
              (setq input (cons '<COND> (apply #'(LAMBDA (A B C D) (CONS (QUOTE FILTER) C)) (reduce 4)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(DOT RIGHT-BRACE) (car input)))))
         (<PRIM-EXPR>-33.1
           (selectq (car input)
            ((WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) ; REDUCE(33) op
              (setq input (cons '<MULT-EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE /) A C)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) (car input)))))
         (<PRIM-EXPR>-32.1
           (selectq (car input)
            ((WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) ; REDUCE(32) op
              (setq input (cons '<MULT-EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE *) A C)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) (car input)))))
         (<PRIM-EXPR>-34.1
           (selectq (car input)
            ((WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) ; REDUCE(34) op
              (setq input (cons '<MULT-EXPR> (apply #'(LAMBDA (A) A) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) (car input)))))
         (<IRI-REF>-41.1
           (selectq (car input)
            ((WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) ; REDUCE(41) op
              (setq input (cons '<LITERAL> (apply #'(LAMBDA (A B C) (APPEND A (LIST C))) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) (car input)))))
         (NUMBER-42.1
           (selectq (car input)
            ((WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) ; REDUCE(42) op
              (setq input (cons '<LITERAL> (apply #'(LAMBDA (A) (CONS (QUOTE NUMBER) A)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) (car input)))))
         (TRUE-43.1
           (selectq (car input)
            ((WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) ; REDUCE(43) op
              (setq input (cons '<LITERAL> (apply #'(LAMBDA (A) (QUOTE (TRUE))) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) (car input)))))
         (FALSE-44.1
           (selectq (car input)
            ((WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) ; REDUCE(44) op
              (setq input (cons '<LITERAL> (apply #'(LAMBDA (A) (QUOTE (FALSE))) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) (car input)))))
         (LANGTAG-46.1
           (selectq (car input)
            ((WHERE FROM DOUBLE-CAP RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) ; REDUCE(46) op
              (setq input (cons '<STRING-LANG> (apply #'(LAMBDA (A B) (LIST (QUOTE LITERAL) A B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DOUBLE-CAP RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) (car input)))))
         (<PRIM-EXPR>-39.1
           (selectq (car input)
            ((WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) ; REDUCE(39) op
              (setq input (cons '<PRIM-EXPR> (apply #'(LAMBDA (A B) (LIST (QUOTE NOT) B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) (car input)))))
         (VAR-38.1
           (selectq (car input)
            ((WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) ; REDUCE(38) op
              (setq input (cons '<PRIM-EXPR> (apply #'(LAMBDA (A) (CONS (QUOTE VAR) A)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) (car input)))))
         (<IRI-REF>-37.1
           (selectq (car input)
            ((WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) ; REDUCE(37) op
              (setq input (cons '<PRIM-EXPR> (apply #'(LAMBDA (A) A) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) (car input)))))
         (<LITERAL>-36.1
           (selectq (car input)
            ((WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) ; REDUCE(36) op
              (setq input (cons '<PRIM-EXPR> (apply #'(LAMBDA (A) A) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) (car input)))))
         (RIGHT-PAR-35.1
           (selectq (car input)
            ((WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) ; REDUCE(35) op
              (setq input (cons '<PRIM-EXPR> (apply #'(LAMBDA (A B C) B) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) (car input)))))
         (<REL-EXPR>-20.1
           (selectq (car input)
            ((AND OR RIGHT-PAR) ; REDUCE(20) op
              (setq input (cons '<CONJUNCTION> (apply #'(LAMBDA (A) A) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(AND OR RIGHT-PAR) (car input)))))
         (RIGHT-BRACE-5.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(5) op
              (setq input (cons '<SELECT> (apply #'(LAMBDA (A B C D E) (SETF (SELECT-STAT-WHERE A) D) A) (reduce 5)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (IRI-4.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(4) op
              (setq input (cons '<SELECT> (apply #'(LAMBDA (A B C) (SETF (SELECT-STAT-FROM A) C) A) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (<PREFIXED-STAT>-2.1
           (selectq (car input)
            ((-!) ; REDUCE(2) op
              (setq input (cons '<PREFIXED-STAT> (apply #'(LAMBDA (A B C D E) (PUSH (CONS B D) (FIRST E)) E) (reduce 5)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(-!) (car input)))))
         (<SEL-LIST>-7.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(7) op
              (setq input (cons '<SEL-LIST> (apply #'(LAMBDA (A B) (CONS A B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (COUNT-51.1
           (selectq (car input)
            ((LEFT-PAR) ; REDUCE(51) op
              (setq input (cons '<AGG-FN> (apply #'(LAMBDA (A) (QUOTE COUNT)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR) (car input)))))
         (SUM-52.1
           (selectq (car input)
            ((LEFT-PAR) ; REDUCE(52) op
              (setq input (cons '<AGG-FN> (apply #'(LAMBDA (A) (QUOTE SUM)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR) (car input)))))
         (MIN-53.1
           (selectq (car input)
            ((LEFT-PAR) ; REDUCE(53) op
              (setq input (cons '<AGG-FN> (apply #'(LAMBDA (A) (QUOTE MIN)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR) (car input)))))
         (MAX-54.1
           (selectq (car input)
            ((LEFT-PAR) ; REDUCE(54) op
              (setq input (cons '<AGG-FN> (apply #'(LAMBDA (A) (QUOTE MAX)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR) (car input)))))
         (AVG-55.1
           (selectq (car input)
            ((LEFT-PAR) ; REDUCE(55) op
              (setq input (cons '<AGG-FN> (apply #'(LAMBDA (A) (QUOTE AVG)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR) (car input)))))
         (RIGHT-PAR-50.1
           (selectq (car input)
            ((COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI WHERE FROM -!) ; REDUCE(50) op
              (setq input (cons '<AGG-EXPR> (apply #'(LAMBDA (A B C D) (LIST A C)) (reduce 4)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI WHERE FROM -!) (car input)))))
         (<SEL-LIST>-3.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(3) op
              (setq input (cons '<SELECT> (apply #'(LAMBDA (A B) (MAKE-SELECT-STAT :WHAT B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (<PREFIXED-STAT>-0.0
           (selectq (car input)
            (-! (return (cdar stack))) ; ACCEPT op
            (return (list 'SYNTAX-ERROR (caar stack) '(-!) (car input)))))
         (^
           (selectq (car input)
            (<PREFIXED-STAT> (shift '<PREFIXED-STAT>-0.0)) ; REDUCE completion
            (<SELECT> (shift '<SELECT>-1.1-4.3-5.5)) ; REDUCE completion
            (PREFIX (shift 'PREFIX-2.5)) ; SHIFT op
            (SELECT (shift 'SELECT-3.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(PREFIX SELECT) (car input)))))
         (<SELECT>-1.1-4.3-5.5
           (selectq (car input)
            ((-!) ; REDUCE(1) op
              (setq input (cons '<PREFIXED-STAT> (apply #'(LAMBDA (A) (LIST NIL A)) (reduce 1)))))
            (WHERE (shift 'WHERE-5.4)) ; SHIFT op
            (FROM (shift 'FROM-4.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(-! WHERE FROM) (car input)))))
         (WHERE-5.4
           (selectq (car input)
            (LEFT-BRACE (shift 'LEFT-BRACE-5.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-BRACE) (car input)))))
         (LEFT-BRACE-5.3
           (selectq (car input)
            (<CONDS> (shift '<CONDS>-5.2)) ; REDUCE completion
            (<IRI-OR-VAR> (shift '<IRI-OR-VAR>-11.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-15.1)) ; REDUCE completion
            (<COND> (shift '<COND>-8.1-9.2-10.3)) ; REDUCE completion
            (VAR (shift 'VAR-16.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (OPTIONAL (shift 'OPTIONAL-14.4)) ; SHIFT op
            (FILTER (shift 'FILTER-12.4-13.7)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(VAR ID IRI OPTIONAL FILTER) (car input)))))
         (<COND>-8.1-9.2-10.3
           (selectq (car input)
            ((RIGHT-BRACE) ; REDUCE(8) op
              (setq input (cons '<CONDS> (apply #'(LAMBDA (A) (LIST A)) (reduce 1)))))
            (DOT (shift 'DOT-9.1-10.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE DOT) (car input)))))
         (DOT-9.1-10.2
           (selectq (car input)
            (<CONDS> (shift '<CONDS>-10.1)) ; REDUCE completion
            (<IRI-OR-VAR> (shift '<IRI-OR-VAR>-11.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-15.1)) ; REDUCE completion
            (<COND> (shift '<COND>-8.1-9.2-10.3)) ; REDUCE completion
            ((RIGHT-BRACE) ; REDUCE(9) op
              (setq input (cons '<CONDS> (apply #'(LAMBDA (A B) (LIST A)) (reduce 2)))))
            (VAR (shift 'VAR-16.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (OPTIONAL (shift 'OPTIONAL-14.4)) ; SHIFT op
            (FILTER (shift 'FILTER-12.4-13.7)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE VAR ID IRI OPTIONAL FILTER) (car input)))))
         (ID-48.2
           (selectq (car input)
            (LOCALNAME (shift 'LOCALNAME-48.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LOCALNAME) (car input)))))
         (OPTIONAL-14.4
           (selectq (car input)
            (LEFT-BRACE (shift 'LEFT-BRACE-14.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-BRACE) (car input)))))
         (LEFT-BRACE-14.3
           (selectq (car input)
            (<CONDS> (shift '<CONDS>-14.2)) ; REDUCE completion
            (<IRI-OR-VAR> (shift '<IRI-OR-VAR>-11.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-15.1)) ; REDUCE completion
            (<COND> (shift '<COND>-8.1-9.2-10.3)) ; REDUCE completion
            (VAR (shift 'VAR-16.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (OPTIONAL (shift 'OPTIONAL-14.4)) ; SHIFT op
            (FILTER (shift 'FILTER-12.4-13.7)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(VAR ID IRI OPTIONAL FILTER) (car input)))))
         (<CONDS>-14.2
           (selectq (car input)
            (RIGHT-BRACE (shift 'RIGHT-BRACE-14.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE) (car input)))))
         (FILTER-12.4-13.7
           (selectq (car input)
            (REGEX (shift 'REGEX-13.6)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-12.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(REGEX LEFT-PAR) (car input)))))
         (REGEX-13.6
           (selectq (car input)
            (LEFT-PAR (shift 'LEFT-PAR-13.5)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR) (car input)))))
         (LEFT-PAR-13.5
           (selectq (car input)
            (VAR (shift 'VAR-13.4)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(VAR) (car input)))))
         (VAR-13.4
           (selectq (car input)
            (COMMA (shift 'COMMA-13.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA) (car input)))))
         (COMMA-13.3
           (selectq (car input)
            (STRING (shift 'STRING-13.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING) (car input)))))
         (STRING-13.2
           (selectq (car input)
            (RIGHT-PAR (shift 'RIGHT-PAR-13.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-PAR) (car input)))))
         (LEFT-PAR-12.3
           (selectq (car input)
            (<REL-EXPR> (shift '<REL-EXPR>-20.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-21.1-22.3-23.3-24.3-25.3-26.3-27.3-28.3-29.3)) ; REDUCE completion
            (<CONJUNCTION> (shift '<CONJUNCTION>-18.1-19.3)) ; REDUCE completion
            (<EXPR> (shift '<EXPR>-12.2-17.3)) ; REDUCE completion
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(NUMBER TRUE FALSE STRING IRI ID NOT VAR LEFT-PAR MINUS) (car input)))))
         (<EXPR>-12.2-17.3
           (selectq (car input)
            (OR (shift 'OR-17.2)) ; SHIFT op
            (RIGHT-PAR (shift 'RIGHT-PAR-12.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(OR RIGHT-PAR) (car input)))))
         (OR-17.2
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-21.1-22.3-23.3-24.3-25.3-26.3-27.3-28.3-29.3)) ; REDUCE completion
            (<REL-EXPR> (shift '<REL-EXPR>-20.1)) ; REDUCE completion
            (<CONJUNCTION> (shift '<CONJUNCTION>-17.1-19.3)) ; REDUCE completion
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(MINUS LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (<CONJUNCTION>-17.1-19.3
           (selectq (car input)
            ((OR RIGHT-PAR) ; REDUCE(17) op
              (setq input (cons '<EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE OR) A C)) (reduce 3)))))
            (AND (shift 'AND-19.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(OR RIGHT-PAR AND) (car input)))))
         (AND-19.2
           (selectq (car input)
            (<REL-EXPR> (shift '<REL-EXPR>-19.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-21.1-22.3-23.3-24.3-25.3-26.3-27.3-28.3-29.3)) ; REDUCE completion
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(NUMBER TRUE FALSE STRING IRI ID NOT VAR LEFT-PAR MINUS) (car input)))))
         (<CONJUNCTION>-18.1-19.3
           (selectq (car input)
            ((OR RIGHT-PAR) ; REDUCE(18) op
              (setq input (cons '<EXPR> (apply #'(LAMBDA (A) A) (reduce 1)))))
            (AND (shift 'AND-19.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(OR RIGHT-PAR AND) (car input)))))
         (<NUM-EXPR>-21.1-22.3-23.3-24.3-25.3-26.3-27.3-28.3-29.3
           (selectq (car input)
            ((OR RIGHT-PAR AND) ; REDUCE(21) op
              (setq input (cons '<REL-EXPR> (apply #'(LAMBDA (A) A) (reduce 1)))))
            (MINUS (shift 'MINUS-29.2)) ; SHIFT op
            (PLUS (shift 'PLUS-28.2)) ; SHIFT op
            (GREATER-OR-EQUAL (shift 'GREATER-OR-EQUAL-27.2)) ; SHIFT op
            (LESS-OR-EQUAL (shift 'LESS-OR-EQUAL-26.2)) ; SHIFT op
            (GREATER (shift 'GREATER-25.2)) ; SHIFT op
            (LESS (shift 'LESS-24.2)) ; SHIFT op
            (NOT-EQUAL (shift 'NOT-EQUAL-23.2)) ; SHIFT op
            (EQUAL (shift 'EQUAL-22.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(OR RIGHT-PAR AND MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL) (car input)))))
         (MINUS-29.2
           (selectq (car input)
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-29.1-32.3-33.3)) ; REDUCE completion
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(NUMBER TRUE FALSE STRING IRI ID NOT VAR LEFT-PAR) (car input)))))
         (<MULT-EXPR>-29.1-32.3-33.3
           (selectq (car input)
            ((WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT -!) ; REDUCE(29) op
              (setq input (cons '<NUM-EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE -) A C)) (reduce 3)))))
            (DIVIDE (shift 'DIVIDE-33.2)) ; SHIFT op
            (TIMES (shift 'TIMES-32.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT -! DIVIDE TIMES) (car input)))))
         (DIVIDE-33.2
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-33.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (TIMES-32.2
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-32.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (PLUS-28.2
           (selectq (car input)
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-28.1-32.3-33.3)) ; REDUCE completion
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(NUMBER TRUE FALSE STRING IRI ID NOT VAR LEFT-PAR) (car input)))))
         (<MULT-EXPR>-28.1-32.3-33.3
           (selectq (car input)
            ((WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT -!) ; REDUCE(28) op
              (setq input (cons '<NUM-EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE +) A C)) (reduce 3)))))
            (DIVIDE (shift 'DIVIDE-33.2)) ; SHIFT op
            (TIMES (shift 'TIMES-32.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT -! DIVIDE TIMES) (car input)))))
         (GREATER-OR-EQUAL-27.2
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-27.1-28.3-29.3)) ; REDUCE completion
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(MINUS LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (<NUM-EXPR>-27.1-28.3-29.3
           (selectq (car input)
            ((OR RIGHT-PAR AND) ; REDUCE(27) op
              (setq input (cons '<REL-EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE >=) A C)) (reduce 3)))))
            (MINUS (shift 'MINUS-29.2)) ; SHIFT op
            (PLUS (shift 'PLUS-28.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(OR RIGHT-PAR AND MINUS PLUS) (car input)))))
         (LESS-OR-EQUAL-26.2
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-26.1-28.3-29.3)) ; REDUCE completion
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(MINUS LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (<NUM-EXPR>-26.1-28.3-29.3
           (selectq (car input)
            ((OR RIGHT-PAR AND) ; REDUCE(26) op
              (setq input (cons '<REL-EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE <=) A C)) (reduce 3)))))
            (MINUS (shift 'MINUS-29.2)) ; SHIFT op
            (PLUS (shift 'PLUS-28.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(OR RIGHT-PAR AND MINUS PLUS) (car input)))))
         (GREATER-25.2
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-25.1-28.3-29.3)) ; REDUCE completion
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(MINUS LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (<NUM-EXPR>-25.1-28.3-29.3
           (selectq (car input)
            ((OR RIGHT-PAR AND) ; REDUCE(25) op
              (setq input (cons '<REL-EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE >) A C)) (reduce 3)))))
            (MINUS (shift 'MINUS-29.2)) ; SHIFT op
            (PLUS (shift 'PLUS-28.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(OR RIGHT-PAR AND MINUS PLUS) (car input)))))
         (LESS-24.2
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-24.1-28.3-29.3)) ; REDUCE completion
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(MINUS LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (<NUM-EXPR>-24.1-28.3-29.3
           (selectq (car input)
            ((OR RIGHT-PAR AND) ; REDUCE(24) op
              (setq input (cons '<REL-EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE <) A C)) (reduce 3)))))
            (MINUS (shift 'MINUS-29.2)) ; SHIFT op
            (PLUS (shift 'PLUS-28.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(OR RIGHT-PAR AND MINUS PLUS) (car input)))))
         (NOT-EQUAL-23.2
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-23.1-28.3-29.3)) ; REDUCE completion
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(MINUS LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (<NUM-EXPR>-23.1-28.3-29.3
           (selectq (car input)
            ((OR RIGHT-PAR AND) ; REDUCE(23) op
              (setq input (cons '<REL-EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE !=) A C)) (reduce 3)))))
            (MINUS (shift 'MINUS-29.2)) ; SHIFT op
            (PLUS (shift 'PLUS-28.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(OR RIGHT-PAR AND MINUS PLUS) (car input)))))
         (EQUAL-22.2
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-22.1-28.3-29.3)) ; REDUCE completion
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(MINUS LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (<NUM-EXPR>-22.1-28.3-29.3
           (selectq (car input)
            ((OR RIGHT-PAR AND) ; REDUCE(22) op
              (setq input (cons '<REL-EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE =) A C)) (reduce 3)))))
            (MINUS (shift 'MINUS-29.2)) ; SHIFT op
            (PLUS (shift 'PLUS-28.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(OR RIGHT-PAR AND MINUS PLUS) (car input)))))
         (<MULT-EXPR>-31.1-32.3-33.3
           (selectq (car input)
            ((WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT -!) ; REDUCE(31) op
              (setq input (cons '<NUM-EXPR> (apply #'(LAMBDA (A) A) (reduce 1)))))
            (DIVIDE (shift 'DIVIDE-33.2)) ; SHIFT op
            (TIMES (shift 'TIMES-32.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT -! DIVIDE TIMES) (car input)))))
         (<STRING-LANG>-40.1-41.3
           (selectq (car input)
            ((WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -!) ; REDUCE(40) op
              (setq input (cons '<LITERAL> (apply #'(LAMBDA (A) A) (reduce 1)))))
            (DOUBLE-CAP (shift 'DOUBLE-CAP-41.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DIVIDE TIMES DOT COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI RIGHT-BRACE OR RIGHT-PAR AND PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL -! DOUBLE-CAP) (car input)))))
         (DOUBLE-CAP-41.2
           (selectq (car input)
            (<IRI-REF> (shift '<IRI-REF>-41.1)) ; REDUCE completion
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI ID) (car input)))))
         (STRING-45.1-46.2
           (selectq (car input)
            ((WHERE FROM DOUBLE-CAP RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -!) ; REDUCE(45) op
              (setq input (cons '<STRING-LANG> (apply #'(LAMBDA (A) (LIST (QUOTE LITERAL) A)) (reduce 1)))))
            (LANGTAG (shift 'LANGTAG-46.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM DOUBLE-CAP RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT DIVIDE TIMES -! LANGTAG) (car input)))))
         (NOT-39.2
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-39.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (LEFT-PAR-35.3
           (selectq (car input)
            (<REL-EXPR> (shift '<REL-EXPR>-20.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-21.1-22.3-23.3-24.3-25.3-26.3-27.3-28.3-29.3)) ; REDUCE completion
            (<CONJUNCTION> (shift '<CONJUNCTION>-18.1-19.3)) ; REDUCE completion
            (<EXPR> (shift '<EXPR>-17.3-35.2)) ; REDUCE completion
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(NUMBER TRUE FALSE STRING IRI ID NOT VAR LEFT-PAR MINUS) (car input)))))
         (<EXPR>-17.3-35.2
           (selectq (car input)
            (RIGHT-PAR (shift 'RIGHT-PAR-35.1)) ; SHIFT op
            (OR (shift 'OR-17.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-PAR OR) (car input)))))
         (MINUS-30.2
           (selectq (car input)
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-30.1-32.3-33.3)) ; REDUCE completion
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(NUMBER TRUE FALSE STRING IRI ID NOT VAR LEFT-PAR) (car input)))))
         (<MULT-EXPR>-30.1-32.3-33.3
           (selectq (car input)
            ((WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT -!) ; REDUCE(30) op
              (setq input (cons '<NUM-EXPR> (apply #'(LAMBDA (A B) (LIST (QUOTE -) B)) (reduce 2)))))
            (DIVIDE (shift 'DIVIDE-33.2)) ; SHIFT op
            (TIMES (shift 'TIMES-32.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM RIGHT-PAR MINUS PLUS GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS NOT-EQUAL EQUAL AND OR RIGHT-BRACE COUNT SUM MIN MAX AVG NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI DOT -! DIVIDE TIMES) (car input)))))
         (<IRI-OR-VAR>-11.3
           (selectq (car input)
            (<IRI-OR-VAR> (shift '<IRI-OR-VAR>-11.2)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-15.1)) ; REDUCE completion
            (VAR (shift 'VAR-16.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(VAR ID IRI) (car input)))))
         (<IRI-OR-VAR>-11.2
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-11.1-28.3-29.3)) ; REDUCE completion
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(MINUS LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (<NUM-EXPR>-11.1-28.3-29.3
           (selectq (car input)
            ((DOT RIGHT-BRACE) ; REDUCE(11) op
              (setq input (cons '<COND> (apply #'(LAMBDA (A B C) (LIST (QUOTE TRIPLE) A B C)) (reduce 3)))))
            (MINUS (shift 'MINUS-29.2)) ; SHIFT op
            (PLUS (shift 'PLUS-28.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(DOT RIGHT-BRACE MINUS PLUS) (car input)))))
         (<CONDS>-5.2
           (selectq (car input)
            (RIGHT-BRACE (shift 'RIGHT-BRACE-5.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE) (car input)))))
         (FROM-4.2
           (selectq (car input)
            (IRI (shift 'IRI-4.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI) (car input)))))
         (PREFIX-2.5
           (selectq (car input)
            (ID (shift 'ID-2.4)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(ID) (car input)))))
         (ID-2.4
           (selectq (car input)
            (LOCALNAME (shift 'LOCALNAME-2.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LOCALNAME) (car input)))))
         (LOCALNAME-2.3
           (selectq (car input)
            (IRI (shift 'IRI-2.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI) (car input)))))
         (IRI-2.2
           (selectq (car input)
            (<PREFIXED-STAT> (shift '<PREFIXED-STAT>-2.1)) ; REDUCE completion
            (<SELECT> (shift '<SELECT>-1.1-4.3-5.5)) ; REDUCE completion
            (PREFIX (shift 'PREFIX-2.5)) ; SHIFT op
            (SELECT (shift 'SELECT-3.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(PREFIX SELECT) (car input)))))
         (SELECT-3.2
           (selectq (car input)
            (<SEL-LIST> (shift '<SEL-LIST>-3.1)) ; REDUCE completion
            (<AGG-FN> (shift '<AGG-FN>-50.4)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-28.3-29.3-49.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<AGG-EXPR> (shift '<AGG-EXPR>-6.1-7.2)) ; REDUCE completion
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (COUNT (shift 'COUNT-51.1)) ; SHIFT op
            (SUM (shift 'SUM-52.1)) ; SHIFT op
            (MIN (shift 'MIN-53.1)) ; SHIFT op
            (MAX (shift 'MAX-54.1)) ; SHIFT op
            (AVG (shift 'AVG-55.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(NUMBER TRUE FALSE STRING IRI ID NOT VAR LEFT-PAR MINUS COUNT SUM MIN MAX AVG) (car input)))))
         (<AGG-EXPR>-6.1-7.2
           (selectq (car input)
            (<SEL-LIST> (shift '<SEL-LIST>-7.1)) ; REDUCE completion
            (<AGG-FN> (shift '<AGG-FN>-50.4)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-28.3-29.3-49.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<AGG-EXPR> (shift '<AGG-EXPR>-6.1-7.2)) ; REDUCE completion
            ((WHERE FROM -!) ; REDUCE(6) op
              (setq input (cons '<SEL-LIST> (apply #'(LAMBDA (A) (LIST A)) (reduce 1)))))
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (COUNT (shift 'COUNT-51.1)) ; SHIFT op
            (SUM (shift 'SUM-52.1)) ; SHIFT op
            (MIN (shift 'MIN-53.1)) ; SHIFT op
            (MAX (shift 'MAX-54.1)) ; SHIFT op
            (AVG (shift 'AVG-55.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -! NUMBER TRUE FALSE STRING IRI ID NOT VAR LEFT-PAR MINUS COUNT SUM MIN MAX AVG) (car input)))))
         (<NUM-EXPR>-28.3-29.3-49.1
           (selectq (car input)
            ((COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI WHERE FROM -!) ; REDUCE(49) op
              (setq input (cons '<AGG-EXPR> (apply #'(LAMBDA (A) A) (reduce 1)))))
            (MINUS (shift 'MINUS-29.2)) ; SHIFT op
            (PLUS (shift 'PLUS-28.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(COUNT SUM MIN MAX AVG MINUS NOT VAR LEFT-PAR FALSE TRUE NUMBER STRING ID IRI WHERE FROM -! MINUS PLUS) (car input)))))
         (<AGG-FN>-50.4
           (selectq (car input)
            (LEFT-PAR (shift 'LEFT-PAR-50.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR) (car input)))))
         (LEFT-PAR-50.3
           (selectq (car input)
            (<PRIM-EXPR> (shift '<PRIM-EXPR>-34.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-40.1-41.3)) ; REDUCE completion
            (<IRI-REF> (shift '<IRI-REF>-37.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-36.1)) ; REDUCE completion
            (<MULT-EXPR> (shift '<MULT-EXPR>-31.1-32.3-33.3)) ; REDUCE completion
            (<NUM-EXPR> (shift '<NUM-EXPR>-28.3-29.3-50.2)) ; REDUCE completion
            (MINUS (shift 'MINUS-30.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-35.3)) ; SHIFT op
            (VAR (shift 'VAR-38.1)) ; SHIFT op
            (NOT (shift 'NOT-39.2)) ; SHIFT op
            (ID (shift 'ID-48.2)) ; SHIFT op
            (IRI (shift 'IRI-47.1)) ; SHIFT op
            (STRING (shift 'STRING-45.1-46.2)) ; SHIFT op
            (FALSE (shift 'FALSE-44.1)) ; SHIFT op
            (TRUE (shift 'TRUE-43.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(MINUS LEFT-PAR VAR NOT ID IRI STRING FALSE TRUE NUMBER) (car input)))))
         (<NUM-EXPR>-28.3-29.3-50.2
           (selectq (car input)
            (RIGHT-PAR (shift 'RIGHT-PAR-50.1)) ; SHIFT op
            (MINUS (shift 'MINUS-29.2)) ; SHIFT op
            (PLUS (shift 'PLUS-28.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-PAR MINUS PLUS) (car input)))))
         (return 'INTERNAL-ERROR))))))
