;;; SLR1-parser generated by GRM Parser Builder
;;; (C) 2001-2011, Andrej Andrejev

;;; INPUT-FN is a function returning (terminal . value) pairs
;;; or NIL when input is exhausted
;;; DATA is any data structure transmitted to the parser and visible in reduce actions

(defun brian-sf-slr1-parser (input-fn data)
  (let ((stack '((^))) ; contains pairs (key . value), ^ is bottom-marker
        (input (funcall input-fn)) (delayed-input nil))
    (flet ((shift (key) ; SHIFT op
             (push (cons key (cdr input)) stack) ; push new key with input value
             (if delayed-input (progn (setq input delayed-input)
                                      (setq delayed-input nil)) ; restore input after REDUCE
               (setq input (funcall input-fn)))) ; feed input
           (reduce (n) ; REDUCE op: returns list of n top values from stack
             (let ((values nil))
               (dotimes (i n) (push (cdr (pop stack)) values))
               (setq delayed-input input) ; non-terminal will be put into INPUT
               values)))
      (do () (nil t) ; main cycle - no stop condition
       (unless input (setq input (cons '-! nil))) ; end-marker
       (selectq (caar stack) ; outer KEY switch
         (ISSA-3.1
           (selectq (car input)
            ((GRAD) ; REDUCE(3) op
              (setq input (cons '<ALGORITHM> (apply #'(LAMBDA (A) ":issa_Algorithm") (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(GRAD) (car input)))))
         (SWITCH-4.1
           (selectq (car input)
            ((D) ; REDUCE(4) op
              (setq input (cons '<INPUT> (apply #'(LAMBDA (A B) ":GradientWithSwitching_Input") (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(D) (car input)))))
         (INT-1.1
           (selectq (car input)
            ((-!) ; REDUCE(1) op
              (setq input (cons '<SF> (apply #'(LAMBDA (A B C D E F G H I J K L M N O P Q R S U) (MAKE-SF :MODEL A :VERSION B :ALGORITHM C :INPUT D :D (CONCAT F "." G) :TF I :TSTEP K :SON (CONCAT M "." N) :KM P :KON R :TRAJNO U)) (reduce 20)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(-!) (car input)))))
         (ALT-2.1
           (selectq (car input)
            ((INT) ; REDUCE(2) op
              (setq input (cons '<MODEL> (apply #'(LAMBDA (A B) "\"ALL_alt\"") (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(INT) (car input)))))
         (<SF>-0.0
           (selectq (car input)
            ((-!) (return (cdar stack))) ; ACCEPT op
            (return (list 'SYNTAX-ERROR (caar stack) '(-!) (car input)))))
         (^
           (selectq (car input)
            (<SF> (shift '<SF>-0.0)) ; REDUCE completion
            (<MODEL> (shift '<MODEL>-1.20)) ; REDUCE completion
            (ALL (shift 'ALL-2.2)) ; SHIFT op
            ((-!) (return nil)) ; ACCEPT EMPTY INPUT
            (return (list 'SYNTAX-ERROR (caar stack) '(ALL) (car input)))))
         (<MODEL>-1.20
           (selectq (car input)
            (INT (shift 'INT-1.19)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(INT) (car input)))))
         (INT-1.19
           (selectq (car input)
            (<ALGORITHM> (shift '<ALGORITHM>-1.18)) ; REDUCE completion
            (ISSA (shift 'ISSA-3.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(ISSA) (car input)))))
         (<ALGORITHM>-1.18
           (selectq (car input)
            (<INPUT> (shift '<INPUT>-1.17)) ; REDUCE completion
            (GRAD (shift 'GRAD-4.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(GRAD) (car input)))))
         (GRAD-4.2
           (selectq (car input)
            (SWITCH (shift 'SWITCH-4.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(SWITCH) (car input)))))
         (<INPUT>-1.17
           (selectq (car input)
            (D (shift 'D-1.16)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(D) (car input)))))
         (D-1.16
           (selectq (car input)
            (INT (shift 'INT-1.15)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(INT) (car input)))))
         (INT-1.15
           (selectq (car input)
            (INT (shift 'INT-1.14)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(INT) (car input)))))
         (INT-1.14
           (selectq (car input)
            (TF (shift 'TF-1.13)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(TF) (car input)))))
         (TF-1.13
           (selectq (car input)
            (INT (shift 'INT-1.12)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(INT) (car input)))))
         (INT-1.12
           (selectq (car input)
            (TSTEP (shift 'TSTEP-1.11)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(TSTEP) (car input)))))
         (TSTEP-1.11
           (selectq (car input)
            (INT (shift 'INT-1.10)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(INT) (car input)))))
         (INT-1.10
           (selectq (car input)
            (SON (shift 'SON-1.9)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(SON) (car input)))))
         (SON-1.9
           (selectq (car input)
            (INT (shift 'INT-1.8)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(INT) (car input)))))
         (INT-1.8
           (selectq (car input)
            (INT (shift 'INT-1.7)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(INT) (car input)))))
         (INT-1.7
           (selectq (car input)
            (KM (shift 'KM-1.6)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(KM) (car input)))))
         (KM-1.6
           (selectq (car input)
            (INT (shift 'INT-1.5)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(INT) (car input)))))
         (INT-1.5
           (selectq (car input)
            (KON (shift 'KON-1.4)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(KON) (car input)))))
         (KON-1.4
           (selectq (car input)
            (FLOAT (shift 'FLOAT-1.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(FLOAT) (car input)))))
         (FLOAT-1.3
           (selectq (car input)
            (DASH (shift 'DASH-1.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(DASH) (car input)))))
         (DASH-1.2
           (selectq (car input)
            (INT (shift 'INT-1.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(INT) (car input)))))
         (ALL-2.2
           (selectq (car input)
            (ALT (shift 'ALT-2.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(ALT) (car input)))))
         (return 'INTERNAL-ERROR))))))
