#define yyFlexLexer SQLFlexLexer
#define yy_create_buffer SQL_create_buffer
#define yy_delete_buffer SQL_delete_buffer
#define yy_flex_debug SQL_flex_debug
#define yy_init_buffer SQL_init_buffer
#define yy_load_buffer_state SQL_load_buffer_state
#define yy_switch_to_buffer SQL_switch_to_buffer
#define yyin SQLin
#define yyleng SQLleng
#define yylex SQLlex
#define yyout SQLout
#define yyrestart SQLrestart
#define yytext SQLtext
#define yywrap SQLwrap

/* A lexical scanner generated by flex */


#define FLEX_SCANNER

#include <io.h>
#include <stdlib.h>
#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#ifdef __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */


#ifdef __TURBOC__
#define YY_USE_CONST
#endif


#ifndef YY_USE_CONST
#ifndef const
#define const
#endif
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.
 */
#define YY_START ((yy_start - 1) / 2)

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file".  Now included
 * only for backward compatibility with previous versions of flex.
 */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#ifdef __cplusplus
extern "C" {
#endif
	extern int yywrap YY_PROTO(( void ));
#ifdef __cplusplus
	}
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

static void yyunput YY_PROTO(( int c, char *buf_ptr ));
void yyrestart YY_PROTO(( FILE *input_file ));
void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));

static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
static void yy_push_state YY_PROTO(( int new_state ));
static void yy_pop_state YY_PROTO(( void ));
static int yy_top_state YY_PROTO(( void ));

static void *yy_flex_alloc YY_PROTO(( unsigned int ));
static void *yy_flex_realloc YY_PROTO(( void *, unsigned int ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define INITIAL 0
#define SQL 1
#define COMMENT 2
typedef unsigned char YY_CHAR;
typedef int yy_state_type;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
extern char *yytext;
#define yytext_ptr yytext

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, const char *, int ));
#endif

#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( const char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = yy_cp - yy_bp; \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_END_OF_BUFFER 110
static const short int yy_accept[400] =
    {   0,
        0,    0,    0,    0,   85,   85,  110,  108,  106,  106,
      108,   95,   95,   96,   95,   98,   90,   88,   91,   94,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,  107,   85,   86,  106,    0,  105,
      104,  100,   98,  100,    0,   84,   99,    0,   92,   89,
       93,   97,   97,   97,    3,   97,   97,   97,    8,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   34,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   49,   50,   97,

       97,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   85,   86,
       86,   87,    0,  103,   99,    0,    0,  101,    1,    2,
        4,    5,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   19,   97,   97,   97,   97,   97,   97,
       97,   97,   27,   97,   97,   97,   97,   97,   97,   97,
       97,   37,   97,   97,   40,   97,   43,   42,   97,   45,
       78,   97,   97,   97,   97,   97,   97,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   97,   60,   97,
       62,   97,   97,   97,   97,   97,   97,   97,   97,   97,

        0,  102,   97,   97,   97,   10,   18,   97,   12,   97,
       97,   97,   97,   97,   97,   97,   97,   21,   97,   97,
       25,   97,   26,   97,   97,   97,   31,   97,   97,   97,
       97,   97,   38,   97,   39,   41,   97,   97,   47,   97,
       97,   97,   97,   97,   46,   97,   54,   97,   97,   97,
       80,   97,   97,   97,   97,   97,   97,   64,   65,   97,
       97,   97,   97,   97,   97,   72,   97,   74,   97,   97,
       97,   97,   11,   97,   97,   15,   97,   17,   97,   97,
       97,   97,   97,   97,   28,   29,   97,   32,   97,   35,
       97,   97,   97,   97,   97,   97,   97,   51,   97,   97,

       97,   81,   97,   97,   97,   97,   97,   97,   97,   97,
       63,   66,   97,   97,   97,   97,   97,   73,   97,   97,
       97,   97,   13,   97,   16,   97,   97,   22,   97,   24,
       97,   97,   33,   36,   97,   97,   41,   97,   97,   97,
       97,   97,   97,   97,   97,   97,   97,   58,   97,   59,
       97,   67,   68,   69,   97,   97,    6,    7,    9,   97,
       97,   19,   20,   97,   76,   30,   37,   75,   83,   44,
       48,   97,   97,   53,   97,   97,   97,   77,   82,   97,
       70,   71,   97,   97,   23,   97,   97,   97,   56,   57,
       61,   18,   97,   79,   52,   97,   14,   55,    0

    } ;

static const int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    4,    5,
        5,    6,    7,    5,    8,    9,   10,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,    5,    5,   12,
       13,   14,   15,    1,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   42,
        5,    5,    5,    1,   16,    1,   17,   18,   19,   20,

       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const int yy_meta[44] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        3,    1,    1,    1,    1,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    1
    } ;

static const short int yy_base[405] =
    {   0,
        0,    0,    0,    0,  429,  428,  433,  436,   42,   44,
       45,  436,   41,   40,  426,   44,   43,  436,  418,  436,
       32,   33,   49,   47,   41,   58,  396,  412,   28,  397,
      406,  401,   59,   62,   57,   68,  388,   73,   76,   83,
       66,  407,   79,    0,  436,    0,  105,  116,  117,  436,
      436,   95,  103,  111,  118,  436,  112,  120,  436,  436,
      436,    0,  395,  402,  402,  397,  383,  387,    0,  382,
      113,  385,  106,  116,  120,  380,  377,  382,  376,  376,
      390,  381,  377,  373,  375,  374,  366,  110,  367,  377,
      360,  373,  359,  368,  361,  102,  121,    0,  376,  361,

      131,  369,  363,  136,  123,  356,  367,  138,  373,  360,
      370,  366,  349,  360,  364,  126,  362,  348,    0,  153,
      155,  436,  370,  369,  156,  161,  368,  367,    0,    0,
        0,    0,  338,  348,  154,  341,  355,  355,  343,  336,
      340,  352,  333,  342,  349,  344,  345,  327,  344,  329,
      326,  338,    0,  323,  340,  335,  326,  317,  328,  331,
      330,  149,  316,  319,    0,  327,    0,  310,  312,    0,
        0,  317,  323,  322,  306,  322,  311,  303,  315,  309,
      315,  299,  306,  298,  298,  310,  299,  308,    0,  300,
        0,  299,  296,  304,  145,  307,  286,  145,  149,  295,

      310,  309,  298,  297,  300,    0,  299,  288,    0,  289,
      277,  276,  275,  275,  280,  271,  271,    0,  281,  277,
        0,  283,    0,  282,  266,  276,    0,  268,  269,  264,
      263,  273,    0,  274,    0,  278,  257,  255,    0,  257,
      256,  264,  263,  270,    0,  265,    0,  251,  250,  265,
        0,  261,  252,  250,  260,  250,  256,    0,    0,  246,
      238,  238,  252,  248,  246,    0,  249,    0,  248,  251,
      247,  247,    0,  229,  230,    0,  242,    0,  245,  233,
      239,  229,  237,  240,    0,    0,  233,    0,  232,    0,
      218,  232,  235,  226,  229,  232,  223,    0,  211,  211,

      211,    0,  223,  218,  225,  224,  223,  219,  202,  212,
        0,    0,  215,  214,  199,  216,  202,    0,  201,  200,
      208,  192,    0,  210,    0,  198,  189,    0,  205,    0,
      194,  192,    0,    0,  187,  191,    0,  184,  190,  198,
      191,  190,  173,  183,  193,  192,  181,    0,  174,    0,
      178,    0,    0,    0,  173,  183,    0,    0,    0,  184,
      179,    0,    0,  167,    0,    0,    0,    0,    0,    0,
        0,  171,  170,    0,  181,  163,  167,    0,    0,  149,
        0,    0,  150,  152,    0,  151,  114,   88,    0,    0,
        0,    0,   65,    0,    0,   53,    0,    0,  436,  186,

      189,   56,  192,  195
    } ;

static const short int yy_def[405] =
    {   0,
      399,    1,    1,    1,  400,  400,  399,  399,  399,  399,
      401,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  399,  403,  404,  399,  401,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,

      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  403,  404,
      404,  399,  399,  399,  399,  399,  399,  399,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,

      399,  399,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,

      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,  402,  402,
      402,  402,  402,  402,  402,  402,  402,  402,    0,  399,

      399,  399,  399,  399
    } ;

static const short int yy_nxt[480] =
    {   0,
        8,    9,   10,   11,   12,   12,   12,   13,   14,   15,
       16,   17,   18,   19,   20,    8,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
       44,   44,   45,   48,   48,   48,   48,   50,   51,   52,
       54,   53,   57,   67,   53,   59,   60,   88,   62,   63,
       55,   64,   89,   68,   58,   70,   65,   75,   80,   66,
       81,   76,   71,   69,   82,   93,   72,   77,   95,   73,
       78,   79,   74,   94,  100,   83,   98,  398,   84,  103,
       99,   85,   96,  104,  107,  114,  108,  115,   97,  111,

      397,  101,  117,  105,  109,   54,  112,  106,  396,  118,
      121,   57,  110,   53,  122,   55,  113,   48,   48,   50,
       51,   54,  125,   58,  123,  123,  127,  127,  124,  136,
      128,   55,  126,  137,  139,  140,  142,  170,  144,  160,
      171,  145,  141,  395,  161,  162,  143,  146,  172,  173,
      183,  176,  180,  197,  147,  177,  187,  181,  399,  198,
      121,  184,  399,  264,  122,  188,  125,  201,  201,  232,
      182,  202,  205,  189,  206,  260,  126,  261,  266,  233,
      394,  393,  267,  392,  391,  265,   46,   46,   46,   49,
       49,   49,  119,  390,  119,  120,  120,  120,  389,  388,

      387,  386,  385,  384,  383,  382,  381,  380,  379,  378,
      377,  376,  375,  374,  373,  372,  371,  370,  369,  368,
      367,  366,  365,  364,  363,  362,  361,  360,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,  349,  348,
      347,  346,  345,  344,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,
      307,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,

      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      277,  276,  275,  274,  273,  272,  271,  270,  269,  202,
      202,  268,  263,  262,  259,  258,  257,  256,  255,  254,
      253,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  239,  238,  237,  236,  235,  234,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  204,  203,  128,  128,  124,
      124,  200,  199,  196,  195,  194,  193,  192,  191,  190,
      186,  185,  179,  178,  175,  174,  169,  168,  167,  166,

      165,  164,  163,  159,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  138,  135,  134,  133,  132,
      131,  130,  129,  116,  102,   92,   91,   90,   87,   86,
       61,   56,  399,   47,   47,    7,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399
    } ;

static const short int yy_chk[480] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    9,    9,   10,   10,   11,   11,   13,
       14,   13,   16,   22,   16,   17,   17,   29,  402,   21,
       14,   21,   29,   22,   16,   23,   21,   24,   25,   21,
       25,   24,   23,   22,   26,   33,   23,   24,   34,   23,
       24,   24,   23,   33,   36,   26,   35,  396,   26,   38,
       35,   26,   34,   38,   39,   41,   39,   41,   34,   40,

      393,   36,   43,   38,   39,   52,   40,   38,  388,   43,
       47,   53,   39,   53,   47,   52,   40,   48,   48,   49,
       49,   54,   57,   53,   55,   55,   58,   58,   55,   71,
       58,   54,   57,   71,   73,   73,   74,   96,   75,   88,
       96,   75,   73,  387,   88,   88,   74,   75,   97,   97,
      105,  101,  104,  116,   75,  101,  108,  104,  120,  116,
      121,  105,  120,  198,  121,  108,  125,  126,  126,  162,
      104,  126,  135,  108,  135,  195,  125,  195,  199,  162,
      386,  384,  199,  383,  380,  198,  400,  400,  400,  401,
      401,  401,  403,  377,  403,  404,  404,  404,  376,  375,

      373,  372,  364,  361,  360,  356,  355,  351,  349,  347,
      346,  345,  344,  343,  342,  341,  340,  339,  338,  336,
      335,  332,  331,  329,  327,  326,  324,  322,  321,  320,
      319,  317,  316,  315,  314,  313,  310,  309,  308,  307,
      306,  305,  304,  303,  301,  300,  299,  297,  296,  295,
      294,  293,  292,  291,  289,  287,  284,  283,  282,  281,
      280,  279,  277,  275,  274,  272,  271,  270,  269,  267,
      265,  264,  263,  262,  261,  260,  257,  256,  255,  254,
      253,  252,  250,  249,  248,  246,  244,  243,  242,  241,
      240,  238,  237,  236,  234,  232,  231,  230,  229,  228,

      226,  225,  224,  222,  220,  219,  217,  216,  215,  214,
      213,  212,  211,  210,  208,  207,  205,  204,  203,  202,
      201,  200,  197,  196,  194,  193,  192,  190,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  169,  168,  166,  164,  163,
      161,  160,  159,  158,  157,  156,  155,  154,  152,  151,
      150,  149,  148,  147,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  134,  133,  128,  127,  124,
      123,  118,  117,  115,  114,  113,  112,  111,  110,  109,
      107,  106,  103,  102,  100,   99,   95,   94,   93,   92,

       91,   90,   89,   87,   86,   85,   84,   83,   82,   81,
       80,   79,   78,   77,   76,   72,   70,   68,   67,   66,
       65,   64,   63,   42,   37,   32,   31,   30,   28,   27,
       19,   15,    7,    6,    5,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399,  399,
      399,  399,  399,  399,  399,  399,  399,  399,  399
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
# line 1 "sql_lexer.l"
/*-*-C-*-**********************************************************************
 * AMOS2
 *
 * Author: (c) 1998-2011 Marcus Eriksson, Tore Risch, Markus Jägerskogh, EDSLAB, UDBL
 * $RCSfile: sql_lexer.l,v $
 * $Revision: 1.14 $ $Date: 2013/02/13 18:41:02 $
 * $State: Exp $ $Locker:  $
 *
 * Description: Lexical analyzer for the SQL parser
 * Generate C code by running: flex -PSQL -i sql_lexer.l
 ****************************************************************************/
# line 14 "sql_lexer.l"
#include "amos.h"
#include "sql_parser_tab.h"

extern oidtype _oidrefs_; 

#define SAVE_REF if(!symbolp(SQLlval.oidval))\
a_setf(globval(_oidrefs_),cons(SQLlval.oidval,globval(_oidrefs_)))

#define TOK(name) {SQLlval.oidval = mksymbol(yytext); SAVE_REF; return name;}

#undef SQLwrap

  /********************* flexstream interface ************************/
  /* Interface must be here since lex defines parser specific macros */
  /*******************************************************************/

  YY_BUFFER_STATE yy_create_buffer( FILE *file, int size );

  void SQL_initialize_flexstream(flexstream *fs)
    /*** called when parser changes from other parser to this parser ***/
    {
      fs->buffer = (char *)yy_create_buffer((FILE*)fs,YY_BUF_SIZE);
    }

  void SQL_finalize_flexstream(flexstream *fs)
    /*** called when parser changes from this parser to other parser ***/
    {
      yy_delete_buffer((YY_BUFFER_STATE)fs->buffer);
    }

  void SQLerror(char *msg)
    /*** called when syntax error detected ***/
    { 
      a_parse_error((flexstream *)SQLin, msg);
    }

#undef YY_INPUT
#define YY_INPUT(buf,result,max_size)\
        result = a_flexstream_getc((flexstream *)SQLin, buf)

  /***************** end of flexstream interface *********************/


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = getc( yyin ); \
		result = c == EOF ? 0 : 1; \
		buf[0] = (char) c; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

# line 62 "sql_lexer.l"



	if ( yy_init )
		{
#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( yy_current_buffer )
			yy_init_buffer( yy_current_buffer, yyin );
		else
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();

		yy_init = 0;
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 400 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 436 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_USER_ACTION
# line 64 "sql_lexer.l"
TOK(ALL)
	YY_BREAK
case 2:
YY_USER_ACTION
# line 65 "sql_lexer.l"
TOK(AND)
	YY_BREAK
case 3:
YY_USER_ACTION
# line 66 "sql_lexer.l"
TOK(AS)
	YY_BREAK
case 4:
YY_USER_ACTION
# line 67 "sql_lexer.l"
TOK(ASC)
	YY_BREAK
case 5:
YY_USER_ACTION
# line 68 "sql_lexer.l"
TOK(AVG)
	YY_BREAK
case 6:
YY_USER_ACTION
# line 69 "sql_lexer.l"
TOK(BETWEEN)
	YY_BREAK
case 7:
YY_USER_ACTION
# line 70 "sql_lexer.l"
TOK(BOOLEAN)
	YY_BREAK
case 8:
YY_USER_ACTION
# line 71 "sql_lexer.l"
TOK(BY)
	YY_BREAK
case 9:
YY_USER_ACTION
# line 72 "sql_lexer.l"
TOK(CASCADE)
	YY_BREAK
case 10:
YY_USER_ACTION
# line 73 "sql_lexer.l"
TOK(CASE)
	YY_BREAK
case 11:
YY_USER_ACTION
# line 74 "sql_lexer.l"
TOK(CHECK)
	YY_BREAK
case 12:
YY_USER_ACTION
# line 75 "sql_lexer.l"
TOK(CLOB)
	YY_BREAK
case 13:
YY_USER_ACTION
# line 76 "sql_lexer.l"
TOK(COMMIT)
	YY_BREAK
case 14:
YY_USER_ACTION
# line 77 "sql_lexer.l"
TOK(CONSTRAINT)
	YY_BREAK
case 15:
YY_USER_ACTION
# line 78 "sql_lexer.l"
TOK(COUNT)
	YY_BREAK
case 16:
YY_USER_ACTION
# line 79 "sql_lexer.l"
TOK(CREATE)
	YY_BREAK
case 17:
YY_USER_ACTION
# line 80 "sql_lexer.l"
TOK(CROSS)
	YY_BREAK
case 18:
YY_USER_ACTION
# line 81 "sql_lexer.l"
TOK(CHARACTER)
	YY_BREAK
case 19:
YY_USER_ACTION
# line 82 "sql_lexer.l"
TOK(DECIMAL)
	YY_BREAK
case 20:
YY_USER_ACTION
# line 83 "sql_lexer.l"
TOK(DEFAULT)
	YY_BREAK
case 21:
YY_USER_ACTION
# line 84 "sql_lexer.l"
TOK(DESC)
	YY_BREAK
case 22:
YY_USER_ACTION
# line 85 "sql_lexer.l"
TOK(_DELETE)
	YY_BREAK
case 23:
YY_USER_ACTION
# line 86 "sql_lexer.l"
TOK(DISTINCT)
	YY_BREAK
case 24:
YY_USER_ACTION
# line 87 "sql_lexer.l"
TOK(DOUBLE)
	YY_BREAK
case 25:
YY_USER_ACTION
# line 88 "sql_lexer.l"
TOK(DROP)
	YY_BREAK
case 26:
YY_USER_ACTION
# line 89 "sql_lexer.l"
TOK(ELSE)
	YY_BREAK
case 27:
YY_USER_ACTION
# line 90 "sql_lexer.l"
TOK(END)
	YY_BREAK
case 28:
YY_USER_ACTION
# line 91 "sql_lexer.l"
TOK(_FALSE)
	YY_BREAK
case 29:
YY_USER_ACTION
# line 92 "sql_lexer.l"
TOK(FLOAT)
	YY_BREAK
case 30:
YY_USER_ACTION
# line 93 "sql_lexer.l"
TOK(FOREIGN)
	YY_BREAK
case 31:
YY_USER_ACTION
# line 94 "sql_lexer.l"
TOK(FROM)
	YY_BREAK
case 32:
YY_USER_ACTION
# line 95 "sql_lexer.l"
TOK(GROUP)
	YY_BREAK
case 33:
YY_USER_ACTION
# line 96 "sql_lexer.l"
TOK(HAVING)
	YY_BREAK
case 34:
YY_USER_ACTION
# line 97 "sql_lexer.l"
TOK(_IN)
	YY_BREAK
case 35:
YY_USER_ACTION
# line 98 "sql_lexer.l"
TOK(INNER)
	YY_BREAK
case 36:
YY_USER_ACTION
# line 99 "sql_lexer.l"
TOK(INSERT)
	YY_BREAK
case 37:
YY_USER_ACTION
# line 100 "sql_lexer.l"
TOK(INTEGER)
	YY_BREAK
case 38:
YY_USER_ACTION
# line 101 "sql_lexer.l"
TOK(INTO)
	YY_BREAK
case 39:
YY_USER_ACTION
# line 102 "sql_lexer.l"
TOK(JOIN)
	YY_BREAK
case 40:
YY_USER_ACTION
# line 103 "sql_lexer.l"
TOK(KEY)
	YY_BREAK
case 41:
YY_USER_ACTION
# line 104 "sql_lexer.l"
TOK(LIKE)
	YY_BREAK
case 42:
YY_USER_ACTION
# line 105 "sql_lexer.l"
TOK(MIN)
	YY_BREAK
case 43:
YY_USER_ACTION
# line 106 "sql_lexer.l"
TOK(MAX)
	YY_BREAK
case 44:
YY_USER_ACTION
# line 107 "sql_lexer.l"
TOK(NATRUAL)
	YY_BREAK
case 45:
YY_USER_ACTION
# line 108 "sql_lexer.l"
TOK(NOT)
	YY_BREAK
case 46:
YY_USER_ACTION
# line 109 "sql_lexer.l"
TOK(_QUIT)
	YY_BREAK
case 47:
YY_USER_ACTION
# line 110 "sql_lexer.l"
TOK(_NULL)
	YY_BREAK
case 48:
YY_USER_ACTION
# line 111 "sql_lexer.l"
TOK(_NUMERIC)
	YY_BREAK
case 49:
YY_USER_ACTION
# line 112 "sql_lexer.l"
TOK(ON)
	YY_BREAK
case 50:
YY_USER_ACTION
# line 113 "sql_lexer.l"
TOK(OR)
	YY_BREAK
case 51:
YY_USER_ACTION
# line 114 "sql_lexer.l"
TOK(ORDER)
	YY_BREAK
case 52:
YY_USER_ACTION
# line 115 "sql_lexer.l"
TOK(PRECISION)
	YY_BREAK
case 53:
YY_USER_ACTION
# line 116 "sql_lexer.l"
TOK(PRIMARY)
	YY_BREAK
case 54:
YY_USER_ACTION
# line 117 "sql_lexer.l"
TOK(REAL)
	YY_BREAK
case 55:
YY_USER_ACTION
# line 118 "sql_lexer.l"
TOK(REFERENCES)
	YY_BREAK
case 56:
YY_USER_ACTION
# line 119 "sql_lexer.l"
TOK(RESTRICT)
	YY_BREAK
case 57:
YY_USER_ACTION
# line 120 "sql_lexer.l"
TOK(ROLLBACK)
	YY_BREAK
case 58:
YY_USER_ACTION
# line 121 "sql_lexer.l"
TOK(SCHEMA)
	YY_BREAK
case 59:
YY_USER_ACTION
# line 122 "sql_lexer.l"
TOK(SELECT)
	YY_BREAK
case 60:
YY_USER_ACTION
# line 123 "sql_lexer.l"
TOK(SET)
	YY_BREAK
case 61:
YY_USER_ACTION
# line 124 "sql_lexer.l"
TOK(INTEGER)
	YY_BREAK
case 62:
YY_USER_ACTION
# line 125 "sql_lexer.l"
TOK(SUM)
	YY_BREAK
case 63:
YY_USER_ACTION
# line 126 "sql_lexer.l"
TOK(TABLE)
	YY_BREAK
case 64:
YY_USER_ACTION
# line 127 "sql_lexer.l"
TOK(THEN)
	YY_BREAK
case 65:
YY_USER_ACTION
# line 128 "sql_lexer.l"
TOK(_TRUE)
	YY_BREAK
case 66:
YY_USER_ACTION
# line 129 "sql_lexer.l"
TOK(UNION)
	YY_BREAK
case 67:
YY_USER_ACTION
# line 130 "sql_lexer.l"
TOK(UNIQUE)
	YY_BREAK
case 68:
YY_USER_ACTION
# line 131 "sql_lexer.l"
TOK(UPDATE)
	YY_BREAK
case 69:
YY_USER_ACTION
# line 132 "sql_lexer.l"
TOK(VALUES)
	YY_BREAK
case 70:
YY_USER_ACTION
# line 133 "sql_lexer.l"
TOK(VARCHAR)
	YY_BREAK
case 71:
YY_USER_ACTION
# line 134 "sql_lexer.l"
TOK(VARYING)
	YY_BREAK
case 72:
YY_USER_ACTION
# line 135 "sql_lexer.l"
TOK(WHEN)
	YY_BREAK
case 73:
YY_USER_ACTION
# line 136 "sql_lexer.l"
TOK(WHERE)
	YY_BREAK
case 74:
YY_USER_ACTION
# line 137 "sql_lexer.l"
TOK(WORK)
	YY_BREAK
case 75:
YY_USER_ACTION
# line 138 "sql_lexer.l"
TOK(ISTREAM) 
	YY_BREAK
case 76:
YY_USER_ACTION
# line 139 "sql_lexer.l"
TOK(DSTREAM) 
	YY_BREAK
case 77:
YY_USER_ACTION
# line 140 "sql_lexer.l"
TOK(RSTREAM) 
	YY_BREAK
case 78:
YY_USER_ACTION
# line 141 "sql_lexer.l"
TOK(NOW) 
	YY_BREAK
case 79:
YY_USER_ACTION
# line 142 "sql_lexer.l"
TOK(PARTITION) 
	YY_BREAK
case 80:
YY_USER_ACTION
# line 143 "sql_lexer.l"
TOK(ROWS) 
	YY_BREAK
case 81:
YY_USER_ACTION
# line 144 "sql_lexer.l"
TOK(RANGE) 
	YY_BREAK
case 82:
YY_USER_ACTION
# line 145 "sql_lexer.l"
TOK(SECONDS)
	YY_BREAK
case 83:
YY_USER_ACTION
# line 146 "sql_lexer.l"
TOK(MINUTES)
	YY_BREAK
     /* comments */
case 84:
YY_USER_ACTION
# line 150 "sql_lexer.l"
BEGIN(COMMENT);
	YY_BREAK
case YY_STATE_EOF(COMMENT):
# line 152 "sql_lexer.l"
{
  SQLerror("syntax error, end of file in comment,");
}
	YY_BREAK
case 85:
YY_USER_ACTION
# line 155 "sql_lexer.l"
/* eat anything that's not a '*' */
	YY_BREAK
case 86:
YY_USER_ACTION
# line 156 "sql_lexer.l"
/* eat '*'s not followed by '/'s */
	YY_BREAK
case 87:
YY_USER_ACTION
# line 157 "sql_lexer.l"
BEGIN(INITIAL);
	YY_BREAK
	/* comparison */
case 88:
YY_USER_ACTION
# line 161 "sql_lexer.l"
TOK(EQ)
	YY_BREAK
case 89:
YY_USER_ACTION
# line 162 "sql_lexer.l"
TOK(NEQ);
	YY_BREAK
case 90:
YY_USER_ACTION
# line 163 "sql_lexer.l"
TOK(LT)
	YY_BREAK
case 91:
YY_USER_ACTION
# line 164 "sql_lexer.l"
TOK(GT)
	YY_BREAK
case 92:
YY_USER_ACTION
# line 165 "sql_lexer.l"
TOK(LTE)
	YY_BREAK
case 93:
YY_USER_ACTION
# line 166 "sql_lexer.l"
TOK(GTE)
	YY_BREAK
	/* Parameter marker */
case 94:
YY_USER_ACTION
# line 170 "sql_lexer.l"
TOK(PARAM)     
	YY_BREAK
case 95:
YY_USER_ACTION
# line 172 "sql_lexer.l"
TOK(yytext[0])
	YY_BREAK
case 96:
YY_USER_ACTION
# line 173 "sql_lexer.l"
{return yytext[0];}
	YY_BREAK
	/* names */
case 97:
YY_USER_ACTION
# line 177 "sql_lexer.l"
TOK(NAME)
	YY_BREAK
        /* [a-zA-Z][A-Za-z0-9_]*"."[a-zA-Z][A-Za-z0-9_]*  TOK(COLUMN) */
	/* numbers */
case 98:
# line 184 "sql_lexer.l"
case 99:
# line 185 "sql_lexer.l"
case 100:
YY_USER_ACTION
# line 185 "sql_lexer.l"
TOK(INTNUM)
	YY_BREAK
case 101:
# line 188 "sql_lexer.l"
case 102:
# line 189 "sql_lexer.l"
case 103:
YY_USER_ACTION
# line 189 "sql_lexer.l"
TOK(APPROXNUM)
	YY_BREAK
	/* strings */
case 104:
YY_USER_ACTION
# line 193 "sql_lexer.l"
{
                  yytext[strlen(yytext)-1]='\0';
                  SQLlval.oidval = mkstring(yytext+1); SAVE_REF;
		  return STRING;
		}
	YY_BREAK
case 105:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_USER_ACTION
# line 199 "sql_lexer.l"
{SQLerror("Unterminated string");}
	YY_BREAK
	/* whitespace */
case 106:
YY_USER_ACTION
# line 203 "sql_lexer.l"
{;}	/* whitespace */
	YY_BREAK
case 107:
YY_USER_ACTION
# line 205 "sql_lexer.l"
return(_EOF);
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(SQL):
# line 206 "sql_lexer.l"
return(_EOF);
	YY_BREAK
	/* anything else */
case 108:
YY_USER_ACTION
# line 209 "sql_lexer.l"
{SQLerror("syntax error, invalid character");}
	YY_BREAK
case 109:
YY_USER_ACTION
# line 212 "sql_lexer.l"
ECHO;
	YY_BREAK

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = yy_cp - yytext_ptr - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
							yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr - 1; /* copy prev. char, too */
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = yy_c_buf_p - yytext_ptr;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset = yy_c_buf_p - b->yy_ch_buf;

			b->yy_buf_size *= 2;
			b->yy_ch_buf = (char *)
				yy_flex_realloc( (void *) b->yy_ch_buf,
						 b->yy_buf_size );

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move - YY_MORE_ADJ == 1 )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	/* yytext begins at the second character in yy_ch_buf; the first
	 * character is the one which preceded it before reading in the latest
	 * buffer; it needs to be kept around in case it's a newline, so
	 * yy_get_previous_state() will have with '^' rules active.
	 */

	yytext_ptr = &yy_current_buffer->yy_ch_buf[1];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 43);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 400 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 43;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 400 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 399);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += dest - source;
		yy_bp += dest - source;
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	if ( yy_cp > yy_bp && yy_cp[-1] == '\n' )
		yy_cp[-2] = '\n';

	*--yy_cp = (char) c;


	/* Note: the formal parameter *must* be called "yy_bp" for this
	 * macro to now work correctly.
	 */
	YY_DO_BEFORE_ACTION; /* set up yytext again */
	}


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );

	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );

	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	yy_flex_free( (void *) b->yy_ch_buf );
	yy_flex_free( (void *) b );
	}


#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif
	{
	b->yy_input_file = file;

	/* We put in the '\n' and start reading from [1] so that an
	 * initial match-at-newline will be true.
	 */

	b->yy_ch_buf[0] = '\n';
	b->yy_n_chars = 1;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[2] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[1];

	b->yy_is_interactive = file ? isatty( fileno(file) ) : 0;

	b->yy_fill_buffer = 1;

	b->yy_buffer_status = YY_BUFFER_NEW;
	}


#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		int new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}


static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}


static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}


#ifdef YY_USE_PROTOS
static void yy_fatal_error( const char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( 1 );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, const char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
const char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( unsigned int size )
#else
static void *yy_flex_alloc( size )
unsigned int size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, unsigned int size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
unsigned int size;
#endif
	{
	return (void *) realloc( ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}
# line 212 "sql_lexer.l"




int SQLwrap(void)
{
  return 1;
}
