SWARD_ROOT = $(AMOS_HOME)/SWARD/
all:
	cd ../src/Java/ && javac -classpath .:$(AMOS_HOME)/bin/javaamos.jar:$(CLASSPATH) -d $(SWARD_ROOT)/classes JavaCharStream.java JJTRdql2AmosState.java Node.java ParseException.java Rdql2Amos.java Rdql2AmosConstants.java Rdql2AmosTokenManager.java Rdql2AmosTreeConstants.java SimpleNode.java Start.java Token.java TokenMgrError.java