#Edutella Configuration Properties
#

### Provider related properties ###

# file name(s) of knowledge base
#provider.modelFile=samples/books.rdf

### Output/Logging related properties ###

# if set, output is written to a Swing console window
#  console.swing=false

# if set, output is written to this file
#  console.logFile=mylog.txt

# if set, output still appears on console, even if console.swing or console.logFile are set
# console.force=false

# edutella.logconfig=log4j.properties

### JXTA related properties ###

# JXTA_HOME directory, where JXTA stores its config files. This may either be a full path
# or a path fragment. In the latter case JXTA_HOME is set to <user_home_dir>.edutella/<configDir>
jxta.configDir=jxtaconfig/provider

# enable/disable automatic JXTA configuration.
jxta.autoConfig=true

# semicolon or comma delimited list of rendezvous
#jxta.rendezvous=http://130.75.87.3:9700;http://130.75.152.40:9700;
jxta.rendezvous=tcp://130.237.228.95:9701

# Old rendezvous points
#http://130.75.87.3:9700;http://130.75.152.40:9700;
#tcp://130.75.87.3:9701;tcp://130.75.152.40:9701;
#tcp://130.237.228.67:9711;

# semicolon or comma delimited list of relays
#jxta.relays=http://130.75.87.3:9700;http://130.75.152.40:9700;
jxta.relays=tcp://130.237.228.95:9701

# Old relay points
#http://130.75.87.3:9700;http://130.75.152.40:9700
#tcp://130.237.228.67:9711;

# if set to true, JXTA configurator panel will show up
#jxta.reconf=true

# preferred TCP port
jxta.tcpPort=9702

# if preferred port not available, search for a free port between lowPort and highPort (inclusive)
jxta.lowPort=9702
jxta.highPort=9780

# proxy address and port. This proxy will be used for all HTTP traffic
#jxta.proxyAddr=myproxy.mydomain.org:8080

#localHostAddr=130.238.11.125;