create table CUSTOMER(CUSTID integer not null,
		      MKTSEGMENT varchar(10),
		      primary key (CUSTID));



create table LIFEEVENT(EID varchar(25) not null,
			LANG varchar(25),
			DESCR varchar(25),
			LAW varchar(25),
			FORM varchar(50),
			primary key (EID));


CREATE TABLE AUTHORS(
	AUTHOR_ID INTEGER NOT NULL, 
	NAME VARCHAR(50),
	SURNAME VARCHAR(50),
	PRIMARY KEY(AUTHOR_ID)
);

CREATE TABLE BOOKS(
	BOOK_ID INTEGER  NOT NULL, 
	AUTHOR_ID INTEGER, 
	TITLE1 VARCHAR(200), 
	DESCRIPTION VARCHAR(200), 
	PRICE INTEGER, 
	PAGES1 INTEGER, 
	PRIMARY KEY(BOOK_ID)
);


CREATE TABLE ORDERS1(
	ORDER_ID INTEGER NOT NULL,
	BYER_NAME VARCHAR(100),
	SHIPPING_ADRESS VARCHAR(100),
	SHIPPING_ZIPCODE VARCHAR(10),
	SHIPPING_CITY VARCHAR(30),
	PRIMARY KEY(ORDER_ID)
);



CREATE TABLE ORDER_ITEMS(
	ORDER_ITEM_ID INTEGER NOT NULL,
	ORDER_ID INTEGER,
	BOOK_ID INTEGER,
	QUANTITY INTEGER,
	PRIMARY KEY(ORDER_ITEM_ID)
);

CREATE TABLE cross_rate
(
    from_currency   VARCHAR(10) NOT NULL,
    to_currency     VARCHAR(10) NOT NULL,
    conv_rate       FLOAT NOT NULL,	
    update_date     DATE,
    snum	    INTEGER,

    PRIMARY KEY (from_currency, to_currency)
);

CREATE TABLE bus
(
    snum1   VARCHAR(10),
    name   VARCHAR(10) NOT NULL,
    PRIMARY KEY (name)	
);


create table FAQLISTS(EID varchar(25) not null,
			FAQNR integer not null,
			QUESTION varchar(50),
			NUMBER varchar(25),
			primary key (EID,FAQNR));

create table RELATEDSERVICES(EID varchar(25) not null,
			SERVICENR integer not null,
			TITLE varchar(50),
			primary key (EID,SERVICENR));


insert into LIFEEVENT 
	(EID, LANG, DESCR, LAW, FORM) 
	values 
	('ABC1234H','EN','Getting married','FRC234','http://www.eGov.org/marriage.html'); 


insert into LIFEEVENT 
	(EID, LANG, DESCR, LAW, FORM) 
	values 
	('ABC1234H1','EN1','Getting married1','FRC2341','http://www.eGov.org/marriage.html1'); 



insert into CUSTOMER (CUSTID, MKTSEGMENT) values (120,'AUTOMOBILE'); 
insert into CUSTOMER (CUSTID, MKTSEGMENT) values (121,'AUTOMOB1'); 
insert into CUSTOMER (CUSTID, MKTSEGMENT) values (122,'AUTOMOB2'); 
insert into CUSTOMER (CUSTID, MKTSEGMENT) values (123,'AUTOMOB3'); 

INSERT INTO cross_rate VALUES ('Dollar', 'CdnDlr',  1.3273,  '11/22/93',1);
INSERT INTO cross_rate VALUES ('Dollar', 'FFranc',  5.9193,  '11/22/93',2);
INSERT INTO cross_rate VALUES ('Dollar', 'Rupee',  38.0212,  '06/25/07',3);
INSERT INTO cross_rate VALUES ('Dollar',  'sek',    6.8193,  '06/25/07',4);

INSERT INTO bus VALUES ('123','TORG');
INSERT INTO bus VALUES('1234','TORG2');
INSERT INTO bus VALUES ('801','ARLANDA');
INSERT INTO bus VALUES('859','STOCKHOLM');



insert into FAQLISTS 
	(EID, FAQNR, QUESTION, NUMBER) 
	values
	('ABC1234M',1,'Possibillity to get married online','Yes');


insert into FAQLISTS 
	(EID, FAQNR, QUESTION, NUMBER) 
	values
	('ABC1234M1',2,'Possibillity to get married online1','Yes1');




insert into RELATEDSERVICES  
	(EID, SERVICENR, TITLE) 
	values
	('ABC1234H', 1, 'Issuing a birth certificate');


insert into RELATEDSERVICES  
	(EID, SERVICENR, TITLE) 
	values
	('ABC1234H', 2, 'Online payment');




INSERT INTO AUTHORS(AUTHOR_ID,NAME, SURNAME) VALUES(1,'GREG', 'BARISH');
INSERT INTO AUTHORS(AUTHOR_ID,NAME,SURNAME) VALUES(2,'TIMOTHY', 'BUDD');
INSERT INTO AUTHORS(AUTHOR_ID,NAME,SURNAME) VALUES(3,'MARK', 'WUTKA');
INSERT INTO AUTHORS(AUTHOR_ID,NAME,SURNAME) VALUES(4,'H.M', 'DIETEL');

INSERT INTO BOOKS(BOOK_ID,AUTHOR_ID, TITLE1, DESCRIPTION, PRICE, PAGES1) 
	VALUES(1, 1, 'BUILDNING SCALABLE AND HIGH-PERFORMANCE JAVA WEB APPLICATIONS USING J2EE TECHNOLOGY', 'A BOOK ABOUT BUILDNING SCALABLE AND HIGH-PERFORMANCE JAVA WEB APPLICATIONS USING J2EE TECHNOLOGY. THE BOOKS DESCRIBES HOW TO USE THE DIFFERENT PARTS OF J2EE TO BUILD A WEB APPLICATION', 600, 392);

INSERT INTO BOOKS(BOOK_ID,AUTHOR_ID, TITLE1, DESCRIPTION, PRICE, PAGES1) VALUES(2, 2, 'CLASSIC DATA STRUCTURES IN C++', 'BUDD EXPLAINS SEVERAL DATA STRUCTURES THAT ARE COMMIN IN C++', 550, 537);

INSERT INTO BOOKS(BOOK_ID,AUTHOR_ID, TITLE1, DESCRIPTION, PRICE, PAGES1) VALUES(3, 2, 'CLASSIC DATA STRUCTURES IN JAVA', 'BUDD EXPLAINS SEVERAL DATA STRUCTURES THAT ARE COMMIN IN JAVA', 650, 437);

INSERT INTO BOOKS(BOOK_ID,AUTHOR_ID, TITLE1, DESCRIPTION, PRICE, PAGES1) VALUES(4, 3, 'SPECIAL EDITION USING JAVA SERVER PAGES', 'A QUITE EXTENSIVE BOOK ABOUT WEB DEVELOPMENT USING JAVA SERVER PAGES AND JAVA SERVLETS', 400, 351);

INSERT INTO BOOKS(BOOK_ID,AUTHOR_ID, TITLE1, DESCRIPTION, PRICE, PAGES1) VALUES(5, 4, 'C: HOW TO PROGRAM', 'AN INTRODUCTION TO C-PROGRAMMING.', 430, 800);

INSERT INTO ORDERS1(ORDER_ID,BYER_NAME,SHIPPING_ADRESS,SHIPPING_ZIPCODE,SHIPPING_CITY) VALUES(1, 'SANTOSH','UPPSALA', '75237', 'UPPSALA1');

INSERT INTO ORDERS1(ORDER_ID,BYER_NAME,SHIPPING_ADRESS,SHIPPING_ZIPCODE,SHIPPING_CITY) VALUES(2, 'SANTOSH REDDY','CENTRUM', '73534', 'STKHLM');

INSERT INTO ORDER_ITEMS(ORDER_ITEM_ID,ORDER_ID,BOOK_ID,QUANTITY) VALUES(1,1,1,5);

INSERT INTO ORDER_ITEMS(ORDER_ITEM_ID,ORDER_ID,BOOK_ID,QUANTITY) VALUES(2,2,2,3);

INSERT INTO ORDER_ITEMS(ORDER_ITEM_ID,ORDER_ID,BOOK_ID,QUANTITY) VALUES(3,3,3,8);

