#!/usr/bin/env python3
"""Generate C_API.md: the public C API declared in AmosNT_floq/C/*.h.

For every EXTERN/EXPORT/extern declaration: its header and section (/*** Section ***/), the
declaration, its comment (same line or the indented comment line below), and where it is
implemented: a system/C source file, or (from `nm`) a binary-only object in system/MVC/.

Usage (from Amos2/):  python3 tools/gen_c_api.py > C_API.md
Needs `nm` on PATH for the binary-only column (it reads the COFF symbol tables).
"""
import os
import re
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_lsp_index as lspidx  # noqa: E402

ROOT = lspidx.ROOT
CDIR = os.path.join(ROOT, "C")
SKIP_HEADERS = {"jni.h", "jni_md.h"}  # Java's own headers, copied in
DECL_RE = re.compile(r"^[ \t]*(EXTERN|EXPORT|extern)\b", re.M)
SECTION_RE = re.compile(r"^/\*{2,3}\s*(.*?)\s*\*{2,3}/\s*$")


def binary_symbols():
    """Map symbol -> module for functions defined in system/MVC/*.obj."""
    out = {}
    mvc = os.path.join(ROOT, "system", "MVC")
    if not shutil.which("nm") or not os.path.isdir(mvc):
        return out
    for f in sorted(os.listdir(mvc)):
        if f.endswith(".obj"):
            r = subprocess.run(["nm", os.path.join(mvc, f)], capture_output=True, text=True)
            for line in r.stdout.splitlines():
                parts = line.split()
                if len(parts) == 3 and parts[1] == "T":
                    out.setdefault(parts[2].lstrip("_"), f[:-4])
    return out


def source_definitions(names):
    """Map name -> (path, line) for definitions in system/C/**.c."""
    out = {}
    src = os.path.join(ROOT, "system", "C")
    for d, _, fs in os.walk(src):
        if "CVS" in d:
            continue
        for f in fs:
            if f.endswith(".c"):
                p = os.path.join(d, f)
                t = lspidx.read(p)
                for m in re.finditer(r"^[A-Za-z_][^;\n]*?\b([A-Za-z_]\w*)\s*\([^;{]*$", t, re.M):
                    n = m.group(1)
                    if n in names and n not in out:
                        out[n] = (os.path.relpath(p, os.path.join(ROOT, "..")), t.count("\n", 0, m.start()) + 1)
    return out


def declarations(path):
    t = lspidx.read(path)
    lines = t.split("\n")
    section = ""
    sec_at = {}
    for n, l in enumerate(lines, 1):
        m = SECTION_RE.match(l.strip())
        if m and m.group(1).strip("* "):
            section = m.group(1).strip("* ")
        sec_at[n] = section
    out = []
    for m in DECL_RE.finditer(t):
        start = m.start()
        end = t.find(";", start)
        if end < 0:
            continue
        decl = t[start:end + 1]
        if "{" in decl or decl.count("\n") > 8:
            continue
        line = t.count("\n", 0, start) + 1
        last = t.count("\n", 0, end) + 1
        body = re.sub(r"/\*.*?\*/", " ", decl, flags=re.S)
        body = " ".join(re.sub(r"^\s*(EXTERN|EXPORT|extern)\s+", "", body).split())
        comment = ""
        rest = lines[last - 1][lines[last - 1].find(";") + 1:]
        cm = re.search(r"/\*(.*?)\*/", rest)
        if cm:
            comment = cm.group(1)
        elif last < len(lines) and re.match(r"^\s+/\*.*\*/\s*$", lines[last]):
            comment = re.search(r"/\*(.*?)\*/", lines[last]).group(1)
        inl = re.search(r"/\*(.*?)\*/", decl, re.S)
        if not comment and inl:
            comment = inl.group(1)
        name_m = re.search(r"\(?\s*\*?\s*([A-Za-z_]\w*)\s*\)?\s*\(", body)
        is_fn = bool(name_m) and not body.startswith("typedef")
        name = name_m.group(1) if is_fn else (re.findall(r"([A-Za-z_]\w*)\s*(?:\[[^\]]*\])?\s*;?$", body) or [""])[0]
        out.append((line, sec_at.get(line, ""), name, body, " ".join(comment.split()), is_fn))
    return out


def main():
    headers = sorted(f for f in os.listdir(CDIR) if f.endswith(".h") and f not in SKIP_HEADERS)
    decls = {h: declarations(os.path.join(CDIR, h)) for h in headers}
    names = {d[2] for ds in decls.values() for d in ds if d[5]}
    binsym = binary_symbols()
    srcdef = source_definitions(names)

    total = sum(len(v) for v in decls.values())
    fns = [d for ds in decls.values() for d in ds if d[5]]
    n_src = sum(1 for d in fns if d[2] in srcdef)
    n_bin = sum(1 for d in fns if d[2] not in srcdef and d[2] in binsym)
    w = sys.stdout.write
    w("# Public C API (`C/*.h`)\n\n")
    w("Every declaration exported by the headers in [AmosNT_floq/C/](AmosNT_floq/C/), the API for C programs that\n")
    w("embed Amos II (*callin*) or implement AmosQL functions in C (*callout*). Generated by\n")
    w("[tools/gen_c_api.py](tools/gen_c_api.py). Do not edit by hand; rerun the script.\n")
    w("How the API is used: [KERNEL.md §6–7](KERNEL.md#6-the-c--lisp-bridge); examples in\n")
    w("[C/](AmosNT_floq/C/) (`amosdemo.c`, `callout.cpp`) and [demo/](AmosNT_floq/demo/).\n\n")
    w(f"- **{total}** declarations in **{len(decls)}** headers ({len(fns)} functions). `jni.h`/`jni_md.h` "
      "(Java's own headers) are skipped.\n")
    w(f"- **Implemented in**: for functions, where the body is. **{n_src}** are defined in `system/C` source "
      f"(linked). **{n_bin}** exist only in a binary object in `system/MVC/` (named by module, from `nm`; "
      "see [KERNEL.md §2](KERNEL.md#2-what-has-source-and-what-doesnt)). Blank means neither was found: a macro, "
      "a function defined elsewhere (e.g. JavaAmos), or one missing from this checkout.\n")
    w("- **Section** is the nearest preceding `/*** … ***/` heading in the header.\n")
    w("- **Comment** is the header's own comment for that declaration.\n\n")
    w("## Headers\n\n| Header | Declarations |\n|---|---|\n")
    for h in headers:
        if decls[h]:
            w(f"| [{h}](#{re.sub(r'[^a-z0-9_ -]', '', h.lower())}) | {len(decls[h])} |\n")
    w("\n")
    for h in headers:
        if not decls[h]:
            continue
        w(f"## {h}\n\n[Source](AmosNT_floq/C/{h})\n\n")
        w("| Section | Declaration | Comment | Implemented in | Line |\n|---|---|---|---|---|\n")
        for line, sec, name, body, comment, is_fn in decls[h]:
            impl = ""
            if is_fn:
                if name in srcdef:
                    p, l = srcdef[name]
                    impl = f"[{os.path.basename(p)}:{l}]({p}#L{l})"
                elif name in binsym:
                    impl = f"binary `{binsym[name]}.obj`"
            w(f"| {lspidx.md(sec)} | `{lspidx.code(body)}` | {lspidx.md(comment)} | {impl} | "
              f"[{line}](AmosNT_floq/C/{h}#L{line}) |\n")
        w("\n")


if __name__ == "__main__":
    main()
