#!/usr/bin/env python3
"""Generate GRAMMAR_MAP.md: which Lisp form each AmosQL grammar rule builds, and what handles it.

For every rule in AmosNT_floq/system/C/parser.y, collect the head symbols its actions put at
the front of a constructed list (cons/a_list/list2/... with mksymbol("head") first). Each head
is then looked up among lsp/ defun/defmacro definitions and system/C extfunction registrations.

Usage (from Amos2/):  python3 tools/gen_grammar_map.py > GRAMMAR_MAP.md
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_lsp_index as lspidx  # noqa: E402

ROOT = lspidx.ROOT
PARSER = os.path.join(ROOT, "system", "C", "parser.y")
CSRC = os.path.join(ROOT, "system", "C")
RULE_RE = re.compile(r"^([a-z_][a-z_0-9]*)\s*:", re.M)
HEAD_RE = re.compile(r'\b(?:a_list|cons|list[1-9]|a_cons)\s*\(\s*mksymbol\s*\(\s*"([^"]+)"\s*\)')
REG_RE = re.compile(r'extfunction[0-5nq]\s*\(\s*"([^"]+)"')


def main():
    text = lspidx.read(PARSER)
    starts = [(m.start(), m.group(1)) for m in RULE_RE.finditer(text)]

    lisp = {}
    for f in os.listdir(lspidx.LSP):
        if f.endswith(".lsp"):
            for kind, name, line, doc, quoted in lspidx.definitions(os.path.join(lspidx.LSP, f)):
                if not quoted:
                    lisp.setdefault(name.lower(), []).append((f, line, kind))
    cbuilt = {}
    for d, _, fs in os.walk(CSRC):
        for f in fs:
            if f.endswith(".c"):
                p = os.path.join(d, f)
                t = lspidx.read(p)
                for m in REG_RE.finditer(t):
                    cbuilt.setdefault(m.group(1).lower(), (os.path.relpath(p, os.path.join(ROOT, "..")),
                                                          t.count("\n", 0, m.start()) + 1))

    rows, heads_seen = [], set()
    for k, (pos, rule) in enumerate(starts):
        end = starts[k + 1][0] if k + 1 < len(starts) else len(text)
        heads = []
        for m in HEAD_RE.finditer(text, pos, end):
            h = m.group(1)
            if h not in heads:
                heads.append(h)
        if heads:
            rows.append((rule, text.count("\n", 0, pos) + 1, heads))
            heads_seen.update(h.lower() for h in heads)

    def handler(h):
        out = []
        for f, line, kind in lisp.get(h.lower(), []):
            out.append(f"[{f}:{line}](AmosNT_floq/lsp/{f}#L{line})" + (" macro" if kind == "defmacro" else ""))
        if h.lower() in cbuilt:
            p, line = cbuilt[h.lower()]
            out.append(f"[{os.path.basename(p)}:{line}]({p}#L{line}) C")
        return ", ".join(out)

    w = sys.stdout.write
    w("# AmosQL grammar → Lisp forms\n\n")
    w("For each rule in [parser.y](AmosNT_floq/system/C/parser.y), the Lisp forms its actions build, and\n")
    w("where a function or macro of that name is defined. Generated by\n")
    w("[tools/gen_grammar_map.py](tools/gen_grammar_map.py). Do not edit by hand; rerun the script.\n")
    w("Context: [KERNEL.md §5](KERNEL.md#5-the-grammars) (parsing) and\n")
    w("[QUERY_COMPILER.md §4.1](QUERY_COMPILER.md#41-from-parsed-statement-to-derived-function) (what\n")
    w("happens when a form is evaluated).\n\n")
    w("How to read it:\n\n")
    w("- The parser builds a Lisp list whose first element is the **head** symbol, e.g.\n")
    w("  `select_stmt1` builds `(osql-select …)`. `parse_and_eval` then evaluates that list, so the head is\n")
    w("  called as a function, macro or special form.\n")
    w("- **Defined in** lists `defun`/`defmacro` definitions in `lsp/` (\"macro\" marks a macro) and C\n")
    w("  built-ins registered in `system/C` (\"C\"). Several links mean several definitions of that name.\n")
    w("- **Blank** means no Lisp or C definition was found. Most blanks are one of:\n")
    w("  - **AmosQL function names inside query expressions** (`plus`, `times`, `<`, `vref`, `and`, `or`,\n")
    w("    …). These sit inside an `osql-select`/`select` form and are never evaluated as Lisp. The\n")
    w("    query compiler looks them up as AmosQL functions while flattening\n")
    w("    ([QUERY_COMPILER.md §4.2](QUERY_COMPILER.md#42-flattening-overload-resolution-and-type-checks-compileselect)).\n")
    w("  - **Keyword markers** read by an enclosing handler (`distinct`, `into`, `foreach`, `where`,\n")
    w("    `foreign`, `KEY`, `as`, …).\n")
    w("  - **Special forms or built-ins of the binary-only kernel** (`quote`, `commit`, `rollback`, …),\n")
    w("    or names defined some other way, e.g. by `movd`.\n")
    w("- Only heads written as `mksymbol(\"…\")` at the front of `a_list`/`cons`/`listN` are found. Forms\n")
    w("  built through a variable (e.g. `a_list(lispsymbol, …)`) are missed.\n\n")
    w(f"{len(rows)} rules build {len(heads_seen)} distinct heads.\n\n")
    w("| Rule | Line | Builds | Defined in |\n|---|---|---|---|\n")
    for rule, line, heads in rows:
        for i, h in enumerate(heads):
            r = f"`{rule}`" if i == 0 else ""
            l = f"[{line}](AmosNT_floq/system/C/parser.y#L{line})" if i == 0 else ""
            w(f"| {r} | {l} | `({h} …)` | {handler(h)} |\n")


if __name__ == "__main__":
    main()
