#!/usr/bin/env python3
"""Generate C_BUILTINS.md: every Lisp built-in registered from the C kernel sources.

Scans AmosNT_floq/system/C/**/*.c for extfunctionN("lisp-name", c_function) calls and,
for each, finds where c_function is defined in the same source tree.
Only modules with source are covered; see KERNEL.md §2 for the binary-only ones.

Usage (from Amos2/):  python3 tools/gen_c_builtins.py > C_BUILTINS.md
"""
import os
import re
import sys
from collections import defaultdict

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "AmosNT_floq")
SRC = os.path.join(ROOT, "system", "C")
REG_RE = re.compile(r'extfunction([0-5nq])\s*\(\s*"([^"]+)"\s*,\s*([A-Za-z_][A-Za-z_0-9]*)')
ARITY = {"n": "variable", "q": "variable, unevaluated (presumably)"}


def read(path):
    with open(path, "rb") as f:
        return f.read().decode("latin-1").replace("\r\n", "\n").replace("\r", "\n")


def c_files():
    for d, _, fs in os.walk(SRC):
        if "CVS" in d:
            continue
        for f in sorted(fs):
            if f.endswith(".c"):
                yield os.path.join(d, f)


def main():
    texts = {p: read(p) for p in c_files()}
    regs = []
    for p, t in texts.items():
        for m in REG_RE.finditer(t):
            if t.rfind("//", t.rfind("\n", 0, m.start()), m.start()) != -1:
                continue  # commented out with //
            line = t.count("\n", 0, m.start()) + 1
            regs.append((p, line, m.group(1), m.group(2), m.group(3)))

    wanted = {r[4] for r in regs}
    defs = defaultdict(list)
    for p, t in texts.items():
        for fn in wanted:
            for m in re.finditer(r"^[A-Za-z_][^;\n(]*\b" + re.escape(fn) + r"\s*\([^;]*$", t, re.M):
                defs[fn].append((p, t.count("\n", 0, m.start()) + 1))
                break

    rel = lambda p: os.path.relpath(p, os.path.join(ROOT, ".."))
    out = sys.stdout.write
    by_file = defaultdict(list)
    for r in regs:
        by_file[r[0]].append(r)

    out("# C built-ins registered from `system/C`\n\n")
    out("Every `extfunctionN(\"lisp-name\", c_function)` call in [AmosNT_floq/system/C/](AmosNT_floq/system/C/),\n")
    out("generated by [tools/gen_c_builtins.py](tools/gen_c_builtins.py). Do not edit by hand; rerun the script.\n")
    out("How the mechanism works: [KERNEL.md §6](KERNEL.md#6-the-c--lisp-bridge).\n\n")
    out(f"- **{len(regs)}** registrations in **{len(by_file)}** files.\n")
    out("- **Arity**: the `N` in `extfunctionN`, the number of arguments. `n` is variable; `q` is variable\n"
        "  and, presumably, unevaluated (`evalargs` can be `NO_EVAL`, `C/alisp.h:40`).\n")
    out("- **Defined at**: the first line in `system/C` that looks like the C function's definition. Blank if\n"
        "  none was found.\n")
    out("- **Not covered**: built-ins registered by the binary-only modules (`eval`, `storage`, `rel`,\n"
        "  `olog`, `extfns`, …). They have no source here; [KERNEL.md §2](KERNEL.md#2-what-has-source-and-what-doesnt)\n"
        "  lists them from their symbol tables. Built-ins registered outside `system/C` (extenders,\n"
        "  wrappers) are not covered either.\n\n")

    out("## Files\n\n| File | Registrations |\n|---|---|\n")
    for p in sorted(by_file, key=lambda p: (-len(by_file[p]), p)):
        name = os.path.relpath(p, SRC)
        anchor = re.sub(r"[^a-z0-9_ -]", "", name.lower())
        out(f"| [{name}](#{anchor}) | {len(by_file[p])} |\n")
    out("\n")

    for p in sorted(by_file, key=lambda p: os.path.relpath(p, SRC)):
        out(f"## {os.path.relpath(p, SRC)}\n\n| Lisp name | C function | Arity | Registered | Defined at |\n|---|---|---|---|---|\n")
        for _, line, ar, lname, cfn in sorted(by_file[p], key=lambda r: r[1]):
            d = defs.get(cfn)
            where = f"[{os.path.relpath(d[0][0], SRC)}:{d[0][1]}]({rel(d[0][0])}#L{d[0][1]})" if d else ""
            out(f"| `{lname}` | `{cfn}` | {ARITY.get(ar, ar)} | [{line}]({rel(p)}#L{line}) | {where} |\n")
        out("\n")


if __name__ == "__main__":
    main()
