;;; ============================================================
;;; AMOS2
;;; 
;;; Author: (c) 1998 Timour Katchaounov, EDSLAB
;;; $RCSfile: qd_treedistr.lsp,v $
;;; $Revision: 1.28 $ $Date: 2006/04/22 06:39:46 $
;;; $State: Exp $ $Locker:  $
;;;
;;; Description: MDB query plan optimization of multidatabase query plans.
;;;              New Decomposition Trees are generated by
;;;              merging consecutive SAE nodes, thus distributing the
;;;              decomposition tree.
;;;              The tree with minimal cost is chosen as a result.
;;;
;;;              TODO: all function are built on the assumption that 
;;;                    tNode-mbl actually contains one element.
;;;                    FIX IT with (mapcar ...) instead of getting the 
;;;                    CAR of tNode-mbl.
;;;              TODO: also it is assumed that tNode-ppl consists 
;;;                    only of one gNode.
;;; =============================================================
;;; $Log: qd_treedistr.lsp,v $
;;; Revision 1.28  2006/04/22 06:39:46  torer
;;; *** empty log message ***
;;;
;;; Revision 1.27  2006/04/12 19:17:45  torer
;;; Cost profile of predicate now always on format (COST FANOUT [pred])
;;;
;;; =============================================================


; controls strategy
; use_best   - select the better node
; always_merge  - always select the merged node
(defglobal _DISTRIBUTE-TREE-STRATEGY_ 'use_best)

(defun distribute-tree (dTree)
"Traverses a Decomposition Tree, searches for consecutive nodes wich
 are 'mergeable', merges all these nodes into one single node in case
 the total cost of the tree is MINIMIZED.
 Main entry point. Must be called before gen_decomposed_pred.
 Called in decompose_pred.
 In : dTree of type tNode - the input Decomposition Tree
 Out: returns a tree with possibly mergerd nodes"
  (if _DISTRIBUTE-TREE_
      (let* ((root dTree)
	     (curr-subtree dTree)
	     (new-subtree NIL)
	     (up-node dTree)
	     (bot-node (car (tNode-mbl up-node)))
	     (up-father NIL)  ; the father of the upper node
	     (force_merge? (equal _DISTRIBUTE-TREE-STRATEGY_ 'always_merge)))

	(while (not (null bot-node))
	  (if (mergeable? up-node bot-node)
	      (progn
		(setq new-subtree (merge-tNodes up-node bot-node))
		(if (or force_merge?
			(< (tNode-cost new-subtree) (tNode-cost curr-subtree)))
		    (progn ; successfull merge
		      (setq curr-subtree new-subtree)
		      (setq up-node new-subtree)
		      (if (null up-father)
			  (setq root new-subtree)                       ; at top of the tree
			  (rplaca (tNode-mbl up-father) new-subtree)))  ; inside the tree
		    (progn
		      (setq up-father up-node)
		      (setq curr-subtree bot-node)
		      (setq up-node bot-node))))
	      (progn
		(setq up-father up-node)
		(setq curr-subtree bot-node)
		(setq up-node bot-node)))
	  (setq bot-node (car (tNode-mbl bot-node))))
	root)
      dTree))

(defun mergeable? (top-node bot-node)
"Check if two nodes are mergable (how?).
 TODO: Generalize it, so we can merge 2 nodes in the same DB."
  (and (null (tNode-ppl bot-node)) ; bottom node has no Post Processing Node (PPL)
       (neq (gNode-db (tNode-sae top-node))   ; the two nodes are to be executed in
	    (gNode-db (tNode-sae bot-node)))  ; different databases.
       ))

(defun merge-tNodes (topNode botNode)
"Merge two tNodes.
 In : topNode, botNode - a couple of nodes, one is parent for the other
 Out: a new Decomposition Tree node. Most data is copied from the topNode.
           - mbl of the node points to the child of the bottom node.
           - sae is a merge between the sae of both input nodes."
  (assert (eq (car (tNode-mbl topNode)) botNode) "merge-tNodes: Incompatible nodes.")

  (let* ((res       (tNode-res      topNode))
	 (restypes  (tNode-restypes topNode))
	 (ppl       (tNode-ppl      topNode))
	 (ppl-input
	  (if (null ppl)
	      nil
	      (let* ((ppl-vars  (mapcan (f/l (gn) (gNode-vars     gn)) ppl))
		     (ppl-types (mapcan (f/l (gn) (gNode-vartypes gn)) ppl))
		     (ppl-bpat  (mapcan (f/l (gn) (gNode-bpat     gn)) ppl)))
		(get-bound-vars (vinfo-unique (varInfo ppl-vars ppl-types ppl-bpat))))))
	 (sae-io-suspects (append ppl-input (varInfo res restypes '+)))
;(dummy (bp merge-tn))
	 (newTreeNode
	  (make-tNode
	   :db         (tNode-db  topNode)
	   :mbl        (tNode-mbl botNode)
	   :sae        (merge-sae-nodes
			(tNode-sae topNode) (tNode-sae botNode) sae-io-suspects)
	   :ppl        ppl
	   :pplCost    (tNode-pplCost topNode)
	   :cost       NIL    ; it is calculated below.
	   :fanout     (tNode-fanout topNode)
	   :rem        (tNode-rem topNode)
	   :res        res
	   :restypes   restypes
	   :params     (tNode-params     topNode)
	   :paramtypes (tNode-paramtypes topNode)))
	   ; TODO: these two are set only to check if they are equal to the ones
	   ; coming from the topNode. So check it.
	 (new-fanout (get_tNode_fanout newTreeNode))
	 (new-res    (get_tNode_res    newTreeNode)))
    ; if they are not the same, then they should be set up here:
    ; (setf (tNode-fanout newTreeNode) (get_tNode_fanout newTreeNode))
    ; (setf (tNode-res    newTreeNode) (get_tNode_res    newTreeNode))
    ; calculate the new cost of the node.
    (setf (tNode-cost newTreeNode) (get_tNode_cost newTreeNode))
    newTreeNode))

(defun get-locals-and-io (top-vnfo-lst bot-vnfo-lst sae-io-suspects)
  (let ((locals NIL)
	(iovars NIL)
        var-type)
    (do* ((rest  top-vnfo-lst   (cdr rest))
	  (top-vnfo (car rest)  (car rest)))
	 ((null rest) (list locals iovars))
	 (setq var-type (get-var-type top-vnfo bot-vnfo-lst sae-io-suspects))
	 (cond
	  ((equal var-type 'local) (push top-vnfo locals))
	  ((equal var-type 'io-)   (push top-vnfo iovars))
	  ((equal var-type 'io+)   (progn
				     (setf (varInfo-bind top-vnfo) '+)
				     (push top-vnfo iovars)))))))
 
(defun get-var-type (top-vnfo bot-vnfo-lst sae-io-suspects)
"Check if a variable is an I/O or a local one in respect to vtb-lst."
  (let ((top-var  (varInfo-name top-vnfo))
	(top-bind (varInfo-bind top-vnfo)))
    (do* ((rest bot-vnfo-lst (cdr rest))
	  (bot-vnfo (car rest) (car rest)))
	 ((null rest))
	 ; if both variables have the same names
	 (if (equal top-var (varInfo-name bot-vnfo))
	     (progn
	       (assert (neq top-bind '+) "Illegal unbound variable in top sae node.")
	       (cond ((equal (varInfo-bind bot-vnfo) '-)
		      (return 'io-))
		     ((equal (varInfo-bind bot-vnfo) '+)
		      (if (member top-var (varname-lst sae-io-suspects))
			  (return 'io+) ; it MUST be output (unbound)
		          (return 'local)))))))))

(defun get-predl-vars (node)
"Order variables which will be used in a call to a function in the right order."
  (let* ((all-vars (mapcar #'list (gNode-vars node) (gNode-bpat node)))
	 (input-vars (mapfilter (f/l (v-b) (if (equal (second v-b) '-) T))
				all-vars
				#'car))
	 (output-vars (mapfilter (f/l (v-b) (if (equal (second v-b) '+) T))
				 all-vars
				 #'car))
	 (param-vars (gNode-params node)))
    (append input-vars param-vars output-vars)))

(defun merge-sae-nodes (topGNode botGNode sae-io-suspects)
"Merge two SAE nodes (gNode structures).
 The '-vtb' suffix stands for vars-types-bindings."

  ;(formatl t "merging " (gNode-db  topGNode) " + " (gNode-db  botGNode) t)
  (let* ((top-vtb-old (gNode-vars-varInfo topGNode))
	 (bot-vtb-old (gNode-vars-varInfo botGNode))
	 ; find all new variables as:
	 (top-vtb-new1 (vinfo-set-diff top-vtb-old bot-vtb-old))
	 (bot-vtb-new  (vinfo-set-diff bot-vtb-old top-vtb-old))
	 ; find all locals (common vars) - these will be the "quant"
	 ; in create-function
	 (locals-io-vtb (get-locals-and-io top-vtb-old bot-vtb-old sae-io-suspects))
	 (locals-vtb (first  locals-io-vtb))
	 (io-vtb     (second locals-io-vtb))
	 ; the I/O variables  are not locals, so append them to the
	 ; variable list of the top node
	 (top-vtb-new (append top-vtb-new1 io-vtb))
	 ; params & bpats - we take all unique params from both nodes
	 ; by removing duplicates of parameters
	 (top-ptb (gNode-params-varInfo topGNode))
	 (bot-ptb (gNode-params-varInfo botGNode))

	 ; TODO: to fake or not to fake? If yes, where to restore?
	 ;(ptb-lst (fake-types (vinfo-unique (append top-ptb bot-ptb))))
	 (ptb-lst (vinfo-unique (append top-ptb bot-ptb)))
	 wrapper-fn-data-1
	 wrapper-fn-data-2
	 wrapper-fn-data
	 node-vars
	 saeNode)

	 ; generate wrapper functions in both databases

	 ; variable lists for the predicate list
	 (setq wrapper-fn-data-1
	       (gen-wrapper-function
		topGNode top-vtb-new ; local
		botGNode (fake-types bot-vtb-new) ; remote
		'first-first
		locals-vtb
		ptb-lst))

	 (setq wrapper-fn-data-2
	       (gen-wrapper-function
		botGNode (restore-types bot-vtb-new) ; local
		topGNode (fake-types    top-vtb-new) ; remote
		'second-first
		locals-vtb
		ptb-lst))

	 ; get that function (plan) which costs less
	 (setq wrapper-fn-data (if (< (second wrapper-fn-data-1)
				 (second wrapper-fn-data-2))
			      ; restore the situation after the first call
			      (progn
				(restore-types top-vtb-new)
				(fake-types    bot-vtb-new)
				wrapper-fn-data-1)
			      ; in this case types are ok after the second call
			      wrapper-fn-data-2))
	 ; some data for the node
	 (setq node-vars (append (convert-to-proxy-types top-vtb-new (gNode-db topGNode))
				 (convert-to-proxy-types bot-vtb-new (gNode-db botGNode))))
	 ; make the node itself
	 (setq saeNode (make-gNode
		  :db             (proxy-database (first  wrapper-fn-data))
		  :vars           (varname-lst node-vars)
		  :vartypes       (type-lst    node-vars)
		  :org_vartypes   (orgtype-lst node-vars)
		  :predl          (append (gNode-predl topGNode) (gNode-predl botGNode))
		  :fno            (first  wrapper-fn-data)  ; get the wrapper function
		  :cost           (second wrapper-fn-data)
		  :fanout         (third  wrapper-fn-data)
		  :params         (varname-lst ptb-lst)
		  :paramtypes     (type-lst    ptb-lst)
		  :org_paramtypes (orgtype-lst ptb-lst)
		  :bpat           (append (bind-lst node-vars) (bind-lst ptb-lst))
		  ))
    saeNode
))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Wrapper function generation
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun gen-wrapper-function (local-node  local-vtb
			     remote-node remote-vtb
			     order
			     locals-vtb
			     ptb-lst)
"Retrieve information for the wrapper function and make a remote call
 to accept-gen-wrapper-fn in db.
 This function is executed in the mediator. It generates a new fn in
 local-node which ships data from the local-node to the remote-node
 and then back to the local-node.
 Out: a list of the format: (fno, cost, fanout)."

  (let* ( (local-db (gNode-db local-node))                         ; symbol
	  (local-fn-id (proxy-oid      (gNode-fno local-node)))    ; integer
	  (remote-db   (proxy-database (gNode-fno remote-node)))   ; symbol
	  (remote-fn (getobject (gNode-fno remote-node) 'ORIGNAME))   ; string

	  (dummy (assert (neq local-db remote-db)
		  "Remote and local databases must be different"))
	  
	  ; variables of the remote fn
	  (remote-v (get-predl-vars remote-node))
	  ; variables of the local fn
	  (local-v  (get-predl-vars local-node))

	  ; make a list of both sets of variables
	  (vtb-lst (if (eq order 'first-first)
		       (append local-vtb  remote-vtb)
		       (append remote-vtb local-vtb)))

	  ; select the bound variables from the arguments of the function
	  (input-vars-vtb (get-bound-vars vtb-lst))
	  ; the arguments for the new function are both input variables and parameters
	  (args-vtb (append input-vars-vtb ptb-lst))
	  ; infer which are the result vars by selecting only the un-bound variables
	  (results-vtb (get-free-vars vtb-lst))

	  (remote-wrapper-expr (list 'accept-gen-wrapper-fn
				     (kwote remote-db)
				     (kwote remote-fn)
				     (kwote remote-v)
				     (kwote remote-vtb)
				     (kwote local-fn-id)
				     (kwote local-v)
				     (kwote args-vtb)
				     (kwote locals-vtb)
				     (kwote results-vtb)))
	  (wrapper_fn_data (remote-eval remote-wrapper-expr (mkstring local-db))))
    (/putobject (car wrapper_fn_data) 'origname (fourth wrapper_fn_data))
    wrapper_fn_data))

(defun accept-gen-wrapper-fn (remote-db
			      remote-fn    remote-v remote-vtb
			      local-fn-id  local-v
			      args-vtb
			      locals-vtb
			      results-vtb)
  "Generate a wrapper function in the AMOS where it is executed.
   To be executed in a remote DB, i.e. via a remote-eval call.
   Out: a list in the format: (fno, cost, fanout)"

  ;; import remote-db if not already imported
  (import-db remote-db)
  (let* ((*no_typechecks* t)		; TODO: should this be here?
	 (*DSVE-STRATEGY* 'dsve-none)	; disable distributed view expansion
	 (remote-fn  (let ((*executable-proxies* NIL) 
			   ;; do not generate executable proxies
			   (*real-types* (type-name-lst 
					  (restore-types remote-vtb))))
		       (import_single_func remote-fn remote-db T)))
	 (local-fn   (getobjectnumbered local-fn-id))
	 (fname (concat "_" _amosid_
			"_" (mkstring remote-db)
			"_" (setq _mdbfunc_ (1+ _mdbfunc_)) "_"))
					; generate the predicate list
	 (pred-remote (cons remote-fn remote-v))
	 (pred-local  (cons local-fn  local-v))
	 (predl (list pred-local pred-remote))
	 (bindings (append
		    (buildn (length args-vtb)    '-)
		    (buildn (length results-vtb) '+)))
	 ;; TODO: is it so? I saw it in a "normal call" to createfunction
	 ;;(quant-tv1 (append results-tv quant-tv))
	 (wrapper-fn 
	  (let ((*real-types* 
		 (type-name-lst (restore-types remote-vtb))))
	    ;; *real-types* is used to pass it's value to DEF_TMP_FUNC
	    (createfunction 
	     fname
	     (type-name-lst args-vtb)
	     (type-name-lst results-vtb)
	     (varname-lst   results-vtb)
	     (type-name-lst locals-vtb)
	     (list 'IMPORTED (varname-lst locals-vtb)  predl))))
	 (cost-fo (obsolete-exec-cost-of-fn wrapper-fn bindings))
					; fix the remote function types
	 (old-funcinfo      (get-proxy-funcinfo remote-fn))
	 (new-remote-dtree  (selectbody-decomptree 
			     (getobject wrapper-fn 'selectbody)))
	 (new-remote-sae    (find-gnode new-remote-dtree remote-fn))
	 (new-remote-fn     (gNode-fno new-remote-sae))
	 (new-remote-fn-num (proxy-oid new-remote-fn))
	 (new-remote-fn-db  (proxy-database new-remote-fn)))
    (remote-eval (list 'fix-wrapper-types 
		       old-funcinfo new-remote-fn (kwote new-remote-fn-db))
		 (mkstring new-remote-fn-db))
    (list wrapper-fn (first cost-fo) (second cost-fo) (oid-name wrapper-fn))))

(defun get-proxy-funcinfo (proxyfno)
  "Get a funcinfo structure which describes a proxy function."
  (assert (proxy-p proxyfno) "A proxy function object was expected")
  (let ((db (proxy-database proxyfno))
	(fno (proxy-oid proxyfno)))
    (remote-eval (list 'accept-get-proxy-funcinfo fno) db)))


(defun accept-get-proxy-funcinfo (fno)
  "Accept requests for function info."
  (let* ((fnoid (getobjectnumbered fno)))
    (if (not (proxy-p fnoid))
	; the function is defined in this database
	(let* ((sb (getobject fnoid 'selectbody))
	       (resvars  (selectbody-resl sb))
	       (argvars  (selectbody-argl sb))
	       (restypes (get-resolvent-restypes fnoid))
	       (argtypes (get-resolvent-argtypes fnoid))
	       (argl (pairlist argtypes argvars))
	       (resl (pairlist restypes resvars)))
	  (make-funcinfo
	   :name (oid-name fnoid)
	   :oid fnoid
	   :genericname (generic-fnname (oid-name fnoid))
	   :argumentl argl
	   :resultl resl
	   :proxyinfo NIL))
        ; the function was imported from somewhere else
        ; TODO: this case is not treated completely - some proxy functions
        ; have a selectbody. It is not clear to me what to do in this case.
        (let* ((proxyinfo (get-proxy-funcinfo fnoid)))
	  (make-funcinfo
	   :name (oid-name fnoid)
	   :oid fnoid
	   :genericname (proxyfunc-origname fnoid)
	   :argumentl NIL
	   :resultl NIL
	   :proxyinfo proxyinfo)))))

(defun find-gnode (dtree fno)
  "Find a gNode in DTREE with a predicate list that contains FNO."
  (let ((node (tnode-sae dtree))); first check the topmost gNode
    (if node
	(let ((predl (gnode-predl node)))
	  (if (some (f/l (p) (memq fno p)) predl)
	      node ; return this gnode
	      (let ((subtree (car (tNode-mbl dtree))))
		(if subtree
		    (find-gnode subtree fno)  ; check the next tNode
		  )))))))

 (defun fix-wrapper-types (old-funcinfo new-fn-no new-fn-db)
 "Copy the types of the variables from the old function definition to
  the new wrapper function definition.
  Why do we have to do it... ?
  TODO: this is a patch function."
   (let* ((o-types (append (mapcar #'first (funcinfo-resultl old-funcinfo))
			   (mapcar #'first (funcinfo-argumentl old-funcinfo))))
	  (o-vars  (append (mapcar #'second (funcinfo-resultl old-funcinfo))
			   (mapcar #'second (funcinfo-argumentl old-funcinfo)))))
     (let* (
	    ;(newfn (getobjectnumbered new-fn-no))
	    (newfn new-fn-no)
	    (n-sb  (getobject newfn 'selectbody))
   	    ; if it is a proxy (other cases?) n-sb can be nil.
	    (n-argvars (if n-sb (selectbody-argl n-sb)))
	    (argtypes (subpair o-vars o-types n-argvars))) ; the new type list
       (/putobject newfn 'argtypes argtypes))))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; definition and operations on a varInfo structure
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun varInfo (varnames-lst types-lst &optional binds-lst)
"varInfo constructor"
  (let ((binds-lst1 (cond
		     ((null binds-lst)     (buildn (length varnames-lst) nil))
		     ((listp binds-lst)    binds-lst)
		     ((equal binds-lst '-) (buildn (length varnames-lst) '-))
		     ((equal binds-lst '+) (buildn (length varnames-lst) '+)))))
    (mapcar (f/l (n tp b)
		      (make-varInfo
		       :name n
		       :type tp
		       :orgtype NIL
		       :bind b))
		 varnames-lst types-lst binds-lst1)))

(defun gNode-vars-varInfo (gnode)
  (varInfo (gNode-vars     gnode)
	   (gNode-vartypes gnode)
	   (gNode-bpat     gnode)))

(defun gNode-params-varInfo (gnode)
  (varInfo (gNode-params     gnode)
	   (gNode-paramtypes gnode)
	   '-))

(defun varname-lst (vinfo-lst)
"Extract a list of variable names from a list of varInfo."
  (mapcar (f/l (vi) (varInfo-name vi)) vinfo-lst))

(defun type-lst (vinfo-lst)
"Extract a list of variable types from a list of varInfo."
  (mapcar (f/l (vi) (varInfo-type vi)) vinfo-lst))

(defun orgtype-lst (vinfo-lst)
"Extract a list of the original variable types from a list of varInfo."
  (mapcar (f/l (vi) (varInfo-orgtype vi)) vinfo-lst))

(defun bind-lst (vinfo-lst)
"Extract a list of the original variable types from a list of varInfo."
  (mapcar (f/l (vi) (varInfo-bind vi)) vinfo-lst))

(defun type-name-lst (vinfo-lst)
"Extract a list of the form ((type varname) ...) from a list of varInfo."
  (mapcar (f/l (vi) (list (varInfo-type vi) (varInfo-name vi))) vinfo-lst))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; variable and binding functions
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun get-bound-vars (vinfo-lst)
"Get only the bound variables from a varInfo list."
  (mapfilter
   (f/l (vinfo)
	(if (equal (varInfo-bind vinfo) '-) T))
   vinfo-lst))

(defun get-free-vars (vinfo-lst)
"Get only the free (unbound) variables from a varInfo list."
  (mapfilter
   (f/l (vinfo)
	(if (equal (varInfo-bind vinfo) '+) T))
   vinfo-lst))

; CURRENTLY NOT USED. DO NOT REMOVE.
(defun bind-vars (vinfo-lst)
"make all the variables in a varInfo list to be BOUND"
  (mapcar (f/l (vinfo)
	       (setf (varInfo-bind vinfo) '-))
	  vinfo-lst))

; CURRENTLY NOT USED. DO NOT REMOVE.
(defun free-vars (vinfo-lst)
"make all the variables in a varInfo list to be UNBOUND"
  (mapcar (f/l (vinfo)
	       (setf (varInfo-bind vinfo) '+))
	  vinfo-lst))



;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; type functions
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun fake-types (vinfo-lst)
"remap all non-existing and user-defined types to INTEGER
 and save the original types in the orgtype field of varInfo."
  (mapcar (f/l (vnfo)
	       (if (or (not (gettypenamed (varInfo-type vnfo) T))
		       (ut_p (gettypenamed (varInfo-type vnfo))))
		   (progn
		     (setf (varInfo-orgtype vnfo) (varInfo-type vnfo))
		     (setf (varInfo-type vnfo) 'INTEGER))))
	  vinfo-lst)
  vinfo-lst)

(defun restore-types (vinfo-lst)
"restore the original type information in a varInfo list
 if varInfo-orgtype is not nil, then types have been changed and only then
 we restore them."
  (mapcar (f/l (vnfo)
	       (if (not (null (varInfo-orgtype vnfo)))
		   (progn
		     (setf (varInfo-type vnfo) (varInfo-orgtype vnfo))
		     (setf (varInfo-orgtype vnfo) NIL))))
	  vinfo-lst)
  vinfo-lst)

(defun convert-to-proxy-types (vinfo-lst db)
  (mapcar (f/l (vnfo)
	       (let ((tp    (varInfo-type    vnfo))
		     (orgtp (varInfo-orgtype vnfo)))
		 (if (not (null orgtp))
		     (if (not (gettypenamed orgtp T))
			 (setf (varInfo-orgtype vnfo) (proxy_type_name orgtp db)))
		     (if (not (gettypenamed tp T))
			 (setf (varInfo-type vnfo) (proxy_type_name tp db))))))
	  vinfo-lst)
  vinfo-lst)

;(defun get-real-var-types (saeNode)
; select types alternatively from the two type lists stored in an SAE node
; the rule is: if a type in the origtyes is NIL then the type stored in argtypes
; is a the real type. Otherwise take the one from the origtypes
;  (let* ((possibly_faked_tp    (gNode-vartypes saeNode))
;	 (possibly_original_tp (gNode-org_vartypes saeNode)))
;    (if (null possibly_original_tp)
;	possibly_faked_tp
;	(mapcar (f/l (f_tp o_tp) (if (null o_tp) f_tp o_tp))
;		possibly_faked_tp
;		possibly_original_tp))))

(defun get-real-types (faked_tp original_tp)
"Select types alternatively from the two type lists stored in an SAE node.
 The rule is:
 - if a type in ORIGINAL_TP is NIL then the corresponding type stored in
   FAKED_TP is a the real type.
 - otherwise take the one from the ORIGINAL_TP."
    (if (null original_tp)
	faked_tp
	(mapcar (f/l (f_tp o_tp) (if (null o_tp) f_tp o_tp))
		faked_tp
		original_tp)))

(defun make-proxy-obj (remote-oid db)
"Create a proxy object to an object in DB with oid REMOTE-OID
 TODO: improve speed."
  (let ((bucket (gethash remote-oid _proxytable_))
	(obj nil))
    (if bucket ; there are proxies with the same xoidno
	; check if they are in the same DB
	(let ((duplicate-lst (mapfilter (f/l (obj) (eq (proxy-database obj) db))
					bucket)))
	  (if duplicate-lst   ; do not create a new object, return the old one
	      (setq obj (car duplicate-lst)))))
    (if obj
	obj                                ; return the old object
        (let ((obj (createobject _proxy_))) ; create a new object
	  (/putobject obj 'xoidno   remote-oid)
	  (/putobject obj 'exportto db)
	  ; append the new obj at the end of the bucket put it in the hashtable
	  (puthash remote-oid _proxytable_ (nconc1 bucket obj))
	  obj))))


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; set functions
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun vinfo-set-diff (vi-lst-1 vi-lst-2)
"Calculate the set-difference of 2 lists of varInfo,
 using the varInfo-name field as a key.
 Out: a list of varInfo, containing the set difference of the inputs."
  (let ((result NIL))
    (do* ((rest-1 vi-lst-1     (cdr rest-1))
	  (vnfo-1 (car rest-1) (car rest-1)))
	 ((null rest-1) result)
	 (if (not-contained? vnfo-1 vi-lst-2)
	     (push vnfo-1 result)))))

(defun not-contained? (vnfo vi-lst)
"check if a varInfo is not contained in a list of varInfo."
  (let ((varname (varInfo-name vnfo)))
    (do* ((rest vi-lst (cdr rest))
	  (curr-vnfo (car rest) (car rest)))
	 ((null rest) T)
	 (if (equal varname (varInfo-name curr-vnfo))
	     (return NIL)))))

(defun vinfo-unique (vi-lst)
"Similar to (unique lst), but works on a list of varInfo, using the
name field as a key.
Duplicate vars at beggining of the lists are removed, while their
last occurence remains in the new list."
  (let ((result NIL))
    (do* ((rest vi-lst (cdr rest))
	  (curr-vnfo (car rest) (car rest)))
	 ((null rest) result)
	 (if (not-contained? curr-vnfo (cdr rest))
	     (push curr-vnfo result)))))


(defun ppvi (vinfo)
"pretty-print a varInfo structure."
  (formatl t "["    (varInfo-name vinfo) ", "
	             (varInfo-type vinfo) ", "
		     (varInfo-orgtype vinfo) ", "
		     (varInfo-bind vinfo) "]" t))
