/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame1.java
 *
 * Created on Dec 9, 2012, 10:42:17 PM
 */
import com.udbl.amos.JavaClient.*;


import java.awt.Color;
import java.io.IOException;

import info.monitorenter.gui.chart.*;
import info.monitorenter.gui.chart.traces.Trace2DLtd;

/**
 * 
 * @author Mehrdad
 */
@SuppressWarnings("serial")
public class ClientDemoGUI extends javax.swing.JFrame {

	/** Creates new form NewJFrame1 */
	public ClientDemoGUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		textFieldServerA = new java.awt.TextField();
		textFieldServerB = new java.awt.TextField();
		jBtnServerA = new javax.swing.JButton();
		jBtnServerB = new javax.swing.JButton();
		chartServerB = new info.monitorenter.gui.chart.Chart2D();
		chartServerA1 = new info.monitorenter.gui.chart.Chart2D();
		jBtnStartDemo = new javax.swing.JButton();
		jBtnStopDemo = new javax.swing.JButton();
		label1 = new java.awt.Label();
		label2 = new java.awt.Label();
		label3 = new java.awt.Label();
		label4 = new java.awt.Label();
		label5 = new java.awt.Label();
		label6 = new java.awt.Label();
		label7 = new java.awt.Label();
		lstServerA = new java.awt.List();
		lstServerB = new java.awt.List();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jBtnServerA.setText("Set");
		jBtnServerA.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jBtnServerAActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		jBtnServerB.setText("Set");
		jBtnServerB.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					jBtnServerBActionPerformed(evt);
				} catch (Exception e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		});

		chartServerB.setAutoscrolls(true);

		javax.swing.GroupLayout chartServerBLayout = new javax.swing.GroupLayout(
				chartServerB);
		chartServerB.setLayout(chartServerBLayout);
		chartServerBLayout.setHorizontalGroup(chartServerBLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 565, Short.MAX_VALUE));
		chartServerBLayout.setVerticalGroup(chartServerBLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 270, Short.MAX_VALUE));

		chartServerA1.setAutoscrolls(true);

		javax.swing.GroupLayout chartServerA1Layout = new javax.swing.GroupLayout(
				chartServerA1);
		chartServerA1.setLayout(chartServerA1Layout);
		chartServerA1Layout.setHorizontalGroup(chartServerA1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 565, Short.MAX_VALUE));
		chartServerA1Layout.setVerticalGroup(chartServerA1Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 270, Short.MAX_VALUE));

		jBtnStartDemo.setText("Start");
		jBtnStartDemo.setVisible(false);
		jBtnStartDemo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBtnStartDemoActionPerformed(evt);
			}
		});

		jBtnStopDemo.setBackground(new java.awt.Color(255, 51, 51));
		jBtnStopDemo.setText("CLose");
		jBtnStopDemo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jBtnStopDemoActionPerformed(evt);
			}
		});

		label1.setText("Threshold Server A");

		label2.setText("Stream data Server B");

		label3.setText("Graph Server B");

		label4.setText("Stream data Server A");

		label5.setText("Graph Server A");

		label6.setFont(new java.awt.Font("Dialog", 1, 18));
		label6.setText("Pure java SCSQ client demo");

		label7.setText("Threshold Server B");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(317,
																		317,
																		317)
																.addComponent(
																		jBtnStartDemo)
																.addGap(117,
																		117,
																		117)
																.addComponent(
																		jBtnStopDemo))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jBtnServerA)
																				.addGroup(
																						layout.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								false)
																								.addComponent(
																										textFieldServerA,
																										javax.swing.GroupLayout.Alignment.LEADING,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)
																								.addComponent(
																										textFieldServerB,
																										javax.swing.GroupLayout.Alignment.LEADING,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										133,
																										Short.MAX_VALUE))
																				.addComponent(
																						jBtnServerB)
																				.addComponent(
																						label1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						label7,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						chartServerA1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						chartServerB,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						label3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						label5,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(58, 58,
																		58)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						lstServerB,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						label4,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						label2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						lstServerA,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						172,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(345,
																		345,
																		345)
																.addComponent(
																		label6,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		265,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(32, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addComponent(label6,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(29, 29, 29)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														label1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														label4,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														label5,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														lstServerA,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														270, Short.MAX_VALUE)
												.addGroup(
														layout.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
																.addComponent(
																		chartServerA1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createSequentialGroup()
																				.addComponent(
																						textFieldServerA,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(
																						javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addComponent(
																						jBtnServerA))))
								.addGap(29, 29, 29)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														label3,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														label2,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														label7,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														lstServerB,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		textFieldServerB,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(27, 27,
																		27)
																.addComponent(
																		jBtnServerB))
												.addComponent(
														chartServerB,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										61, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jBtnStopDemo)
												.addComponent(jBtnStartDemo))
								.addContainerGap()));

		pack();
	}// </editor-fold>

	private void jBtnServerAActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
	    Connection conn = new Connection("localhost","A");

	    System.out.println("Server A : set threshold() = "+textFieldServerA.getText()+";");
	    conn.execute("set threshold() = "+textFieldServerA.getText()+";");
	    conn.disconnect();

	}

	private void jBtnServerBActionPerformed(java.awt.event.ActionEvent evt) throws Exception{
	    Connection conn = new Connection("localhost","B");

	    System.out.println("Server B : set threshold() = "+textFieldServerB.getText()+";");
	    conn.execute("set threshold() = "+textFieldServerB.getText()+";");
	    conn.disconnect();

	}

	private void jBtnStartDemoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jBtnStopDemoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		try {
			Runtime.getRuntime().exec("taskkill /im amos2.exe /f");
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		System.exit(0);
	}

	/**
	 * @param args
	 *            the command line arguments
	 * @throws Exception
	 */
	public static void main(String args[]) throws Exception {
		ClientDemoGUI nf = new ClientDemoGUI();
		//nf.getContentPane().add(new MyCanvas());
		// nf.setVisible(true);
		nf.DemoInit();
		// nf.setVisible(true);
	}

	public void DemoInit() throws Exception {
		// Connection.initializeClient();
		System.out.println("\nDisplaying result from one continuous query");
		System.out.println("which is updated at run time from client\n");

		Connection conn = new Connection("localhost", "A");

		/* Install filter functions in server A: */
		conn.execute("create function threshold() -> number as stored;");
		conn.execute("set threshold() = -1;");
		conn.execute("create function filter1() -> bag of number "
				+ "as for each number x where x in sin(heartbeatbag(0.5)) "
				+ "if x > threshold() then return x;");
		conn.disconnect();
		Connection conn2 = new Connection("localhost", "B");

		/* Install filter functions in server A: */
		conn2.execute("create function threshold() -> number as stored;");
		conn2.execute("set threshold() = -1;");
		conn2.execute("create function filter1() -> bag of number "
				+ "as for each number x where x in cos(heartbeatbag(1)) "
				+ "if x > threshold() then return x;");
		conn2.disconnect();

		/*
		 * Start thread displaying the result of the continuous query filter1():
		 */
		ServerThreads st = null;
		try {
			st = new ServerThreads();
		} catch (Throwable e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		/* Start thread dynamically changing parameter threshold(): */
		// new myControlThread().start();
		Thread.sleep(35000);
		st.stopFlagA=true;
		st.stopFlagB=true;
		Runtime.getRuntime().exec("taskkill /im amos2.exe /f");
		//System.exit(0); /* Stop after 15 seconds */
	}

	// Variables declaration - do not modify
	public info.monitorenter.gui.chart.Chart2D chartServerA1;
	public info.monitorenter.gui.chart.Chart2D chartServerB;
	private javax.swing.JButton jBtnServerA;
	private javax.swing.JButton jBtnServerB;
	private javax.swing.JButton jBtnStartDemo;
	private javax.swing.JButton jBtnStopDemo;
	public java.awt.List lstServerA;
	public java.awt.List lstServerB;
	private java.awt.Label label1;
	private java.awt.Label label2;
	private java.awt.Label label3;
	private java.awt.Label label4;
	private java.awt.Label label5;
	private java.awt.Label label6;
	private java.awt.Label label7;
	private java.awt.TextField textFieldServerA;
	private java.awt.TextField textFieldServerB;
	// End of variables declaration

}
class ServerThreads{
	public ClientDemoGUI clDemo = new ClientDemoGUI();
	public ServerAThread a = new ServerAThread();
	public ServerBThread b = new ServerBThread();
	public boolean stopFlagA;
	public boolean stopFlagB;
	public ServerThreads() throws Throwable{
		stopFlagA=false;
		stopFlagB=false;
		Thread.sleep(50);
		a.start();
		Thread.sleep(50);
		b.start();
		clDemo.setVisible(true);
	}
	class ServerAThread extends Thread {
		int i = 0;
	
		public void run() {
			/*
			 * This thread continuously displays the result tuples of the standing
			 * query filter1() on standard output
			 */
			ITrace2D traceA = new Trace2DLtd(200);
			traceA.setColor(Color.BLUE);
			traceA.setName("Server A");
			clDemo.chartServerA1.addTrace(traceA);
			try {
				Connection conn = new Connection("localhost", "A");
				Scan s;
				Tuple tpl;
	
				s = conn.executeCustom("filter1();", "(:buffersize 1)");
				if (!stopFlagA)
					System.out.println("Server A is started");
	
				while (!s.eos() && !stopFlagA) {
					tpl = s.getRow();
					System.out.println("A<< " + tpl.getElem(0));
					traceA.addPoint(i, (Double) tpl.getElem(0));
					clDemo.lstServerA.add(tpl.getElem(0).toString());
					s.nextRow();
					i++;
				}
				i = 0;
				// conn.disconnect();
			} catch (AmosException e) {
				System.out.println(e.getMessage() + " myFilterThread");
				e.printStackTrace();
			} 
		}
	}
	
	class ServerBThread extends Thread {
		int i = 0;
		
		public void run() {
			/*
			 * This thread continuously displays the result tuples of the standing
			 * query filter1() on standard output
			 */
			ITrace2D traceB = new Trace2DLtd(200);
			traceB.setColor(Color.red);
			traceB.setName("Server B");
			clDemo.chartServerB.addTrace(traceB);
			try {
				Connection conn = new Connection("localhost", "B");
				if (!stopFlagB)
					System.out.println("Server B is started");
				Scan s;
				Tuple tpl;
	
				s = conn.executeCustom("filter1();", "(:buffersize 1)");
	
				while (!s.eos() && !stopFlagB) {
					tpl = s.getRow();
					System.out.println("B<< " + tpl.getElem(0));
					traceB.addPoint(i, (Double) tpl.getElem(0));
					clDemo.lstServerB.add(tpl.getElem(0).toString());
					s.nextRow();
					i++;
				}
				i = 0;
				// conn.disconnect();
			} catch (AmosException e) {
				System.out.println(e.getMessage() + " myFilterThread");
				e.printStackTrace();
			} 
		}
	}
}