<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://ws.digiposs.com/WorldTime.jws" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://ws.digiposs.com/WorldTime.jws" xmlns:intf="http://ws.digiposs.com/WorldTime.jws" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:message name="utcStampNowResponse">
    <wsdl:part name="utcStampNowReturn" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="utcStampNowResponse1">
    <wsdl:part name="utcStampNowReturn" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="tzStampNowResponse">
    <wsdl:part name="tzStampNowReturn" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="tzStampNowRequest">
    <wsdl:part name="tZone" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="tzStampNowResponse1">
    <wsdl:part name="tzStampNowReturn" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="utcStampNowRequest1">
    <wsdl:part name="format" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="tzStampNowRequest1">
    <wsdl:part name="tZone" type="xsd:string"/>
    <wsdl:part name="format" type="xsd:string"/>
  </wsdl:message>
  <wsdl:message name="utcStampNowRequest">
  </wsdl:message>
  <wsdl:portType name="WorldTime">
    <wsdl:operation name="tzStampNow" parameterOrder="tZone">
      <wsdl:input message="impl:tzStampNowRequest" name="tzStampNowRequest"/>
      <wsdl:output message="impl:tzStampNowResponse" name="tzStampNowResponse"/>
    </wsdl:operation>
    <wsdl:operation name="tzStampNow" parameterOrder="tZone format">
      <wsdl:input message="impl:tzStampNowRequest1" name="tzStampNowRequest1"/>
      <wsdl:output message="impl:tzStampNowResponse1" name="tzStampNowResponse1"/>
    </wsdl:operation>
    <wsdl:operation name="utcStampNow">
      <wsdl:input message="impl:utcStampNowRequest" name="utcStampNowRequest"/>
      <wsdl:output message="impl:utcStampNowResponse" name="utcStampNowResponse"/>
    </wsdl:operation>
    <wsdl:operation name="utcStampNow" parameterOrder="format">
      <wsdl:input message="impl:utcStampNowRequest1" name="utcStampNowRequest1"/>
      <wsdl:output message="impl:utcStampNowResponse1" name="utcStampNowResponse1"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="WorldTimeSoapBinding" type="impl:WorldTime">
    <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="tzStampNow">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input name="tzStampNowRequest">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.digiposs.com/WorldTime.jws" use="encoded"/>
      </wsdl:input>
      <wsdl:output name="tzStampNowResponse">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.digiposs.com/WorldTime.jws" use="encoded"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="tzStampNow">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input name="tzStampNowRequest1">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.digiposs.com/WorldTime.jws" use="encoded"/>
      </wsdl:input>
      <wsdl:output name="tzStampNowResponse1">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.digiposs.com/WorldTime.jws" use="encoded"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="utcStampNow">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input name="utcStampNowRequest">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.digiposs.com/WorldTime.jws" use="encoded"/>
      </wsdl:input>
      <wsdl:output name="utcStampNowResponse">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.digiposs.com/WorldTime.jws" use="encoded"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="utcStampNow">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input name="utcStampNowRequest1">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.digiposs.com/WorldTime.jws" use="encoded"/>
      </wsdl:input>
      <wsdl:output name="utcStampNowResponse1">
        <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://ws.digiposs.com/WorldTime.jws" use="encoded"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="WorldTimeService">
    <wsdl:port binding="impl:WorldTimeSoapBinding" name="WorldTime">
      <wsdlsoap:address location="http://ws.digiposs.com/WorldTime.jws"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>