/* Generated By:JJTree&JavaCC: Do not edit this line. Rdql2Amos.java */
import java.util.*;
import callin.*;
import callout.*;

public class Rdql2Amos/*@bgen(jjtree)*/implements Rdql2AmosTreeConstants, Rdql2AmosConstants {/*@bgen(jjtree)*/
  protected static JJTRdql2AmosState jjtree = new JJTRdql2AmosState();static String[] wholeQuery=new String[10];
static Vector selectVariables=new Vector();
static Vector sources=new Vector();
static Vector rdfTripleVariables=new Vector();
static Vector rdfTriples=new Vector();
static Vector prefixvec=new Vector();
static Vector constraintvec=new Vector();
static int andVar=0;


public Rdql2Amos() {
}

public void reinit() {
        wholeQuery=new String[10];
        selectVariables=new Vector();
        sources=new Vector();
        rdfTripleVariables=new Vector();
        rdfTriples=new Vector();
        prefixvec=new Vector();
        constraintvec=new Vector();
        andVar=0;
}


        public String upvofuri(String uri){
        Tuple argl;
        String res;

        res = "";
        try{
        argl = new Tuple(1);
        Connection tmpConnection = new Connection("");
        argl.setElem(0,uri);
        res = tmpConnection.callFunction("charstring.upvofuri->charstring",argl).getRow().getStringElem(0);
        }catch(AmosException e){}
        return res;
    }

public String output() {

/************** remove doubles in rdfTripleVariables ************************************/

                for (int a=0;a<rdfTripleVariables.size();a++)   {
                                int last=rdfTripleVariables.lastIndexOf(rdfTripleVariables.get(a));
                                if (last!=a)    {
                                        rdfTripleVariables.remove(last);
                                        a--;
                                }
                        }

/*************** handling of the select variables following ***************************************/

                int b=0;
                String selectvars="";
                if (selectVariables.size()==0)  {  //if it is "select *"
                        selectVariables=rdfTripleVariables;
                }
                while(b < selectVariables.size()) {
                        if (b==selectVariables.size()-1)        {
                                //selectvars+= "rid(" + selectVariables.elementAt(b)+")";
                                selectvars+=selectVariables.elementAt(b);
                        } else  {
                                //selectvars+= "rid(" + selectVariables.elementAt(b)+"), ";
                                selectvars+=selectVariables.elementAt(b)+ ", ";
                        }
                        b++;
                        }

        wholeQuery[1]= selectvars;

//wholeQuery[2]="from" (in the grammar)        
/*********************** sources are in AmosQL all select variables and variables in RDFtriples - following *****/

                Vector sourceVars=(Vector) selectVariables.clone();
                for (int c=0;c<rdfTripleVariables.size();c++) {
                                if (!selectVariables.contains(rdfTripleVariables.get(c))) {
                                sourceVars.addElement(rdfTripleVariables.get(c));
                                }
                        }
                        for (int d=0;d<sourceVars.size();d++)   {       //we need just the variables
                                if (sourceVars.elementAt(d).equals(","))        {
                                        sourceVars.remove(d);
                                        d--;
                                }
                        }
                        int e=0;
                String sourceVarsOut="";
                while(e < sourceVars.size()) {
                        if (e==sourceVars.size()-1) {

                                sourceVarsOut+="Charstring "+sourceVars.elementAt(e);
                                //sourceVarsOut+="resource "+sourceVars.elementAt(e);
                        } else {

                                sourceVarsOut+="Charstring "+sourceVars.elementAt(e)+", ";
                                //sourceVarsOut+="resource "+sourceVars.elementAt(e)+", ";
                        }
                        e++;
                        }

        wholeQuery[3]=sourceVarsOut; //output of the sources. These are the select variables and all variables in the TriplePatterns

//wholeQuery[4]="where" (in the grammar)
/************** that will be in the form: "rdf_triples('source') in AmosQL****************/
                //not fixed for more than one source. 
                int f=0;
                while (f < sources.size())      {
                                if (Start.SourceNameSpace==null)        {
                                        //wholeQuery[5]= "rdf_triples('"+sources.elementAt(f)+"')";
                                        //wholeQuery[5]= sources.elementAt(f)+"triples()";
                                        wholeQuery[5]= upvofuri((String)sources.elementAt(f))+"()";

                                } else  {
                                //wholeQuery[5]= "rdf_triples('"+Start.SourceNameSpace+sources.elementAt(f)+"')";
                                //wholeQuery[5]= Start.SourceNameSpace+sources.elementAt(f)+"triples()";
                                wholeQuery[5]= upvofuri(Start.SourceNameSpace+sources.elementAt(f))+"()";

                        }
                        f++;
                }

//**************************************************************************************/

        wholeQuery[6]="=";

/****************** prefixes from PrefixClause must be inserted into TriplePatterns - following ************/

                for (int prefsize=prefixvec.size();prefsize>0;prefsize=prefsize-2)      {
                        String shortcut=(String)prefixvec.elementAt(1);
                        int length=shortcut.length();
                        for (int g=0;g<rdfTriples.size();g++)   {
                                String tripleElement=(String)rdfTriples.elementAt(g);
                                if (tripleElement.length()>length)      {
                                        if (tripleElement.substring(1,length+1).equals(shortcut))       {
                                                int colonindex=tripleElement.lastIndexOf(":");
                                                String postfix=tripleElement.substring(colonindex+1);
                                                rdfTriples.set(g,"'"+prefixvec.elementAt(0)+postfix); //see also URI method for description
                                        }
                                }
                        }
                        prefixvec.removeElementAt(1);
                        prefixvec.removeElementAt(0);
                }
/**************** now the prefixes are inserted into the RDFTriples ***************************/
/****************** this the handling of the RDFTriples following******************************/
                int h=0;
                while(h < rdfTriples.size()) {
                        String svo="";
                        if (andVar==0)  {
                                for (int i=0; i<5; i++) {
                                        svo+=rdfTriples.elementAt(h);
                                        h++;
                                }
                                if (wholeQuery[7]==null)        {
                                        wholeQuery[7]="<"+svo+">";
                                } else  {
                                        wholeQuery[7]+="<"+svo+">";
                                }
                        } else  {
                                for (int i=0; i<5; i++) {
                                        svo+=rdfTriples.elementAt(h);
                                        h++;
                                }
                                andVar--;
                                if (wholeQuery[7]==null)        {
                                        wholeQuery[7]="<"+svo+"> and "+wholeQuery[5]+" = ";
                                } else  {
                                        wholeQuery[7]+="<"+svo+"> and "+wholeQuery[5]+" = ";
                                }
                        }
                }
/************************ now comes constraint syntax (for Example where age>=24)***************/

                for (int j=0; j<constraintvec.size(); j++)      {
                        if (wholeQuery[8]==null)        {
                                wholeQuery[8]=(String)constraintvec.elementAt(j);
                        } else  {
                                wholeQuery[8]+=(String)" "+constraintvec.elementAt(j);
                        }
                }

/*************************** output of the AmosQL query following *******************************/

        wholeQuery[9]=";";

        String parsedquery="";
        int k=0;
        while(k < 10) {
                if (wholeQuery[k]==null)        {
                        k++;
                } else  {
                        //System.out.print(wholeQuery[k]+" "); //output of the whole query
                        parsedquery+=wholeQuery[k]+" ";
                        k++;
                }
        }

        //System.out.println("");
        reinit();
                return parsedquery;
        }

// **** Debug point
  static final public void CompilationUnit() throws ParseException {
    Query();
    jj_consume_token(0);
  }

// Optional comma
//commaflag==0 means more than one selectvariable
//commaflag==1 means more than one source
//commaflag==2 means more than one triplepattern
//commaflag==3 means more than one prefix (Using ... for , ... for)
//commaflag==4 are the commas in the rdfTriples
  static final public void CommaOpt(int commaflag) throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      break;
    default:
      jj_la1[0] = jj_gen;
      ;
    }
        //if(commaflag==0) {selectVariables.addElement(",");} //comma output is done in the output directly
        if(commaflag==1) {sources.addElement(",");}           //not tested for more than one source
        if(commaflag==2) {andVar=andVar+1;}
        //if(commaflag==3) {prefixvec.addElement(",");}
        if(commaflag==4) {rdfTriples.addElement(",");}
  }

// **** Debug point
  static final public void Query() throws ParseException {
 /*@bgen(jjtree) Query */
  SimpleNode jjtn000 = new SimpleNode(JJTQUERY);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      SelectClause();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOURCE:
      case FROM:
        SourceClause();
        break;
      default:
        jj_la1[1] = jj_gen;
        ;
      }
      TriplePatternClause();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SUCHTHAT:
        ConstraintClause();
        break;
      default:
        jj_la1[2] = jj_gen;
        ;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PREFIXES:
        PrefixesClause();
        break;
      default:
        jj_la1[3] = jj_gen;
        ;
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void SelectClause() throws ParseException {
 /*@bgen(jjtree) SelectClause */
  SimpleNode jjtn000 = new SimpleNode(JJTSELECTCLAUSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      if (jj_2_1(2)) {
        jj_consume_token(SELECT);
        Var(0);
        label_1:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case COMMA:
          case HOOK:
            ;
            break;
          default:
            jj_la1[4] = jj_gen;
            break label_1;
          }
          CommaOpt(0);
          Var(0);
        }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
        wholeQuery[0]="select";
      } else {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SELECT:
          jj_consume_token(SELECT);
          jj_consume_token(STAR);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
        wholeQuery[0]="select";
          break;
        default:
          jj_la1[5] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void SourceClause() throws ParseException {
 /*@bgen(jjtree) SourceClause */
  SimpleNode jjtn000 = new SimpleNode(JJTSOURCECLAUSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOURCE:
        jj_consume_token(SOURCE);
        break;
      case FROM:
        jj_consume_token(FROM);
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
   wholeQuery[2]="from";
      SourceSelector();
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
        case LT:
          ;
          break;
        default:
          jj_la1[7] = jj_gen;
          break label_2;
        }
        CommaOpt(1);
        SourceSelector();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void SourceSelector() throws ParseException {
 /*@bgen(jjtree) SourceSelector */
  SimpleNode jjtn000 = new SimpleNode(JJTSOURCESELECTOR);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      URI(0);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void TriplePatternClause() throws ParseException {
 /*@bgen(jjtree) TriplePatternClause */
  SimpleNode jjtn000 = new SimpleNode(JJTTRIPLEPATTERNCLAUSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(WHERE);
      TriplePattern();
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LPAREN:
        case COMMA:
          ;
          break;
        default:
          jj_la1[8] = jj_gen;
          break label_3;
        }
        CommaOpt(2);
        TriplePattern();
      }
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
        wholeQuery[4]="where";
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void ConstraintClause() throws ParseException {
 /*@bgen(jjtree) ConstraintClause */
  SimpleNode jjtn000 = new SimpleNode(JJTCONSTRAINTCLAUSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(SUCHTHAT);
              constraintvec.addElement("and");
      Expression();
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case SUCHTHAT:
        case COMMA:
          ;
          break;
        default:
          jj_la1[9] = jj_gen;
          break label_4;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          jj_consume_token(COMMA);
          break;
        case SUCHTHAT:
          jj_consume_token(SUCHTHAT);
          break;
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
                                                                                       constraintvec.addElement("and");
        Expression();
      }
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void PrefixesClause() throws ParseException {
 /*@bgen(jjtree) PrefixesClause */
  SimpleNode jjtn000 = new SimpleNode(JJTPREFIXESCLAUSE);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(PREFIXES);
      PrefixDecl();
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case IDENTIFIER:
        case COMMA:
          ;
          break;
        default:
          jj_la1[11] = jj_gen;
          break label_5;
        }
        CommaOpt(3);
        PrefixDecl();
      }
    } catch (Throwable jjte000) {
      if (jjtc000) {
        jjtree.clearNodeScope(jjtn000);
        jjtc000 = false;
      } else {
        jjtree.popNode();
      }
      if (jjte000 instanceof RuntimeException) {
        {if (true) throw (RuntimeException)jjte000;}
      }
      if (jjte000 instanceof ParseException) {
        {if (true) throw (ParseException)jjte000;}
      }
      {if (true) throw (Error)jjte000;}
    } finally {
      if (jjtc000) {
        jjtree.closeNodeScope(jjtn000, true);
      }
    }
  }

  static final public void PrefixDecl() throws ParseException {
 /*@bgen(jjtree) PrefixDecl */
 SimpleNode jjtn000 = new SimpleNode(JJTPREFIXDECL);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String prefix="";
    try {
      prefix = Identifier();
      jj_consume_token(FOR);
      URI(1);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
        prefixvec.addElement(prefix);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void TriplePattern() throws ParseException {
 /*@bgen(jjtree) TriplePattern */
  SimpleNode jjtn000 = new SimpleNode(JJTTRIPLEPATTERN);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(LPAREN);
      VarOrURI();
      CommaOpt(4);
      VarOrURI();
      CommaOpt(4);
      VarOrLiteral();
      jj_consume_token(RPAREN);
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void VarOrURI() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case HOOK:
      Var(1);
      break;
    case LT:
      URI(2);
      break;
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void VarOrLiteral() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case HOOK:
      Var(1);
      break;
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL1:
    case STRING_LITERAL2:
    case BOOLEAN_LITERAL:
    case NULL_LITERAL:
    case LT:
      Literal();
      break;
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//varflag==0: coming from SelectClause
//varflag==1; coming from Triplepattern
//varflag==2; coming from PrimaryExpression
  static final public void Var(int varflag) throws ParseException {
 /*@bgen(jjtree) Var */
 SimpleNode jjtn000 = new SimpleNode(JJTVAR);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String varName="";
    try {
      jj_consume_token(HOOK);
      varName = Identifier();
                             jjtree.closeNodeScope(jjtn000, true);
                             jjtc000 = false;
        if (varflag==0) {selectVariables.addElement(varName);}
        if (varflag==1) {rdfTripleVariables.addElement(varName);
                                rdfTriples.addElement(varName);}
        if (varflag==2) {constraintvec.addElement(varName);}
    } catch (Throwable jjte000) {
    if (jjtc000) {
      jjtree.clearNodeScope(jjtn000);
      jjtc000 = false;
    } else {
      jjtree.popNode();
    }
    if (jjte000 instanceof RuntimeException) {
      {if (true) throw (RuntimeException)jjte000;}
    }
    if (jjte000 instanceof ParseException) {
      {if (true) throw (ParseException)jjte000;}
    }
    {if (true) throw (Error)jjte000;}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

/******************************************************************/
// Constraint syntax follows.

// **** Debug point
  static final public void Expression() throws ParseException {
    ConditionalOrExpression();
  }

  static final public void ConditionalOrExpression() throws ParseException {
    ConditionalXorExpression();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SC_OR:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_6;
      }
      jj_consume_token(SC_OR);
             constraintvec.addElement(getToken(0).toString());
                                                                  SimpleNode jjtn001 = new SimpleNode(JJTLOGICALOR);
                                                                  boolean jjtc001 = true;
                                                                  jjtree.openNodeScope(jjtn001);
      try {
        ConditionalXorExpression();
      } catch (Throwable jjte001) {
                                                                  if (jjtc001) {
                                                                    jjtree.clearNodeScope(jjtn001);
                                                                    jjtc001 = false;
                                                                  } else {
                                                                    jjtree.popNode();
                                                                  }
                                                                  if (jjte001 instanceof RuntimeException) {
                                                                    {if (true) throw (RuntimeException)jjte001;}
                                                                  }
                                                                  if (jjte001 instanceof ParseException) {
                                                                    {if (true) throw (ParseException)jjte001;}
                                                                  }
                                                                  {if (true) throw (Error)jjte001;}
      } finally {
                                                                  if (jjtc001) {
                                                                    jjtree.closeNodeScope(jjtn001,  2);
                                                                  }
      }
    }
  }

  static final public void ConditionalXorExpression() throws ParseException {
    ConditionalAndExpression();
  }

  static final public void ConditionalAndExpression() throws ParseException {
    ValueLogical();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SC_AND:
        ;
        break;
      default:
        jj_la1[15] = jj_gen;
        break label_7;
      }
      jj_consume_token(SC_AND);
               constraintvec.addElement(getToken(0).toString());
                                                                    SimpleNode jjtn001 = new SimpleNode(JJTLOGICALAND);
                                                                    boolean jjtc001 = true;
                                                                    jjtree.openNodeScope(jjtn001);
      try {
        ValueLogical();
      } catch (Throwable jjte001) {
                                                                    if (jjtc001) {
                                                                      jjtree.clearNodeScope(jjtn001);
                                                                      jjtc001 = false;
                                                                    } else {
                                                                      jjtree.popNode();
                                                                    }
                                                                    if (jjte001 instanceof RuntimeException) {
                                                                      {if (true) throw (RuntimeException)jjte001;}
                                                                    }
                                                                    if (jjte001 instanceof ParseException) {
                                                                      {if (true) throw (ParseException)jjte001;}
                                                                    }
                                                                    {if (true) throw (Error)jjte001;}
      } finally {
                                                                    if (jjtc001) {
                                                                      jjtree.closeNodeScope(jjtn001,  2);
                                                                    }
      }
    }
  }

// End of boolean expressions

/******************************************************************/

// Things that are not operations on boolean terms.
  static final public void ValueLogical() throws ParseException {
    StringEqualityExpression();
  }

  static final public void StringEqualityExpression() throws ParseException {
    NumericalLogical();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STR_EQ:
      case STR_NE:
      case STR_MATCH:
        ;
        break;
      default:
        jj_la1[16] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STR_EQ:
        jj_consume_token(STR_EQ);
              constraintvec.addElement(getToken(0).toString());
                                                                   SimpleNode jjtn001 = new SimpleNode(JJTSTRINGEQUAL);
                                                                   boolean jjtc001 = true;
                                                                   jjtree.openNodeScope(jjtn001);
        try {
          NumericalLogical();
        } catch (Throwable jjte001) {
                                                                   if (jjtc001) {
                                                                     jjtree.clearNodeScope(jjtn001);
                                                                     jjtc001 = false;
                                                                   } else {
                                                                     jjtree.popNode();
                                                                   }
                                                                   if (jjte001 instanceof RuntimeException) {
                                                                     {if (true) throw (RuntimeException)jjte001;}
                                                                   }
                                                                   if (jjte001 instanceof ParseException) {
                                                                     {if (true) throw (ParseException)jjte001;}
                                                                   }
                                                                   {if (true) throw (Error)jjte001;}
        } finally {
                                                                   if (jjtc001) {
                                                                     jjtree.closeNodeScope(jjtn001,  2);
                                                                   }
        }
        break;
      case STR_NE:
        jj_consume_token(STR_NE);
              constraintvec.addElement(getToken(0).toString());
                                                                   SimpleNode jjtn002 = new SimpleNode(JJTSTRINGNOTEQUAL);
                                                                   boolean jjtc002 = true;
                                                                   jjtree.openNodeScope(jjtn002);
        try {
          NumericalLogical();
        } catch (Throwable jjte002) {
                                                                   if (jjtc002) {
                                                                     jjtree.clearNodeScope(jjtn002);
                                                                     jjtc002 = false;
                                                                   } else {
                                                                     jjtree.popNode();
                                                                   }
                                                                   if (jjte002 instanceof RuntimeException) {
                                                                     {if (true) throw (RuntimeException)jjte002;}
                                                                   }
                                                                   if (jjte002 instanceof ParseException) {
                                                                     {if (true) throw (ParseException)jjte002;}
                                                                   }
                                                                   {if (true) throw (Error)jjte002;}
        } finally {
                                                                   if (jjtc002) {
                                                                     jjtree.closeNodeScope(jjtn002,  2);
                                                                   }
        }
        break;
      case STR_MATCH:
        jj_consume_token(STR_MATCH);
                 constraintvec.addElement("(");
                 constraintvec.addElement(constraintvec.elementAt(constraintvec.size()-2));
                 constraintvec.addElement(",");
                 constraintvec.setElementAt("like",constraintvec.size()-4);
                 constraintvec.addElement("areg(" + getNextToken().toString() + ")");
                 constraintvec.addElement(")");
        Pattern();
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void Pattern() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 0:
      jj_consume_token(0);
      break;
    case SUCHTHAT:
      ConstraintClause();
      break;
    case PREFIXES:
      PrefixesClause();
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

// Expressions that involve comparing numbers.
  static final public void NumericalLogical() throws ParseException {
    InclusiveOrExpression();
  }

  static final public void InclusiveOrExpression() throws ParseException {
    ExclusiveOrExpression();
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BIT_OR:
        ;
        break;
      default:
        jj_la1[19] = jj_gen;
        break label_9;
      }
      jj_consume_token(BIT_OR);
              constraintvec.addElement(getToken(0).toString());
                                                                   SimpleNode jjtn001 = new SimpleNode(JJTBITOR);
                                                                   boolean jjtc001 = true;
                                                                   jjtree.openNodeScope(jjtn001);
      try {
        ExclusiveOrExpression();
      } catch (Throwable jjte001) {
                                                                   if (jjtc001) {
                                                                     jjtree.clearNodeScope(jjtn001);
                                                                     jjtc001 = false;
                                                                   } else {
                                                                     jjtree.popNode();
                                                                   }
                                                                   if (jjte001 instanceof RuntimeException) {
                                                                     {if (true) throw (RuntimeException)jjte001;}
                                                                   }
                                                                   if (jjte001 instanceof ParseException) {
                                                                     {if (true) throw (ParseException)jjte001;}
                                                                   }
                                                                   {if (true) throw (Error)jjte001;}
      } finally {
                                                                   if (jjtc001) {
                                                                     jjtree.closeNodeScope(jjtn001,  2);
                                                                   }
      }
    }
  }

  static final public void ExclusiveOrExpression() throws ParseException {
    AndExpression();
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BIT_XOR:
        ;
        break;
      default:
        jj_la1[20] = jj_gen;
        break label_10;
      }
      jj_consume_token(BIT_XOR);
               constraintvec.addElement(getToken(0).toString());
                                                                    SimpleNode jjtn001 = new SimpleNode(JJTBITXOR);
                                                                    boolean jjtc001 = true;
                                                                    jjtree.openNodeScope(jjtn001);
      try {
        AndExpression();
      } catch (Throwable jjte001) {
                                                                    if (jjtc001) {
                                                                      jjtree.clearNodeScope(jjtn001);
                                                                      jjtc001 = false;
                                                                    } else {
                                                                      jjtree.popNode();
                                                                    }
                                                                    if (jjte001 instanceof RuntimeException) {
                                                                      {if (true) throw (RuntimeException)jjte001;}
                                                                    }
                                                                    if (jjte001 instanceof ParseException) {
                                                                      {if (true) throw (ParseException)jjte001;}
                                                                    }
                                                                    {if (true) throw (Error)jjte001;}
      } finally {
                                                                    if (jjtc001) {
                                                                      jjtree.closeNodeScope(jjtn001,  2);
                                                                    }
      }
    }
  }

  static final public void AndExpression() throws ParseException {
    ArithmeticCondition();
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BIT_AND:
        ;
        break;
      default:
        jj_la1[21] = jj_gen;
        break label_11;
      }
      jj_consume_token(BIT_AND);
               constraintvec.addElement(getToken(0).toString());
                                                                    SimpleNode jjtn001 = new SimpleNode(JJTBITAND);
                                                                    boolean jjtc001 = true;
                                                                    jjtree.openNodeScope(jjtn001);
      try {
        ArithmeticCondition();
      } catch (Throwable jjte001) {
                                                                    if (jjtc001) {
                                                                      jjtree.clearNodeScope(jjtn001);
                                                                      jjtc001 = false;
                                                                    } else {
                                                                      jjtree.popNode();
                                                                    }
                                                                    if (jjte001 instanceof RuntimeException) {
                                                                      {if (true) throw (RuntimeException)jjte001;}
                                                                    }
                                                                    if (jjte001 instanceof ParseException) {
                                                                      {if (true) throw (ParseException)jjte001;}
                                                                    }
                                                                    {if (true) throw (Error)jjte001;}
      } finally {
                                                                    if (jjtc001) {
                                                                      jjtree.closeNodeScope(jjtn001,  2);
                                                                    }
      }
    }
  }

  static final public void ArithmeticCondition() throws ParseException {
    EqualityExpression();
  }

  static final public void EqualityExpression() throws ParseException {
    RelationalExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
    case NEQ:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
        jj_consume_token(EQ);
          constraintvec.addElement(getToken(0).toString());
                                                               SimpleNode jjtn001 = new SimpleNode(JJTEQUAL);
                                                               boolean jjtc001 = true;
                                                               jjtree.openNodeScope(jjtn001);
        try {
          RelationalExpression();
        } catch (Throwable jjte001) {
                                                               if (jjtc001) {
                                                                 jjtree.clearNodeScope(jjtn001);
                                                                 jjtc001 = false;
                                                               } else {
                                                                 jjtree.popNode();
                                                               }
                                                               if (jjte001 instanceof RuntimeException) {
                                                                 {if (true) throw (RuntimeException)jjte001;}
                                                               }
                                                               if (jjte001 instanceof ParseException) {
                                                                 {if (true) throw (ParseException)jjte001;}
                                                               }
                                                               {if (true) throw (Error)jjte001;}
        } finally {
                                                               if (jjtc001) {
                                                                 jjtree.closeNodeScope(jjtn001,  2);
                                                               }
        }
        break;
      case NEQ:
        jj_consume_token(NEQ);
           constraintvec.addElement(getToken(0).toString());
                                                                SimpleNode jjtn002 = new SimpleNode(JJTNOTEQUAL);
                                                                boolean jjtc002 = true;
                                                                jjtree.openNodeScope(jjtn002);
        try {
          RelationalExpression();
        } catch (Throwable jjte002) {
                                                                if (jjtc002) {
                                                                  jjtree.clearNodeScope(jjtn002);
                                                                  jjtc002 = false;
                                                                } else {
                                                                  jjtree.popNode();
                                                                }
                                                                if (jjte002 instanceof RuntimeException) {
                                                                  {if (true) throw (RuntimeException)jjte002;}
                                                                }
                                                                if (jjte002 instanceof ParseException) {
                                                                  {if (true) throw (ParseException)jjte002;}
                                                                }
                                                                {if (true) throw (Error)jjte002;}
        } finally {
                                                                if (jjtc002) {
                                                                  jjtree.closeNodeScope(jjtn002,  2);
                                                                }
        }
        break;
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[23] = jj_gen;
      ;
    }
  }

  static final public void RelationalExpression() throws ParseException {
    NumericExpression();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case GT:
    case LT:
    case LE:
    case GE:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LT:
        jj_consume_token(LT);
          constraintvec.addElement(getToken(0).toString());
                                                               SimpleNode jjtn001 = new SimpleNode(JJTLESSTHAN);
                                                               boolean jjtc001 = true;
                                                               jjtree.openNodeScope(jjtn001);
        try {
          NumericExpression();
        } catch (Throwable jjte001) {
                                                               if (jjtc001) {
                                                                 jjtree.clearNodeScope(jjtn001);
                                                                 jjtc001 = false;
                                                               } else {
                                                                 jjtree.popNode();
                                                               }
                                                               if (jjte001 instanceof RuntimeException) {
                                                                 {if (true) throw (RuntimeException)jjte001;}
                                                               }
                                                               if (jjte001 instanceof ParseException) {
                                                                 {if (true) throw (ParseException)jjte001;}
                                                               }
                                                               {if (true) throw (Error)jjte001;}
        } finally {
                                                               if (jjtc001) {
                                                                 jjtree.closeNodeScope(jjtn001,  2);
                                                               }
        }
        break;
      case GT:
        jj_consume_token(GT);
          constraintvec.addElement(getToken(0).toString());
                                                               SimpleNode jjtn002 = new SimpleNode(JJTGREATERTHAN);
                                                               boolean jjtc002 = true;
                                                               jjtree.openNodeScope(jjtn002);
        try {
          NumericExpression();
        } catch (Throwable jjte002) {
                                                               if (jjtc002) {
                                                                 jjtree.clearNodeScope(jjtn002);
                                                                 jjtc002 = false;
                                                               } else {
                                                                 jjtree.popNode();
                                                               }
                                                               if (jjte002 instanceof RuntimeException) {
                                                                 {if (true) throw (RuntimeException)jjte002;}
                                                               }
                                                               if (jjte002 instanceof ParseException) {
                                                                 {if (true) throw (ParseException)jjte002;}
                                                               }
                                                               {if (true) throw (Error)jjte002;}
        } finally {
                                                               if (jjtc002) {
                                                                 jjtree.closeNodeScope(jjtn002,  2);
                                                               }
        }
        break;
      case LE:
        jj_consume_token(LE);
          constraintvec.addElement(getToken(0).toString());
                                                               SimpleNode jjtn003 = new SimpleNode(JJTLESSTHANOREQUAL);
                                                               boolean jjtc003 = true;
                                                               jjtree.openNodeScope(jjtn003);
        try {
          NumericExpression();
        } catch (Throwable jjte003) {
                                                               if (jjtc003) {
                                                                 jjtree.clearNodeScope(jjtn003);
                                                                 jjtc003 = false;
                                                               } else {
                                                                 jjtree.popNode();
                                                               }
                                                               if (jjte003 instanceof RuntimeException) {
                                                                 {if (true) throw (RuntimeException)jjte003;}
                                                               }
                                                               if (jjte003 instanceof ParseException) {
                                                                 {if (true) throw (ParseException)jjte003;}
                                                               }
                                                               {if (true) throw (Error)jjte003;}
        } finally {
                                                               if (jjtc003) {
                                                                 jjtree.closeNodeScope(jjtn003,  2);
                                                               }
        }
        break;
      case GE:
        jj_consume_token(GE);
          constraintvec.addElement(getToken(0).toString());
                                                               SimpleNode jjtn004 = new SimpleNode(JJTGREATERTHANOREQUAL);
                                                               boolean jjtc004 = true;
                                                               jjtree.openNodeScope(jjtn004);
        try {
          NumericExpression();
        } catch (Throwable jjte004) {
                                                               if (jjtc004) {
                                                                 jjtree.clearNodeScope(jjtn004);
                                                                 jjtc004 = false;
                                                               } else {
                                                                 jjtree.popNode();
                                                               }
                                                               if (jjte004 instanceof RuntimeException) {
                                                                 {if (true) throw (RuntimeException)jjte004;}
                                                               }
                                                               if (jjte004 instanceof ParseException) {
                                                                 {if (true) throw (ParseException)jjte004;}
                                                               }
                                                               {if (true) throw (Error)jjte004;}
        } finally {
                                                               if (jjtc004) {
                                                                 jjtree.closeNodeScope(jjtn004,  2);
                                                               }
        }
        break;
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[25] = jj_gen;
      ;
    }
  }

/*************************************************************/

// **** Debug point
  static final public void NumericExpression() throws ParseException {
    ShiftExpression();
  }

  static final public void ShiftExpression() throws ParseException {
    AdditiveExpression();
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LSHIFT:
      case RSIGNEDSHIFT:
      case RUNSIGNEDSHIFT:
        ;
        break;
      default:
        jj_la1[26] = jj_gen;
        break label_12;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LSHIFT:
        jj_consume_token(LSHIFT);
              constraintvec.addElement(getToken(0).toString());
                                                                   SimpleNode jjtn001 = new SimpleNode(JJTLEFTSHIFT);
                                                                   boolean jjtc001 = true;
                                                                   jjtree.openNodeScope(jjtn001);
        try {
          AdditiveExpression();
        } catch (Throwable jjte001) {
                                                                   if (jjtc001) {
                                                                     jjtree.clearNodeScope(jjtn001);
                                                                     jjtc001 = false;
                                                                   } else {
                                                                     jjtree.popNode();
                                                                   }
                                                                   if (jjte001 instanceof RuntimeException) {
                                                                     {if (true) throw (RuntimeException)jjte001;}
                                                                   }
                                                                   if (jjte001 instanceof ParseException) {
                                                                     {if (true) throw (ParseException)jjte001;}
                                                                   }
                                                                   {if (true) throw (Error)jjte001;}
        } finally {
                                                                   if (jjtc001) {
                                                                     jjtree.closeNodeScope(jjtn001,  2);
                                                                   }
        }
        break;
      case RSIGNEDSHIFT:
        jj_consume_token(RSIGNEDSHIFT);
                    constraintvec.addElement(getToken(0).toString());
                                                                         SimpleNode jjtn002 = new SimpleNode(JJTRIGHTSIGNEDSHIFT);
                                                                         boolean jjtc002 = true;
                                                                         jjtree.openNodeScope(jjtn002);
        try {
          AdditiveExpression();
        } catch (Throwable jjte002) {
                                                                         if (jjtc002) {
                                                                           jjtree.clearNodeScope(jjtn002);
                                                                           jjtc002 = false;
                                                                         } else {
                                                                           jjtree.popNode();
                                                                         }
                                                                         if (jjte002 instanceof RuntimeException) {
                                                                           {if (true) throw (RuntimeException)jjte002;}
                                                                         }
                                                                         if (jjte002 instanceof ParseException) {
                                                                           {if (true) throw (ParseException)jjte002;}
                                                                         }
                                                                         {if (true) throw (Error)jjte002;}
        } finally {
                                                                         if (jjtc002) {
                                                                           jjtree.closeNodeScope(jjtn002,  2);
                                                                         }
        }
        break;
      case RUNSIGNEDSHIFT:
        jj_consume_token(RUNSIGNEDSHIFT);
                      constraintvec.addElement(getToken(0).toString());
                                                                           SimpleNode jjtn003 = new SimpleNode(JJTRIGHTUNSIGNEDSHIFT);
                                                                           boolean jjtc003 = true;
                                                                           jjtree.openNodeScope(jjtn003);
        try {
          AdditiveExpression();
        } catch (Throwable jjte003) {
                                                                           if (jjtc003) {
                                                                             jjtree.clearNodeScope(jjtn003);
                                                                             jjtc003 = false;
                                                                           } else {
                                                                             jjtree.popNode();
                                                                           }
                                                                           if (jjte003 instanceof RuntimeException) {
                                                                             {if (true) throw (RuntimeException)jjte003;}
                                                                           }
                                                                           if (jjte003 instanceof ParseException) {
                                                                             {if (true) throw (ParseException)jjte003;}
                                                                           }
                                                                           {if (true) throw (Error)jjte003;}
        } finally {
                                                                           if (jjtc003) {
                                                                             jjtree.closeNodeScope(jjtn003,  2);
                                                                           }
        }
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void AdditiveExpression() throws ParseException {
    MultiplicativeExpression();
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[28] = jj_gen;
        break label_13;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
            constraintvec.addElement(getToken(0).toString());
                                                                 SimpleNode jjtn001 = new SimpleNode(JJTADD);
                                                                 boolean jjtc001 = true;
                                                                 jjtree.openNodeScope(jjtn001);
        try {
          MultiplicativeExpression();
        } catch (Throwable jjte001) {
                                                                 if (jjtc001) {
                                                                   jjtree.clearNodeScope(jjtn001);
                                                                   jjtc001 = false;
                                                                 } else {
                                                                   jjtree.popNode();
                                                                 }
                                                                 if (jjte001 instanceof RuntimeException) {
                                                                   {if (true) throw (RuntimeException)jjte001;}
                                                                 }
                                                                 if (jjte001 instanceof ParseException) {
                                                                   {if (true) throw (ParseException)jjte001;}
                                                                 }
                                                                 {if (true) throw (Error)jjte001;}
        } finally {
                                                                 if (jjtc001) {
                                                                   jjtree.closeNodeScope(jjtn001,  2);
                                                                 }
        }
        break;
      case MINUS:
        jj_consume_token(MINUS);
             constraintvec.addElement(getToken(0).toString());
                                                                  SimpleNode jjtn002 = new SimpleNode(JJTSUBTRACT);
                                                                  boolean jjtc002 = true;
                                                                  jjtree.openNodeScope(jjtn002);
        try {
          MultiplicativeExpression();
        } catch (Throwable jjte002) {
                                                                  if (jjtc002) {
                                                                    jjtree.clearNodeScope(jjtn002);
                                                                    jjtc002 = false;
                                                                  } else {
                                                                    jjtree.popNode();
                                                                  }
                                                                  if (jjte002 instanceof RuntimeException) {
                                                                    {if (true) throw (RuntimeException)jjte002;}
                                                                  }
                                                                  if (jjte002 instanceof ParseException) {
                                                                    {if (true) throw (ParseException)jjte002;}
                                                                  }
                                                                  {if (true) throw (Error)jjte002;}
        } finally {
                                                                  if (jjtc002) {
                                                                    jjtree.closeNodeScope(jjtn002,  2);
                                                                  }
        }
        break;
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void MultiplicativeExpression() throws ParseException {
    UnaryExpression();
    label_14:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STAR:
      case SLASH:
      case REM:
        ;
        break;
      default:
        jj_la1[30] = jj_gen;
        break label_14;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STAR:
        jj_consume_token(STAR);
             constraintvec.addElement(getToken(0).toString());
                                                                  SimpleNode jjtn001 = new SimpleNode(JJTMULTIPLY);
                                                                  boolean jjtc001 = true;
                                                                  jjtree.openNodeScope(jjtn001);
        try {
          UnaryExpression();
        } catch (Throwable jjte001) {
                                                                  if (jjtc001) {
                                                                    jjtree.clearNodeScope(jjtn001);
                                                                    jjtc001 = false;
                                                                  } else {
                                                                    jjtree.popNode();
                                                                  }
                                                                  if (jjte001 instanceof RuntimeException) {
                                                                    {if (true) throw (RuntimeException)jjte001;}
                                                                  }
                                                                  if (jjte001 instanceof ParseException) {
                                                                    {if (true) throw (ParseException)jjte001;}
                                                                  }
                                                                  {if (true) throw (Error)jjte001;}
        } finally {
                                                                  if (jjtc001) {
                                                                    jjtree.closeNodeScope(jjtn001,  2);
                                                                  }
        }
        break;
      case SLASH:
        jj_consume_token(SLASH);
             constraintvec.addElement(getToken(0).toString());
                                                                  SimpleNode jjtn002 = new SimpleNode(JJTDIVIDE);
                                                                  boolean jjtc002 = true;
                                                                  jjtree.openNodeScope(jjtn002);
        try {
          UnaryExpression();
        } catch (Throwable jjte002) {
                                                                  if (jjtc002) {
                                                                    jjtree.clearNodeScope(jjtn002);
                                                                    jjtc002 = false;
                                                                  } else {
                                                                    jjtree.popNode();
                                                                  }
                                                                  if (jjte002 instanceof RuntimeException) {
                                                                    {if (true) throw (RuntimeException)jjte002;}
                                                                  }
                                                                  if (jjte002 instanceof ParseException) {
                                                                    {if (true) throw (ParseException)jjte002;}
                                                                  }
                                                                  {if (true) throw (Error)jjte002;}
        } finally {
                                                                  if (jjtc002) {
                                                                    jjtree.closeNodeScope(jjtn002,  2);
                                                                  }
        }
        break;
      case REM:
        jj_consume_token(REM);
             constraintvec.addElement(getToken(0).toString());
                                                                  SimpleNode jjtn003 = new SimpleNode(JJTMODULUS);
                                                                  boolean jjtc003 = true;
                                                                  jjtree.openNodeScope(jjtn003);
        try {
          UnaryExpression();
        } catch (Throwable jjte003) {
                                                                  if (jjtc003) {
                                                                    jjtree.clearNodeScope(jjtn003);
                                                                    jjtc003 = false;
                                                                  } else {
                                                                    jjtree.popNode();
                                                                  }
                                                                  if (jjte003 instanceof RuntimeException) {
                                                                    {if (true) throw (RuntimeException)jjte003;}
                                                                  }
                                                                  if (jjte003 instanceof ParseException) {
                                                                    {if (true) throw (ParseException)jjte003;}
                                                                  }
                                                                  {if (true) throw (Error)jjte003;}
        } finally {
                                                                  if (jjtc003) {
                                                                    jjtree.closeNodeScope(jjtn003,  2);
                                                                  }
        }
        break;
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  static final public void UnaryExpression() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL1:
    case STRING_LITERAL2:
    case BOOLEAN_LITERAL:
    case NULL_LITERAL:
    case LPAREN:
    case LT:
    case BANG:
    case TILDE:
    case HOOK:
      UnaryExpressionNotPlusMinus();
      break;
    case PLUS:
    case MINUS:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
             constraintvec.addElement(getToken(0).toString());
                                                                  SimpleNode jjtn001 = new SimpleNode(JJTUNARYPLUS);
                                                                  boolean jjtc001 = true;
                                                                  jjtree.openNodeScope(jjtn001);
        try {
          UnaryExpression();
        } catch (Throwable jjte001) {
                                                                  if (jjtc001) {
                                                                    jjtree.clearNodeScope(jjtn001);
                                                                    jjtc001 = false;
                                                                  } else {
                                                                    jjtree.popNode();
                                                                  }
                                                                  if (jjte001 instanceof RuntimeException) {
                                                                    {if (true) throw (RuntimeException)jjte001;}
                                                                  }
                                                                  if (jjte001 instanceof ParseException) {
                                                                    {if (true) throw (ParseException)jjte001;}
                                                                  }
                                                                  {if (true) throw (Error)jjte001;}
        } finally {
                                                                  if (jjtc001) {
                                                                    jjtree.closeNodeScope(jjtn001,  1);
                                                                  }
        }
        break;
      case MINUS:
        jj_consume_token(MINUS);
             constraintvec.addElement(getToken(0).toString());
                                                                  SimpleNode jjtn002 = new SimpleNode(JJTUNARYMINUS);
                                                                  boolean jjtc002 = true;
                                                                  jjtree.openNodeScope(jjtn002);
        try {
          UnaryExpression();
        } catch (Throwable jjte002) {
                                                                  if (jjtc002) {
                                                                    jjtree.clearNodeScope(jjtn002);
                                                                    jjtc002 = false;
                                                                  } else {
                                                                    jjtree.popNode();
                                                                  }
                                                                  if (jjte002 instanceof RuntimeException) {
                                                                    {if (true) throw (RuntimeException)jjte002;}
                                                                  }
                                                                  if (jjte002 instanceof ParseException) {
                                                                    {if (true) throw (ParseException)jjte002;}
                                                                  }
                                                                  {if (true) throw (Error)jjte002;}
        } finally {
                                                                  if (jjtc002) {
                                                                    jjtree.closeNodeScope(jjtn002,  1);
                                                                  }
        }
        break;
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[33] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void UnaryExpressionNotPlusMinus() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case BANG:
    case TILDE:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TILDE:
        jj_consume_token(TILDE);
        break;
      case BANG:
        jj_consume_token(BANG);
        break;
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                        constraintvec.addElement(getToken(0).toString());
                                                                             SimpleNode jjtn001 = new SimpleNode(JJTUNARYNOT);
                                                                             boolean jjtc001 = true;
                                                                             jjtree.openNodeScope(jjtn001);
      try {
        UnaryExpression();
      } catch (Throwable jjte001) {
                                                                             if (jjtc001) {
                                                                               jjtree.clearNodeScope(jjtn001);
                                                                               jjtc001 = false;
                                                                             } else {
                                                                               jjtree.popNode();
                                                                             }
                                                                             if (jjte001 instanceof RuntimeException) {
                                                                               {if (true) throw (RuntimeException)jjte001;}
                                                                             }
                                                                             if (jjte001 instanceof ParseException) {
                                                                               {if (true) throw (ParseException)jjte001;}
                                                                             }
                                                                             {if (true) throw (Error)jjte001;}
      } finally {
                                                                             if (jjtc001) {
                                                                               jjtree.closeNodeScope(jjtn001,  1);
                                                                             }
      }
      break;
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL1:
    case STRING_LITERAL2:
    case BOOLEAN_LITERAL:
    case NULL_LITERAL:
    case LPAREN:
    case LT:
    case HOOK:
      PrimaryExpression();
      break;
    default:
      jj_la1[35] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  static final public void PrimaryExpression() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case HOOK:
      Var(2);
      break;
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
    case STRING_LITERAL1:
    case STRING_LITERAL2:
    case BOOLEAN_LITERAL:
    case NULL_LITERAL:
    case LT:
      Literal1();
      break;
    case LPAREN:
      jj_consume_token(LPAREN);
            constraintvec.addElement(getToken(0).toString());
      Expression();
      jj_consume_token(RPAREN);
                                                                                     constraintvec.addElement(getToken(0).toString());
      break;
    default:
      jj_la1[36] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

/*********************************************************************/

//Literal comes from Triplepattern
  static final public void Literal() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LT:
      URI(2);
      break;
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
      NumericLiteral(0);
      break;
    case STRING_LITERAL1:
    case STRING_LITERAL2:
      TextLiteral(0);
      break;
    case BOOLEAN_LITERAL:
      BooleanLiteral(0);
      break;
    case NULL_LITERAL:
      NullLiteral(0);
      break;
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

//Literal1 comes from Primary Expression
  static final public void Literal1() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LT:
      URI(3);
      break;
    case INTEGER_LITERAL:
    case FLOATING_POINT_LITERAL:
      NumericLiteral(1);
      break;
    case STRING_LITERAL1:
    case STRING_LITERAL2:
      TextLiteral(1);
      break;
    case BOOLEAN_LITERAL:
      BooleanLiteral(1);
      break;
    case NULL_LITERAL:
      NullLiteral(1);
      break;
    default:
      jj_la1[38] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

// for the rest of the literals: 
//0, from Triplepattern
//1, from PrimaryExpression
  static final public void NumericLiteral(int numlit) throws ParseException {
 /*@bgen(jjtree) NumericLiteral */
  SimpleNode jjtn000 = new SimpleNode(JJTNUMERICLITERAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case INTEGER_LITERAL:
        jj_consume_token(INTEGER_LITERAL);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
  if(numlit==0) {rdfTriples.addElement(getToken(0).toString());}
  if (numlit==1) {constraintvec.addElement("'"+getToken(0).toString()+"'");}
        break;
      case FLOATING_POINT_LITERAL:
        jj_consume_token(FLOATING_POINT_LITERAL);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
  if (numlit==0) {rdfTriples.addElement(getToken(0).toString());}
  if (numlit==1) {constraintvec.addElement("'"+getToken(0).toString()+"'");}
        break;
      default:
        jj_la1[39] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void TextLiteral(int textlit) throws ParseException {
 /*@bgen(jjtree) TextLiteral */
  SimpleNode jjtn000 = new SimpleNode(JJTTEXTLITERAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STRING_LITERAL1:
        jj_consume_token(STRING_LITERAL1);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
  if (textlit==0) {rdfTriples.addElement(getToken(0).toString());}
  //if (textlit==0) {rdfTriples.addElement("lit(" + getToken(0).toString() + ")");}
  if (textlit==1) {constraintvec.addElement("'"+getToken(0).toString()+"'");}
        break;
      case STRING_LITERAL2:
        jj_consume_token(STRING_LITERAL2);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
  if (textlit==0) {rdfTriples.addElement(getToken(0).toString());}
  //if (textlit==0) {rdfTriples.addElement("lit(" + getToken(0).toString() + ")");}
  if (textlit==1) {constraintvec.addElement("'"+getToken(0).toString()+"'");}
        break;
      default:
        jj_la1[40] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void BooleanLiteral(int boollit) throws ParseException {
 /*@bgen(jjtree) BooleanLiteral */
  SimpleNode jjtn000 = new SimpleNode(JJTBOOLEANLITERAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(BOOLEAN_LITERAL);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
  if (boollit==0) {rdfTriples.addElement(getToken(0).toString());}
  if (boollit==1) {constraintvec.addElement(getToken(0).toString());}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

  static final public void NullLiteral(int nulllit) throws ParseException {
 /*@bgen(jjtree) NullLiteral */
  SimpleNode jjtn000 = new SimpleNode(JJTNULLLITERAL);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(NULL_LITERAL);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
  if (nulllit==0) {rdfTriples.addElement(getToken(0).toString());}
  if (nulllit==1) {constraintvec.addElement("'"+getToken(0).toString()+"'");} //"null" does not exist in AmosQL

    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
  }

//uriflag==0, source
//uriflag==1, prefix (... for URI)
//uriflag==2, URI in rdfTriple
//uriflag==3, URI in PrimaryExpression
  static final public void URI(int uriflag) throws ParseException {
 /*@bgen(jjtree) URI */
 SimpleNode jjtn000 = new SimpleNode(JJTURI);
 boolean jjtc000 = true;
 jjtree.openNodeScope(jjtn000);String ident="";
    try {
      jj_consume_token(LT);
      ident = Identifier();
      jj_consume_token(GT);
          jjtree.closeNodeScope(jjtn000, true);
          jjtc000 = false;
        if (uriflag==0) {sources.addElement(ident);}
        if (uriflag==1) {prefixvec.addElement(ident);}/*that's a bit tricky: in the postfix (prefix:postfix)
  													we have the "'" after it included because it's extractet
  													from an	Uri in a RDFTriple. But not before the prefix*/
        if (uriflag==2) {rdfTriples.addElement("'"+ident+"'");}
        //if (uriflag==2) {rdfTriples.addElement("uri('"+ident+"')");}
        if (uriflag==3) {constraintvec.addElement("'"+ident+"'");}
    } catch (Throwable jjte000) {
          if (jjtc000) {
            jjtree.clearNodeScope(jjtn000);
            jjtc000 = false;
          } else {
            jjtree.popNode();
          }
          if (jjte000 instanceof RuntimeException) {
            {if (true) throw (RuntimeException)jjte000;}
          }
          if (jjte000 instanceof ParseException) {
            {if (true) throw (ParseException)jjte000;}
          }
          {if (true) throw (Error)jjte000;}
    } finally {
          if (jjtc000) {
            jjtree.closeNodeScope(jjtn000, true);
          }
    }
  }

  static final public String Identifier() throws ParseException {
 /*@bgen(jjtree) Identifier */
  SimpleNode jjtn000 = new SimpleNode(JJTIDENTIFIER);
  boolean jjtc000 = true;
  jjtree.openNodeScope(jjtn000);
    try {
      jj_consume_token(IDENTIFIER);
    jjtree.closeNodeScope(jjtn000, true);
    jjtc000 = false;
        {if (true) return getToken(0).toString();}
    } finally {
    if (jjtc000) {
      jjtree.closeNodeScope(jjtn000, true);
    }
    }
    throw new Error("Missing return statement in function");
  }

  static final private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static final private boolean jj_3R_15() {
    if (jj_scan_token(HOOK)) return true;
    return false;
  }

  static final private boolean jj_3_1() {
    if (jj_scan_token(SELECT)) return true;
    if (jj_3R_15()) return true;
    return false;
  }

  static private boolean jj_initialized_once = false;
  static public Rdql2AmosTokenManager token_source;
  static JavaCharStream jj_input_stream;
  static public Token token, jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static public boolean lookingAhead = false;
  static private boolean jj_semLA;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[41];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
      jj_la1_0();
      jj_la1_1();
      jj_la1_2();
   }
   private static void jj_la1_0() {
      jj_la1_0 = new int[] {0x0,0x600000,0x1000000,0x2000000,0x0,0x100000,0x600000,0x0,0x0,0x1000000,0x1000000,0x20000000,0x0,0xc0034800,0x0,0x0,0x18000000,0x18000000,0x3000001,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xc0034800,0x0,0xc0034800,0xc0034800,0xc0034800,0xc0034800,0x4800,0x30000,};
   }
   private static void jj_la1_1() {
      jj_la1_1 = new int[] {0x100,0x0,0x0,0x0,0x8100,0x0,0x0,0x1100,0x102,0x100,0x100,0x100,0x9000,0x9000,0x200000,0x400000,0x0,0x0,0x0,0x40000000,0x80000000,0x20000000,0x60000,0x60000,0x181800,0x181800,0x0,0x0,0x6000000,0x6000000,0x18000000,0x18000000,0x6000000,0x600f002,0x6000,0xf002,0x9002,0x1000,0x1000,0x0,0x0,};
   }
   private static void jj_la1_2() {
      jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x10,0x10,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0xe,0xe,0x0,0x0,0x1,0x1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[1];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  public Rdql2Amos(java.io.InputStream stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new Rdql2AmosTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static public void ReInit(java.io.InputStream stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public Rdql2Amos(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new JavaCharStream(stream, 1, 1);
    token_source = new Rdql2AmosTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public Rdql2Amos(Rdql2AmosTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  You must");
      System.out.println("       either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  public void ReInit(Rdql2AmosTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jjtree.reset();
    jj_gen = 0;
    for (int i = 0; i < 41; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static final private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static final private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }

  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

  static final public Token getToken(int index) {
    Token t = lookingAhead ? jj_scanpos : token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static final private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.Vector jj_expentries = new java.util.Vector();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Enumeration e = jj_expentries.elements(); e.hasMoreElements();) {
        int[] oldentry = (int[])(e.nextElement());
        if (oldentry.length == jj_expentry.length) {
          exists = true;
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.addElement(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  static public ParseException generateParseException() {
    jj_expentries.removeAllElements();
    boolean[] la1tokens = new boolean[72];
    for (int i = 0; i < 72; i++) {
      la1tokens[i] = false;
    }
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 41; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
          if ((jj_la1_2[i] & (1<<j)) != 0) {
            la1tokens[64+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 72; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.addElement(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = (int[])jj_expentries.elementAt(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  static final public void enable_tracing() {
  }

  static final public void disable_tracing() {
  }

  static final private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
    }
    jj_rescan = false;
  }

  static final private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
