/* Generated By:JJTree&JavaCC: Do not edit this line. Rdql2AmosConstants.java */
public interface Rdql2AmosConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 8;
  int MULTI_LINE_COMMENT = 9;
  int INTEGER_LITERAL = 11;
  int DECIMAL_LITERAL = 12;
  int HEX_LITERAL = 13;
  int FLOATING_POINT_LITERAL = 14;
  int EXPONENT = 15;
  int STRING_LITERAL1 = 16;
  int STRING_LITERAL2 = 17;
  int LETTER = 18;
  int DIGIT = 19;
  int SELECT = 20;
  int SOURCE = 21;
  int FROM = 22;
  int WHERE = 23;
  int SUCHTHAT = 24;
  int PREFIXES = 25;
  int FOR = 26;
  int STR_EQ = 27;
  int STR_NE = 28;
  int IDENTIFIER = 29;
  int BOOLEAN_LITERAL = 30;
  int NULL_LITERAL = 31;
  int DIGITS = 32;
  int LPAREN = 33;
  int RPAREN = 34;
  int LBRACE = 35;
  int RBRACE = 36;
  int LBRACKET = 37;
  int RBRACKET = 38;
  int SEMICOLON = 39;
  int COMMA = 40;
  int DOT = 41;
  int ASSIGN = 42;
  int GT = 43;
  int LT = 44;
  int BANG = 45;
  int TILDE = 46;
  int HOOK = 47;
  int COLON = 48;
  int EQ = 49;
  int NEQ = 50;
  int LE = 51;
  int GE = 52;
  int SC_OR = 53;
  int SC_AND = 54;
  int INCR = 55;
  int DECR = 56;
  int PLUS = 57;
  int MINUS = 58;
  int STAR = 59;
  int SLASH = 60;
  int BIT_AND = 61;
  int BIT_OR = 62;
  int BIT_XOR = 63;
  int REM = 64;
  int LSHIFT = 65;
  int RSIGNEDSHIFT = 66;
  int RUNSIGNEDSHIFT = 67;
  int STR_MATCH = 68;
  int STR_NMATCH = 69;
  int DATATYPE = 70;
  int AT = 71;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "<token of kind 10>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL1>",
    "<STRING_LITERAL2>",
    "<LETTER>",
    "<DIGIT>",
    "\"select\"",
    "\"source\"",
    "\"from\"",
    "\"where\"",
    "\"and\"",
    "\"using\"",
    "\"for\"",
    "\"eq\"",
    "\"ne\"",
    "<IDENTIFIER>",
    "<BOOLEAN_LITERAL>",
    "\"null\"",
    "<DIGITS>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "<STR_MATCH>",
    "\"!~\"",
    "\"^^\"",
    "\"@\"",
  };

}
