;;; ===========================================================================
;;; AMOS2
;;;
;;; Author: (c) 2004 Markus Jägerskogh, UDBL
;;; $RCSfile: MakeRegress.lsp,v $
;;; $Revision: 1.3 $ $Date: 2004/12/09 16:13:53 $
;;; $State: Exp $ $Locker:  $
;;;
;;; Description: Functions to help making regression test from SQL Test suite files.
;;;
;;; ===========================================================================


;* The files in the SQL Test suite 
;* The list is based on information in the file "SQL Test Suite/SQL/runsql.all".
;* Files not to be checked are commented out of the list.
;* FORMAT: ((<path>  <run under schema>  <description>) ...)
(setq SQL_Test_suite_files '(
  ("schema\\schema1.smi" HU "Schema creation")
  ("schema\\schema2.smi" CUGINI "Schema creation")
  ("schema\\schema3.smi" MCGINN "Schema creation")
  ("schema\\schema4.smi" SULLIVAN1 "Schema creation")
  ("schema\\schema5.smi" FLATER "Schema creation")
  ("schema\\schema6.smi" FLATER "Schema creation")
  ("schema\\schema7.smi" CANWEPARSELENGTH18 "Schema creation")
  ("schema\\schema8.smi" SUN "Schema creation: Integrity Enhancement Feature")
  ("schema\\schema9.smi" SULLIVAN "Schema creation: Integrity Enhancement Feature")
  ("schema\\schem10.smi" SCHANZLE "Schema creation: Integrity Enhancement Feature")
  ("schema\\schem11.std" FLATER "Transitional SQL")
  ("schema\\schem12.std" FLATER "Intermediate SQL")
  ("schema\\cts5sch1.sql" CTS2 "Intermediate SQL")
  ("schema\\cts5sch2.sql" CTS1 "Intermediate SQL")
  ("schema\\cts5sch3.sql" CTS1 "Intermediate SQL")
  ("schema\\cts5sch4.sql" CTS4 "Intermediate SQL")
  ("schema\\cts5sch5.sql" CTS3 "Intermediate SQL")
  ("schema\\xschema1.sql" XOPEN1 "X/Open Profiles ")
  ("schema\\xschema2.sql" XOPEN2 "X/Open Profiles")
  ("sql\\basetab.sql" HU "Dataload Programs")
  ("sql\\cugtab.sql" CUGINI "Dataload Programs")
  ("sql\\flattab.sql" FLATER "Dataload Programs")
  ("sql\\suntab0.sql" SUN "Dataload Programs")
  ("sql\\suntab1.sql" SUN "Dataload Programs")
  ("sql\\suntab2.sql" SUN "Dataload Programs")
  ("sql\\suntab3.sql" SUN "Dataload Programs")
  ("sql\\sultab1.sql" SULLIVAN "Dataload Programs")
;INTERVAL, TIME, DATE  ("sql\\sc11tab.sql" FLATER "Dataload Programs: not used for Entry SQL")
;The Schema TIDES is used, but does not exist! ("sql\\sc12tab.sql" FLATER "Dataload Programs: not used for Entry SQL")
  ("sql\\cts5tab.sql" CTS1 "Dataload Programs: not used for Entry SQL")
  ("sql\\flg011.sql" FLATER "Entry Syntax Flags")
  ("sql\\flg012.sql" FLATER "Entry Syntax Flags")
  ("sql\\flg005.sql" HU "Entry Syntax Flags")
  ("sql\\flg008.sql" HU "Entry Syntax Flags")
  ("sql\\sdl026.sql" CANWEPARSELENGTH18 "Entry SQL")
  ("sql\\sdl005.sql" CUGINI "Entry SQL")
  ("sql\\dml087.sql" FLATER "Entry SQL")
;Negative test  ("sql\\dml141.sql" FLATER "Entry SQL")
;Negative test  ("sql\\dml143.sql" FLATER "Entry SQL")
  ("sql\\sdl032.sql" FLATER "Entry SQL")
  ("sql\\dml001.sql" HU "Entry SQL")
  ("sql\\dml004.sql" HU "Entry SQL")
  ("sql\\dml008.sql" HU "Entry SQL")
  ("sql\\dml009.sql" HU "Entry SQL")
  ("sql\\dml010.sql" HU "Entry SQL")
  ("sql\\dml011.sql" HU "Entry SQL")
  ("sql\\dml012.sql" HU "Entry SQL")
  ("sql\\dml013.sql" HU "Entry SQL")
  ("sql\\dml014.sql" HU "Entry SQL")
  ("sql\\dml015.sql" HU "Entry SQL")
  ("sql\\dml018.sql" HU "Entry SQL")
  ("sql\\dml019.sql" HU "Entry SQL")
  ("sql\\dml020.sql" HU "Entry SQL")
  ("sql\\dml021.sql" HU "Entry SQL")
  ("sql\\dml022.sql" HU "Entry SQL")
  ("sql\\dml023.sql" HU "Entry SQL")
  ("sql\\dml024.sql" HU "Entry SQL")
  ("sql\\dml025.sql" HU "Entry SQL")
  ("sql\\dml026.sql" HU "Entry SQL")
  ("sql\\dml027.sql" HU "Entry SQL")
  ("sql\\dml029.sql" HU "Entry SQL")
  ("sql\\dml033.sql" HU "Entry SQL")
  ("sql\\dml034.sql" HU "Entry SQL")
  ("sql\\dml035.sql" HU "Entry SQL")
  ("sql\\dml037.sql" HU "Entry SQL")
  ("sql\\dml038.sql" HU "Entry SQL")
  ("sql\\dml039.sql" HU "Entry SQL")
  ("sql\\dml040.sql" HU "Entry SQL")
  ("sql\\dml041.sql" HU "Entry SQL")
  ("sql\\dml051.sql" HU "Entry SQL")
  ("sql\\dml052.sql" HU "Entry SQL")
  ("sql\\dml053.sql" HU "Entry SQL")
; Reserved word USER  ("sql\\dml058.sql" HU "Entry SQL")
  ("sql\\dml059.sql" HU "Entry SQL")
  ("sql\\dml060.sql" HU "Entry SQL")
  ("sql\\dml061.sql" HU "Entry SQL")
  ("sql\\dml062.sql" HU "Entry SQL")
  ("sql\\dml064.sql" HU "Entry SQL")
  ("sql\\dml065.sql" HU "Entry SQL")
  ("sql\\dml069.sql" HU "Entry SQL")
  ("sql\\dml070.sql" HU "Entry SQL")
  ("sql\\dml073.sql" HU "Entry SQL")
  ("sql\\dml075.sql" HU "Entry SQL")
  ("sql\\dml076.sql" HU "Entry SQL")
  ("sql\\dml077.sql" HU "Entry SQL")
  ("sql\\dml079.sql" HU "Entry SQL")
  ("sql\\dml086.sql" HU "Entry SQL")
  ("sql\\dml090.sql" HU "Entry SQL")
  ("sql\\dml142.sql" HU "Entry SQL")
  ("sql\\sdl001.sql" HU "Entry SQL")
  ("sql\\sdl012.sql" HU "Entry SQL")
  ("sql\\sdl013.sql" HU "Entry SQL")
  ("sql\\sdl014.sql" HU "Entry SQL")
  ("sql\\sdl015.sql" HU "Entry SQL")
  ("sql\\sdl016.sql" HU "Entry SQL")
  ("sql\\sdl017.sql" HU "Entry SQL")
  ("sql\\sdl018.sql" HU "Entry SQL")
  ("sql\\sdl019.sql" HU "Entry SQL")
  ("sql\\sdl020.sql" HU "Entry SQL")
  ("sql\\sdl024.sql" HU "Entry SQL")
  ("sql\\sdl025.sql" HU "Entry SQL")
  ("sql\\sdl027.sql" HU "Entry SQL")
  ("sql\\sdl028.sql" HU "Entry SQL")
;  ("sql\\cdr023.sql" SCHANZLE "Entry SQL")
;  ("sql\\cdr028.sql" SCHANZLE "Entry SQL")
;  ("sql\\cdr029.sql" SCHANZLE "Entry SQL")
  ("sql\\dml080.sql" SCHANZLE "Entry SQL")
  ("sql\\dml081.sql" SCHANZLE "Entry SQL")
  ("sql\\dml082.sql" SCHANZLE "Entry SQL")
  ("sql\\dml083.sql" SCHANZLE "Entry SQL")
  ("sql\\dml084.sql" SCHANZLE "Entry SQL")
  ("sql\\dml085.sql" SCHANZLE "Entry SQL")
  ("sql\\dml091.sql" SCHANZLE "Entry SQL")
  ("sql\\sdl003.sql" SCHANZLE "Entry SQL")
  ("sql\\sdl023.sql" SCHANZLE "Entry SQL")
  ("sql\\sdl029.sql" SCHANZLE "Entry SQL")
  ("sql\\sdl030.sql" SCHANZLE "Entry SQL")
  ("sql\\sdl031.sql" SCHANZLE "Entry SQL")
  ("sql\\sdl033.sql" SCHANZLE "Entry SQL")
  ("sql\\sdl034.sql" SCHANZLE "Entry SQL")
  ("sql\\sdl035.sql" SCHANZLE "Entry SQL")
  ("sql\\sdl036.sql" SCHANZLE "Entry SQL")
;  ("sql\\cdr022.sql" SULLIVAN "Entry SQL")
  ("sql\\dml016.sql" SULLIVAN "Entry SQL")
  ("sql\\sdl002.sql" SULLIVAN "Entry SQL")
  ("sql\\sdl004.sql" SULLIVAN "Entry SQL")
  ("sql\\sdl006.sql" SULLIVAN "Entry SQL")
  ("sql\\sdl007.sql" SULLIVAN "Entry SQL")
  ("sql\\sdl008.sql" SULLIVAN "Entry SQL")
  ("sql\\sdl009.sql" SULLIVAN "Entry SQL")
  ("sql\\sdl010.sql" SULLIVAN "Entry SQL")
  ("sql\\sdl021.sql" SULLIVAN "Entry SQL")
  ("sql\\sdl022.sql" SULLIVAN "Entry SQL")
  ("sql\\sdl011.sql" SULLIVAN1 "Entry SQL")
  ("sql\\sdl037.sql" SULLIVAN1 "Entry SQL")
;  ("sql\\cdr001.sql" SUN "Entry SQL")
;  ("sql\\cdr002.sql" SUN "Entry SQL")
;  ("sql\\cdr003.sql" SUN "Entry SQL")
;  ("sql\\cdr004.sql" SUN "Entry SQL")
;  ("sql\\cdr005.sql" SUN "Entry SQL")
;  ("sql\\cdr006.sql" SUN "Entry SQL")
;  ("sql\\cdr007.sql" SUN "Entry SQL")
;  ("sql\\cdr008.sql" SUN "Entry SQL")
;  ("sql\\cdr009.sql" SUN "Entry SQL")
;  ("sql\\cdr010.sql" SUN "Entry SQL")
;  ("sql\\cdr011.sql" SUN "Entry SQL")
;  ("sql\\cdr012.sql" SUN "Entry SQL")
;  ("sql\\cdr013.sql" SUN "Entry SQL")
;  ("sql\\cdr017.sql" SUN "Entry SQL")
;  ("sql\\cdr019.sql" SUN "Entry SQL")
;  ("sql\\cdr020.sql" SUN "Entry SQL")
;  ("sql\\cdr021.sql" SUN "Entry SQL")
;  ("sql\\cdr024.sql" SUN "Entry SQL")
;  ("sql\\cdr025.sql" SUN "Entry SQL")
;  ("sql\\cdr026.sql" SUN "Entry SQL")
;  ("sql\\cdr027.sql" SUN "Entry SQL")
;  ("sql\\cdr030.sql" SUN "Entry SQL")
  ("sql\\dml099.sql" FLATER "Transitional Only Features")
  ("sql\\dml100.sql" FLATER "Transitional Only Features")
  ("sql\\dml104.sql" FLATER "Transitional Only Features")
  ("sql\\dml106.sql" FLATER "Transitional Only Features")
  ("sql\\dml108.sql" FLATER "Transitional Only Features")
  ("sql\\dml112.sql" FLATER "Transitional Only Features")
  ("sql\\dml114.sql" FLATER "Transitional Only Features")
  ("sql\\dml117.sql" FLATER "Transitional Only Features")
  ("sql\\dml119.sql" FLATER "Transitional Only Features")
  ("sql\\dml121.sql" FLATER "Transitional Only Features")
  ("sql\\dml130.sql" FLATER "Transitional Only Features")
  ("sql\\dml131.sql" FLATER "Transitional Only Features")
  ("sql\\dml133.sql" FLATER "Transitional Only Features")
  ("sql\\dml134.sql" FLATER "Transitional Only Features")
  ("sql\\dml135.sql" FLATER "Transitional Only Features")
  ("sql\\dml136.sql" FLATER "Transitional Only Features")
  ("sql\\dml137.sql" FLATER "Transitional Only Features")
  ("sql\\dml144.sql" FLATER "Transitional Only Features")
  ("sql\\dml147.sql" FLATER "Transitional Only Features")
  ("sql\\dml148.sql" FLATER "Transitional Only Features")
  ("sql\\dml149.sql" FLATER "Transitional Only Features")
  ("sql\\dml153.sql" FLATER "Transitional Only Features")
  ("sql\\dml154.sql" FLATER "Transitional Only Features")
  ("sql\\dml157.sql" FLATER "Transitional Only Features")
  ("sql\\dml162.sql" FLATER "Transitional Only Features")
  ("sql\\dml185.sql" FLATER "Transitional Only Features")
;  ("sql\\ist001.sql" FLATER "Transitional Only Features")
;  ("sql\\ist002.sql" FLATER "Transitional Only Features")
;  ("sql\\ist003.sql" FLATER "Transitional Only Features")
;  ("sql\\ist004.sql" FLATER "Transitional Only Features")
;  ("sql\\ist005.sql" FLATER "Transitional Only Features")
;  ("sql\\ist006.sql" FLATER "Transitional Only Features")
;  ("sql\\ist007.sql" FLATER "Transitional Only Features")
;  ("sql\\mpa010a.sql" FLATER "Transitional Only Features")
;  ("sql\\mpb010a.sql" HU "Transitional Only Features")
;  ("sql\\mpa010b.sql" FLATER "Transitional Only Features")
;  ("sql\\mpb010b.sql" HU "Transitional Only Features")
;  ("sql\\mpa010c.sql" FLATER "Transitional Only Features")
;  ("sql\\mpb010c.sql" HU "Transitional Only Features")
;  ("sql\\mpa010d.sql" FLATER "Transitional Only Features")
;  ("sql\\mpb010d.sql" HU "Transitional Only Features")
;  ("sql\\mpa010e.sql" FLATER "Transitional Only Features")
;  ("sql\\mpb010e.sql" HU "Transitional Only Features")
;  ("sql\\mpa010f.sql" FLATER "Transitional Only Features")
;  ("sql\\mpb010f.sql" HU "Transitional Only Features")
;  ("sql\\mpa010g.sql" FLATER "Transitional Only Features")
  ("sql\\dml139.sql" HU "Transitional Only Features")
  ("sql\\dml158.sql" HU "Transitional Only Features")
  ("sql\\xts700.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts701.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts702.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts703.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts716.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts717.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts718.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts727.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts728.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts729.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts730.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts731.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts732.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts733.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts734.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts735.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts736.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts740.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts741.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts742.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts744.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts745.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts746.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts747.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts748.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts749.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts750.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts752.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts753.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts754.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts755.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts756.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts760.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts761.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts762.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts763.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts764.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts765.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts766.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts767.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts768.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts798.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts799.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts750.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts751.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts752.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts753.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts754.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts755.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts756.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts757.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts759.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts760.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts761.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts762.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts763.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts764.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts765.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts766.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts767.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts768.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts769.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts770.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts771.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts772.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts773.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts774.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts776.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts778.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts779.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts780.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts781.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts782.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts788.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts789.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts790.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts793.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts796.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts797.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts798.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts799.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts800.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts802.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts803.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts805.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts806.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts807.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts808.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts809.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts810.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts811.sql" CTS1 "Intermediate Only Features")
  ("sql\\yts812.sql" CTS1 "Intermediate Only Features")
  ("sql\\xts714.sql" CTS2 "Intermediate Only Features")
  ("sql\\yts777.sql" CTS2 "Intermediate Only Features")
  ("sql\\yts791.sql" CTS2 "Intermediate Only Features")
  ("sql\\yts794.sql" CTS2 "Intermediate Only Features")
  ("sql\\xts769.sql" CTS3 "Intermediate Only Features")
  ("sql\\xts770.sql" CTS3 "Intermediate Only Features")
  ("sql\\xts771.sql" CTS3 "Intermediate Only Features")
  ("sql\\xts715.sql" CTS4 "Intermediate Only Features")
  ("sql\\xts719.sql" CTS4 "Intermediate Only Features")
  ("sql\\xts720.sql" CTS4 "Intermediate Only Features")
  ("sql\\xts721.sql" CTS4 "Intermediate Only Features")
  ("sql\\xts722.sql" CTS4 "Intermediate Only Features")
  ("sql\\xts723.sql" CTS4 "Intermediate Only Features")
  ("sql\\xts724.sql" CTS4 "Intermediate Only Features")
  ("sql\\yts792.sql" CTS4 "Intermediate Only Features")
  ("sql\\yts795.sql" CTS4 "Intermediate Only Features")
  ("sql\\dml160.sql" FLATER "Intermediate Only Features")
  ("sql\\dml161.sql" FLATER "Intermediate Only Features")
  ("sql\\dml163.sql" FLATER "Intermediate Only Features")
  ("sql\\dml164.sql" FLATER "Intermediate Only Features")
  ("sql\\dml165.sql" FLATER "Intermediate Only Features")
  ("sql\\dml167.sql" FLATER "Intermediate Only Features")
  ("sql\\dml168.sql" FLATER "Intermediate Only Features")
  ("sql\\dml169.sql" FLATER "Intermediate Only Features")
  ("sql\\dml170.sql" FLATER "Intermediate Only Features")
  ("sql\\dml171.sql" FLATER "Intermediate Only Features")
  ("sql\\dml172.sql" FLATER "Intermediate Only Features")
  ("sql\\dml184.sql" FLATER "Intermediate Only Features")
;  ("sql\\isi001.sql" FLATER "Intermediate Only Features")
;  ("sql\\isi002.sql" FLATER "Intermediate Only Features")
;  ("sql\\isi003.sql" FLATER "Intermediate Only Features")
;  ("sql\\isi004.sql" FLATER "Intermediate Only Features")
;  ("sql\\isi005.sql" FLATER "Intermediate Only Features")
;  ("sql\\isi006.sql" FLATER "Intermediate Only Features")
;  ("sql\\isi007.sql" FLATER "Intermediate Only Features")
  ("sql\\xts713.sql" T7013PC "Intermediate Only Features")
;  ("sql\\cdr031.sql" FLATER "Entry Sizing")
  ("sql\\dml132.sql" FLATER "Entry Sizing")
  ("sql\\dml005.sql" HU "Entry Sizing")
  ("sql\\dml042.sql" HU "Entry Sizing")
  ("sql\\dml043.sql" HU "Entry Sizing")
  ("sql\\dml044.sql" HU "Entry Sizing")
  ("sql\\dml045.sql" HU "Entry Sizing")
  ("sql\\dml046.sql" HU "Entry Sizing")
  ("sql\\dml047.sql" HU "Entry Sizing")
  ("sql\\dml049.sql" HU "Entry Sizing")
  ("sql\\dml050.sql" HU "Entry Sizing")
  ("sql\\dml055.sql" HU "Entry Sizing")
  ("sql\\dml056.sql" HU "Entry Sizing")
  ("sql\\dml057.sql" HU "Entry Sizing")
;  ("sql\\cdr014.sql" SUN "Entry Sizing")
;  ("sql\\cdr015.sql" SUN "Entry Sizing")
;  ("sql\\cdr016.sql" SUN "Entry Sizing")
;  ("sql\\cdr017.sql" SUN "Entry Sizing")
;  ("sql\\cdr018.sql" SUN "Entry Sizing")
  ("sql\\dml106.sql" FLATER "Transitional Sizing")
  ("sql\\dml173.sql" FLATER "Intermediate Sizing")
  ("sql\\dml174.sql" FLATER "Intermediate Sizing")
  ("sql\\dml175.sql" FLATER "Intermediate Sizing")
  ("sql\\dml176.sql" FLATER "Intermediate Sizing")
  ("sql\\dml177.sql" FLATER "Intermediate Sizing")
  ("sql\\dml178.sql" FLATER "Intermediate Sizing")
  ("sql\\dml179.sql" FLATER "Intermediate Sizing")
  ("sql\\dml181.sql" FLATER "Intermediate Sizing")
  ("sql\\dml182.sql" FLATER "Intermediate Sizing")
  ("sql\\dml183.sql" FLATER "Intermediate Sizing")
  ("sql\\dml186.sql" FLATER "Intermediate Sizing")
  ("sql\\flg009.sql" HU "Optional/Informational Tests")
  ("sql\\flg006.sql" MCGINN "Optional/Informational Tests")
  ("sql\\dml068.sql" HU "Optional/Informational Tests")
  ("sql\\dml084.sql" SCHANZLE "Optional/Informational Tests")
;  ("sql\\cdr025.sql" SUN "Optional/Informational Tests")
  ("sql\\mpquic.txt" SULLIVAN1 "Manual Procedures")
  ("schema\\xdrop1.sql" XOPEN1 "dropping tables for xschema1.sql")
  ("schema\\xdrop2.sql" XOPEN2 "dropping tables for xschema2.sql")
))



;* checkfile
;*
;* This function opens a file and searches for SQL statements,
;* when found, these are executed. If there was no errors, either (sql "...") or (checkequal ...)
;* statements are created depending on the result of the execution (nil -> "(sql ...)").
;* On error, the statement is displayed together with the error message
;* Comments (rows starting with "--") are displayed together with a row number.
;*
;* The function adds together all rows that are not comments until a row ending with
;* semicolon is found. This is then executed as SQL. White spaces are packed into a single space.
;************************************************************************
(defun checkfile (filename)
 (let ((statement "") (ch 0) (file nil) (rownum 1) (row "") (lastchar 10)
       (comment 0) (result nil) (err nil) (donespace 'T))
   (setq file (openstream filename "r"))
   (dotimes (x (1- (file-length filename)))
     (setq ch (read-charcode file))

     (if (= comment 1)
       (if (= ch 45)
         (setq comment 2)
         (setq comment 0)
       )
     )
     (if (and (= ch 45) (= lastchar 10))
       (setq comment 1)
     )
;(princ (concat ch ", "))

     ;-- Radbrytning! 
     (if (= ch 10)
      (progn
       (if (and (not donespace) (/= lastchar 59))
         (setq row (concat row " "))
       )
       (if (< comment 2)
         (setq statement (concat statement row))
       )
       (if (= comment 2)
        (progn
         (princ (concat ";" rownum ": " row))
         (terpri)
       ))
       
       (if (and (= lastchar 59) (< comment 2))  ;-- Om förra raden slutade med ";" så exekvera!
        (progn
         (setq err (catch-error (setq result (sql statement)) ))
         (if (error? err)
          (progn
           (princ (concat ";" rownum ":  ERROR: "))
           (princ (errcond-msg err))
           (princ ": ")
           (princ (errcond-arg err))
           (terpri)
           (princ (concat ";   " statement))
           (terpri)
           (princ ";")
          )
          (progn
           (if result
            (progn
             (princ "(checkequal ")
             (prin1 filename)
             (terpri)
             (princ "  (")
           ))
           (princ "(sql \"")
           (princ statement)
           (princ "\")")
           (if result
            (progn
             (princ " '")
             (prin1 result)
             (princ ")")
             (terpri)
             (princ ")")
           ))
         ))
         (terpri)
;         (terpri)
;         (princ (concat "! " statement "! ")) (terpri)
         (setq statement "")
         (setq donespace 'T)
       ))
       
       (setq rownum (1+ rownum))
       (setq row "")
       (setq comment 0)
      )
       (if (and (numberp ch) (or (/= ch 32) (not donespace)))
         (setq row (concat row (int-char ch)))
       )
     )
     
     (setq donespace nil)
     (if (member ch '(32 10))
       (setq donespace 'T)
     )
     
     ;-- Updatera lastchar
     (if (not (member ch '(32)))
       (setq lastchar ch)
     )
   )
   (closestream file)
 )
)


;* check
;*
;* This function is an extended variant of (checkfile (nth num SQL_Test_suite_files),
;* which adds the correct path to the filename and prints out comments about the file
;* suitable for regression test file creation.
;* The function also makes sure to switch to the correct SCHEMA before calling (checkfile).
;************************************************************************
(defun check (num &optional filelist)
  (if (not filelist)
    (setq filelist SQL_Test_suite_files)
  )
  (princ "/////////////////////////////////////////////////////////////////////////////") (terpri)
  (princ "/////////////// CHECK: ")
  (prin1 (nth num filelist))
  (princ " ///////////////")
  (terpri)
  (princ "/////////////////////////////////////////////////////////////////////////////") (terpri)
  (princ ";** ")
  (princ (car (nth num filelist))) (terpri)
  (princ ";** ") (terpri)
  (princ ";** ") (princ (nth 2 (nth num filelist))) (terpri)
  (princ (concat "(sql \"SCHEMA " (nth 1 (nth num filelist)) ";\")")) (terpri)
  (let ((res nil) (str ""))
;    (dolist (x filelist)
    (let ((x (nth num filelist)))
      (eval (sql-parse (concat "SCHEMA " (nth 1 x)) ))
      (setq res (checkfile (concat "c:\\maja4141\\SQL Test suite\\" (car x)) ))
      (eval (sql-parse "SCHEMA DEFAULT"))
    )
  )
)



;* q
;*
;* Useful function when debugging SQL parsing.
;* Executes an SQL statement, just as (sql), but prints the result of each parsing step.
;************************************************************************
(defun q (sql)
  (let ((x (sql-parse sql)) (y nil) (debugval sql-debugging))
    (setq sql-debugging 'T)
    (princ "parsed: ") (terpri)
    (print x) 
    (setq y (eval x))
    (princ "evaluated: ")
    (print y)
    (print (eval y))
    (setq sql-debugging debugval)
  )
)