;;; ============================================================
;;; AMOS2
;;; 
;;; Author: (c) 2004 Markus Jägerskogh, UDBL
;;; $RCSfile: sql-testcreate.lsp,v $
;;; $Revision: 1.2 $ $Date: 2012/02/04 17:14:19 $
;;; $State: Exp $ $Locker:  $
;;;
;;; Description: Regression test for SQLFront - creates tables 
;;; =============================================================

;** schema\schema1.smi
;**
;** This file defines the base tables used in most of the tests.
(princ "[Executing SQL Test suite\\schema\\schema1.smi ...")
(sql "SCHEMA HU;")
(sql "CREATE TABLE BASE_TESTREPORT (TESTNO CHAR(4), RESULT CHAR(4), 
      TESTTYPE CHAR(3));")
(sql "CREATE TABLE HU.ECCO (C1 CHAR(2));")
(sql "CREATE TABLE STAFF (EMPNUM CHAR(3) NOT NULL UNIQUE, 
      EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15));")
(sql "CREATE TABLE PROJ (PNUM CHAR(3) NOT NULL UNIQUE, PNAME CHAR(20), 
      PTYPE CHAR(6), BUDGET DECIMAL(9), CITY CHAR(15));")
(sql "CREATE TABLE WORKS (EMPNUM CHAR(3) NOT NULL, PNUM CHAR(3) NOT NULL, 
      HOURS DECIMAL(5), UNIQUE(EMPNUM,PNUM));")
(sql "CREATE TABLE FIPS1 (FIPS_TEST CHAR(20));")
(sql "CREATE TABLE STAFF1 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), 
      GRADE DECIMAL(4), CITY CHAR(15));")
(sql "CREATE TABLE PROJ1 (PNUM CHAR(3) NOT NULL UNIQUE, PNAME CHAR(20), 
      PTYPE CHAR(6), BUDGET DECIMAL(9), CITY CHAR(15));")
(sql "CREATE TABLE WORKS1(EMPNUM CHAR(3) NOT NULL, PNUM CHAR(3) NOT NULL, 
      HOURS DECIMAL(5), UNIQUE(EMPNUM, PNUM));")
(sql "CREATE TABLE STAFF3 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), 
      GRADE DECIMAL(4), CITY CHAR(15));")
;** Create VIEWS ... **
(osql "
create function HUsql:STAFFV1 (Charstring EMPNUM, Charstring EMPNAME, Real GRADE, Charstring CITY)->Boolean as
  select true
  where HUsql:STAFF(EMPNUM, EMPNAME, GRADE, CITY) and GRADE >= 12.0;

create function HUsql:STAFFV2 (Charstring EMPNUM, Charstring EMPNAME, Real GRADE, Charstring CITY)->Boolean as
  select true
  where HUsql:STAFF(EMPNUM, EMPNAME, GRADE, CITY) and GRADE >= 12.0;

create function HUsql:STAFFV2_VIEW (Charstring EMPNUM, Charstring EMPNAME, Real GRADE, Charstring CITY)->Boolean as
  select true
  where HUsql:STAFFV2 (EMPNUM, EMPNAME, GRADE, CITY) and CITY = 'Vienna';

create function HUsql:DOMAIN_VIEW (Charstring EMPNUM, Charstring PNUM, Real HOURS)->Boolean as
  select true
  where HUsql:WORKS(EMPNUM, PNUM, HOURS) and
      ((EMPNUM='E1' and HOURS=80.0) or
       (EMPNUM='E2'and HOURS=40.0) or
       (EMPNUM='E4' and HOURS=20.0));

create function HUsql:STAFF2 (Charstring EMPNUM, Charstring EMPNAME, Real GRADE, Charstring CITY)->Boolean as
  select true
  where HUsql:STAFF(EMPNUM, EMPNAME, GRADE, CITY);

create function HUsql:STAFF_WORKS_DESIGN (Charstring NAME, Real COST, Charstring PROJECT)->Boolean as
  select true
  from Charstring EMPNUM, Real GRADE, Charstring sCITY, Charstring PNUM, Charstring PNAME,
       Charstring PTYPE, Real BUDGET, Charstring pCITY, Real HOURS
  where HUsql:STAFF(EMPNUM, NAME, GRADE, sCITY) and
        HUsql:PROJ(PNUM, PNAME, PTYPE, BUDGET, pCITY) and
        HUsql:WORKS(EMPNUM, PNUM, HOURS) and COST=HOURS*2*GRADE and PTYPE='Design' and PROJECT=PNAME;

create function HUsql:SUBSP (Charstring EMPNUM, Charstring PNUM, Real HOURS)->Boolean as
  select true
  where HUsql:WORKS(EMPNUM, PNUM, HOURS) and EMPNUM='E3';

create function HUsql:TEMP_SS (Charstring EMPNUM, Real GRADE, Charstring CITY)->Boolean as
  select true
  from Charstring EMPNAME
  where HUsql:STAFF(EMPNUM, EMPNAME, GRADE, CITY) and GRADE >= 12.0;

create function HUsql:V_WORKS1 (Charstring EMPNUM, Charstring PNUM, Real HOURS)->Boolean as
  select true
  where HUsql:WORKS(EMPNUM, PNUM, HOURS) and HOURS > 15.0;

create function HUsql:V_WORKS2 (Charstring EMPNUM, Charstring PNUM, Real HOURS)->Boolean as
  select true
  where HUsql:V_WORKS1(EMPNUM, PNUM, HOURS) and (EMPNUM='E1' or EMPNUM='E6');

create function HUsql:V_WORKS3 (Charstring EMPNUM, Charstring PNUM, Real HOURS)->Boolean as
  select true
  where HUsql:V_WORKS2(EMPNUM, PNUM, HOURS) and (PNUM='P2' or PNUM='P7');

create function HUsql:UPDATE_VIEW1 (Charstring CITY)->Boolean as
  select true
  from Charstring PNUM, Charstring PNAME, Charstring PTYPE, Real BUDGET
  where HUsql:PROJ(PNUM, PNAME, PTYPE, BUDGET, CITY);

create function HUsql:UPDATE_VIEW2 (Real HOURS, Charstring EMPNUM, Charstring PNUM)->Boolean as
  select true
  where HUsql:WORKS(EMPNUM, PNUM, HOURS) and
       (HOURS=10.0 or HOURS=20.0 or HOURS=40.0);

create function HUsql:UPDATE_VIEW3 (Charstring EMPNUM, Charstring PNUM, Real HOURS)->Boolean as
  select true
  where HUsql:WORKS(EMPNUM, PNUM, HOURS) and
       (PNUM >= 'P2' and PNUM <= 'P4') and (EMPNUM < 'E2' and EMPNUM > 'E3');

create function HUsql:UPDATE_VIEW4 (Charstring PNUM, Charstring EMPNUM)->Boolean as
  select true
  from Real HOURS
  where HUsql:WORKS(EMPNUM, PNUM, HOURS) and like(PNUM, '?2*');

/* Skipped: UPDATE_VIEW5 - NULL */

create function HUsql:UPDATE_VIEW6 (Charstring EMPNAME, Charstring CITY, Real GRADE)->Boolean as
  select true
  from Charstring EMPNUM
  where HUsql:STAFF(EMPNUM, EMPNAME, GRADE, CITY) and
        ((EMPNAME >= 'Betty' and EMPNUM < 'E35') or
         (CITY <= 'Deale' and GRADE > 12.0) or
         (GRADE = 13.0 and CITY != 'Akron'));

create function HUsql:UPDATE_VIEW7 (Charstring EMPNAME, Charstring CITY, Real GRADE)->Boolean as
  select true
  from Charstring EMPNUM
  where HUsql:STAFFV2(EMPNUM, EMPNAME, GRADE, CITY) and
        ((EMPNAME >= 'Betty' and EMPNUM < 'E35') or
         (CITY <= 'Deale' and GRADE > 12.0) or
         (GRADE = 13.0 and CITY != 'Akron'));

create function HUsql:UPDATE_VIEW8 (Charstring EMPNUM, Charstring EMPNAME)->Boolean as
  select true
  from Charstring CITY, Real GRADE
  where HUsql:STAFF(EMPNUM, EMPNAME, GRADE, CITY) and GRADE=12.0;

/* create function HUsql:UPDATE_VIEW9 (Charstring EMPNAME, Charstring CITY, Real GRADE)->Boolean as
  select true
  from Charstring EMPNUM
  where HUsql:STAFF(EMPNUM, EMPNAME, GRADE, CITY) AND 
        ((EMPNAME < 'Betty' AND EMPNUM >= 'E35') OR 
         (CITY > 'Deale' AND GRADE <= 9.0) OR
         (GRADE = 13.0 AND CITY <> 'Akron')); */

create function HUsql:VSTAFF3 (Charstring EMPNUM, Charstring EMPNAME, Real GRADE, Charstring CITY)->Boolean as
  select true
  where HUsql:STAFF3(EMPNUM, EMPNAME, GRADE, CITY);")

(sql "CREATE TABLE STAFF4 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15));")
(sql "CREATE TABLE LONGINT (LONG_INT DECIMAL(15));")
(sql "CREATE TABLE TEMP_S (EMPNUM CHAR(3), GRADE DECIMAL(4), CITY CHAR(15));")
(sql "CREATE TABLE TMP (T1 CHAR (10), T2 DECIMAL(2), T3 CHAR (10));")
(sql "CREATE TABLE AA (CHARTEST CHAR(20));")
(sql "CREATE TABLE BB (CHARTEST CHAR);")
(sql "CREATE TABLE CC (CHARTEST CHARACTER(20));")
(sql "CREATE TABLE DD (CHARTEST CHARACTER);")
(sql "CREATE TABLE EE (INTTEST INTEGER);")
(sql "CREATE TABLE FF (INTTEST INT);")
(sql "CREATE TABLE GG (REALTEST REAL);")
(sql "CREATE TABLE HH (SMALLTEST SMALLINT);")
(sql "CREATE TABLE II (DOUBLETEST DOUBLE PRECISION);")
(sql "CREATE TABLE JJ (FLOATTEST FLOAT);")
(sql "CREATE TABLE KK (FLOATTEST FLOAT(32));")
(sql "CREATE TABLE LL (NUMTEST NUMERIC(13,6));")
(sql "CREATE TABLE MM (NUMTEST NUMERIC);")
(sql "CREATE TABLE MM2 (NUMTEST NUMERIC(10));")
(sql "CREATE TABLE NN (NUMTEST NUMERIC(9));")
(sql "CREATE TABLE OO (NUMTEST NUMERIC(9));")
(sql "CREATE TABLE PP (NUMTEST DECIMAL(13,6));")
(sql "CREATE TABLE QQ (NUMTEST DECIMAL);")
(sql "CREATE TABLE RR (NUMTEST DECIMAL(8));")
(sql "CREATE TABLE SS (NUMTEST DEC(13,6));")
(sql "CREATE TABLE P1 (NUMTEST NUMERIC(1));")
(sql "CREATE TABLE P7 (NUMTEST NUMERIC(7));")
(sql "CREATE TABLE P12 (NUMTEST NUMERIC(12));")
(sql "CREATE TABLE P15 (NUMTEST NUMERIC(15));")
(sql "CREATE TABLE VTABLE (COL1 INTEGER, COL2 INTEGER, COL3 INTEGER, COL4 INTEGER, COL5 DECIMAL(7,2));")
(sql "CREATE TABLE UPUNIQ (NUMKEY DECIMAL(3) NOT NULL UNIQUE, COL2 CHAR(2));")
(sql "CREATE TABLE TEXT80 (TEXXT CHAR(80));")
(sql "CREATE TABLE TEXT132 (TEXXT CHAR(132));")
(sql "CREATE TABLE TEXT240 (TEXXT CHAR(240));")
(sql "CREATE TABLE TEXT256 (TEXXT CHAR(256));")
(sql "CREATE TABLE TEXT512 (TEXXT CHAR(512));")
(sql "CREATE TABLE TEXT1024 (TEXXT CHAR(1024));")
;** The following tables are used to test the limitations (12-14-88)
(sql "CREATE TABLE T240(STR240 CHAR(240));")
(sql "CREATE TABLE DEC15(COL1 DECIMAL(15,7));")
(sql "CREATE TABLE FLO15(COL1 FLOAT(15));")
(sql "CREATE TABLE INT10(COL1 INTEGER, COL2 SMALLINT);")
(sql (concat "CREATE TABLE T100(C1 CHAR(2),C2 CHAR(2),C3 CHAR(2),C4 CHAR(2), C5 CHAR(2),C6 CHAR(2),C7 CHAR(2),"
      "C8 CHAR(2), C9 CHAR(2),C10 CHAR(2),C11 CHAR(2),C12 CHAR(2), C13 CHAR(2),C14 CHAR(2),C15 CHAR(2),"
      "C16 CHAR(2), C17 CHAR(2),C18 CHAR(2),C19 CHAR(2),C20 CHAR(2), C21 CHAR(2),C22 CHAR(2),C23 CHAR(2),"
      "C24 CHAR(2), C25 CHAR(2),C26 CHAR(2),C27 CHAR(2),C28 CHAR(2), C29 CHAR(2),C30 CHAR(2),C31 CHAR(2),"
      "C32 CHAR(2), C33 CHAR(2),C34 CHAR(2),C35 CHAR(2),C36 CHAR(2), C37 CHAR(2),C38 CHAR(2),C39 CHAR(2),"
      "C40 CHAR(2), C41 CHAR(2),C42 CHAR(2),C43 CHAR(2),C44 CHAR(2), C45 CHAR(2),C46 CHAR(2),C47 CHAR(2),"
      "C48 CHAR(2), C49 CHAR(2),C50 CHAR(2),C51 CHAR(2),C52 CHAR(2), C53 CHAR(2),C54 CHAR(2),C55 CHAR(2),"
      "C56 CHAR(2), C57 CHAR(2),C58 CHAR(2),C59 CHAR(2),C60 CHAR(2), C61 CHAR(2),C62 CHAR(2),C63 CHAR(2),"
      "C64 CHAR(2), C65 CHAR(2),C66 CHAR(2),C67 CHAR(2),C68 CHAR(2), C69 CHAR(2),C70 CHAR(2),C71 CHAR(2),"
      "C72 CHAR(2), C73 CHAR(2),C74 CHAR(2),C75 CHAR(2),C76 CHAR(2), C77 CHAR(2),C78 CHAR(2),C79 CHAR(2),"
      "C80 CHAR(2), C81 CHAR(2),C82 CHAR(2),C83 CHAR(2),C84 CHAR(2), C85 CHAR(2),C86 CHAR(2),C87 CHAR(2),"
      "C88 CHAR(2), C89 CHAR(2),C90 CHAR(2),C91 CHAR(2),C92 CHAR(2), C93 CHAR(2),C94 CHAR(2),C95 CHAR(2),"
      "C96 CHAR(2), C97 CHAR(2),C98 CHAR(2),C99 CHAR(2),C100 CHAR(2));"))
(sql "CREATE TABLE T2000(STR110 CHAR(110),STR120 CHAR(120), STR130 CHAR(130),STR140 CHAR(140), STR150 CHAR(150),STR160 CHAR(160), STR170 CHAR(170),STR180 CHAR(180), STR190 CHAR(190),STR200 CHAR(200), STR210 CHAR(210),STR216 CHAR(216));")
(sql "CREATE TABLE T8(COL1 CHAR(2) NOT NULL,COL2 CHAR(4) NOT NULL, COL3 CHAR(6) NOT NULL,COL4 CHAR(8) NOT NULL, COL5 CHAR(10) NOT NULL,COL6 CHAR(12) NOT NULL, COL7 CHAR(14),COL8 CHAR(16), UNIQUE(COL1,COL2,COL3,COL4,COL5,COL6));")
(sql "CREATE TABLE T118(STR118 CHAR(118) NOT NULL UNIQUE);")
(sql "CREATE TABLE T4(STR110 CHAR(110) NOT NULL, NUM6 NUMERIC(6) NOT NULL, COL3 CHAR(10),COL4 CHAR(20), UNIQUE(STR110,NUM6));")
(sql "CREATE TABLE T12(COL1 CHAR(1), COL2 CHAR(2), COL3 CHAR(4), COL4 CHAR(6), COL5 CHAR(8), COL6 CHAR(10), COL7 CHAR(20), COL8 CHAR(30), COL9 CHAR(40), COL10 CHAR(50), COL11 INTEGER, COL12 INTEGER);")
(sql "CREATE TABLE NEXTKEY (KEYNUM INTEGER, AUTHOR CHAR(1), DOLLARS INTEGER);")
(sql "CREATE TABLE SV (NUMTEST NUMERIC(8,3));")
(sql "CREATE TABLE JJ_20 (FLOATTEST FLOAT(20));")
(sql "CREATE TABLE PP_15 (NUMTEST DECIMAL(15,15));")
(sql "CREATE TABLE PP_7 (NUMTEST DECIMAL(15,7));")
(sql "CREATE TABLE P15_15 (NUMTEST NUMERIC(15,15));")
(sql "CREATE TABLE P15_7 (NUMTEST NUMERIC(15,7));")
(sql "CREATE TABLE TEMP_OBSERV (YEAR_OBSERV NUMERIC(4), CITY CHAR(10), MAX_TEMP NUMERIC(5,2), MIN_TEMP NUMERIC(5,2));")
(sql "CREATE TABLE TOKENS (PROG_NO INT, TOKEN_NO INT);")
(sql "CREATE TABLE WHICH_SCHEMA1 (C1 CHAR (1));")
(princ "OK]")
(terpri)

;** schema\schema2.smi
;**
;**
(princ "[Executing SQL Test suite\\schema\\schema2.smi ...") 
(sql "SCHEMA CUGINI;")
(sql "CREATE TABLE VTABLE (COL1 INTEGER, COL2 INTEGER, COL3 INTEGER, COL4 INTEGER, COL5 DECIMAL(7,2));")
(sql "CREATE TABLE AA (CHARTEST CHAR(20));")
(sql "CREATE TABLE BB (CHARTEST CHAR);")
(sql "CREATE TABLE CC (CHARTEST CHARACTER(20));")
(sql "CREATE TABLE DD (CHARTEST CHARACTER);")
(sql "CREATE TABLE EE (INTTEST INTEGER);")
(sql "CREATE TABLE FF (INTTEST INT);")
(sql "CREATE TABLE GG (C1 INT);")
(sql "CREATE TABLE HH (SMALLTEST SMALLINT);")
(sql "CREATE TABLE II (C1 INT);")
(sql "CREATE TABLE JJ (C1 INT);")
(sql "CREATE TABLE SRCH1 (C1 INT);")
(sql "CREATE TABLE BADG1 (C1 INT);")
(sql "CREATE TABLE BADG2 (C1 INT);")
(princ "OK]")
(terpri)


;** schema\schema3.smi
;**
;** 
(princ "[Executing SQL Test suite\\schema\\schema3.smi ...")
(sql "SCHEMA MCGINN;")
(sql "CREATE TABLE TABLEFGHIJKLMNOPQ19 (COL2 INTEGER);")
(sql "CREATE TABLE SHORTTABLE (COLUMN123456789IS19 INTEGER);")
(sql "CREATE TABLE BASETABLE1 (COL1 INTEGER);")
(princ "OK]")
(terpri)


;** schema\schema4.smi
;**
;** 
(princ "[Executing SQL Test suite\\schema\\schema4.smi ...")
(sql "SCHEMA SULLIVAN1;")
(sql "CREATE TABLE AUTH_TABLE (FIRST1 INTEGER, SECOND2 CHAR);")
(sql "CREATE TABLE MP1_MM2 (NUMTEST NUMERIC(10));")
(sql "CREATE TABLE MP1_NN (NUMTEST NUMERIC(9));")
(sql "CREATE TABLE MP1_NEXTKEY (KEYNUM INTEGER, AUTHOR CHAR(1), DOLLARS INTEGER);")
(sql "CREATE TABLE MP2_MM2 (NUMTEST NUMERIC(10));")
(sql "CREATE TABLE MP2_NN (NUMTEST NUMERIC(9));") 
(sql "CREATE TABLE MP2_NEXTKEY (KEYNUM INTEGER, AUTHOR CHAR(1), DOLLARS INTEGER);")
(sql "CREATE TABLE MP3_MM2 (NUMTEST NUMERIC(10));")
(sql "CREATE TABLE MP3_NN (NUMTEST NUMERIC(9));")
(sql "CREATE TABLE MP3_NEXTKEY (KEYNUM INTEGER, AUTHOR CHAR(1), DOLLARS INTEGER);")
(sql "CREATE TABLE MP4_MM2 (NUMTEST NUMERIC(10));")
(sql "CREATE TABLE MP4_NN (NUMTEST NUMERIC(9));") 
(sql "CREATE TABLE MP4_NEXTKEY (KEYNUM INTEGER, AUTHOR CHAR(1), DOLLARS INTEGER);")
(sql "CREATE TABLE MP5_AA (ANUM NUMERIC(4));")
(sql "CREATE TABLE MP5_AA_INDEX (ANUM NUMERIC(4) NOT NULL UNIQUE);")
(sql "CREATE TABLE MP5_TT (TESTTYPE CHAR(3), KOUNT DECIMAL(4));")
(sql "CREATE TABLE TTT (ANUM NUMERIC(4) NOT NULL UNIQUE, AUTHOR CHAR(1));")
(sql "CREATE TABLE TT (DOLLARS NUMERIC(4), ANUM NUMERIC(4));")
(sql "CREATE TABLE AA (ANUM NUMERIC(4));")
(sql "CREATE TABLE BB (BNUM NUMERIC(4));")
(sql "CREATE TABLE MP6_MM2 (NUMTEST NUMERIC(10));")
(sql "CREATE TABLE MP6_NN (NUMTEST NUMERIC(9));")
(sql "CREATE TABLE MP6_NEXTKEY (KEYNUM INTEGER, AUTHOR CHAR(1), DOLLARS INTEGER);")
(sql "CREATE TABLE MP6_AA (ANUM NUMERIC(4));")
(sql "CREATE TABLE MP6_BB (BNUM NUMERIC(4));")
(sql "CREATE TABLE MP7_NN (NUMTEST NUMERIC(9));")
(sql "CREATE TABLE MP7_NEXTKEY (KEYNUM INTEGER, AUTHOR CHAR(1), DOLLARS INTEGER);")
(sql "CREATE TABLE MP7_AA (ANUM NUMERIC(4));")
(sql "CREATE TABLE MP7_BB (BNUM NUMERIC(4));")
(sql "CREATE TABLE MP8_NEXTKEY (KEYNUM INTEGER, AUTHOR CHAR(1), DOLLARS INTEGER);")
(sql "CREATE TABLE MP8_AA (ANUM NUMERIC(4) NOT NULL, AUTHOR CHAR(1), UNIQUE (ANUM));")
(sql "CREATE TABLE MP8_BB (NUMTEST NUMERIC(9));")
(sql "CREATE TABLE MP9_NN (NUMTEST NUMERIC(9));")
(sql "CREATE TABLE MP9_NEXTKEY (KEYNUM INTEGER, AUTHOR CHAR(1), DOLLARS INTEGER);")
(sql "CREATE TABLE MP9_AA (ANUM NUMERIC(4));")
(sql "CREATE TABLE MP9_BB (BNUM NUMERIC(4));")
(sql "CREATE TABLE USG102 (C1 INT, C_1 INT);")
(sql "CREATE TABLE USG103 (C1 INT, C_1 INT);")
(princ "OK]")
(terpri)


;** schema\schema5.smi
;**
;** 
(princ "[Executing SQL Test suite\\schema\\schema5.smi ...")
(sql "SCHEMA FLATER;")
(sql "CREATE TABLE CONCATBUF (ZZ CHAR(240));")
(sql "CREATE TABLE USIG (C1 INT, C_1 INT);")
(sql "CREATE TABLE U_SIG (C1 INT, C_1 INT);")
;** (sql "CREATE TABLE TINY (C1 CHAR(33000));")  -- Ska inte gå igenom enl. NIST... Ska ge "overflow data exception"

;-- For generation of "with check option violation" SQLSTATE.
(sql "CREATE TABLE BASE_WCOV (C1 INT);")

(sql "CREATE TABLE BASE_VS1 (C1 INT, C2 INT);")
(princ "OK]")
(terpri)


;** schema\schema6.smi
;**
;** This SDL file requires Feature 17 of Transitional SQL (multiple schemas per user).
(princ "[Executing SQL Test suite\\schema\\schema6.smi ...")
(sql "SCHEMA FLATER;")
(sql "CREATE TABLE SHIRLEY_HURWITZ.MEETINGS (TIMESLOT INT, AGENDA CHAR(4));")
(sql "CREATE TABLE LEN_GALLAGHER.TRAVEL ( TRAVEL_ORDER CHAR(40) NOT NULL UNIQUE, DESTINATION CHAR(40), REASON_CODE NUMERIC(9));")
(princ "OK]")
(terpri)


;** schema\schema7.smi
;**
;** used in program SDL026
(princ "[Executing SQL Test suite\\schema\\schema7.smi ...")
(sql "SCHEMA CANWEPARSELENGTH18;")
(sql "CREATE TABLE CHARACTER18TABLE18 (CHARS18NAME18CHARS CHAR(4));")
(princ "OK]")
(terpri)


;** schema\schema8.smi
;**
;** This file defines the base tables used in most of the CDR tests.
(princ "[Executing SQL Test suite\\schema\\schema8.smi ...")
(sql "SCHEMA SUN;")
(sql "CREATE TABLE SUN.ECCO (C1 CHAR(2));")
(sql "CREATE TABLE STAFF (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15));")
(sql "CREATE TABLE PROJ (PNUM CHAR(3) NOT NULL, PNAME CHAR(20), PTYPE CHAR(6), BUDGET DECIMAL(9), CITY CHAR(15));")
(sql "CREATE TABLE WORKS (EMPNUM CHAR(3) NOT NULL, PNUM CHAR(3) NOT NULL, HOURS DECIMAL(5));")
(sql "CREATE TABLE PROJ3 (PNUM CHAR(3) NOT NULL, PNAME CHAR(20), PTYPE CHAR(6), BUDGET DECIMAL(9), CITY CHAR(15), UNIQUE (PNUM));")
(sql "CREATE TABLE WORKS3 (EMPNUM CHAR(3) NOT NULL, PNUM CHAR(3) NOT NULL, HOURS DECIMAL(5), FOREIGN KEY (EMPNUM) REFERENCES STAFF3(EMPNUM), FOREIGN KEY (PNUM) REFERENCES PROJ3(PNUM));")
(sql "CREATE TABLE STAFF4 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20) DEFAULT NULL, GRADE DECIMAL(4) DEFAULT 0, CITY CHAR(15) DEFAULT ' ');")
(sql "CREATE TABLE STAFF14 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20) DEFAULT USER, GRADE DECIMAL(4), CITY CHAR(15));")
;(sql "CREATE TABLE STAFF5 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), PRIMARY KEY (EMPNUM), CHECK (GRADE > 0 AND GRADE < 20));")
(sql "CREATE TABLE STAFF6 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4) CHECK (GRADE > 0 AND GRADE < 20), CITY CHAR(15));")
;(sql "CREATE TABLE STAFF7 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), PRIMARY KEY (EMPNUM), CHECK (GRADE BETWEEN 1 AND 20));")
;(sql "CREATE TABLE STAFF8 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), PRIMARY KEY (EMPNUM), CHECK (EMPNAME IS NOT NULL));")
;(sql "CREATE TABLE STAFF9 (EMPNUM CHAR(3) NOT NULL PRIMARY KEY, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), CHECK (EMPNAME NOT LIKE 'T%'));")
;(sql "CREATE TABLE STAFF10 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), PRIMARY KEY (EMPNUM), CHECK (GRADE NOT IN (5,22)));")
;(sql "CREATE TABLE STAFF11 (EMPNUM CHAR(3) NOT NULL PRIMARY KEY, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), CHECK (GRADE NOT IN (5,22) AND EMPNAME NOT LIKE 'T%'));")
;(sql "CREATE TABLE STAFF12 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), PRIMARY KEY (EMPNUM), CHECK (NOT GRADE IN (5,22) AND NOT EMPNAME LIKE 'T%'));")
;(sql "CREATE TABLE STAFF13 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), PRIMARY KEY (EMPNUM), CHECK (NOT EMPNAME IS NULL));")
(sql "CREATE TABLE STAFF15 (EMPNUM CHAR(3), EMPNAME CHAR(20) NOT NULL, GRADE DECIMAL(4), CITY CHAR(15));")
;(sql "CREATE TABLE STAFF16 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20) DEFAULT NULL, GRADE DECIMAL(4) NOT NULL CHECK (GRADE IN (100,150,200)), CITY CHAR(15), PRIMARY KEY (GRADE,EMPNUM));")
(sql "CREATE TABLE SIZ1_P (S1 CHAR(3) NOT NULL, S2 CHAR(3) NOT NULL, S3 DECIMAL(4) NOT NULL, S4 CHAR(3) NOT NULL, S5 DECIMAL(4) NOT NULL, S6 CHAR(3) NOT NULL, R1 CHAR(3), R2 CHAR(3), R3 DECIMAL(4), UNIQUE (S1,S2,S3,S4,S5,S6));")
(sql "CREATE TABLE SIZ1_F (F1 CHAR(3) NOT NULL, F2 CHAR(3), F3 DECIMAL(4), F4 CHAR(3), F5 DECIMAL(4), F6 CHAR(3), R1 CHAR(3), R2 DECIMAL(5), R3 DECIMAL(4), FOREIGN KEY (F1,F2,F3,F4,F5,F6) REFERENCES SIZ1_P(S1,S2,S3,S4,S5,S6));")
(sql (concat "CREATE TABLE SIZ2_P (P1 CHAR(3) NOT NULL, P2 CHAR(3) NOT NULL, P3 DECIMAL(4) NOT NULL, "
      "P4 CHAR(3) NOT NULL, P5 DECIMAL(4) NOT NULL, P6 CHAR(3) NOT NULL, P7 CHAR(3) NOT NULL, P8 DECIMAL(4) NOT NULL, "
      "P9 DECIMAL(4) NOT NULL, P10 DECIMAL(4) NOT NULL, P11 CHAR(4), UNIQUE (P1), UNIQUE (P2), UNIQUE (P3), "
      "UNIQUE (P4), UNIQUE (P5), UNIQUE (P6), UNIQUE (P7), UNIQUE (P8), UNIQUE (P9), UNIQUE (P10));"))
(sql "CREATE TABLE SIZ2_F1 (F1 CHAR(3) NOT NULL, F2 CHAR(8), FOREIGN KEY (F1) REFERENCES SIZ2_P(P1));")
(sql "CREATE TABLE SIZ2_F2 (F1 CHAR(3) NOT NULL, F2 CHAR(8), FOREIGN KEY (F1) REFERENCES SIZ2_P(P2));")
(sql "CREATE TABLE SIZ2_F3 (F1 DECIMAL(4) NOT NULL, F2 CHAR(8), FOREIGN KEY (F1) REFERENCES SIZ2_P(P3));")
(sql "CREATE TABLE SIZ2_F4 (F1 CHAR(3) NOT NULL, F2 CHAR(8), FOREIGN KEY (F1) REFERENCES SIZ2_P(P4));")(sql "CREATE TABLE SIZ2_F5 (F1 DECIMAL(4) NOT NULL, F2 CHAR(8), FOREIGN KEY (F1) REFERENCES SIZ2_P(P5));")
(sql "CREATE TABLE SIZ2_F6 (F1 CHAR(3) NOT NULL, F2 CHAR(8), FOREIGN KEY (F1) REFERENCES SIZ2_P(P6));")
(sql "CREATE TABLE SIZ2_F7 (F1 CHAR(3) NOT NULL, F2 CHAR(8), FOREIGN KEY (F1) REFERENCES SIZ2_P(P7));")
(sql "CREATE TABLE SIZ2_F8 (F1 DECIMAL(4) NOT NULL, F2 CHAR(8), FOREIGN KEY (F1) REFERENCES SIZ2_P(P8));")
(sql "CREATE TABLE SIZ2_F9 (F1 DECIMAL(4) NOT NULL, F2 CHAR(8), FOREIGN KEY (F1) REFERENCES SIZ2_P(P9));")
(sql "CREATE TABLE SIZ2_F10 (F1 DECIMAL(4) NOT NULL, F2 CHAR(8), FOREIGN KEY (F1) REFERENCES SIZ2_P(P10));")
(sql "CREATE TABLE SIZ3_P1 (F1 CHAR(3) NOT NULL, F2 CHAR(8), UNIQUE (F1));")
(sql "CREATE TABLE SIZ3_P2 (F1 CHAR(3) NOT NULL, F2 CHAR(8), UNIQUE (F1));")
(sql "CREATE TABLE SIZ3_P3 (F1 DECIMAL(4) NOT NULL, F2 CHAR(8), UNIQUE (F1));")
(sql "CREATE TABLE SIZ3_P4 (F1 CHAR(3) NOT NULL, F2 CHAR(8), UNIQUE (F1));")
(sql "CREATE TABLE SIZ3_P5 (F1 DECIMAL(4) NOT NULL, F2 CHAR(8), UNIQUE (F1));")
(sql "CREATE TABLE SIZ3_P6 (F1 CHAR(3) NOT NULL, F2 CHAR(8), UNIQUE (F1));")
(sql "CREATE TABLE SIZ3_P7 (F1 CHAR(3) NOT NULL, F2 CHAR(8), UNIQUE (F1));")
(sql "CREATE TABLE SIZ3_P8 (F1 DECIMAL(4) NOT NULL, F2 CHAR(8), UNIQUE (F1));")
(sql "CREATE TABLE SIZ3_P9 (F1 DECIMAL(4) NOT NULL, F2 CHAR(8), UNIQUE (F1));")
(sql "CREATE TABLE SIZ3_P10 (F1 DECIMAL(4) NOT NULL, F2 CHAR(8), UNIQUE (F1));")
(sql (concat "CREATE TABLE SIZ3_F (P1 CHAR(3) NOT NULL, P2 CHAR(3), P3 DECIMAL(4), P4 CHAR(3), P5 DECIMAL(4), "
      "P6 CHAR(3), P7 CHAR(3), P8 DECIMAL(4), P9 DECIMAL(4), P10 DECIMAL(4), P11 CHAR(4), "
      "FOREIGN KEY (P1) REFERENCES SIZ3_P1(F1), FOREIGN KEY (P2) REFERENCES SIZ3_P2(F1), "
      "FOREIGN KEY (P3) REFERENCES SIZ3_P3(F1), FOREIGN KEY (P4) REFERENCES SIZ3_P4(F1), "
      "FOREIGN KEY (P5) REFERENCES SIZ3_P5(F1), FOREIGN KEY (P6) REFERENCES SIZ3_P6(F1), "
      "FOREIGN KEY (P7) REFERENCES SIZ3_P7(F1), FOREIGN KEY (P8) REFERENCES SIZ3_P8(F1), "
      "FOREIGN KEY (P9) REFERENCES SIZ3_P9(F1), FOREIGN KEY (P10) REFERENCES SIZ3_P10(F1));"))
(sql "CREATE TABLE DEPT (DNO DECIMAL(4) NOT NULL, DNAME CHAR(20) NOT NULL, DEAN CHAR(30), PRIMARY KEY (DNO), UNIQUE (DNAME));")
(sql "CREATE TABLE EMP (ENO DECIMAL(4) NOT NULL, ENAME CHAR(20) NOT NULL, EDESC CHAR(30), DNO DECIMAL(4) NOT NULL, DNAME CHAR(20), BTH_DATE DECIMAL(6) NOT NULL, PRIMARY KEY (ENO), UNIQUE (ENAME,BTH_DATE), FOREIGN KEY (DNO) REFERENCES DEPT(DNO), FOREIGN KEY (DNAME) REFERENCES DEPT(DNAME));")
(sql "CREATE TABLE EXPERIENCE (EXP_NAME CHAR(20), BTH_DATE DECIMAL(6), WK_DATE DECIMAL(6), DESCR CHAR(40), FOREIGN KEY (EXP_NAME,BTH_DATE) REFERENCES EMP(ENAME,BTH_DATE));")
(sql "CREATE TABLE STAFF_M (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), PRI_WK CHAR(3), UNIQUE (EMPNUM));")
(sql "CREATE TABLE PROJ_M (PNUM CHAR(3) NOT NULL, PNAME CHAR(20), PTYPE CHAR(6), BUDGET DECIMAL(9), CITY CHAR(15), MGR CHAR(3), UNIQUE (PNUM), FOREIGN KEY (MGR) REFERENCES STAFF_M(EMPNUM));")
(sql "CREATE TABLE STAFF_C (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), MGR CHAR(3), UNIQUE (EMPNUM), FOREIGN KEY (MGR) REFERENCES STAFF_C(EMPNUM));")
(sql "CREATE TABLE STAFF_P (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), UNIQUE (EMPNUM));")
(sql "CREATE TABLE PROJ_P (PNUM CHAR(3) NOT NULL, PNAME CHAR(20), PTYPE CHAR(6), BUDGET DECIMAL(9), CITY CHAR(15), UNIQUE (PNUM));")
(sql "CREATE TABLE MID1 (P_KEY DECIMAL(4) NOT NULL UNIQUE, F_KEY DECIMAL(4) REFERENCES MID1(P_KEY));")
(sql "CREATE TABLE ACR_SCH_P(P1 DECIMAL(4) NOT NULL UNIQUE, P2 CHAR(4));")
(sql "CREATE TABLE CHAR_DEFAULT (SEX_CODE CHAR(1) DEFAULT 'F', NICKNAME CHAR(20) DEFAULT 'No nickname given', INSURANCE1 CHAR(5) DEFAULT 'basic');")
(sql "CREATE TABLE APPROX_DEF (X_COUNT REAL DEFAULT 1.78E12, Y_COUNT REAL DEFAULT -9.99E10, Z_COUNT REAL DEFAULT 3.45E-11, ZZ_COUNT REAL DEFAULT -7.6777E-7);")
   (sql "CREATE TABLE SIZE_TAB (COL1 CHAR(75) DEFAULT 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz0123456789012', COL2 INTEGER DEFAULT -999888777, COL3 DEC(15,6) DEFAULT 987654321.123456, COL4 REAL DEFAULT -1.048576E22);")
(sql "CREATE TABLE COMMODITY (C_NUM INTEGER NOT NULL, C_NAME CHAR(7) NOT NULL UNIQUE, PRIMARY KEY (C_NUM));")
(sql "CREATE TABLE CURRENCY_TABLE (CURRENCY CHAR(10) NOT NULL, DOLLAR_EQUIV NUMERIC(5, 2), PRIMARY KEY (CURRENCY));")
(sql "CREATE TABLE MEASURE_TABLE (MEASURE CHAR(8) NOT NULL, POUND_EQUIV NUMERIC(8,2), PRIMARY KEY (MEASURE));")
(sql "CREATE TABLE C_TRANSACTION (COMMOD_NO INTEGER, TOT_PRICE DECIMAL(12,2), CURRENCY CHAR(10), UNITS INTEGER, MEASURE CHAR(8), T_DATE INTEGER, FOREIGN KEY (COMMOD_NO) REFERENCES COMMODITY, FOREIGN KEY (CURRENCY) REFERENCES CURRENCY_TABLE, FOREIGN KEY (MEASURE) REFERENCES MEASURE_TABLE);")
(sql "CREATE TABLE T6118REF ( COL1 CHAR(20) NOT NULL, COL2 CHAR(20) NOT NULL, COL3 CHAR(20) NOT NULL, COL4 CHAR(20) NOT NULL, COL5 CHAR(23) NOT NULL, COL6 NUMERIC (4) NOT NULL, STR118 CHAR(118) NOT NULL UNIQUE, UNIQUE (COL1, COL2, COL4, COL3, COL5, COL6));")
(sql "CREATE TABLE T118(STR118 CHAR(118) NOT NULL UNIQUE, FOREIGN KEY (STR118) REFERENCES T6118REF (STR118));")
(sql "CREATE TABLE T6 (COL1 CHAR(20), COL2 CHAR(20), COL3 CHAR(20), COL4 CHAR(20), COL5 CHAR(23), COL6 NUMERIC (4), FOREIGN KEY (COL1, COL2, COL4, COL3, COL5, COL6) REFERENCES T6118REF (COL1, COL2, COL4, COL3, COL5, COL6));")
(princ "OK]")
(terpri)


;** schema\schema9.smi
;**
;** This file defines base tables used in the CDR tests.
(princ "[Executing SQL Test suite\\schema\\schema9.smi ...")
(sql "SCHEMA SULLIVAN;")
(sql "CREATE TABLE WORKS_P (EMPNUM CHAR(3) REFERENCES SUN.STAFF_P(EMPNUM), PNUM CHAR(3), HOURS DECIMAL(5), FOREIGN KEY (PNUM) REFERENCES SUN.PROJ_P(PNUM));")
(sql "CREATE TABLE TTT(P1 DECIMAL(4) NOT NULL UNIQUE, P2 CHAR(4));")
(princ "OK]")
(terpri)


;** schema\schema10.smi
;**
;** This file defines base tables used in the CDR tests.
(princ "[Executing SQL Test suite\\schema\\schem10.smi ...")
(sql "SCHEMA SCHANZLE;")
(sql "CREATE TABLE ACR_SCH_F(F1 DECIMAL(4), F2 CHAR(4), FOREIGN KEY (F1) REFERENCES SUN.ACR_SCH_P(P1));")
; -- Test GRANT REFERENCES without grant permission below -- expect error message!
; -- "WITH GRANT OPTION" purposefully omitted from SUN's GRANT on STAFF_P
; -- Do not change file SCHEMA8 to allow "WITH GRANT OPTION"
;(sql "CREATE TABLE TAB5(F15 CHAR(3), F5 CHAR(4), FOREIGN KEY (F15) REFERENCES SUN.STAFF_P(EMPNUM));")
; -- Test REFERENCES without reference permission below -- expect error message!
; -- GRANT SELECT by SULLIVAN does not imply GRANT REFERENCES.
; -- Do not change file SCHEMA9 to allow "GRANT REFERENCES" on TTT.
;(sql "CREATE TABLE TAB6(F16 DECIMAL(4), F6 CHAR(4), FOREIGN KEY (F16) REFERENCES SULLIVAN.TTT(P1));")
; -- Constraints: column vs. column
;(sql "CREATE TABLE RET_CATALOG ( VENDOR_ID INT, PRODUCT_ID INT, WHOLESALE NUMERIC (10,2), RETAIL NUMERIC (10,2), MARKUP NUMERIC (10,2), EXPORT_CODE CHAR(2), EXPORT_LICNSE_DATE CHAR(20), CHECK (EXPORT_LICNSE_DATE IS NULL OR ( EXPORT_CODE = 'F1' OR EXPORT_CODE = 'F2' OR EXPORT_CODE = 'F3' )), CHECK (EXPORT_CODE <> 'F2' OR WHOLESALE > 10000.00), CHECK (RETAIL >= WHOLESALE), CHECK (RETAIL = WHOLESALE + MARKUP));")
(sql "CREATE TABLE RASTER (C1 INT NOT NULL, FOREIGN KEY (C1) REFERENCES SUN.COMMODITY (C_NUM));")
; -- Test REFERENCES without reference permission below -- expect error message!
; -- GRANT REFERENCES (C_NUM) on COMMODITY by SUN does not imply
; -- GRANT REFERENCES (C_NAME).
; -- Do not change file SCHEMA8 to allow "GRANT REFERENCES" on column C_NAME.
;(sql "CREATE TABLE REFRESH (C1 CHAR (7), FOREIGN KEY (C1) REFERENCES SUN.COMMODITY (C_NAME));")
(sql "CREATE TABLE CPBASE (KC INT NOT NULL, JUNK1 CHAR (10), PRIMARY KEY (KC));")
(sql "CREATE TABLE CPREF (KCR INT, JUNK2 CHAR (10), FOREIGN KEY (KCR) REFERENCES CPBASE);")
(sql "CREATE TABLE FOUR_TYPES (T_INT INTEGER, T_CHAR CHAR(10), T_DECIMAL DECIMAL(10,2), T_REAL REAL);")
(princ "OK]")
(terpri)


;** schema\schem11.smi
;**
;** This SDL file requires Features 5, 6, 17, and 20 of Transitional SQL.
;** It also uses the Integrity Enhancement Feature of Entry SQL.

;(sql "CREATE TABLE HYDROGRAPHY.STATIONS (STATION_ID DEC (7), DCP INT CHECK (DCP >= 0), STATION_NAME VARCHAR (40), DEG_LATITUDE  CHAR (8) NOT NULL, DEG_LONGITUDE CHAR (9) NOT NULL, MERIDIAN INTERVAL HOUR TO MINUTE CHECK (MERIDIAN BETWEEN INTERVAL -'12:59' HOUR TO MINUTE AND INTERVAL '13:00' HOUR TO MINUTE), FEET_MLLW FLOAT, KNOTS_PERM_CURRENT FLOAT, PRIMARY KEY (STATION_ID, DCP))")



;** schema\cts5sch1.sql
;**
;** This file defines the base tables needed for some INFORMATION_SCHEMA tests.
(princ "[Executing SQL Test suite\\schema\\cts5sch1.sql ...")
(sql "SCHEMA CTS2;")
(sql "CREATE TABLE PROJ_MAN (P_REF CHAR(3) NOT NULL UNIQUE, BUDGET DECIMAL(20), SCOPE CHAR(20), MGR CHAR(15) UNIQUE);")
(princ "OK]")
(terpri)


;** schema\cts5sch2.sql
;**
;** This file defines the base tables needed for some INFORMATION_SCHEMA tests.
(princ "[Executing SQL Test suite\\schema\\cts5sch2.sql ...")
(sql "SCHEMA CTS1;")
(sql "CREATE TABLE ECCO (C1 CHAR(2));")
(sql "CREATE TABLE FIPS1 (FIPS_TEST CHAR(20));")
(sql "CREATE TABLE STAFF (EMPNUM CHAR(3) NOT NULL UNIQUE, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15));")
(sql "CREATE TABLE WORKS (EMPNUM CHAR(3) NOT NULL, PNUM CHAR(3) NOT NULL, HOURS DECIMAL(5), UNIQUE(EMPNUM,PNUM));")
(sql "CREATE TABLE STAFF1 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15));")
(sql "CREATE TABLE STAFF4 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15));")
(sql "CREATE TABLE VTABLE (COL1 INTEGER, COL2 INTEGER, COL3 INTEGER, COL4 INTEGER, COL5 DECIMAL(7,2));")
(sql "CREATE TABLE STAFF3 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), UNIQUE (EMPNUM));")
(sql "CREATE TABLE PROJ3 (PNUM CHAR(3) NOT NULL, PNAME CHAR(20), PTYPE CHAR(6), BUDGET DECIMAL(9), CITY CHAR(15), UNIQUE (PNUM));")
;(sql "CREATE TABLE STAFF7 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), PRIMARY KEY (EMPNUM), CHECK (GRADE BETWEEN 1 AND 20));")
(sql "CREATE TABLE WORKS3a (EMPNUM CHAR(3) NOT NULL, PNUM CHAR(3) NOT NULL, HOURS DECIMAL(5), FOREIGN KEY (PNUM) REFERENCES PROJ3(PNUM));")
(sql "CREATE TABLE STAFFa ( HOURS INTEGER, SALARY DECIMAL(6), EMPNUM CHAR(3), PNUM DECIMAL(4), EMPNAME CHAR(20));")
(sql "CREATE TABLE STAFFb ( SALARY DECIMAL(6), EMPNAME CHAR(20), HOURS INTEGER, PNUM CHAR(3), CITY CHAR(15), SEX CHAR);")
(sql "CREATE TABLE STAFFc ( EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15), MGR CHAR(3), UNIQUE (EMPNUM));")
(sql "CREATE TABLE STAFFd ( EMPNUM CHAR(3) NOT NULL, GRADE DECIMAL(4), MGR CHAR(3));")
(sql "CREATE TABLE STAFF_CTS ( PNUM CHAR(3), CITY CHAR(15), GRADE DECIMAL(4), EMPNAME CHAR(20));")
(sql "CREATE TABLE STAFFz ( EMPNUM CHAR(3) REFERENCES STAFF3(EMPNUM), SALARY DECIMAL(6) CHECK (SALARY > 0));")
;(sql "CREATE TABLE PROJ_DURATION ( MONTHS INTEGER, TIME_LEFT INTEGER, EMP_HOURS INTEGER, CHECK (MONTHS > 0));")
(sql "CREATE TABLE STAFF_CTS2 (EMPNUM CHAR(3) NOT NULL, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15));")
(sql "CREATE TABLE EMPLOYEES2 ( name CHAR(10), empno INTEGER);")
(sql "CREATE TABLE A ( p INTEGER, q INTEGER );")
(sql "CREATE TABLE TT (TTA INTEGER, TTB INTEGER, TTC INTEGER);")
(sql "CREATE TABLE TU (TUD CHAR(2), TUE INTEGER);")
(sql "CREATE TABLE TV (A INTEGER, B CHAR);")
(sql "CREATE TABLE TW (D CHAR, E INTEGER);")
(sql "CREATE TABLE TX (TX1 INTEGER, TX2 CHARACTER(5), TX3 CHARACTER VARYING (10));")
(sql "CREATE TABLE COMP_BUDG (P_REF CHAR(3) NOT NULL, BUDGET DECIMAL(20), HOURS INTEGER, SALARY DECIMAL(6), FOREIGN KEY (P_REF) REFERENCES CTS2.PROJ_MAN(P_REF));")
(sql "CREATE TABLE PROJ_STATUS ( MGR CHAR(15) REFERENCES CTS2.PROJ_MAN(MGR), P_REF CHAR(3), ONTIME CHAR, BUDGET DECIMAL(20), COST DECIMAL(20));")
(sql "CREATE TABLE DATA_TYPE ( NUM NUMERIC, DES DECIMAL, ING INTEGER, SMA SMALLINT, FLO FLOAT, REA REAL, DOU DOUBLE PRECISION);")
(sql "CREATE TABLE CL_DATA_TYPE (CL_CHAR CHAR(10), CL_NUM NUMERIC, CL_DEC DECIMAL, CL_REAL REAL);")
(sql "CREATE TABLE CL_EMPLOYEE (EMPNUM NUMERIC(5) PRIMARY KEY, DEPTNO CHAR(3), LOC CHAR(15), EMPNAME CHAR(20), SALARY DECIMAL(6), GRADE DECIMAL(4), HOURS DECIMAL(5));")
(sql "CREATE TABLE TEST6740A (TNUM NUMERIC(4), TCHARA CHAR(10));")
(sql "CREATE TABLE TEST6740B (TNUM NUMERIC(4), TCHARB CHAR(10));")
(sql "CREATE TABLE TEST6740C (TNUMERIC NUMERIC(4), TCHAR CHAR(10));")
(sql "CREATE TABLE TEST6840A (NUM_A NUMERIC(4), CH_A CHAR(10));")
(sql "CREATE TABLE TEST6840B (NUM_B NUMERIC(4), CH_B CHAR(10));")
(sql "CREATE TABLE TEST6840C (NUM_C1 NUMERIC(4), CH_C1 CHAR(10), NUM_C2 NUMERIC(4), CH_C2 CHAR(10));")
(sql "CREATE TABLE TEST12849B (col_num3 NUMERIC(3), PRIMARY KEY (col_num3));")
(sql "CREATE TABLE T4 (STR110 CHAR(110) NOT NULL, NUM6 NUMERIC(6) NOT NULL, COL3 CHAR(10), COL4 CHAR(20), UNIQUE(STR110,NUM6));")
(sql "CREATE TABLE TABX760 ( DEPTNO NUMERIC(5) UNIQUE NOT NULL, EMPNAME CHAR(20) UNIQUE NOT NULL, SALARY DECIMAL(7));")
(sql "CREATE TABLE CL_STANDARD ( COL_NUM1 NUMERIC(4), COL_CH1 CHAR(10), COL_NUM2 NUMERIC(4), COL_CH2 CHAR(10));")
(sql "CREATE TABLE TABLE728a ( C1 CHAR(10), C2 CHAR(10));")
(sql "CREATE TABLE TABLE728b ( COL_1 CHAR(10), COL_2 CHAR(10));")
(sql "CREATE TABLE ET (col1 CHAR(3), col2 CHAR(20), col3 DECIMAL(4), col4 CHAR(15), col5 INTEGER, col6 INTEGER);")
(sql "CREATE TABLE CONCATBUF (ZZ CHAR(240));")
(princ "OK]")
(terpri)


;** schema\xschema1.sql
;**
;** This file defines the base tables used in most of the tests. It is used for X/Open Testing only.
(princ "[Executing SQL Test suite\\schema\\xschema1.sql ...")
(sql "SCHEMA XOPEN1;")
(sql "CREATE TABLE XOPEN1.ECCO (C1 CHAR(6));")
(sql "CREATE TABLE AAA (A1 CHAR(2), A2 CHAR(2), A3 CHAR(2));")
(sql "CREATE TABLE BBB (B1 CHAR(2), B2 CHAR(2), B3 CHAR(2) NOT NULL UNIQUE);")
(sql "CREATE TABLE CCC (C1 CHAR(2), C2 CHAR(2), C3 CHAR(2));")
(sql "CREATE TABLE CHAR_TEST (COL1 CHAR(254));")
(sql "CREATE TABLE INT_TEST (COL1 INTEGER);")
(sql "CREATE TABLE SMALL_TEST (COL1 SMALLINT);")
(sql "CREATE TABLE REAL_TEST (REF CHAR(1),COL1 REAL);")
(sql "CREATE TABLE REAL3_TEST (COL1 REAL,COL2 REAL,COL3 REAL);")
(sql "CREATE TABLE DOUB_TEST (REF CHAR(1),COL1 DOUBLE PRECISION);")
(sql "CREATE TABLE DOUB3_TEST (COL1 DOUBLE PRECISION,COL2 DOUBLE PRECISION,COL3 DOUBLE PRECISION);")
(sql "CREATE TABLE FLOAT_TEST (REF CHAR(1),COL1 FLOAT);")
(sql "CREATE TABLE INDEXLIMIT(COL1 CHAR(2), COL2 CHAR(2), COL3 CHAR(2), COL4 CHAR(2), COL5 CHAR(2), COL6 CHAR(2), COL7 CHAR(2));")
(sql "CREATE TABLE WIDETABLE (WIDE CHAR(118));")
(sql "CREATE TABLE WIDETAB (WIDE1 CHAR(38), WIDE2 CHAR(38), WIDE3 CHAR(38));")
(sql "CREATE TABLE TEST_TRUNC (TEST_STRING CHAR (6));")
(sql "CREATE TABLE WARNING(TESTCHAR CHAR(6), TESTINT INTEGER);")
(sql "CREATE TABLE TV (dec3 DECIMAL(3), dec1514 DECIMAL(15,14), dec150 DECIMAL(15,0), dec1515 DECIMAL(15,15));")
(sql "CREATE TABLE TU (smint SMALLINT, dec1514 DECIMAL(15,14), integr INTEGER, dec1515 DECIMAL(15,15));")
(sql "CREATE TABLE STAFF (EMPNUM CHAR(3) NOT NULL UNIQUE, EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15));")
(sql "CREATE TABLE PROJ (PNUM CHAR(3) NOT NULL UNIQUE, PNAME CHAR(20), PTYPE CHAR(6), BUDGET DECIMAL(9), CITY CHAR(15));")
(sql "CREATE TABLE WORKS (EMPNUM CHAR(3) NOT NULL, PNUM CHAR(3) NOT NULL, HOURS DECIMAL(5), UNIQUE(EMPNUM,PNUM));")
(sql "CREATE TABLE INTS (INT1 SMALLINT NOT NULL, INT2 SMALLINT NOT NULL);")
(princ "OK]")
(terpri)


(sql "SCHEMA DEFAULT;")

;************************************ END OF sql-testcreate.lsp ************************************




