;;; ============================================================
;;; AMOS2
;;; 
;;; Author: (c) 2004 Markus Jägerskogh, UDBL
;;; $RCSfile: sql-testdataload.lsp,v $
;;; $Revision: 1.2 $ $Date: 2004/12/09 16:13:53 $
;;; $State: Exp $ $Locker:  $
;;;
;;; Description: Regression test for SQLFront - insert data
;;; =============================================================

;** sql\basetab.sql
;**
;** 
(sql "SCHEMA HU;")
(sql "DELETE FROM HU.ECCO;")
(sql "INSERT INTO HU.ECCO VALUES ('NL');")
(sql "DELETE FROM STAFF;")
(sql "DELETE FROM PROJ;")
(sql "DELETE FROM WORKS;")
(sql "INSERT INTO STAFF VALUES ('E1','Alice',12,'Deale');")
(sql "INSERT INTO STAFF VALUES ('E2','Betty',10,'Vienna');")
(sql "INSERT INTO STAFF VALUES ('E3','Carmen',13,'Vienna');")
(sql "INSERT INTO STAFF VALUES ('E4','Don',12,'Deale');")
(sql "INSERT INTO STAFF VALUES ('E5','Ed',13,'Akron');")
(sql "INSERT INTO PROJ VALUES ('P1','MXSS','Design',10000,'Deale');")
(sql "INSERT INTO PROJ VALUES ('P2','CALM','Code',30000,'Vienna');")
(sql "INSERT INTO PROJ VALUES ('P3','SDP','Test',30000,'Tampa');")
(sql "INSERT INTO PROJ VALUES ('P4','SDP','Design',20000,'Deale');")
(sql "INSERT INTO PROJ VALUES ('P5','IRM','Test',10000,'Vienna');")
(sql "INSERT INTO PROJ VALUES ('P6','PAYR','Design',50000,'Deale');")
(sql "INSERT INTO WORKS VALUES ('E1','P1',40);")
(sql "INSERT INTO WORKS VALUES ('E1','P2',20);")
(sql "INSERT INTO WORKS VALUES ('E1','P3',80);")
(sql "INSERT INTO WORKS VALUES ('E1','P4',20);")
(sql "INSERT INTO WORKS VALUES ('E1','P5',12);")
(sql "INSERT INTO WORKS VALUES ('E1','P6',12);")
(sql "INSERT INTO WORKS VALUES ('E2','P1',40);")
(sql "INSERT INTO WORKS VALUES ('E2','P2',80);")
(sql "INSERT INTO WORKS VALUES ('E3','P2',20);")
(sql "INSERT INTO WORKS VALUES ('E4','P2',20);")
(sql "INSERT INTO WORKS VALUES ('E4','P4',40);")
(sql "INSERT INTO WORKS VALUES ('E4','P5',80);")
(sql "COMMIT WORK;")
(checkequal "SQL Test suite\\sql\\basetab.sql"
  ((sql "SELECT COUNT(*) FROM PROJ;") '((6)))
  ((sql "SELECT COUNT(*) FROM STAFF;") '((5)))
  ((sql "SELECT COUNT(*) FROM WORKS;") '((12)))
)
(sql "DELETE FROM STAFF3;")
(sql "DELETE FROM VTABLE;")
(sql "DELETE FROM UPUNIQ;")
(sql "INSERT INTO VTABLE VALUES(10,+20,30,40,10.50);")
(sql "INSERT INTO VTABLE VALUES(0,1,2,3,4.25);")
(sql "INSERT INTO VTABLE VALUES(100,200,300,400,500.01);")
   (sql "INSERT INTO VTABLE VALUES(1000,-2000,3000,0,4000.00);") ; Instead of NULL row bellow
;"INSERT INTO VTABLE VALUES(1000,-2000,3000,NULL,4000.00);"
(sql "INSERT INTO UPUNIQ VALUES(1,'A');")
(sql "INSERT INTO UPUNIQ VALUES(2,'B');")
(sql "INSERT INTO UPUNIQ VALUES(3,'C');")
(sql "INSERT INTO UPUNIQ VALUES(4,'D');")
(sql "INSERT INTO UPUNIQ VALUES(6,'F');")
(sql "INSERT INTO UPUNIQ VALUES(8,'H');")

;** Originally: "INSERT INTO STAFF3 SELECT * FROM STAFF;"
(sql "INSERT INTO STAFF3 VALUES ('E1', 'Alice', 12.0, 'Deale'), ('E2', 'Betty', 10.0, 'Vienna'), ('E3', 'Carmen', 13.0, 'Vienna'), ('E4', 'Don', 12.0, 'Deale'), ('E5', 'Ed', 13.0, 'Akron')")
(sql "COMMIT WORK;")
(checkequal "SQL Test suite\\sql\\basetab.sql"
  ((sql "SELECT COUNT(*) FROM STAFF3;") '((5)))
  ((sql "SELECT COUNT(*) FROM VTABLE;") '((4)))
  ((sql "SELECT COUNT(*) FROM UPUNIQ;") '((6)))
)


;** sql\cugtab.sql
;**
;** Dataload Programs
(sql "SCHEMA HERD;")
(sql "DELETE FROM CUGINI.AA;")
(sql "INSERT INTO CUGINI.AA VALUES('Twenty Characters...');")
(sql "DELETE FROM CUGINI.BB;")
(sql "DELETE FROM CUGINI.CC;")
(sql "INSERT INTO CUGINI.CC VALUES('Twenty Characters...');")
(sql "DELETE FROM CUGINI.DD;")
(sql "INSERT INTO CUGINI.DD VALUES('a');")
(checkequal "SQL Test suite\\sql\\cugtab.sql"
  ((sql "SELECT COUNT(*) FROM CUGINI.AA;") '((1)))
  ((sql "SELECT COUNT(*) FROM CUGINI.BB;") '((0)))
  ((sql "SELECT COUNT(*) FROM CUGINI.CC;") '((1)))
  ((sql "SELECT COUNT(*) FROM CUGINI.DD;") '((1)))
)
(sql "COMMIT WORK;")
(sql "DELETE FROM CUGINI.EE;")
(sql "INSERT INTO CUGINI.EE VALUES(0);")
(sql "DELETE FROM CUGINI.FF;")
(sql "DELETE FROM CUGINI.GG;")
(sql "INSERT INTO CUGINI.GG VALUES(1);")
(sql "DELETE FROM CUGINI.HH;")
(sql "INSERT INTO CUGINI.HH VALUES(2);")
(checkequal "SQL Test suite\\sql\\cugtab.sql"
  ((sql "SELECT COUNT(*) FROM CUGINI.EE;") '((1)))
  ((sql "SELECT COUNT(*) FROM CUGINI.FF;") '((0)))
  ((sql "SELECT COUNT(*) FROM CUGINI.GG;") '((1)))
  ((sql "SELECT COUNT(*) FROM CUGINI.HH;") '((1)))
)
(sql "COMMIT WORK;")
(sql "DELETE FROM CUGINI.SRCH1;")
(sql "INSERT INTO CUGINI.SRCH1 VALUES (0);")
(sql "INSERT INTO CUGINI.SRCH1 VALUES (1);")
(sql "DELETE FROM CUGINI.BADG1;")
(sql "INSERT INTO CUGINI.BADG1 VALUES (2);")
(sql "DELETE FROM CUGINI.BADG2;")
(sql "INSERT INTO CUGINI.BADG2 VALUES (2);")
(checkequal "SQL Test suite\\sql\\cugtab.sql"
  ((sql "SELECT COUNT(*) FROM CUGINI.SRCH1;") '((2)))
  ((sql "SELECT COUNT(*) FROM CUGINI.BADG1;") '((1)))
  ((sql "SELECT COUNT(*) FROM CUGINI.BADG2;") '((1)))
)
(sql "COMMIT WORK;")


;** sql\flattab.sql
;**
;** Dataload Programs
(sql "SCHEMA FLATER;")
; -- This routine initializes the contents of tables:
; -- BASE_VS1, USIG and U_SIG
; -- This routine may be run at any time to re-initialize tables.
(sql "DELETE FROM BASE_VS1;")
(sql "INSERT INTO BASE_VS1 VALUES (0,1);")
(sql "INSERT INTO BASE_VS1 VALUES (1,0);")
(sql "INSERT INTO BASE_VS1 VALUES (0,0);")
(sql "INSERT INTO BASE_VS1 VALUES (1,1);")
(checkequal "SQL Test suite\\sql\\flattab.sql"
  ((sql "SELECT COUNT(*) FROM BASE_VS1;") '((4)))
)
(sql "DELETE FROM USIG;")
(sql "INSERT INTO USIG VALUES (0,2);")
(sql "INSERT INTO USIG VALUES (1,3);")
(sql "DELETE FROM U_SIG;")
(sql "INSERT INTO U_SIG VALUES (4,6);")
(sql "INSERT INTO U_SIG VALUES (5,7);")
(checkequal "SQL Test suite\\sql\\flattab.sql"
  ((sql "SELECT COUNT(*) FROM USIG;") '((2)))
  ((sql "SELECT COUNT(*) FROM U_SIG;") '((2)))
)
(sql "COMMIT WORK;")


;** sql\suntab0.sql
;**
;** Dataload Programs
(sql "SCHEMA SUN;")
; -- This routine initializes the contents of tables:
; -- STAFF, PROJ, and WORKS
; -- This routine may be run at any time to re-initialize tables.
(sql "DELETE FROM STAFF;")
(sql "DELETE FROM PROJ;")
(sql "DELETE FROM WORKS;")
(sql "INSERT INTO STAFF VALUES ('E1','Alice',12,'Deale');")
(sql "INSERT INTO STAFF VALUES ('E2','Betty',10,'Vienna');")
(sql "INSERT INTO STAFF VALUES ('E3','Carmen',13,'Vienna');")
(sql "INSERT INTO STAFF VALUES ('E4','Don',12,'Deale');")
(sql "INSERT INTO STAFF VALUES ('E5','Ed',13,'Akron');")
(sql "INSERT INTO PROJ VALUES ('P1','MXSS','Design',10000,'Deale');")
(sql "INSERT INTO PROJ VALUES ('P2','CALM','Code',30000,'Vienna');")
(sql "INSERT INTO PROJ VALUES ('P3','SDP','Test',30000,'Tampa');")
(sql "INSERT INTO PROJ VALUES ('P4','SDP','Design',20000,'Deale');")
(sql "INSERT INTO PROJ VALUES ('P5','IRM','Test',10000,'Vienna');")
(sql "INSERT INTO PROJ VALUES ('P6','PAYR','Design',50000,'Deale');")
(sql "INSERT INTO WORKS VALUES ('E1','P1',40);")
(sql "INSERT INTO WORKS VALUES ('E1','P2',20);")
(sql "INSERT INTO WORKS VALUES ('E1','P3',80);")
(sql "INSERT INTO WORKS VALUES ('E1','P4',20);")
(sql "INSERT INTO WORKS VALUES ('E1','P5',12);")
(sql "INSERT INTO WORKS VALUES ('E1','P6',12);")
(sql "INSERT INTO WORKS VALUES ('E2','P1',40);")
(sql "INSERT INTO WORKS VALUES ('E2','P2',80);")
(sql "INSERT INTO WORKS VALUES ('E3','P2',20);")
(sql "INSERT INTO WORKS VALUES ('E4','P2',20);")
(sql "INSERT INTO WORKS VALUES ('E4','P4',40);")
(sql "INSERT INTO WORKS VALUES ('E4','P5',80);")
(sql "COMMIT WORK;")
(checkequal "SQL Test suite\\sql\\suntab0.sql"
  ((sql "SELECT COUNT(*) FROM PROJ;") '((6)))
  ((sql "SELECT COUNT(*) FROM STAFF;") '((5)))
  ((sql "SELECT COUNT(*) FROM WORKS;") '((12)))
)
(sql "COMMIT WORK;")


;** sql\suntab1.sql
;**
;** Dataload Programs
(sql "SCHEMA SUN;")
(sql "DELETE FROM STAFF_C;")
(sql "DELETE FROM PROJ_M;")
(sql "DELETE FROM STAFF_M;")
(sql "INSERT INTO STAFF_M VALUES('E1','Alice',12,'Deale','');")
(sql "INSERT INTO STAFF_M VALUES('E2','Betty',10,'Vienna','');")
(sql "INSERT INTO STAFF_M VALUES('E3','Carmen',13,'Vienna','');")
(sql "INSERT INTO STAFF_M VALUES('E5','Don',12,'Deale','');")
(sql "INSERT INTO STAFF_M VALUES('E4','Don',12,'Deale','');")
(sql "INSERT INTO PROJ_M VALUES('P1','MXSS','Design',10000,'Deale','');")
(sql "INSERT INTO PROJ_M VALUES('P2','CALM','Code',30000,'Vienna','');")
(sql "INSERT INTO PROJ_M VALUES('P4','SDP','Design',20000,'Deale','');")
(sql "INSERT INTO PROJ_M VALUES('P3','SDP','Test',30000,'Tample','');")
(sql "INSERT INTO PROJ_M VALUES('P5','IRM','Test',10000,'Vienna','');")
(sql "INSERT INTO PROJ_M VALUES('P6','PAYR','Design',50000,'Deale','');")
(sql "UPDATE STAFF_M SET PRI_WK = 'P1' WHERE EMPNUM = 'E1';")
(sql "UPDATE STAFF_M SET PRI_WK = 'P1' WHERE EMPNUM = 'E2';")
(sql "UPDATE STAFF_M SET PRI_WK = 'P1' WHERE EMPNUM = 'E3';")
(sql "UPDATE STAFF_M SET PRI_WK = 'P2' WHERE EMPNUM = 'E4';")
(sql "UPDATE STAFF_M SET PRI_WK = 'P4' WHERE EMPNUM = 'E5';")
(sql "UPDATE PROJ_M SET MGR = 'E2' WHERE PNUM = 'P1';")
(sql "UPDATE PROJ_M SET MGR = 'E2' WHERE PNUM = 'P2';")
(sql "UPDATE PROJ_M SET MGR = 'E3' WHERE PNUM = 'P3';")
(sql "UPDATE PROJ_M SET MGR = 'E4' WHERE PNUM = 'P4';")
(sql "UPDATE PROJ_M SET MGR = 'E4' WHERE PNUM = 'P5';")
(sql "INSERT INTO STAFF_C VALUES('E1','Alice',12,'Deale','');")
(sql "INSERT INTO STAFF_C VALUES('E2','Betty',10,'Vienna','E1');")
(sql "INSERT INTO STAFF_C VALUES('E3','Carmen',13,'Vienna','E2');")
(sql "INSERT INTO STAFF_C VALUES('E4','Don',12,'Deale','E2');")
(sql "INSERT INTO STAFF_C VALUES('E5','Don',12,'Deale','E1');")
(sql "INSERT INTO STAFF_C VALUES('E6','Tom',14,'Gettysburg','E5');")
(sql "INSERT INTO STAFF_C VALUES('E7','Kingdom',18,'Gettysburg','E7');")
(sql "COMMIT WORK;")
(checkequal "SQL Test suite\\sql\\suntab1.sql"
  ((sql "SELECT COUNT(*) FROM STAFF_M;") '((5)))
  ((sql "SELECT COUNT(*) FROM PROJ_M;") '((6)))
  ((sql "SELECT COUNT(*) FROM STAFF_C;") '((7)))
)


;** sql\suntab2.sql
;**
;** Dataload Programs
(sql "SCHEMA SUN;")
; -- This routine initializes the contents of tables:
; -- SIZ1_P, SIZ1_F
; -- SIZ2_P, SIZ2_F1 through SIZ2_F10
; -- SIZ3_P1 through SIZ3_P10, SIZ3_F
; -- This routine may be run at any time to re-initialize tables.
(sql "DELETE FROM SIZ1_F;")
(sql "DELETE FROM SIZ1_P;")
(sql "DELETE FROM SIZ2_F1;")
(sql "DELETE FROM SIZ2_F2;")
(sql "DELETE FROM SIZ2_F3;")
(sql "DELETE FROM SIZ2_F4;")
(sql "DELETE FROM SIZ2_F5;")
(sql "DELETE FROM SIZ2_F6;")
(sql "DELETE FROM SIZ2_F7;")
(sql "DELETE FROM SIZ2_F8;")
(sql "DELETE FROM SIZ2_F9;")
(sql "DELETE FROM SIZ2_F10;")
(sql "DELETE FROM SIZ2_P;")
(sql "DELETE FROM SIZ3_F;")
(sql "DELETE FROM SIZ3_P1;")
(sql "DELETE FROM SIZ3_P2;")
(sql "DELETE FROM SIZ3_P3;")
(sql "DELETE FROM SIZ3_P4;")
(sql "DELETE FROM SIZ3_P5;")
(sql "DELETE FROM SIZ3_P6;")
(sql "DELETE FROM SIZ3_P7;")
(sql "DELETE FROM SIZ3_P8;")
(sql "DELETE FROM SIZ3_P9;")
(sql "DELETE FROM SIZ3_P10;")
(sql "INSERT INTO SIZ1_P VALUES('E1','TTT',1,'SSS',10,'RRR','HHH','YYY',20);")
(sql "INSERT INTO SIZ1_P VALUES('E1','TTS',1,'SSS',10,'RRR','HHH','YYY',21);")
(sql "INSERT INTO SIZ1_P VALUES('E2','TTT',1,'SSS',10,'RRR','HHH','YYY',22);")
(sql "INSERT INTO SIZ1_P VALUES('E3','TTT',1,'SSS',11,'RRR','HHH','YYY',23);")
(sql "INSERT INTO SIZ1_P VALUES('E4','TTT',2,'SSS',10,'RRR','HHH','YYY',24);")
(sql "INSERT INTO SIZ1_P VALUES('E1','TTS',3,'SSS',10,'RRR','HHH','YYY',25);")
(sql "INSERT INTO SIZ1_P VALUES('E2','TTT',1,'SSS',10,'TRR','HHH','YYY',26);")
(sql "INSERT INTO SIZ1_P VALUES('E3','TTT',4,'SSS',11,'RRR','HHH','YYY',27);")
(sql "INSERT INTO SIZ1_F VALUES('E1','TTT',1,'SSS',10,'RRR','YYY',90,20);")
(sql "INSERT INTO SIZ1_F VALUES('E1','TTS',1,'SSS',10,'RRR','YYY',91,20);")
(sql "INSERT INTO SIZ1_F VALUES('E2','TTT',1,'SSS',10,'RRR','YYY',92,20);")
(sql "INSERT INTO SIZ1_F VALUES('E3','TTT',1,'SSS',11,'RRR','YYY',93,20);")
(sql "INSERT INTO SIZ1_F VALUES('E4','TTT',2,'SSS',10,'RRR','YYY',94,20);")
(sql "INSERT INTO SIZ1_F VALUES('E1','TTS',3,'SSS',10,'RRR','YYY',95,20);")
(sql "INSERT INTO SIZ1_F VALUES('E2','TTT',1,'SSS',10,'TRR','YYY',96,20);")
(sql "INSERT INTO SIZ1_F VALUES('E2','TTT',1,'SSS',10,'TRR','YYY',97,20);")
(sql "INSERT INTO SIZ2_P VALUES (' A',' B',1,' C',2,' D',' E',3,4,5,'TTT');")
(sql "INSERT INTO SIZ2_P VALUES (' B',' C',2,' D',3,' E',' F',4,5,6,'TTT');")
(sql "INSERT INTO SIZ2_P VALUES (' C',' D',3,' E',4,' F',' G',5,6,7,'TTT');")
(sql "INSERT INTO SIZ2_P VALUES (' D',' E',4,' F',5,' G',' H',6,7,8,'TTT');")
(sql "INSERT INTO SIZ2_F1 VALUES (' A','AAA');")
(sql "INSERT INTO SIZ2_F1 VALUES (' C','AAB');")
(sql "INSERT INTO SIZ2_F1 VALUES (' C','AAC');")
(sql "INSERT INTO SIZ2_F1 VALUES (' D','AAD');")
(sql "INSERT INTO SIZ2_F2 VALUES (' E','BBA');")
(sql "INSERT INTO SIZ2_F2 VALUES (' E','BBB');")
(sql "INSERT INTO SIZ2_F2 VALUES (' C','BBC');")
(sql "INSERT INTO SIZ2_F2 VALUES (' D','BBD');")
(sql "INSERT INTO SIZ2_F3 VALUES (1,'CCA');")
(sql "INSERT INTO SIZ2_F3 VALUES (1,'CCB');")
(sql "INSERT INTO SIZ2_F3 VALUES (2,'CCC');")
(sql "INSERT INTO SIZ2_F3 VALUES (3,'CCD');")
(sql "INSERT INTO SIZ2_F4 VALUES (' E','DDA');")
(sql "INSERT INTO SIZ2_F4 VALUES (' F','DDB');")
(sql "INSERT INTO SIZ2_F4 VALUES (' C','DDC');")
(sql "INSERT INTO SIZ2_F4 VALUES (' D','DDD');")
(sql "INSERT INTO SIZ2_F5 VALUES (4,'EEA');")
(sql "INSERT INTO SIZ2_F5 VALUES (4,'EEB');")
(sql "INSERT INTO SIZ2_F5 VALUES (2,'EEC');")
(sql "INSERT INTO SIZ2_F5 VALUES (3,'EED');")
(sql "INSERT INTO SIZ2_F6 VALUES (' E','FFA');")
(sql "INSERT INTO SIZ2_F6 VALUES (' F','FFB');")
(sql "INSERT INTO SIZ2_F6 VALUES (' G','FFC');")
(sql "INSERT INTO SIZ2_F6 VALUES (' D','FFD');")
(sql "INSERT INTO SIZ2_F7 VALUES (' H','GGA');")
(sql "INSERT INTO SIZ2_F7 VALUES (' F','GGB');")
(sql "INSERT INTO SIZ2_F7 VALUES (' G','GGC');")
(sql "INSERT INTO SIZ2_F7 VALUES (' H','GGD');")
(sql "INSERT INTO SIZ2_F8 VALUES (4,'HHA');")
(sql "INSERT INTO SIZ2_F8 VALUES (4,'HHB');")
(sql "INSERT INTO SIZ2_F8 VALUES (5,'HHC');")
(sql "INSERT INTO SIZ2_F8 VALUES (3,'HHD');")
(sql "INSERT INTO SIZ2_F9 VALUES (4,'JJA');")
(sql "INSERT INTO SIZ2_F9 VALUES (4,'JJB');")
(sql "INSERT INTO SIZ2_F9 VALUES (6,'JJC');")
(sql "INSERT INTO SIZ2_F9 VALUES (7,'JJD');")
(sql "INSERT INTO SIZ2_F10 VALUES (5,'KKA');")
(sql "INSERT INTO SIZ2_F10 VALUES (5,'KKB');")
(sql "INSERT INTO SIZ2_F10 VALUES (7,'KKC');")
(sql "INSERT INTO SIZ2_F10 VALUES (8,'KKD');")
(sql "INSERT INTO SIZ3_P1 VALUES (' A','AAA');")
(sql "INSERT INTO SIZ3_P1 VALUES (' B','AAB');")
(sql "INSERT INTO SIZ3_P1 VALUES (' C','AAC');")
(sql "INSERT INTO SIZ3_P1 VALUES (' D','AAD');")
(sql "INSERT INTO SIZ3_P2 VALUES (' B','BBA');")
(sql "INSERT INTO SIZ3_P2 VALUES (' C','BBB');")
(sql "INSERT INTO SIZ3_P2 VALUES (' D','BBC');")
(sql "INSERT INTO SIZ3_P2 VALUES (' E','BBD');")
(sql "INSERT INTO SIZ3_P3 VALUES (1,'CCA');")
(sql "INSERT INTO SIZ3_P3 VALUES (2,'CCB');")
(sql "INSERT INTO SIZ3_P3 VALUES (3,'CCC');")
(sql "INSERT INTO SIZ3_P3 VALUES (4,'CCD');")
(sql "INSERT INTO SIZ3_P4 VALUES (' E','DDA');")
(sql "INSERT INTO SIZ3_P4 VALUES (' F','DDB');")
(sql "INSERT INTO SIZ3_P4 VALUES (' C','DDC');")
(sql "INSERT INTO SIZ3_P4 VALUES (' D','DDD');")
(sql "INSERT INTO SIZ3_P5 VALUES (4,'EEA');")
(sql "INSERT INTO SIZ3_P5 VALUES (5,'EEB');")
(sql "INSERT INTO SIZ3_P5 VALUES (2,'EEC');")
(sql "INSERT INTO SIZ3_P5 VALUES (3,'EED');")
(sql "INSERT INTO SIZ3_P6 VALUES (' E','FFA');")
(sql "INSERT INTO SIZ3_P6 VALUES (' F','FFB');")
(sql "INSERT INTO SIZ3_P6 VALUES (' G','FFC');")
(sql "INSERT INTO SIZ3_P6 VALUES (' D','FFD');")
(sql "INSERT INTO SIZ3_P7 VALUES (' H','GGA');")
(sql "INSERT INTO SIZ3_P7 VALUES (' F','GGB');")
(sql "INSERT INTO SIZ3_P7 VALUES (' G','GGC');")
(sql "INSERT INTO SIZ3_P7 VALUES (' E','GGD');")
(sql "INSERT INTO SIZ3_P8 VALUES (4,'HHA');")
(sql "INSERT INTO SIZ3_P8 VALUES (6,'HHB');")
(sql "INSERT INTO SIZ3_P8 VALUES (5,'HHC');")
(sql "INSERT INTO SIZ3_P8 VALUES (3,'HHD');")
(sql "INSERT INTO SIZ3_P9 VALUES (4,'JJA');")
(sql "INSERT INTO SIZ3_P9 VALUES (5,'JJB');")
(sql "INSERT INTO SIZ3_P9 VALUES (6,'JJC');")
(sql "INSERT INTO SIZ3_P9 VALUES (7,'JJD');")
(sql "INSERT INTO SIZ3_P10 VALUES (5,'KKA');")
(sql "INSERT INTO SIZ3_P10 VALUES (6,'KKB');")
(sql "INSERT INTO SIZ3_P10 VALUES (7,'KKC');")
(sql "INSERT INTO SIZ3_P10 VALUES (8,'KKD');")
(sql "INSERT INTO SIZ3_F VALUES (' A',' B',1,' C',2,' D',' E',3,4,5,'TTT');")
(sql "INSERT INTO SIZ3_F VALUES (' B',' C',2,' D',3,' E',' F',4,5,6,'TTT');")
(sql "INSERT INTO SIZ3_F VALUES (' C',' D',3,' E',4,' F',' G',5,6,7,'TTT');")
(sql "INSERT INTO SIZ3_F VALUES (' D',' E',4,' F',5,' G',' H',6,7,8,'TTT');")
(sql "INSERT INTO SIZ3_F VALUES (' B',' B',1,' C',2,' D',' E',3,4,5,'TTT');")
(sql "INSERT INTO SIZ3_F VALUES (' C',' C',2,' D',3,' E',' F',4,5,6,'TTT');")
(sql "INSERT INTO SIZ3_F VALUES (' C',' D',3,' E',4,' F',' G',5,6,7,'TTT');")
(sql "INSERT INTO SIZ3_F VALUES (' D',' E',4,' F',5,' G',' H',6,7,8,'TTT');")
(checkequal "SQL Test suite\\sql\\suntab2.sql"
  ((sql "SELECT COUNT(*) FROM SIZ1_P;") '((8)))
  ((sql "SELECT COUNT(*) FROM SIZ1_F;") '((8)))
  ((sql "SELECT COUNT(*) FROM SIZ2_P;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ2_F1;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ2_F2;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ2_F3;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ2_F4;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ2_F5;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ2_F6;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ2_F7;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ2_F8;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ2_F9;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ2_F10;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ3_P1;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ3_P2;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ3_P3;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ3_P4;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ3_P5;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ3_P6;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ3_P7;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ3_P8;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ3_P9;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ3_P10;") '((4)))
  ((sql "SELECT COUNT(*) FROM SIZ3_F;") '((8)))
)
(sql "COMMIT WORK;")


;** sql\suntab3.sql
;**
;** Dataload Programs
(sql "SCHEMA SUN;")
(sql "DELETE FROM SUN.ECCO;")
(sql "INSERT INTO SUN.ECCO VALUES ('NL');")
(sql "DELETE FROM EXPERIENCE;")
(sql "DELETE FROM EMP;")
(sql "DELETE FROM DEPT;")
(sql "DELETE FROM STAFF_P;")
(sql "DELETE FROM PROJ_P;")
(sql "DELETE FROM ACR_SCH_P;")
(sql "INSERT INTO DEPT VALUES (12,'Computer','Charles');")
(sql "INSERT INTO DEPT VALUES (13,'Physics','Richard');")
(sql "INSERT INTO DEPT VALUES (14,'Education','Jeffersion');")
(sql "INSERT INTO DEPT VALUES (15,'English','Liss');")
(sql "INSERT INTO EMP VALUES (21,'Tom','Languages & Operating System',12,'Computer',040523);")
(sql "INSERT INTO EMP VALUES (22,'David','Database', 12,'Computer',101024);")
(sql "INSERT INTO EMP VALUES (23,'Lilian','Software Enginerring', 12,'Computer',112156);")
(sql "INSERT INTO EMP VALUES (24,'Mary','Liquid Mechanics', 13,'Physics',121245);")
(sql "INSERT INTO EMP VALUES (25,'John','Fraction', 13,'Physics',030542);")
(sql "INSERT INTO EMP VALUES (26,'Joseph','Child Education',14, 'Education',020556);")
(sql "INSERT INTO EMP VALUES (27,'Peter','Literature', 15,'English',020434);")
(sql "INSERT INTO EXPERIENCE VALUES ('Tom',040523,000046,'Teacher');")
(sql "INSERT INTO EXPERIENCE VALUES ('Tom',040523,000066,'Officer');")
(sql "INSERT INTO EXPERIENCE VALUES ('Tom',040523,000076,'Retire');")
(sql "INSERT INTO EXPERIENCE VALUES ('David',101024,000048,'Farmer');")
(sql "INSERT INTO EXPERIENCE VALUES ('David',101024,000066,'Porter');")
(sql "INSERT INTO EXPERIENCE VALUES ('Lilian',112156,000072,'Baby siter');")
(sql "INSERT INTO EXPERIENCE VALUES ('Lilian',112156,000082,'Nurse');")
(sql "INSERT INTO EXPERIENCE VALUES ('Mary',121245,000065,'Fashion Model');")
(sql "INSERT INTO EXPERIENCE VALUES ('John',030542,000064,'Actor');")
(sql "INSERT INTO EXPERIENCE VALUES ('Joseph',020556,000072,'Sportsman');")
(sql "INSERT INTO EXPERIENCE VALUES ('Joseph',020556,000072,'Teacher');")
(sql "INSERT INTO EXPERIENCE VALUES ('Peter',020434,000071,'Photographer');")
(sql "INSERT INTO EXPERIENCE VALUES ('Peter',020434,000081,'Movie Producer');")
(sql "INSERT INTO STAFF_P VALUES ('E1','Alice',12,'Deale');")
(sql "INSERT INTO STAFF_P VALUES ('E2','Betty',10,'Vienna');")
(sql "INSERT INTO STAFF_P VALUES ('E3','Carmen',13,'Vienna');")
(sql "INSERT INTO STAFF_P VALUES ('E4','Don',12,'Deale');")
(sql "INSERT INTO STAFF_P VALUES ('E5','Ed',13,'Akron');")
(sql "INSERT INTO PROJ_P VALUES ('P1','MXSS','Design',10000,'Deale');")
(sql "INSERT INTO PROJ_P VALUES ('P2','CALM','Code',30000,'Vienna');")
(sql "INSERT INTO PROJ_P VALUES ('P3','SDP','Test',30000,'Tampa');")
(sql "INSERT INTO PROJ_P VALUES ('P4','SDP','Design',20000,'Deale');")
(sql "INSERT INTO PROJ_P VALUES ('P5','IRM','Test',10000,'Vienna');")
(sql "INSERT INTO PROJ_P VALUES ('P6','PAYR','Design',50000,'Deale');")
(sql "INSERT INTO ACR_SCH_P VALUES(1,'AAA');")
(checkequal "SQL Test suite\\sql\\suntab3.sql"
  ((sql "SELECT COUNT(*) FROM DEPT;") '((4)))
  ((sql "SELECT COUNT(*) FROM EMP;") '((7)))
  ((sql "SELECT COUNT(*) FROM EXPERIENCE;") '((13)))
  ((sql "SELECT COUNT(*) FROM STAFF_P;") '((5)))
  ((sql "SELECT COUNT(*) FROM PROJ_P;") '((6)))
  ((sql "SELECT COUNT(*) FROM ACR_SCH_P;") '((1)))
)
(sql "COMMIT WORK;")


;** sql\sultab1.sql
;**
;** Dataload Programs
(sql "SCHEMA SULLIVAN;")
(sql "DELETE FROM WORKS_P;")
(sql "INSERT INTO WORKS_P VALUES ('E1','P1',40);")
(sql "INSERT INTO WORKS_P VALUES ('E1','P2',20);")
(sql "INSERT INTO WORKS_P VALUES ('E1','P3',80);")
(sql "INSERT INTO WORKS_P VALUES ('E1','P4',20);")
(sql "INSERT INTO WORKS_P VALUES ('E1','P5',12);")
(sql "INSERT INTO WORKS_P VALUES ('E1','P6',12);")
(sql "INSERT INTO WORKS_P VALUES ('E2','P1',40);")
(sql "INSERT INTO WORKS_P VALUES ('E2','P2',80);")
(sql "INSERT INTO WORKS_P VALUES ('E3','P2',20);")
(sql "INSERT INTO WORKS_P VALUES ('E4','P2',20);")
(sql "INSERT INTO WORKS_P VALUES ('E4','P4',40);")
(sql "INSERT INTO WORKS_P VALUES ('E4','P5',80);")
(sql "DELETE FROM TTT;")
(sql "INSERT INTO TTT VALUES (1,'AAA');")
(checkequal "SQL Test suite\\sql\\sultab1.sql"
  ((sql "SELECT COUNT(*) FROM WORKS_P;") '((12)))
  ((sql "SELECT COUNT(*) FROM TTT;") '((1)))
)
(sql "COMMIT WORK;")


;** sql\cts5tab.sql
;**
;** Dataload Programs: not used for Entry SQL
(sql "SCHEMA CTS1;")
(sql "ROLLBACK WORK;")
(sql "DELETE FROM CTS1.ECCO;")
(sql "INSERT INTO CTS1.ECCO VALUES ('NL');")
(sql "DELETE FROM STAFF;")
(sql "INSERT INTO STAFF VALUES ('E1','Alice',12,'Deale');")
(sql "INSERT INTO STAFF VALUES ('E2','Betty',10,'Vienna');")
(sql "INSERT INTO STAFF VALUES ('E3','Carmen',13,'Vienna');")
(sql "INSERT INTO STAFF VALUES ('E4','Don',12,'Deale');")
(sql "INSERT INTO STAFF VALUES ('E5','Ed',13,'Akron');")
(sql "DELETE FROM WORKS;")
(sql "INSERT INTO WORKS VALUES ('E1','P1',40);")
(sql "INSERT INTO WORKS VALUES ('E1','P2',20);")
(sql "INSERT INTO WORKS VALUES ('E1','P3',80);")
(sql "INSERT INTO WORKS VALUES ('E1','P4',20);")
(sql "INSERT INTO WORKS VALUES ('E1','P5',12);")
(sql "INSERT INTO WORKS VALUES ('E1','P6',12);")
(sql "INSERT INTO WORKS VALUES ('E2','P1',40);")
(sql "INSERT INTO WORKS VALUES ('E2','P2',80);")
(sql "INSERT INTO WORKS VALUES ('E3','P2',20);")
(sql "INSERT INTO WORKS VALUES ('E4','P2',20);")
(sql "INSERT INTO WORKS VALUES ('E4','P4',40);")
(sql "INSERT INTO WORKS VALUES ('E4','P5',80);")
(sql "DELETE FROM VTABLE;")
(sql "INSERT INTO VTABLE VALUES(10,+20,30,40,10.50);")
(sql "INSERT INTO VTABLE VALUES(0,1,2,3,4.25);")
(sql "INSERT INTO VTABLE VALUES(100,200,300,400,500.01);")
;  66:  ERROR: sql-parse: 'NULL'
;  (sql "INSERT INTO VTABLE VALUES(1000,-2000,3000,NULL,4000.00);
(sql "DELETE FROM CTS1.STAFFb;")
(sql "INSERT INTO CTS1.STAFFb VALUES (10000,'Fred',40,'P2','Vienna','M');")
(sql "INSERT INTO CTS1.STAFFb VALUES (10000,'Fred',40,'P2','Vienna','M');")
(sql "INSERT INTO CTS1.STAFFb VALUES (10000,'Fred',40,'P2','Vienna','M');")
(sql "INSERT INTO CTS1.STAFFb VALUES (15000,'Carmen',35,'P2','Vienna','F');")
(sql "INSERT INTO CTS1.STAFFb VALUES (15000,'Carmen',35,'P2','Vienna','F');")
(sql "INSERT INTO CTS1.STAFFb VALUES (10000,'Alice',40,'P3','Prague','F');")
(sql "INSERT INTO CTS1.STAFFb VALUES (20000,'Betty',30,'P1','Deale','F');")
(sql "INSERT INTO CTS1.STAFFb VALUES (20000,'Betty',30,'P1','Deale','F');")
(sql "INSERT INTO CTS1.STAFFb VALUES (40000,'Don',70,'P3','Prague','M');")
(sql "INSERT INTO CTS1.STAFFb VALUES (40000,'Don',70,'P3','Prague','M');")
(sql "INSERT INTO CTS1.STAFFb VALUES (40000,'Don',70,'P3','Prague','M');")
(sql "INSERT INTO CTS1.STAFFb VALUES (10000,'Ed',40,'P1','Deale','M');")
(sql "DELETE FROM CTS1.STAFFa;")
(sql "INSERT INTO CTS1.STAFFa VALUES (40,10000,'E6',2,'Fred');")
(sql "INSERT INTO CTS1.STAFFa VALUES (40,10000,'E6',2,'Fred');")
(sql "INSERT INTO CTS1.STAFFa VALUES (40,10000,'E1',3,'Alice');")
(sql "INSERT INTO CTS1.STAFFa VALUES (40,10000,'E1',3,'Alice');")
(sql "INSERT INTO CTS1.STAFFa VALUES (70,40000,'E4',3,'Don');")
(sql "INSERT INTO CTS1.STAFFa VALUES (70,40000,'E4',3,'Don');")
(sql "INSERT INTO CTS1.STAFFa VALUES (70,40000,'E4',3,'Don');")
(sql "INSERT INTO CTS1.STAFFa VALUES (30,20000,'E2',1,'Betty');")
(sql "INSERT INTO CTS1.STAFFa VALUES (60,45000,'E7',4,'Grace');")
(sql "INSERT INTO CTS1.STAFFa VALUES (60,45000,'E7',4,'Grace');")
(sql "INSERT INTO CTS1.STAFFa VALUES (30,8000,'E8',2,'Henry');")
(sql "INSERT INTO CTS1.STAFFa VALUES (15,7000,'E9',1,'Imogen');")
(sql "DELETE FROM STAFFc;")
;  122:  ERROR: sql-parse: 'NULL'
;   INSERT INTO STAFFc VALUES ('E1','Alice',12,'Deale',NULL);
(sql "INSERT INTO STAFFc VALUES ('E2','Betty',10,'Vienna','E1');")
(sql "INSERT INTO STAFFc VALUES ('E3','Carmen',13,'Vienna','E2');")
(sql "INSERT INTO STAFFc VALUES ('E4','Don',12,'Deale','E2');")
(sql "INSERT INTO STAFFc VALUES ('E5','Don',12,'Deale','E1');")
(sql "INSERT INTO STAFFc VALUES ('E6','Tom',14,'Gettysburg','E5');")
(sql "INSERT INTO STAFFc VALUES ('E7','Kingdom',18,'Gettysburg','E7');")
(sql "DELETE FROM STAFF_CTS2;")
(sql "INSERT INTO STAFF_CTS2 VALUES ('E1','Alice',12,'Deale');")
(sql "INSERT INTO STAFF_CTS2 VALUES ('E1','Alice',12,'Deale');")
(sql "INSERT INTO STAFF_CTS2 VALUES ('E2','Betty',10,'Vienna');")
(sql "INSERT INTO STAFF_CTS2 VALUES ('E3','Carmen',13,'Vienna');")
(sql "INSERT INTO STAFF_CTS2 VALUES ('E3','Carmen',13,'Vienna');")
(sql "INSERT INTO STAFF_CTS2 VALUES ('E3','Carmen',13,'Vienna');")
(sql "INSERT INTO STAFF_CTS2 VALUES ('E4','Don',12,'Deale');")
(sql "INSERT INTO STAFF_CTS2 VALUES ('E6','Don',12,'Deale');")
(sql "DELETE FROM STAFF_CTS;")
(sql "INSERT INTO STAFF_CTS VALUES ('P1','Deale',12,'Don');")
(sql "INSERT INTO STAFF_CTS VALUES ('P3','Vienna',10,'Betty');")
(sql "INSERT INTO STAFF_CTS VALUES ('P3','Vienna',10,'Betty');")
(sql "INSERT INTO STAFF_CTS VALUES ('P4','Vienna',13,'Carmen');")
(sql "INSERT INTO STAFF_CTS VALUES ('P5','Prague',15,'Ed');")
(sql "DELETE FROM EMPLOYEES2;")
(sql "INSERT INTO EMPLOYEES2 VALUES ('Atherton',1);")
(sql "INSERT INTO EMPLOYEES2 VALUES ('Botham',2);")
(sql "INSERT INTO EMPLOYEES2 VALUES ('Cowdrey',3);")
(sql "INSERT INTO EMPLOYEES2 VALUES ('Dev',4);")
(sql "INSERT INTO EMPLOYEES2 VALUES ('Edmunds',5);")
(sql "INSERT INTO EMPLOYEES2 VALUES ('Fields',6);")
(sql "INSERT INTO EMPLOYEES2 VALUES ('Gower',7);")
(sql "DELETE FROM A;")
(sql "INSERT INTO A VALUES (1, 15);")
(sql "INSERT INTO A VALUES (3, 17);")
(sql "INSERT INTO A VALUES (7, 11);")
(sql "INSERT INTO A VALUES (5, 9);")
(sql "INSERT INTO A VALUES (13, 13);")
(sql "INSERT INTO A VALUES (9, 5);")
(sql "INSERT INTO A VALUES (11, 7);")
(sql "INSERT INTO A VALUES (17, 3);")
(sql "INSERT INTO A VALUES (15, 1);")
(sql "INSERT INTO A VALUES (13, 5);")
(sql "INSERT INTO A VALUES (13, 15);")
(sql "INSERT INTO A VALUES (11, 1);")
(sql "INSERT INTO A VALUES (5, 5);")
(sql "INSERT INTO A VALUES (5, 3);")
(sql "INSERT INTO A VALUES (1, 1);")
(sql "DELETE FROM TT;")
;  216:  ERROR: SQL-INSERT: Insufficent number of arguments. Table CTS1#TT expects 3 arguments.
;   INSERT INTO TT (TTA, TTC) VALUES (1, 99);
;  218:  ERROR: SQL-INSERT: Insufficent number of arguments. Table CTS1#TT expects 3 arguments.
;   INSERT INTO TT (TTA, TTB) VALUES (2, 98);
(sql "INSERT INTO TT VALUES (3, 97, 96);")
;  222:  ERROR: SQL-INSERT: Insufficent number of arguments. Table CTS1#TT expects 3 arguments.
;     INSERT INTO TT (TTA) VALUES (4);
(sql "INSERT INTO TT VALUES (5, 42, 26);")
(sql "DELETE FROM TU;")
(sql "INSERT INTO TU VALUES ('ab', 3);")
;  230:  ERROR: SQL-INSERT: Insufficent number of arguments. Table CTS1#TU expects 2 arguments.
;     INSERT INTO TU (TUE) VALUES (5);
(sql "INSERT INTO TU VALUES ('cd', 4);")
;  234:  ERROR: SQL-INSERT: Insufficent number of arguments. Table CTS1#TU expects 2 arguments.
;     INSERT INTO TU (TUE) VALUES (11);
(sql "INSERT INTO TU VALUES ('ef', 12);")
(sql "INSERT INTO TU VALUES ('gh', 11);")
(sql "DELETE FROM TV;")
(sql "INSERT INTO TV VALUES (1,'a');")
(sql "INSERT INTO TV VALUES (2,'b');")
(sql "INSERT INTO TV VALUES (3,'c');")
(sql "INSERT INTO TV VALUES (4,'d');")
(sql "INSERT INTO TV VALUES (5,'e');")
(sql "DELETE FROM TW;")
(sql "INSERT INTO TW VALUES ('b',2);")
(sql "INSERT INTO TW VALUES ('g',1);")
(sql "INSERT INTO TW VALUES ('f',2);")
(sql "INSERT INTO TW VALUES ('h',4);")
(sql "INSERT INTO TW VALUES ('i',5);")
(sql "DELETE FROM TX;")
;  278:  ERROR: SQL-INSERT: Insufficent number of arguments. Table CTS1#TX expects 3 arguments.
;     INSERT INTO TX (TX1, TX3) VALUES (1, 'Susan');
;  280:  ERROR: SQL-INSERT: Insufficent number of arguments. Table CTS1#TX expects 3 arguments.
;     INSERT INTO TX (TX1, TX2) VALUES (2, 'lemon');
(sql "INSERT INTO TX VALUES (3, 'apple', '');")
(sql "INSERT INTO TX VALUES (4, 'melon', 'Peter');")
(sql "INSERT INTO TX VALUES (5, 'peach', 'Matthew');")
(sql "DELETE FROM TEST12849B;")
(sql "INSERT INTO TEST12849B VALUES (1);")
(sql "INSERT INTO TEST12849B VALUES (2);")
(sql "INSERT INTO TEST12849B VALUES (3);")
(sql "INSERT INTO TEST12849B VALUES (4);")
(sql "DELETE FROM TABX760;")
(sql "INSERT INTO CTS1.TABX760 VALUES (10,'SPYROS',25000);")
(sql "INSERT INTO CTS1.TABX760 VALUES (11,'ALEXIS',18000);")
(sql "INSERT INTO CTS1.TABX760 VALUES (12,'LAMBIS',9000);")
(sql "INSERT INTO CTS1.TABX760 VALUES (13,'ELENI',4000);")
(sql "INSERT INTO CTS1.TABX760 VALUES (14,'MARIOS',47000);")
(sql "INSERT INTO CTS1.TABX760 VALUES (15,'NICKOLAS',78000);")
(sql "DELETE FROM CL_STANDARD;")
(sql "INSERT INTO CTS1.CL_STANDARD VALUES (1000,'NICKOS',4000,'ATHENS');")
(sql "INSERT INTO CTS1.CL_STANDARD VALUES (1001,'MARIA',4001,'RHODES');")
(sql "INSERT INTO CTS1.CL_STANDARD VALUES (1002,'MAKIS',4002,'HANIA');")
(sql "INSERT INTO CTS1.CL_STANDARD VALUES (1003,'GEORGE',4003,'ARTA');")
(sql "INSERT INTO CTS1.CL_STANDARD VALUES (1004,'MORRIS',4004,'PARGA');")
(sql "DELETE FROM TABLE728a;")
(sql "INSERT INTO CTS1.TABLE728a VALUES ('NICKOS','GEORGE');")
(sql "INSERT INTO CTS1.TABLE728a VALUES ('HARRY','TANIA');")
;  366:  ERROR: sql-parse: 'NULL'
;     INSERT INTO CTS1.TABLE728a VALUES ('KILLER',NULL);
;  368:  ERROR: sql-parse: 'NULL'
;     INSERT INTO CTS1.TABLE728a VALUES (NULL,NULL);

; ***************** TRA BORT ALLT OM CTS1#TAB734 OM DEN INTE BEHÖVS *****************
;  370:  ERROR: getparameters: Table CTS1#TAB734 does not exist!
;     DELETE FROM TAB734;
;  
;  372:  ERROR: sql-parse: '' !'
;     INSERT INTO CTS1.TAB734 VALUES (N' !',N'* *');
;  
;  374:  ERROR: sql-parse: '' * '
;     INSERT INTO CTS1.TAB734 VALUES (N' * ',N'+ +');
;  
;  376:  ERROR: sql-parse: ''+ +'
;     INSERT INTO CTS1.TAB734 VALUES (N'+ +',N'+ +');
;  
;  378:  ERROR: sql-parse: 'NULL'
;     INSERT INTO CTS1.TAB734 VALUES (NULL,N' + ');

(sql "DELETE FROM CL_DATA_TYPE;")
(sql "INSERT INTO CTS1.CL_DATA_TYPE VALUES ('GEORGE',1,10,100);")
(sql "INSERT INTO CTS1.CL_DATA_TYPE VALUES ('NICK',2,20,200);")
(sql "INSERT INTO CTS1.CL_DATA_TYPE VALUES ('PAUL',3,30,300);")
(sql "INSERT INTO CTS1.CL_DATA_TYPE VALUES ('PETER',4,40,400);")
(sql "INSERT INTO CTS1.CL_DATA_TYPE VALUES ('KEVIN',5,50,500);")
(sql "INSERT INTO CTS1.CL_DATA_TYPE VALUES ('JASON',6,60,600);")
(sql "COMMIT WORK;")


(sql "SCHEMA DEFAULT;")

;************************************ END OF sql-testdataload.lsp ************************************

