;;; ============================================================
;;; AMOS2
;;; 
;;; Author: (c) 2011 Tore Risch, UDBL
;;; $RCSfile: testparse.lsp,v $
;;; $Revision: 1.1 $ $Date: 2011/12/30 14:24:29 $
;;; $State: Exp $ $Locker:  $
;;;
;;; Description: Testing SQL parser
;;; =============================================================
;;; $Log: testparse.lsp,v $
;;; Revision 1.1  2011/12/30 14:24:29  torer
;;; Regression testing SQL parser
;;;
;;; =============================================================

(checkequal 
 "SQL parser"
 ((sql-parse "SCHEMA HU;") '(SETQ *CURRENTSCHEMA* (QUOTE HU)))
 ((sql-parse "CREATE TABLE BASE_TESTREPORT (TESTNO CHAR(4), RESULT CHAR(4), 
      TESTTYPE CHAR(3));")
  '(SQL-CREATE-TABLE BASE_TESTREPORT ((TESTNO (CHAR 4)) 
				      (RESULT (CHAR 4)) (TESTTYPE (CHAR 3)))))
 ((sql-parse "CREATE TABLE HU.ECCO (C1 CHAR(2));")
  '(SQL-CREATE-TABLE (HU . ECCO) ((C1 (CHAR 2)))))
 ((sql-parse "CREATE TABLE STAFF (EMPNUM CHAR(3) NOT NULL UNIQUE, 
      EMPNAME CHAR(20), GRADE DECIMAL(4), CITY CHAR(15));")
  '(SQL-CREATE-TABLE STAFF ((EMPNUM (CHAR 3) NOT-NULL UNIQUE) 
			    (EMPNAME (CHAR 20)) (GRADE (DECIMAL 4)) 
			    (CITY (CHAR 15)))))
 ((sql-parse "CREATE TABLE PROJ (PNUM CHAR(3) NOT NULL UNIQUE, PNAME CHAR(20), 
      PTYPE CHAR(6), BUDGET DECIMAL(9), CITY CHAR(15));")
  '(SQL-CREATE-TABLE PROJ ((PNUM (CHAR 3) NOT-NULL UNIQUE) (PNAME (CHAR 20)) 
			   (PTYPE (CHAR 6)) (BUDGET (DECIMAL 9)) 
			   (CITY (CHAR 15)))))
 ((sql-parse "CREATE TABLE WORKS (EMPNUM CHAR(3) NOT NULL, PNUM CHAR(3) 
      NOT NULL, HOURS DECIMAL(5), UNIQUE(EMPNUM,PNUM));")
  '(SQL-CREATE-TABLE WORKS ((EMPNUM (CHAR 3) NOT-NULL) 
			    (PNUM (CHAR 3) NOT-NULL) (HOURS (DECIMAL 5)) 
			    (CONSTRAINT UNIQUE ((COLUMN NIL NIL PNUM) 
						(COLUMN NIL NIL EMPNUM))))))
 ((sql-parse "CREATE TABLE FIPS1 (FIPS_TEST CHAR(20));")
  '(SQL-CREATE-TABLE FIPS1 ((FIPS_TEST (CHAR 20)))))
 ((sql-parse "CREATE TABLE II (DOUBLETEST DOUBLE PRECISION);")
  '(SQL-CREATE-TABLE II ((DOUBLETEST (DOUBLE)))))
 ((sql-parse "CREATE TABLE LL (NUMTEST NUMERIC(13,6));")
  '(SQL-CREATE-TABLE LL ((NUMTEST (NUMERIC 13 6)))))
 ((sql-parse "CREATE TABLE SS (NUMTEST DEC(13,6));")
  '(SQL-CREATE-TABLE SS ((NUMTEST (DEC 13 6)))))
 ((sql-parse "CREATE TABLE UPUNIQ (NUMKEY DECIMAL(3) NOT NULL UNIQUE, 
      COL2 CHAR(2));")
  '(SQL-CREATE-TABLE UPUNIQ ((NUMKEY (DECIMAL 3) NOT-NULL UNIQUE) 
			     (COL2 (CHAR 2)))))  
 ((sql-parse "CREATE TABLE T118(STR118 CHAR(118) NOT NULL UNIQUE);")
  '(SQL-CREATE-TABLE T118 ((STR118 (CHAR 118) NOT-NULL UNIQUE))))
 ((sql-parse "CREATE TABLE T4(STR110 CHAR(110) NOT NULL, NUM6 NUMERIC(6) 
        NOT NULL, COL3 CHAR(10),COL4 CHAR(20), UNIQUE(STR110,NUM6));")
  '(SQL-CREATE-TABLE T4 ((STR110 (CHAR 110) NOT-NULL) 
			 (NUM6 (NUMERIC 6) NOT-NULL) (COL3 (CHAR 10)) 
			 (COL4 (CHAR 20)) 
			 (CONSTRAINT UNIQUE ((COLUMN NIL NIL NUM6) 
					     (COLUMN NIL NIL STR110))))))
 ((sql-parse "CREATE TABLE USG102 (C1 INT, C_1 INT);")
  '(SQL-CREATE-TABLE USG102 ((C1 (INT)) (C_1 (INT)))))
 ((sql-parse "CREATE TABLE WORKS3 (EMPNUM CHAR(3) NOT NULL, 
               PNUM CHAR(3) NOT NULL, HOURS DECIMAL(5), 
               FOREIGN KEY (EMPNUM) REFERENCES STAFF3(EMPNUM), 
               FOREIGN KEY (PNUM) REFERENCES PROJ3(PNUM));")
  '(SQL-CREATE-TABLE WORKS3 ((EMPNUM (CHAR 3) NOT-NULL) 
			     (PNUM (CHAR 3) NOT-NULL) (HOURS (DECIMAL 5)) 
			     (CONSTRAINT FOREIGN-KEY ((COLUMN NIL NIL EMPNUM)) 
					 REFERENCES STAFF3 
					 ((COLUMN NIL NIL EMPNUM))) 
			     (CONSTRAINT FOREIGN-KEY ((COLUMN NIL NIL PNUM)) 
					 REFERENCES PROJ3 
					 ((COLUMN NIL NIL PNUM))))))
 ((sql-parse "CREATE TABLE STAFF4 (EMPNUM CHAR(3) NOT NULL, 
              EMPNAME CHAR(20) DEFAULT NULL, GRADE DECIMAL(4) DEFAULT 0, 
              CITY CHAR(15) DEFAULT ' ');")
  '(SQL-CREATE-TABLE STAFF4 ((EMPNUM (CHAR 3) NOT-NULL) 
			     (EMPNAME (CHAR 20) (DEFAULT NULL)) 
			     (GRADE (DECIMAL 4) (DEFAULT 0)) 
			     (CITY (CHAR 15) (DEFAULT " ")))))

 ((sql-parse "CREATE TABLE DEPT (DNO DECIMAL(4) NOT NULL, 
              DNAME CHAR(20) NOT NULL, DEAN CHAR(30), PRIMARY KEY (DNO), 
              UNIQUE (DNAME));")
  '(SQL-CREATE-TABLE DEPT ((DNO (DECIMAL 4) NOT-NULL) 
			   (DNAME (CHAR 20) NOT-NULL) (DEAN (CHAR 30)) 
			   (CONSTRAINT PRIMARY-KEY (DNO)) 
			   (CONSTRAINT UNIQUE ((COLUMN NIL NIL DNAME))))))
 ((sql-parse "CREATE TABLE MID1 (P_KEY DECIMAL(4) NOT NULL UNIQUE, 
              F_KEY DECIMAL(4) REFERENCES MID1(P_KEY));")
  '(SQL-CREATE-TABLE MID1 ((P_KEY (DECIMAL 4) NOT-NULL UNIQUE) 
			   (F_KEY (DECIMAL 4) REFERENCES MID1))))
 ((sql-parse "CREATE TABLE APPROX_DEF (X_COUNT REAL DEFAULT 1.78E12, 
              Y_COUNT REAL DEFAULT -9.99E10, Z_COUNT REAL DEFAULT 3.45E-11, 
              ZZ_COUNT REAL DEFAULT -7.6777E-7);")
  '(SQL-CREATE-TABLE APPROX_DEF ((X_COUNT (REAL) (DEFAULT 1780000000000.0)) 
				 (Y_COUNT (REAL) (DEFAULT -99900000000.0)) 
				 (Z_COUNT (REAL) (DEFAULT 3.45E-011)) 
				 (ZZ_COUNT (REAL) (DEFAULT -7.6777E-007)))))
 ((sql-parse "CREATE TABLE T6118REF ( COL1 CHAR(20) NOT NULL, 
              COL2 CHAR(20) NOT NULL, COL3 CHAR(20) NOT NULL, 
              COL4 CHAR(20) NOT NULL, COL5 CHAR(23) NOT NULL, 
              COL6 NUMERIC (4) NOT NULL, STR118 CHAR(118) NOT NULL UNIQUE, 
              UNIQUE (COL1, COL2, COL4, COL3, COL5, COL6));")
  '(SQL-CREATE-TABLE T6118REF ((COL1 (CHAR 20) NOT-NULL) 
			       (COL2 (CHAR 20) NOT-NULL) 
			       (COL3 (CHAR 20) NOT-NULL) 
			       (COL4 (CHAR 20) NOT-NULL) 
			       (COL5 (CHAR 23) NOT-NULL) 
			       (COL6 (NUMERIC 4) NOT-NULL) 
			       (STR118 (CHAR 118) NOT-NULL UNIQUE) 
			       (CONSTRAINT UNIQUE ((COLUMN NIL NIL COL6) 
						   (COLUMN NIL NIL COL5) 
						   (COLUMN NIL NIL COL3) 
						   (COLUMN NIL NIL COL4) 
						   (COLUMN NIL NIL COL2) 
						   (COLUMN NIL NIL COL1))))))
 ((sql-parse "CREATE TABLE T6 (COL1 CHAR(20), COL2 CHAR(20), COL3 CHAR(20), 
              COL4 CHAR(20), COL5 CHAR(23), COL6 NUMERIC (4), 
              FOREIGN KEY (COL1, COL2, COL4, COL3, COL5, COL6) 
              REFERENCES T6118REF (COL1, COL2, COL4, COL3, COL5, COL6));")
  '(SQL-CREATE-TABLE T6 ((COL1 (CHAR 20)) (COL2 (CHAR 20)) (COL3 (CHAR 20)) 
			 (COL4 (CHAR 20)) (COL5 (CHAR 23)) (COL6 (NUMERIC 4)) 
			 (CONSTRAINT FOREIGN-KEY ((COLUMN NIL NIL COL6) 
						  (COLUMN NIL NIL COL5) 
						  (COLUMN NIL NIL COL3) 
						  (COLUMN NIL NIL COL4) 
						  (COLUMN NIL NIL COL2) 
						  (COLUMN NIL NIL COL1)) 
				     REFERENCES T6118REF 
				     ((COLUMN NIL NIL COL6) 
				      (COLUMN NIL NIL COL5) 
				      (COLUMN NIL NIL COL3) 
				      (COLUMN NIL NIL COL4) 
				      (COLUMN NIL NIL COL2) 
				      (COLUMN NIL NIL COL1))))))
 ((sql-parse "CREATE TABLE WORKS_P (EMPNUM CHAR(3) 
              REFERENCES SUN.STAFF_P(EMPNUM), PNUM CHAR(3), 
              HOURS DECIMAL(5), FOREIGN KEY (PNUM) 
              REFERENCES SUN.PROJ_P(PNUM));")
  '(SQL-CREATE-TABLE WORKS_P ((EMPNUM (CHAR 3) REFERENCES (SUN . STAFF_P)) 
			      (PNUM (CHAR 3)) (HOURS (DECIMAL 5)) 
			      (CONSTRAINT FOREIGN-KEY ((COLUMN NIL NIL PNUM)) 
					  REFERENCES (SUN . PROJ_P) 
					  ((COLUMN NIL NIL PNUM))))))
 ((sql-parse "DELETE FROM HU.ECCO;")
  '(SQL-DELETE (HU . ECCO)))
 ((sql-parse "INSERT INTO HU.ECCO VALUES ('NL');")
  '(SQL-INSERT (HU . ECCO) VALUES ("NL")))
 ((sql-parse "DELETE FROM STAFF;") '(SQL-DELETE STAFF))
 ((sql-parse "INSERT INTO STAFF VALUES ('E1','Alice',12,'Deale');")
  '(SQL-INSERT STAFF VALUES ("E1" "Alice" 12 "Deale")))
 ((sql-parse "COMMIT WORK;") '(COMMIT))
 ((sql-parse "SELECT COUNT(*) FROM STAFF3;")
  '(SQL-SELECT ((SQL_COUNT *)) FROM ((NIL STAFF3))))
 ((sql-parse "ROLLBACK WORK;") '(ROLLBACK))
 ((sql-parse "UPDATE STAFF SET GRADE = -GRADE;")
  '(SQL-UPDATE STAFF SET ((GRADE MINUS 0 (COLUMN NIL NIL GRADE)))))
 ((sql-parse "SELECT COUNT(*) FROM STAFF WHERE GRADE IN (12.0, -12.0);")
  '(SQL-SELECT ((SQL_COUNT *)) FROM ((NIL STAFF)) WHERE 
	       (IN (COLUMN NIL NIL GRADE) 12.0 -12.0)))

 ((sql-parse "SELECT CORRELATIONNAMES18.CHARS18NAME18CHARS 
              FROM CANWEPARSELENGTH18.CHARACTER18TABLE18 CORRELATIONNAMES18 
              WHERE CORRELATIONNAMES18.CHARS18NAME18CHARS = 'VAL4';")
  '(SQL-SELECT ((COLUMN NIL CORRELATIONNAMES18 CHARS18NAME18CHARS)) FROM 
	       ((NIL (CANWEPARSELENGTH18 . CHARACTER18TABLE18) 
		     CORRELATIONNAMES18)) 
	       WHERE (= (COLUMN NIL CORRELATIONNAMES18 CHARS18NAME18CHARS) 
			"VAL4")))
 ((sql-parse "UPDATE HU.WORKS SET EMPNUM = 'E8',PNUM = 'P8' 
              WHERE EMPNUM = 'E3';")
  '(SQL-UPDATE (HU . WORKS) SET ((EMPNUM . "E8") (PNUM . "P8")) 
	       (WHERE (= (COLUMN NIL NIL EMPNUM) "E3"))))
 ((sql-parse "SELECT EMPNUM, EMPNAME, GRADE, CITY FROM HU.VSTAFF3 
              WHERE EMPNUM = 'E0';")
  '(SQL-SELECT ((COLUMN NIL NIL EMPNUM) (COLUMN NIL NIL EMPNAME) 
		(COLUMN NIL NIL GRADE) (COLUMN NIL NIL CITY)) 
	       FROM ((NIL (HU . VSTAFF3))) WHERE 
	       (= (COLUMN NIL NIL EMPNUM) "E0")))
 ((sql-parse "SELECT EMPNUM,HOURS FROM WORKS WHERE PNUM='P2' 
              ORDER BY EMPNUM DESC;")
  '(SQL-SELECT ((COLUMN NIL NIL EMPNUM) (COLUMN NIL NIL HOURS)) 
	       FROM ((NIL WORKS)) WHERE (= (COLUMN NIL NIL PNUM) "P2") 
	       ORDERBY ((DESC (COLUMN NIL NIL EMPNUM)))))
 ((sql-parse "SELECT EMPNUM,HOURS FROM WORKS WHERE PNUM = 'P2' 
              ORDER BY 2 DESC,EMPNUM DESC;")
  '(SQL-SELECT ((COLUMN NIL NIL EMPNUM) (COLUMN NIL NIL HOURS)) FROM 
	       ((NIL WORKS)) WHERE (= (COLUMN NIL NIL PNUM) "P2")
	       ORDERBY ((DESC 2) (DESC (COLUMN NIL NIL EMPNUM)))))
 ((sql-parse "SELECT ALL EMPNUM FROM WORKS WHERE HOURS = 12.0;")
  '(SQL-SELECT ALL ((COLUMN NIL NIL EMPNUM)) FROM ((NIL WORKS)) WHERE 
	       (= (COLUMN NIL NIL HOURS) 12.0)))
 ((sql-parse "SELECT DISTINCT EMPNUM FROM WORKS WHERE HOURS = 12.0;")
  '(SQL-SELECT DISTINCT ((COLUMN NIL NIL EMPNUM)) FROM ((NIL WORKS)) WHERE 
	       (= (COLUMN NIL NIL HOURS) 12.0)))
 ((sql-parse "INSERT INTO TEMP_S(EMPNUM,GRADE,CITY) 
              VALUES('E23',2323.4,'China');")
  '(SQL-INSERT TEMP_S (EMPNUM GRADE CITY) VALUES ("E23" 2323.4 "China")))
 ((sql-parse "SELECT COUNT(DISTINCT HOURS) FROM WORKS;") 
  '(SQL-SELECT ((SQL_COUNTD (COLUMN NIL NIL HOURS))) FROM ((NIL WORKS))))
 ((sql-parse "SELECT SUM(ALL HOURS) FROM WORKS;")
  '(SQL-SELECT ((SQL_SUM (COLUMN NIL NIL HOURS))) FROM ((NIL WORKS))))
 ((sql-parse "SELECT SUM(HOURS)+10 FROM WORKS WHERE PNUM = 'P2';")
  '(SQL-SELECT ((PLUS (SQL_SUM (COLUMN NIL NIL HOURS)) 10)) FROM 
	       ((NIL WORKS)) WHERE (= (COLUMN NIL NIL PNUM) "P2")))
 ((sql-parse "SELECT PNUM FROM PROJ WHERE BUDGET BETWEEN 40000 AND 60000;")
  '(SQL-SELECT ((COLUMN NIL NIL PNUM)) FROM ((NIL PROJ)) WHERE 
	       (BETWEEN (COLUMN NIL NIL BUDGET) 40000 60000)))
 ((sql-parse "SELECT CITY FROM STAFF WHERE NOT(GRADE BETWEEN 12 AND 13);")
  '(SQL-SELECT ((COLUMN NIL NIL CITY)) FROM ((NIL STAFF)) WHERE 
	       (NOT (BETWEEN (COLUMN NIL NIL GRADE) 12 13))))
 ((sql-parse "SELECT WORKS.HOURS FROM WORKS WHERE WORKS.PNUM NOT IN 
              ('P1', 'P2', 'P3', 'P4', 'P5');")
  '(SQL-SELECT ((COLUMN NIL WORKS HOURS)) FROM ((NIL WORKS)) 
	       WHERE (NOT (IN (COLUMN NIL WORKS PNUM) 
			      "P1" "P2" "P3" "P4" "P5"))))
 ((sql-parse "SELECT EMPNAME FROM STAFF WHERE EMPNAME LIKE 'Al%';")
  '(SQL-SELECT ((COLUMN NIL NIL EMPNAME)) FROM ((NIL STAFF)) WHERE 
	       (LIKE (COLUMN NIL NIL EMPNAME) "Al*")))
 ((sql-parse "SELECT PNUM FROM WORKS WHERE PNUM > 'P1' GROUP BY PNUM 
              HAVING COUNT(*) > 1;")
  '(SQL-SELECT ((COLUMN NIL NIL PNUM)) FROM ((NIL WORKS)) WHERE 
	       (> (COLUMN NIL NIL PNUM) "P1") GROUPBY 
	       ((COLUMN NIL NIL PNUM)) HAVING (> (SQL_COUNT *) 1)))
 ((sql-parse "SELECT EMPNUM, PNUM, HOURS FROM WORKS GROUP BY PNUM, EMPNUM, 
              HOURS HAVING MIN(HOURS) > 12 AND MAX(HOURS) < 80;")
  '(SQL-SELECT ((COLUMN NIL NIL EMPNUM) (COLUMN NIL NIL PNUM) 
		(COLUMN NIL NIL HOURS)) FROM ((NIL WORKS)) GROUPBY 
		((COLUMN NIL NIL PNUM) (COLUMN NIL NIL EMPNUM) 
		 (COLUMN NIL NIL HOURS)) HAVING 
		(AND (> (SQL_MIN (COLUMN NIL NIL HOURS)) 12) 
		     (< (SQL_MAX (COLUMN NIL NIL HOURS)) 80))))
 ((sql-parse "SELECT PNUM FROM PROJ WHERE CITY <> 'Deale';")
  '(SQL-SELECT ((COLUMN NIL NIL PNUM)) FROM ((NIL PROJ)) WHERE 
	       (!= (COLUMN NIL NIL CITY) "Deale")))
 ((sql-parse "SELECT PNUM,AVG(HOURS),MIN(HOURS),MAX(HOURS)
              FROM WORKS GROUP BY PNUM ORDER BY PNUM;")
  '(SQL-SELECT ((COLUMN NIL NIL PNUM) (SQL_AVG (COLUMN NIL NIL HOURS)) 
		(SQL_MIN (COLUMN NIL NIL HOURS)) 
		(SQL_MAX (COLUMN NIL NIL HOURS))) 
	       FROM ((NIL WORKS)) GROUPBY ((COLUMN NIL NIL PNUM)) ORDERBY 
	       ((ASC (COLUMN NIL NIL PNUM)))))
 ((sql-parse "SELECT -MAX(DISTINCT HOURS) FROM WORKS;")
  '(SQL-SELECT ((MINUS 0 (SQL_MAX (COLUMN NIL NIL HOURS)))) 
	       FROM ((NIL WORKS))))
 ((sql-parse "SELECT +COL1+COL2 - COL3*COL4/COL1 FROM VTABLE WHERE COL1=10;")
  '(SQL-SELECT ((MINUS (PLUS (COLUMN NIL NIL COL1) (COLUMN NIL NIL COL2)) 
		       (DIV (TIMES (COLUMN NIL NIL COL3) 
				   (COLUMN NIL NIL COL4)) 
			    (COLUMN NIL NIL COL1)))) FROM ((NIL VTABLE)) 
			    WHERE (= (COLUMN NIL NIL COL1) 10)))
 ((sql-parse "SELECT COUNT(*) FROM WORKS 
              WHERE HOURS BETWEEN 11.999 AND 12 OR HOURS BETWEEN 19.999 
              AND 2.001E1;")
  '(SQL-SELECT ((SQL_COUNT *)) FROM ((NIL WORKS)) WHERE 
	       (OR (BETWEEN (COLUMN NIL NIL HOURS) 11.999 12) 
		   (BETWEEN (COLUMN NIL NIL HOURS) 19.999 20.01))))
 )