;;; SLR1-parser generated by GRM Parser Builder
;;; (C) 2001-2010, Andrej Andrejev

;;; INPUT-FN is a function returning (terminal . value) pairs
;;; or NIL when input is exhausted
;;; DATA is any data structure transmitted to the parser and visible in reduce actions

(defun turtle2ntriples-slr1-parser (input-fn data)
  (let ((stack '((^))) ; contains pairs (key . value), ^ is bottom-marker
        (input (funcall input-fn)) (delayed-input nil))
    (labels ((shift (key) ; SHIFT op
               (push (cons key (cdr input)) stack) ; push new key with input value
               (if delayed-input (progn (setq input delayed-input)
                                        (setq delayed-input nil)) ; restore input after REDUCE
                 (setq input (funcall input-fn)))) ; feed input
             (reduce (n) ; REDUCE op: returns list of n top values from stack
               (let ((values nil))
                 (dotimes (i n) (push (cdr (pop stack)) values))
                 (setq delayed-input input) ; non-terminal will be put into INPUT
                 values)))
      (do () (nil t) ; main cycle - no stop condition
       (unless input (setq input (cons '-! nil))) ; end-marker
       (selectq (caar stack) ; outer KEY switch
         (<RDF-TERM>-5.1
           (selectq (car input)
            ((COMMA SEMICOLON DOT) ; REDUCE(5) op
              (setq input (cons '<TRIPLES> (apply #'(LAMBDA (A B C) (LIST (LIST A B C))) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT) (car input)))))
         (<RDF-TERM>-7.1
           (selectq (car input)
            ((COMMA SEMICOLON DOT) ; REDUCE(7) op
              (setq input (cons '<TRIPLES> (apply #'(LAMBDA (A B C) (CONS (LIST (CAAR A) (CADAR A) C) A)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT) (car input)))))
         (<RDF-TERM>-6.1
           (selectq (car input)
            ((COMMA SEMICOLON DOT) ; REDUCE(6) op
              (setq input (cons '<TRIPLES> (apply #'(LAMBDA (A B C D) (CONS (LIST (CAAR A) C D) A)) (reduce 4)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT) (car input)))))
         (DOT-4.1
           (selectq (car input)
            ((STRING NUMBER IRI ID IRI-TAIL BLANK PREFIX -!) ; REDUCE(4) op
              (setq input (cons '<NTRIPLES> (apply #'(LAMBDA (A B C) (WHEN (CAR DATA) (DOLIST (TR (NREVERSE B)) (WHEN (APPLY (CDR DATA) TR) (FORMATL (CAR DATA) T (TERM-TO-STR (FIRST TR) A) " " (TERM-TO-STR (SECOND TR) A) " " (TERM-TO-STR (THIRD TR) A) " . ")))) A) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING NUMBER IRI ID IRI-TAIL BLANK PREFIX -!) (car input)))))
         (IRI-13.1
           (selectq (car input)
            ((COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK) ; REDUCE(13) op
              (setq input (cons '<RESOURCE> (apply #'(LAMBDA (A) (LIST (QUOTE IRI) A)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK) (car input)))))
         (IRI-TAIL-14.1
           (selectq (car input)
            ((COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK) ; REDUCE(14) op
              (setq input (cons '<RESOURCE> (apply #'(LAMBDA (A B) (LIST (QUOTE PREFIXED) A B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK) (car input)))))
         (IRI-TAIL-15.1
           (selectq (car input)
            ((COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK) ; REDUCE(15) op
              (setq input (cons '<RESOURCE> (apply #'(LAMBDA (A) (LIST (QUOTE PREFIXED) "" A)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK) (car input)))))
         (NUMBER-16.1
           (selectq (car input)
            ((COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK) ; REDUCE(16) op
              (setq input (cons '<LITERAL> (apply #'(LAMBDA (A) (LIST (QUOTE NUMBER) A)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK) (car input)))))
         (<RESOURCE>-18.1
           (selectq (car input)
            ((COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK) ; REDUCE(18) op
              (setq input (cons '<LITERAL> (apply #'(LAMBDA (A B C) (SETF (FOURTH A) C) A) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK) (car input)))))
         (LANGTAG-20.1
           (selectq (car input)
            ((DOUBLE-CAP STRING NUMBER IRI ID IRI-TAIL BLANK COMMA SEMICOLON DOT) ; REDUCE(20) op
              (setq input (cons '<STRING-LANG> (apply #'(LAMBDA (A B) (LIST (QUOTE STRING) A B NIL)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(DOUBLE-CAP STRING NUMBER IRI ID IRI-TAIL BLANK COMMA SEMICOLON DOT) (car input)))))
         (<LITERAL>-12.1
           (selectq (car input)
            ((STRING NUMBER IRI ID IRI-TAIL BLANK COMMA SEMICOLON DOT) ; REDUCE(12) op
              (setq input (cons '<RDF-TERM> (nth 0 (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING NUMBER IRI ID IRI-TAIL BLANK COMMA SEMICOLON DOT) (car input)))))
         (<RESOURCE>-11.1
           (selectq (car input)
            ((STRING NUMBER IRI ID IRI-TAIL BLANK COMMA SEMICOLON DOT) ; REDUCE(11) op
              (setq input (cons '<RDF-TERM> (nth 0 (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING NUMBER IRI ID IRI-TAIL BLANK COMMA SEMICOLON DOT) (car input)))))
         (IRI-TAIL-10.1
           (selectq (car input)
            ((STRING NUMBER IRI ID IRI-TAIL BLANK COMMA SEMICOLON DOT) ; REDUCE(10) op
              (setq input (cons '<RDF-TERM> (apply #'(LAMBDA (A B) (LIST (QUOTE BLANK) B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING NUMBER IRI ID IRI-TAIL BLANK COMMA SEMICOLON DOT) (car input)))))
         (DOT-3.1
           (selectq (car input)
            ((STRING NUMBER IRI ID IRI-TAIL BLANK PREFIX -!) ; REDUCE(3) op
              (setq input (cons '<NTRIPLES> (apply #'(LAMBDA (A B C D E) (PUTHASH "" A D) A) (reduce 5)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING NUMBER IRI ID IRI-TAIL BLANK PREFIX -!) (car input)))))
         (DOT-2.1
           (selectq (car input)
            ((STRING NUMBER IRI ID IRI-TAIL BLANK PREFIX -!) ; REDUCE(2) op
              (setq input (cons '<NTRIPLES> (apply #'(LAMBDA (A B C D E F) (PUTHASH C A E) A) (reduce 6)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING NUMBER IRI ID IRI-TAIL BLANK PREFIX -!) (car input)))))
         (^
           (selectq (car input)
            (<NTRIPLES> (shift '<NTRIPLES>-0.0-2.6-3.5-4.3)) ; REDUCE completion
            ((STRING NUMBER IRI ID IRI-TAIL BLANK PREFIX -!) ; REDUCE(1) op
              (setq input (cons '<NTRIPLES> (apply #'(LAMBDA NIL (MAKE-HASH-TABLE :TEST (FUNCTION EQUAL))) (reduce 0)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING NUMBER IRI ID IRI-TAIL BLANK PREFIX -!) (car input)))))
         (<NTRIPLES>-0.0-2.6-3.5-4.3
           (selectq (car input)
            (<RESOURCE> (shift '<RESOURCE>-11.1)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-12.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-17.1-18.3)) ; REDUCE completion
            (<TRIPLES> (shift '<TRIPLES>-4.2-6.4-7.3-8.2-9.2)) ; REDUCE completion
            (<RDF-TERM> (shift '<RDF-TERM>-5.3)) ; REDUCE completion
            (-! (return (cdar stack))) ; ACCEPT op
            (IRI (shift 'IRI-13.1)) ; SHIFT op
            (ID (shift 'ID-14.2)) ; SHIFT op
            (IRI-TAIL (shift 'IRI-TAIL-15.1)) ; SHIFT op
            (NUMBER (shift 'NUMBER-16.1)) ; SHIFT op
            (STRING (shift 'STRING-19.1-20.2)) ; SHIFT op
            (BLANK (shift 'BLANK-10.2)) ; SHIFT op
            (PREFIX (shift 'PREFIX-2.5-3.4)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(-! IRI ID IRI-TAIL NUMBER STRING BLANK PREFIX) (car input)))))
         (<RDF-TERM>-5.3
           (selectq (car input)
            (<RDF-TERM> (shift '<RDF-TERM>-5.2)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-17.1-18.3)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-12.1)) ; REDUCE completion
            (<RESOURCE> (shift '<RESOURCE>-11.1)) ; REDUCE completion
            (BLANK (shift 'BLANK-10.2)) ; SHIFT op
            (STRING (shift 'STRING-19.1-20.2)) ; SHIFT op
            (NUMBER (shift 'NUMBER-16.1)) ; SHIFT op
            (IRI-TAIL (shift 'IRI-TAIL-15.1)) ; SHIFT op
            (ID (shift 'ID-14.2)) ; SHIFT op
            (IRI (shift 'IRI-13.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(BLANK STRING NUMBER IRI-TAIL ID IRI) (car input)))))
         (<RDF-TERM>-5.2
           (selectq (car input)
            (<RDF-TERM> (shift '<RDF-TERM>-5.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-17.1-18.3)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-12.1)) ; REDUCE completion
            (<RESOURCE> (shift '<RESOURCE>-11.1)) ; REDUCE completion
            (BLANK (shift 'BLANK-10.2)) ; SHIFT op
            (STRING (shift 'STRING-19.1-20.2)) ; SHIFT op
            (NUMBER (shift 'NUMBER-16.1)) ; SHIFT op
            (IRI-TAIL (shift 'IRI-TAIL-15.1)) ; SHIFT op
            (ID (shift 'ID-14.2)) ; SHIFT op
            (IRI (shift 'IRI-13.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(BLANK STRING NUMBER IRI-TAIL ID IRI) (car input)))))
         (<TRIPLES>-4.2-6.4-7.3-8.2-9.2
           (selectq (car input)
            (COMMA (shift 'COMMA-7.2-9.1)) ; SHIFT op
            (SEMICOLON (shift 'SEMICOLON-6.3-8.1)) ; SHIFT op
            (DOT (shift 'DOT-4.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT) (car input)))))
         (COMMA-7.2-9.1
           (selectq (car input)
            (<RDF-TERM> (shift '<RDF-TERM>-7.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-17.1-18.3)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-12.1)) ; REDUCE completion
            (<RESOURCE> (shift '<RESOURCE>-11.1)) ; REDUCE completion
            ((COMMA SEMICOLON DOT) ; REDUCE(9) op
              (setq input (cons '<TRIPLES> (nth 0 (reduce 2)))))
            (BLANK (shift 'BLANK-10.2)) ; SHIFT op
            (STRING (shift 'STRING-19.1-20.2)) ; SHIFT op
            (NUMBER (shift 'NUMBER-16.1)) ; SHIFT op
            (IRI-TAIL (shift 'IRI-TAIL-15.1)) ; SHIFT op
            (ID (shift 'ID-14.2)) ; SHIFT op
            (IRI (shift 'IRI-13.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT BLANK STRING NUMBER IRI-TAIL ID IRI) (car input)))))
         (SEMICOLON-6.3-8.1
           (selectq (car input)
            (<RDF-TERM> (shift '<RDF-TERM>-6.2)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-17.1-18.3)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-12.1)) ; REDUCE completion
            (<RESOURCE> (shift '<RESOURCE>-11.1)) ; REDUCE completion
            ((COMMA SEMICOLON DOT) ; REDUCE(8) op
              (setq input (cons '<TRIPLES> (nth 0 (reduce 2)))))
            (BLANK (shift 'BLANK-10.2)) ; SHIFT op
            (STRING (shift 'STRING-19.1-20.2)) ; SHIFT op
            (NUMBER (shift 'NUMBER-16.1)) ; SHIFT op
            (IRI-TAIL (shift 'IRI-TAIL-15.1)) ; SHIFT op
            (ID (shift 'ID-14.2)) ; SHIFT op
            (IRI (shift 'IRI-13.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT BLANK STRING NUMBER IRI-TAIL ID IRI) (car input)))))
         (<RDF-TERM>-6.2
           (selectq (car input)
            (<RDF-TERM> (shift '<RDF-TERM>-6.1)) ; REDUCE completion
            (<STRING-LANG> (shift '<STRING-LANG>-17.1-18.3)) ; REDUCE completion
            (<LITERAL> (shift '<LITERAL>-12.1)) ; REDUCE completion
            (<RESOURCE> (shift '<RESOURCE>-11.1)) ; REDUCE completion
            (BLANK (shift 'BLANK-10.2)) ; SHIFT op
            (STRING (shift 'STRING-19.1-20.2)) ; SHIFT op
            (NUMBER (shift 'NUMBER-16.1)) ; SHIFT op
            (IRI-TAIL (shift 'IRI-TAIL-15.1)) ; SHIFT op
            (ID (shift 'ID-14.2)) ; SHIFT op
            (IRI (shift 'IRI-13.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(BLANK STRING NUMBER IRI-TAIL ID IRI) (car input)))))
         (ID-14.2
           (selectq (car input)
            (IRI-TAIL (shift 'IRI-TAIL-14.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI-TAIL) (car input)))))
         (<STRING-LANG>-17.1-18.3
           (selectq (car input)
            ((COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK) ; REDUCE(17) op
              (setq input (cons '<LITERAL> (nth 0 (reduce 1)))))
            (DOUBLE-CAP (shift 'DOUBLE-CAP-18.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT STRING NUMBER IRI ID IRI-TAIL BLANK DOUBLE-CAP) (car input)))))
         (DOUBLE-CAP-18.2
           (selectq (car input)
            (<RESOURCE> (shift '<RESOURCE>-18.1)) ; REDUCE completion
            (IRI (shift 'IRI-13.1)) ; SHIFT op
            (ID (shift 'ID-14.2)) ; SHIFT op
            (IRI-TAIL (shift 'IRI-TAIL-15.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI ID IRI-TAIL) (car input)))))
         (STRING-19.1-20.2
           (selectq (car input)
            ((DOUBLE-CAP STRING NUMBER IRI ID IRI-TAIL BLANK COMMA SEMICOLON DOT) ; REDUCE(19) op
              (setq input (cons '<STRING-LANG> (apply #'(LAMBDA (A) (LIST (QUOTE STRING) A NIL NIL)) (reduce 1)))))
            (LANGTAG (shift 'LANGTAG-20.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(DOUBLE-CAP STRING NUMBER IRI ID IRI-TAIL BLANK COMMA SEMICOLON DOT LANGTAG) (car input)))))
         (BLANK-10.2
           (selectq (car input)
            (IRI-TAIL (shift 'IRI-TAIL-10.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI-TAIL) (car input)))))
         (PREFIX-2.5-3.4
           (selectq (car input)
            (IRI-TAIL (shift 'IRI-TAIL-3.3)) ; SHIFT op
            (ID (shift 'ID-2.4)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI-TAIL ID) (car input)))))
         (IRI-TAIL-3.3
           (selectq (car input)
            (IRI (shift 'IRI-3.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI) (car input)))))
         (IRI-3.2
           (selectq (car input)
            (DOT (shift 'DOT-3.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(DOT) (car input)))))
         (ID-2.4
           (selectq (car input)
            (IRI-TAIL (shift 'IRI-TAIL-2.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI-TAIL) (car input)))))
         (IRI-TAIL-2.3
           (selectq (car input)
            (IRI (shift 'IRI-2.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(IRI) (car input)))))
         (IRI-2.2
           (selectq (car input)
            (DOT (shift 'DOT-2.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(DOT) (car input)))))
         (return 'INTERNAL-ERROR))))))
