# Application global resources

Application.name = GRM
Application.title = GRM GUI
Application.version = 1.0
Application.vendor = (C) 2012, Andrej Andrejev, UDBL
Application.homepage = http\://it.uu.se/
Application.description = GUI for the GRM Parser Generator
Application.vendorId = UDBL
Application.id = GRM
Application.lookAndFeel = system
