(defmacro lambda-amosfn (fno &rest args)
  `(function (lambda ,args (car (getfunction-firsttuple ,fno (list ,@args) t)))))

(defun in-sequence-p (ifn prev next)
  (equal (funcall (lambda-amosfn ifn old) prev) next))

(defun drain-buffer (pq ifn)
  (let ((out (tconc nil))
	(x (pq-pop pq)))
    (tconc out x)
    (while (and (not (pq-empty-p pq)) (in-sequence-p ifn (pq-node-key x) (pq-node-key (pq-peek pq))))
      (setf x (pq-peek pq))
      (tconc out (pq-pop pq)))
    (car out)))

(defun order-stream (stream order-fn inseq-fn key-fn timeout start-seq emitter)
  (let* ((ofn (theresolvent order-fn))
	 (ifn (if inseq-fn (theresolvent inseq-fn) (theresolvent #'never)))
	 (kfn (if key-fn (theresolvent key-fn) (theresolvent #'identity)))
	 (buffer (pq-make :key-pred (lambda-amosfn ofn e1 e2)))
	 (start (clock))
	 (last-seqno start-seq))
    (when (and timeout (minusp timeout))
      (setf timeout nil))
    (mapbag stream
	    #'(lambda (element)
		(setf element (car element))
		(when (pq-empty-p buffer) ; no timeout on empty buffer
		  (setf start (clock)))
		(when (and timeout (not (pq-empty-p buffer)) (> (- (clock) start) timeout))
		  (mapc #'(lambda (pqn)
			    (setf last-seqno (pq-node-key pqn))
			    (funcall emitter pqn))
			(pq-pop-all buffer))
		  (setf start (clock)))
		(if (null element)
		    (funcall emitter element)
		    (let ((seqno (funcall (lambda-amosfn kfn x) element)))
		      (cond ((or (null last-seqno) ; case 1, output w/ empty buffer
				 (and (pq-empty-p buffer) 
				      (in-sequence-p ifn last-seqno seqno)))
			     (setf start (clock))
			     (setf last-seqno seqno)
			     (funcall emitter element))
			    ((and (not (pq-empty-p buffer)) ; case 2, output & check buffer
				  (in-sequence-p ifn last-seqno seqno))
			     (pq-push buffer seqno element)
			     (mapc #'(lambda (pqn)
				       (setf last-seqno (pq-node-key pqn))
				       (funcall emitter pqn))
				   (drain-buffer buffer ifn))
			     (setf start (clock)))
			    ((funcall (lambda-amosfn ofn new old) seqno last-seqno) ; case 3, drop
			     (funcall emitter nil))
			    ((not (in-sequence-p ifn last-seqno seqno)) ; case 4, buffer
			     (pq-push buffer seqno element)
			     (funcall emitter nil))
			    (t (error "Unhandled case in order-stream!")))))))
    ;; stream ended, flush buffer
    (mapc #'(lambda (pqn)
	      (assert (not (funcall (lambda-amosfn ofn new old) (pq-node-key pqn) last-seqno)))
	      (funcall emitter pqn))
	  (pq-pop-all buffer))))

(defun order-stream------+ (fno stream order-fn inseq-fn key-fn timeout start-seq)
  (order-stream stream order-fn inseq-fn key-fn timeout start-seq
		#'(lambda (x) 
		    (if (pq-node-p x)
			(mapc #'(lambda (y)
				  (osql-result stream order-fn inseq-fn key-fn timeout start-seq y))
			      (pq-node-data x))
			(osql-result stream order-fn inseq-fn key-fn timeout start-seq x)))))

(defun order-stream-----+ (fno stream order-fn inseq-fn key-fn timeout)
  (order-stream stream order-fn inseq-fn key-fn timeout nil
		#'(lambda (x) 
		    (if (pq-node-p x)
			(mapc #'(lambda (y)
				  (osql-result stream order-fn inseq-fn key-fn timeout y))
			      (pq-node-data x))
			(osql-result stream order-fn inseq-fn key-fn timeout x)))))
