;;; SLR1-parser generated by GRM Parser Builder
;;; (C) 2001-2011, Andrej Andrejev

;;; INPUT-FN is a function returning (terminal . value) pairs
;;; or NIL when input is exhausted
;;; DATA is any data structure transmitted to the parser and visible in reduce actions

(defun sparql-slr1 (input-fn data)
  (let ((stack '((^))) ; contains pairs (key . value), ^ is bottom-marker
        (input (funcall input-fn)) (delayed-input nil))
    (flet ((shift (key) ; SHIFT op
             (push (cons key (cdr input)) stack) ; push new key with input value
             (if delayed-input (progn (setq input delayed-input)
                                      (setq delayed-input nil)) ; restore input after REDUCE
               (setq input (funcall input-fn)))) ; feed input
           (reduce (n) ; REDUCE op: returns list of n top values from stack
             (let ((values nil))
               (dotimes (i n) (push (cdr (pop stack)) values))
               (setq delayed-input input) ; non-terminal will be put into INPUT
               values)))
      (do () (nil t) ; main cycle - no stop condition
       (unless input (setq input (cons '-! nil))) ; end-marker
       (selectq (caar stack) ; outer KEY switch
         (STRING-40.1
           (selectq (car input)
            ((RIGHT-BRACE COMMA OR RIGHT-PAR AND SEMICOLON DOT GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) ; REDUCE(40) op
              (setq input (cons '<OBJECT> (apply #'(LAMBDA (A) (CONS (QUOTE STRING) A)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE COMMA OR RIGHT-PAR AND SEMICOLON DOT GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) (car input)))))
         (<URI-OR-VAR>-41.1
           (selectq (car input)
            ((RIGHT-BRACE COMMA OR RIGHT-PAR AND SEMICOLON DOT GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) ; REDUCE(41) op
              (setq input (cons '<OBJECT> (nth 0 (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE COMMA OR RIGHT-PAR AND SEMICOLON DOT GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) (car input)))))
         (<OBJECT>-39.1
           (selectq (car input)
            ((COMMA SEMICOLON DOT RIGHT-BRACE) ; REDUCE(39) op
              (setq input (cons '<TRIPLES> (apply #'(LAMBDA (A B C) (LET ((LT (CAR (LAST A)))) (APPEND A (LIST (LIST (CAR LT) (CADR LT) C))))) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT RIGHT-BRACE) (car input)))))
         (<OBJECT>-38.1
           (selectq (car input)
            ((COMMA SEMICOLON DOT RIGHT-BRACE) ; REDUCE(38) op
              (setq input (cons '<TRIPLES> (apply #'(LAMBDA (A B C D) (APPEND A (LIST (LIST (CAAR (LAST A)) C D)))) (reduce 4)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT RIGHT-BRACE) (car input)))))
         (<CONDS>-13.1
           (selectq (car input)
            ((RIGHT-BRACE) ; REDUCE(13) op
              (setq input (cons '<CONDS> (apply #'(LAMBDA (A B C) (CONS A C)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE) (car input)))))
         (<CONDS>-17.1
           (selectq (car input)
            ((RIGHT-BRACE) ; REDUCE(17) op
              (setq input (cons '<CONDS> (apply #'(LAMBDA (A B) (CONS A B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE) (car input)))))
         (<CONDS>-16.1
           (selectq (car input)
            ((RIGHT-BRACE) ; REDUCE(16) op
              (setq input (cons '<CONDS> (apply #'(LAMBDA (A B C) (CONS A C)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE) (car input)))))
         (<BLOCK>-35.1
           (selectq (car input)
            ((UNION RIGHT-BRACE URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT) ; REDUCE(35) op
              (setq input (cons '<UNION> (apply #'(LAMBDA (A B C) (LIST (QUOTE UNION) A C)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(UNION RIGHT-BRACE URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT) (car input)))))
         (<BLOCK>-36.1
           (selectq (car input)
            ((UNION RIGHT-BRACE URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT) ; REDUCE(36) op
              (setq input (cons '<UNION> (apply #'(LAMBDA (A B C) (APPEND A (LIST C))) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(UNION RIGHT-BRACE URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT) (car input)))))
         (<BLOCK>-33.1
           (selectq (car input)
            ((URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT RIGHT-BRACE) ; REDUCE(33) op
              (setq input (cons '<NONTRIPLES> (apply #'(LAMBDA (A B) (CONS (QUOTE OPTIONAL) B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT RIGHT-BRACE) (car input)))))
         (<EXPR-LIST>-32.1
           (selectq (car input)
            ((RIGHT-PAR) ; REDUCE(32) op
              (setq input (cons '<EXPR-LIST> (apply #'(LAMBDA (A B C) (CONS A C)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-PAR) (car input)))))
         (<REL-EXPR>-22.1
           (selectq (car input)
            ((AND RIGHT-PAR COMMA OR) ; REDUCE(22) op
              (setq input (cons '<CONJUNCTION> (apply #'(LAMBDA (A B C) (LIST (QUOTE AND) A C)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(AND RIGHT-PAR COMMA OR) (car input)))))
         (NOT-EQUAL-45.1
           (selectq (car input)
            ((URI VAR STRING ID NOT LEFT-PAR) ; REDUCE(45) op
              (setq input (cons '<COMPARE-OP> (apply #'(LAMBDA (A) (QUOTE !=)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR STRING ID NOT LEFT-PAR) (car input)))))
         (EQUAL-46.1
           (selectq (car input)
            ((URI VAR STRING ID NOT LEFT-PAR) ; REDUCE(46) op
              (setq input (cons '<COMPARE-OP> (apply #'(LAMBDA (A) (QUOTE =)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR STRING ID NOT LEFT-PAR) (car input)))))
         (LESS-47.1
           (selectq (car input)
            ((URI VAR STRING ID NOT LEFT-PAR) ; REDUCE(47) op
              (setq input (cons '<COMPARE-OP> (apply #'(LAMBDA (A) (QUOTE <)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR STRING ID NOT LEFT-PAR) (car input)))))
         (GREATER-48.1
           (selectq (car input)
            ((URI VAR STRING ID NOT LEFT-PAR) ; REDUCE(48) op
              (setq input (cons '<COMPARE-OP> (apply #'(LAMBDA (A) (QUOTE >)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR STRING ID NOT LEFT-PAR) (car input)))))
         (LESS-OR-EQUAL-49.1
           (selectq (car input)
            ((URI VAR STRING ID NOT LEFT-PAR) ; REDUCE(49) op
              (setq input (cons '<COMPARE-OP> (apply #'(LAMBDA (A) (QUOTE <=)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR STRING ID NOT LEFT-PAR) (car input)))))
         (GREATER-OR-EQUAL-50.1
           (selectq (car input)
            ((URI VAR STRING ID NOT LEFT-PAR) ; REDUCE(50) op
              (setq input (cons '<COMPARE-OP> (apply #'(LAMBDA (A) (QUOTE >=)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR STRING ID NOT LEFT-PAR) (car input)))))
         (<PRIME-EXPR>-25.1
           (selectq (car input)
            ((COMMA OR RIGHT-PAR AND) ; REDUCE(25) op
              (setq input (cons '<REL-EXPR> (apply #'(LAMBDA (A B C) (LIST B A C)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA OR RIGHT-PAR AND) (car input)))))
         (LOCALNAME-44.1
           (selectq (car input)
            ((URI VAR ID STRING GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL COMMA SEMICOLON DOT AND RIGHT-PAR OR RIGHT-BRACE) ; REDUCE(44) op
              (setq input (cons '<URI-OR-VAR> (apply #'(LAMBDA (A B) (LIST (QUOTE PREFIXED) A B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR ID STRING GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL COMMA SEMICOLON DOT AND RIGHT-PAR OR RIGHT-BRACE) (car input)))))
         (<FNCALL>-29.1
           (selectq (car input)
            ((AND RIGHT-PAR COMMA OR GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) ; REDUCE(29) op
              (setq input (cons '<PRIME-EXPR> (nth 0 (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(AND RIGHT-PAR COMMA OR GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) (car input)))))
         (<PRIME-EXPR>-28.1
           (selectq (car input)
            ((AND RIGHT-PAR COMMA OR GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) ; REDUCE(28) op
              (setq input (cons '<PRIME-EXPR> (apply #'(LAMBDA (A B) (LIST (QUOTE NOT) B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(AND RIGHT-PAR COMMA OR GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) (car input)))))
         (RIGHT-PAR-27.1
           (selectq (car input)
            ((AND RIGHT-PAR COMMA OR GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) ; REDUCE(27) op
              (setq input (cons '<PRIME-EXPR> (apply #'(LAMBDA (A B C) B) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(AND RIGHT-PAR COMMA OR GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) (car input)))))
         (<OBJECT>-26.1
           (selectq (car input)
            ((AND RIGHT-PAR COMMA OR GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) ; REDUCE(26) op
              (setq input (cons '<PRIME-EXPR> (nth 0 (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(AND RIGHT-PAR COMMA OR GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL) (car input)))))
         (<REL-EXPR>-23.1
           (selectq (car input)
            ((AND RIGHT-PAR COMMA OR) ; REDUCE(23) op
              (setq input (cons '<CONJUNCTION> (nth 0 (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(AND RIGHT-PAR COMMA OR) (car input)))))
         (RIGHT-PAR-30.1
           (selectq (car input)
            ((COMMA OR RIGHT-PAR AND RIGHT-BRACE GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT) ; REDUCE(30) op
              (setq input (cons '<FNCALL> (apply #'(LAMBDA (A B C D) (CONS (CONS (QUOTE ID) A) C)) (reduce 4)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA OR RIGHT-PAR AND RIGHT-BRACE GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT) (car input)))))
         (<FNCALL>-19.1
           (selectq (car input)
            ((URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT RIGHT-BRACE) ; REDUCE(19) op
              (setq input (cons '<NONTRIPLES> (apply #'(LAMBDA (A B) (CONS (QUOTE FILTER) B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT RIGHT-BRACE) (car input)))))
         (RIGHT-PAR-18.1
           (selectq (car input)
            ((URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT RIGHT-BRACE) ; REDUCE(18) op
              (setq input (cons '<NONTRIPLES> (apply #'(LAMBDA (A B C D) (CONS (QUOTE FILTER) C)) (reduce 4)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT RIGHT-BRACE) (car input)))))
         (URI-42.1
           (selectq (car input)
            ((URI VAR ID STRING GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL COMMA SEMICOLON DOT AND RIGHT-PAR OR RIGHT-BRACE) ; REDUCE(42) op
              (setq input (cons '<URI-OR-VAR> (apply #'(LAMBDA (A) (CONS (QUOTE URI) A)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR ID STRING GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL COMMA SEMICOLON DOT AND RIGHT-PAR OR RIGHT-BRACE) (car input)))))
         (VAR-43.1
           (selectq (car input)
            ((URI VAR ID STRING GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL COMMA SEMICOLON DOT AND RIGHT-PAR OR RIGHT-BRACE) ; REDUCE(43) op
              (setq input (cons '<URI-OR-VAR> (apply #'(LAMBDA (A) (CONS (QUOTE VAR) A)) (reduce 1)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR ID STRING GREATER-OR-EQUAL LESS-OR-EQUAL GREATER LESS EQUAL NOT-EQUAL COMMA SEMICOLON DOT AND RIGHT-PAR OR RIGHT-BRACE) (car input)))))
         (<OBJECT>-37.1
           (selectq (car input)
            ((COMMA SEMICOLON DOT RIGHT-BRACE) ; REDUCE(37) op
              (setq input (cons '<TRIPLES> (apply #'(LAMBDA (A B C) (LIST (QUOTE TRIPLES) (LIST A B C))) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA SEMICOLON DOT RIGHT-BRACE) (car input)))))
         (RIGHT-BRACE-10.1
           (selectq (car input)
            ((RIGHT-BRACE UNION WHERE FROM URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT -!) ; REDUCE(10) op
              (setq input (cons '<BLOCK> (apply #'(LAMBDA (A B C) (MAKE-BLOCK :CONDS B)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE UNION WHERE FROM URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT -!) (car input)))))
         (<BLOCK>-7.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(7) op
              (setq input (cons '<SELECT> (apply #'(LAMBDA (A B C) (SETF (SELECT-STAT-WHERE A) C) A) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (URI-6.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(6) op
              (setq input (cons '<SELECT> (apply #'(LAMBDA (A B C) (SETF (SELECT-STAT-FROM A) C) A) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (<BLOCK>-53.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(53) op
              (setq input (cons '<CONSTRUCT> (apply #'(LAMBDA (A B C) (SETF (CONSTRUCT-STAT-WHERE A) C) A) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (URI-52.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(52) op
              (setq input (cons '<CONSTRUCT> (apply #'(LAMBDA (A B C) (SETF (CONSTRUCT-STAT-FROM A) C) A) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (<PREFIXED-STAT>-3.1
           (selectq (car input)
            ((-!) ; REDUCE(3) op
              (setq input (cons '<PREFIXED-STAT> (apply #'(LAMBDA (A B C D E) (PUSH (CONS B D) (FIRST E)) E) (reduce 5)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(-!) (car input)))))
         (<BLOCK>-51.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(51) op
              (setq input (cons '<CONSTRUCT> (apply #'(LAMBDA (A B) (MAKE-CONSTRUCT-STAT :WHAT B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (<VAR-LIST>-5.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(5) op
              (setq input (cons '<SELECT> (apply #'(LAMBDA (A B C) (MAKE-SELECT-STAT :WHAT C :DISTINCT T)) (reduce 3)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (<VAR-LIST>-9.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(9) op
              (setq input (cons '<VAR-LIST> (apply #'(LAMBDA (A B) (CONS A B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (<VAR-LIST>-4.1
           (selectq (car input)
            ((WHERE FROM -!) ; REDUCE(4) op
              (setq input (cons '<SELECT> (apply #'(LAMBDA (A B) (MAKE-SELECT-STAT :WHAT B)) (reduce 2)))))
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -!) (car input)))))
         (<PREFIXED-STAT>-0.0
           (selectq (car input)
            ((-!) (return (cdar stack))) ; ACCEPT op
            (return (list 'SYNTAX-ERROR (caar stack) '(-!) (car input)))))
         (^
           (selectq (car input)
            (<PREFIXED-STAT> (shift '<PREFIXED-STAT>-0.0)) ; REDUCE completion
            (<CONSTRUCT> (shift '<CONSTRUCT>-2.1-52.3-53.3)) ; REDUCE completion
            (<SELECT> (shift '<SELECT>-1.1-6.3-7.3)) ; REDUCE completion
            (PREFIX (shift 'PREFIX-3.5)) ; SHIFT op
            (CONSTRUCT (shift 'CONSTRUCT-51.2)) ; SHIFT op
            (SELECT (shift 'SELECT-4.2-5.3)) ; SHIFT op
            ((-!) (return nil)) ; ACCEPT EMPTY INPUT
            (return (list 'SYNTAX-ERROR (caar stack) '(PREFIX CONSTRUCT SELECT) (car input)))))
         (<SELECT>-1.1-6.3-7.3
           (selectq (car input)
            ((-!) ; REDUCE(1) op
              (setq input (cons '<PREFIXED-STAT> (apply #'(LAMBDA (A) (LIST NIL A)) (reduce 1)))))
            (WHERE (shift 'WHERE-7.2)) ; SHIFT op
            (FROM (shift 'FROM-6.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(-! WHERE FROM) (car input)))))
         (WHERE-7.2
           (selectq (car input)
            (<BLOCK> (shift '<BLOCK>-7.1)) ; REDUCE completion
            (LEFT-BRACE (shift 'LEFT-BRACE-10.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-BRACE) (car input)))))
         (LEFT-BRACE-10.3
           (selectq (car input)
            (<CONDS> (shift '<CONDS>-10.2)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-37.3)) ; REDUCE completion
            (<UNION> (shift '<UNION>-34.1-36.3)) ; REDUCE completion
            (<BLOCK> (shift '<BLOCK>-35.3)) ; REDUCE completion
            (<NONTRIPLES> (shift '<NONTRIPLES>-14.2-15.1-16.3-17.2)) ; REDUCE completion
            (<TRIPLES> (shift '<TRIPLES>-11.1-12.2-13.3-38.4-39.3)) ; REDUCE completion
            (LEFT-BRACE (shift 'LEFT-BRACE-10.3)) ; SHIFT op
            (OPTIONAL (shift 'OPTIONAL-33.2)) ; SHIFT op
            (FILTER (shift 'FILTER-18.4-19.2)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (ID (shift 'ID-44.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-BRACE OPTIONAL FILTER URI VAR ID) (car input)))))
         (<TRIPLES>-11.1-12.2-13.3-38.4-39.3
           (selectq (car input)
            ((RIGHT-BRACE) ; REDUCE(11) op
              (setq input (cons '<CONDS> (apply #'(LAMBDA (A) (LIST A)) (reduce 1)))))
            (COMMA (shift 'COMMA-39.2)) ; SHIFT op
            (SEMICOLON (shift 'SEMICOLON-38.3)) ; SHIFT op
            (DOT (shift 'DOT-12.1-13.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE COMMA SEMICOLON DOT) (car input)))))
         (COMMA-39.2
           (selectq (car input)
            (<OBJECT> (shift '<OBJECT>-39.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-41.1)) ; REDUCE completion
            (STRING (shift 'STRING-40.1)) ; SHIFT op
            (ID (shift 'ID-44.2)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING ID VAR URI) (car input)))))
         (SEMICOLON-38.3
           (selectq (car input)
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-38.2)) ; REDUCE completion
            (URI (shift 'URI-42.1)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (ID (shift 'ID-44.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR ID) (car input)))))
         (<URI-OR-VAR>-38.2
           (selectq (car input)
            (<OBJECT> (shift '<OBJECT>-38.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-41.1)) ; REDUCE completion
            (STRING (shift 'STRING-40.1)) ; SHIFT op
            (ID (shift 'ID-44.2)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING ID VAR URI) (car input)))))
         (DOT-12.1-13.2
           (selectq (car input)
            (<CONDS> (shift '<CONDS>-13.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-37.3)) ; REDUCE completion
            (<UNION> (shift '<UNION>-34.1-36.3)) ; REDUCE completion
            (<BLOCK> (shift '<BLOCK>-35.3)) ; REDUCE completion
            (<NONTRIPLES> (shift '<NONTRIPLES>-14.2-15.1-16.3-17.2)) ; REDUCE completion
            (<TRIPLES> (shift '<TRIPLES>-11.1-12.2-13.3-38.4-39.3)) ; REDUCE completion
            ((RIGHT-BRACE) ; REDUCE(12) op
              (setq input (cons '<CONDS> (apply #'(LAMBDA (A B) (LIST A)) (reduce 2)))))
            (LEFT-BRACE (shift 'LEFT-BRACE-10.3)) ; SHIFT op
            (OPTIONAL (shift 'OPTIONAL-33.2)) ; SHIFT op
            (FILTER (shift 'FILTER-18.4-19.2)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (ID (shift 'ID-44.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE LEFT-BRACE OPTIONAL FILTER URI VAR ID) (car input)))))
         (<NONTRIPLES>-14.2-15.1-16.3-17.2
           (selectq (car input)
            (<CONDS> (shift '<CONDS>-17.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-37.3)) ; REDUCE completion
            (<UNION> (shift '<UNION>-34.1-36.3)) ; REDUCE completion
            (<BLOCK> (shift '<BLOCK>-35.3)) ; REDUCE completion
            (<NONTRIPLES> (shift '<NONTRIPLES>-14.2-15.1-16.3-17.2)) ; REDUCE completion
            (<TRIPLES> (shift '<TRIPLES>-11.1-12.2-13.3-38.4-39.3)) ; REDUCE completion
            ((RIGHT-BRACE) ; REDUCE(15) op
              (setq input (cons '<CONDS> (apply #'(LAMBDA (A) (LIST A)) (reduce 1)))))
            (LEFT-BRACE (shift 'LEFT-BRACE-10.3)) ; SHIFT op
            (OPTIONAL (shift 'OPTIONAL-33.2)) ; SHIFT op
            (FILTER (shift 'FILTER-18.4-19.2)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (ID (shift 'ID-44.2)) ; SHIFT op
            (DOT (shift 'DOT-14.1-16.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE LEFT-BRACE OPTIONAL FILTER URI VAR ID DOT) (car input)))))
         (DOT-14.1-16.2
           (selectq (car input)
            (<CONDS> (shift '<CONDS>-16.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-37.3)) ; REDUCE completion
            (<UNION> (shift '<UNION>-34.1-36.3)) ; REDUCE completion
            (<BLOCK> (shift '<BLOCK>-35.3)) ; REDUCE completion
            (<NONTRIPLES> (shift '<NONTRIPLES>-14.2-15.1-16.3-17.2)) ; REDUCE completion
            (<TRIPLES> (shift '<TRIPLES>-11.1-12.2-13.3-38.4-39.3)) ; REDUCE completion
            ((RIGHT-BRACE) ; REDUCE(14) op
              (setq input (cons '<CONDS> (apply #'(LAMBDA (A B) (LIST A)) (reduce 2)))))
            (LEFT-BRACE (shift 'LEFT-BRACE-10.3)) ; SHIFT op
            (OPTIONAL (shift 'OPTIONAL-33.2)) ; SHIFT op
            (FILTER (shift 'FILTER-18.4-19.2)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (ID (shift 'ID-44.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE LEFT-BRACE OPTIONAL FILTER URI VAR ID) (car input)))))
         (<BLOCK>-35.3
           (selectq (car input)
            (UNION (shift 'UNION-35.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(UNION) (car input)))))
         (UNION-35.2
           (selectq (car input)
            (<BLOCK> (shift '<BLOCK>-35.1)) ; REDUCE completion
            (LEFT-BRACE (shift 'LEFT-BRACE-10.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-BRACE) (car input)))))
         (<UNION>-34.1-36.3
           (selectq (car input)
            ((URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT RIGHT-BRACE) ; REDUCE(34) op
              (setq input (cons '<NONTRIPLES> (nth 0 (reduce 1)))))
            (UNION (shift 'UNION-36.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR ID LEFT-BRACE FILTER OPTIONAL DOT RIGHT-BRACE UNION) (car input)))))
         (UNION-36.2
           (selectq (car input)
            (<BLOCK> (shift '<BLOCK>-36.1)) ; REDUCE completion
            (LEFT-BRACE (shift 'LEFT-BRACE-10.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-BRACE) (car input)))))
         (OPTIONAL-33.2
           (selectq (car input)
            (<BLOCK> (shift '<BLOCK>-33.1)) ; REDUCE completion
            (LEFT-BRACE (shift 'LEFT-BRACE-10.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-BRACE) (car input)))))
         (FILTER-18.4-19.2
           (selectq (car input)
            (<FNCALL> (shift '<FNCALL>-19.1)) ; REDUCE completion
            (ID (shift 'ID-30.4)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-18.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(ID LEFT-PAR) (car input)))))
         (ID-30.4
           (selectq (car input)
            (LEFT-PAR (shift 'LEFT-PAR-30.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR) (car input)))))
         (LEFT-PAR-30.3
           (selectq (car input)
            (<EXPR-LIST> (shift '<EXPR-LIST>-30.2)) ; REDUCE completion
            (<REL-EXPR> (shift '<REL-EXPR>-23.1)) ; REDUCE completion
            (<OBJECT> (shift '<OBJECT>-26.1)) ; REDUCE completion
            (<FNCALL> (shift '<FNCALL>-29.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-41.1)) ; REDUCE completion
            (<PRIME-EXPR> (shift '<PRIME-EXPR>-24.1-25.3)) ; REDUCE completion
            (<CONJUNCTION> (shift '<CONJUNCTION>-21.1-22.3)) ; REDUCE completion
            (<EXPR> (shift '<EXPR>-20.3-31.1-32.3)) ; REDUCE completion
            (STRING (shift 'STRING-40.1)) ; SHIFT op
            (ID (shift 'ID-30.4-44.2)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (NOT (shift 'NOT-28.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-27.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING ID VAR URI NOT LEFT-PAR) (car input)))))
         (<EXPR>-20.3-31.1-32.3
           (selectq (car input)
            ((RIGHT-PAR) ; REDUCE(31) op
              (setq input (cons '<EXPR-LIST> (apply #'(LAMBDA (A) (LIST A)) (reduce 1)))))
            (COMMA (shift 'COMMA-32.2)) ; SHIFT op
            (OR (shift 'OR-20.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-PAR COMMA OR) (car input)))))
         (COMMA-32.2
           (selectq (car input)
            (<EXPR-LIST> (shift '<EXPR-LIST>-32.1)) ; REDUCE completion
            (<REL-EXPR> (shift '<REL-EXPR>-23.1)) ; REDUCE completion
            (<OBJECT> (shift '<OBJECT>-26.1)) ; REDUCE completion
            (<FNCALL> (shift '<FNCALL>-29.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-41.1)) ; REDUCE completion
            (<PRIME-EXPR> (shift '<PRIME-EXPR>-24.1-25.3)) ; REDUCE completion
            (<CONJUNCTION> (shift '<CONJUNCTION>-21.1-22.3)) ; REDUCE completion
            (<EXPR> (shift '<EXPR>-20.3-31.1-32.3)) ; REDUCE completion
            (STRING (shift 'STRING-40.1)) ; SHIFT op
            (ID (shift 'ID-30.4-44.2)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (NOT (shift 'NOT-28.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-27.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING ID VAR URI NOT LEFT-PAR) (car input)))))
         (OR-20.2
           (selectq (car input)
            (<PRIME-EXPR> (shift '<PRIME-EXPR>-24.1-25.3)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-41.1)) ; REDUCE completion
            (<FNCALL> (shift '<FNCALL>-29.1)) ; REDUCE completion
            (<OBJECT> (shift '<OBJECT>-26.1)) ; REDUCE completion
            (<REL-EXPR> (shift '<REL-EXPR>-23.1)) ; REDUCE completion
            (<CONJUNCTION> (shift '<CONJUNCTION>-20.1-22.3)) ; REDUCE completion
            (LEFT-PAR (shift 'LEFT-PAR-27.3)) ; SHIFT op
            (NOT (shift 'NOT-28.2)) ; SHIFT op
            (ID (shift 'ID-30.4-44.2)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (STRING (shift 'STRING-40.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR NOT ID URI VAR STRING) (car input)))))
         (<CONJUNCTION>-20.1-22.3
           (selectq (car input)
            ((COMMA OR RIGHT-PAR) ; REDUCE(20) op
              (setq input (cons '<EXPR> (apply #'(LAMBDA (A B C) (LIST (QUOTE OR) A C)) (reduce 3)))))
            (AND (shift 'AND-22.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA OR RIGHT-PAR AND) (car input)))))
         (AND-22.2
           (selectq (car input)
            (<REL-EXPR> (shift '<REL-EXPR>-22.1)) ; REDUCE completion
            (<OBJECT> (shift '<OBJECT>-26.1)) ; REDUCE completion
            (<FNCALL> (shift '<FNCALL>-29.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-41.1)) ; REDUCE completion
            (<PRIME-EXPR> (shift '<PRIME-EXPR>-24.1-25.3)) ; REDUCE completion
            (STRING (shift 'STRING-40.1)) ; SHIFT op
            (ID (shift 'ID-30.4-44.2)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (NOT (shift 'NOT-28.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-27.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING ID VAR URI NOT LEFT-PAR) (car input)))))
         (<CONJUNCTION>-21.1-22.3
           (selectq (car input)
            ((COMMA OR RIGHT-PAR) ; REDUCE(21) op
              (setq input (cons '<EXPR> (nth 0 (reduce 1)))))
            (AND (shift 'AND-22.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA OR RIGHT-PAR AND) (car input)))))
         (<PRIME-EXPR>-24.1-25.3
           (selectq (car input)
            (<COMPARE-OP> (shift '<COMPARE-OP>-25.2)) ; REDUCE completion
            ((COMMA OR RIGHT-PAR AND) ; REDUCE(24) op
              (setq input (cons '<REL-EXPR> (nth 0 (reduce 1)))))
            (NOT-EQUAL (shift 'NOT-EQUAL-45.1)) ; SHIFT op
            (EQUAL (shift 'EQUAL-46.1)) ; SHIFT op
            (LESS (shift 'LESS-47.1)) ; SHIFT op
            (GREATER (shift 'GREATER-48.1)) ; SHIFT op
            (LESS-OR-EQUAL (shift 'LESS-OR-EQUAL-49.1)) ; SHIFT op
            (GREATER-OR-EQUAL (shift 'GREATER-OR-EQUAL-50.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(COMMA OR RIGHT-PAR AND NOT-EQUAL EQUAL LESS GREATER LESS-OR-EQUAL GREATER-OR-EQUAL) (car input)))))
         (<COMPARE-OP>-25.2
           (selectq (car input)
            (<PRIME-EXPR> (shift '<PRIME-EXPR>-25.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-41.1)) ; REDUCE completion
            (<FNCALL> (shift '<FNCALL>-29.1)) ; REDUCE completion
            (<OBJECT> (shift '<OBJECT>-26.1)) ; REDUCE completion
            (LEFT-PAR (shift 'LEFT-PAR-27.3)) ; SHIFT op
            (NOT (shift 'NOT-28.2)) ; SHIFT op
            (ID (shift 'ID-30.4-44.2)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (STRING (shift 'STRING-40.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR NOT ID URI VAR STRING) (car input)))))
         (ID-30.4-44.2
           (selectq (car input)
            (LOCALNAME (shift 'LOCALNAME-44.1)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-30.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LOCALNAME LEFT-PAR) (car input)))))
         (NOT-28.2
           (selectq (car input)
            (<PRIME-EXPR> (shift '<PRIME-EXPR>-28.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-41.1)) ; REDUCE completion
            (<FNCALL> (shift '<FNCALL>-29.1)) ; REDUCE completion
            (<OBJECT> (shift '<OBJECT>-26.1)) ; REDUCE completion
            (LEFT-PAR (shift 'LEFT-PAR-27.3)) ; SHIFT op
            (NOT (shift 'NOT-28.2)) ; SHIFT op
            (ID (shift 'ID-30.4-44.2)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (STRING (shift 'STRING-40.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-PAR NOT ID URI VAR STRING) (car input)))))
         (LEFT-PAR-27.3
           (selectq (car input)
            (<REL-EXPR> (shift '<REL-EXPR>-23.1)) ; REDUCE completion
            (<OBJECT> (shift '<OBJECT>-26.1)) ; REDUCE completion
            (<FNCALL> (shift '<FNCALL>-29.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-41.1)) ; REDUCE completion
            (<PRIME-EXPR> (shift '<PRIME-EXPR>-24.1-25.3)) ; REDUCE completion
            (<CONJUNCTION> (shift '<CONJUNCTION>-21.1-22.3)) ; REDUCE completion
            (<EXPR> (shift '<EXPR>-20.3-27.2)) ; REDUCE completion
            (STRING (shift 'STRING-40.1)) ; SHIFT op
            (ID (shift 'ID-30.4-44.2)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (NOT (shift 'NOT-28.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-27.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING ID VAR URI NOT LEFT-PAR) (car input)))))
         (<EXPR>-20.3-27.2
           (selectq (car input)
            (RIGHT-PAR (shift 'RIGHT-PAR-27.1)) ; SHIFT op
            (OR (shift 'OR-20.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-PAR OR) (car input)))))
         (<EXPR-LIST>-30.2
           (selectq (car input)
            (RIGHT-PAR (shift 'RIGHT-PAR-30.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-PAR) (car input)))))
         (LEFT-PAR-18.3
           (selectq (car input)
            (<REL-EXPR> (shift '<REL-EXPR>-23.1)) ; REDUCE completion
            (<OBJECT> (shift '<OBJECT>-26.1)) ; REDUCE completion
            (<FNCALL> (shift '<FNCALL>-29.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-41.1)) ; REDUCE completion
            (<PRIME-EXPR> (shift '<PRIME-EXPR>-24.1-25.3)) ; REDUCE completion
            (<CONJUNCTION> (shift '<CONJUNCTION>-21.1-22.3)) ; REDUCE completion
            (<EXPR> (shift '<EXPR>-18.2-20.3)) ; REDUCE completion
            (STRING (shift 'STRING-40.1)) ; SHIFT op
            (ID (shift 'ID-30.4-44.2)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (NOT (shift 'NOT-28.2)) ; SHIFT op
            (LEFT-PAR (shift 'LEFT-PAR-27.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING ID VAR URI NOT LEFT-PAR) (car input)))))
         (<EXPR>-18.2-20.3
           (selectq (car input)
            (OR (shift 'OR-20.2)) ; SHIFT op
            (RIGHT-PAR (shift 'RIGHT-PAR-18.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(OR RIGHT-PAR) (car input)))))
         (ID-44.2
           (selectq (car input)
            (LOCALNAME (shift 'LOCALNAME-44.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LOCALNAME) (car input)))))
         (<URI-OR-VAR>-37.3
           (selectq (car input)
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-37.2)) ; REDUCE completion
            (URI (shift 'URI-42.1)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (ID (shift 'ID-44.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(URI VAR ID) (car input)))))
         (<URI-OR-VAR>-37.2
           (selectq (car input)
            (<OBJECT> (shift '<OBJECT>-37.1)) ; REDUCE completion
            (<URI-OR-VAR> (shift '<URI-OR-VAR>-41.1)) ; REDUCE completion
            (STRING (shift 'STRING-40.1)) ; SHIFT op
            (ID (shift 'ID-44.2)) ; SHIFT op
            (VAR (shift 'VAR-43.1)) ; SHIFT op
            (URI (shift 'URI-42.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(STRING ID VAR URI) (car input)))))
         (<CONDS>-10.2
           (selectq (car input)
            (RIGHT-BRACE (shift 'RIGHT-BRACE-10.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(RIGHT-BRACE) (car input)))))
         (FROM-6.2
           (selectq (car input)
            (URI (shift 'URI-6.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(URI) (car input)))))
         (<CONSTRUCT>-2.1-52.3-53.3
           (selectq (car input)
            ((-!) ; REDUCE(2) op
              (setq input (cons '<PREFIXED-STAT> (apply #'(LAMBDA (A) (LIST NIL A)) (reduce 1)))))
            (WHERE (shift 'WHERE-53.2)) ; SHIFT op
            (FROM (shift 'FROM-52.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(-! WHERE FROM) (car input)))))
         (WHERE-53.2
           (selectq (car input)
            (<BLOCK> (shift '<BLOCK>-53.1)) ; REDUCE completion
            (LEFT-BRACE (shift 'LEFT-BRACE-10.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-BRACE) (car input)))))
         (FROM-52.2
           (selectq (car input)
            (URI (shift 'URI-52.1)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(URI) (car input)))))
         (PREFIX-3.5
           (selectq (car input)
            (ID (shift 'ID-3.4)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(ID) (car input)))))
         (ID-3.4
           (selectq (car input)
            (LOCALNAME (shift 'LOCALNAME-3.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LOCALNAME) (car input)))))
         (LOCALNAME-3.3
           (selectq (car input)
            (URI (shift 'URI-3.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(URI) (car input)))))
         (URI-3.2
           (selectq (car input)
            (<PREFIXED-STAT> (shift '<PREFIXED-STAT>-3.1)) ; REDUCE completion
            (<CONSTRUCT> (shift '<CONSTRUCT>-2.1-52.3-53.3)) ; REDUCE completion
            (<SELECT> (shift '<SELECT>-1.1-6.3-7.3)) ; REDUCE completion
            (PREFIX (shift 'PREFIX-3.5)) ; SHIFT op
            (CONSTRUCT (shift 'CONSTRUCT-51.2)) ; SHIFT op
            (SELECT (shift 'SELECT-4.2-5.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(PREFIX CONSTRUCT SELECT) (car input)))))
         (CONSTRUCT-51.2
           (selectq (car input)
            (<BLOCK> (shift '<BLOCK>-51.1)) ; REDUCE completion
            (LEFT-BRACE (shift 'LEFT-BRACE-10.3)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(LEFT-BRACE) (car input)))))
         (SELECT-4.2-5.3
           (selectq (car input)
            (<VAR-LIST> (shift '<VAR-LIST>-4.1)) ; REDUCE completion
            (DISTINCT (shift 'DISTINCT-5.2)) ; SHIFT op
            (VAR (shift 'VAR-8.1-9.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(DISTINCT VAR) (car input)))))
         (DISTINCT-5.2
           (selectq (car input)
            (<VAR-LIST> (shift '<VAR-LIST>-5.1)) ; REDUCE completion
            (VAR (shift 'VAR-8.1-9.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(VAR) (car input)))))
         (VAR-8.1-9.2
           (selectq (car input)
            (<VAR-LIST> (shift '<VAR-LIST>-9.1)) ; REDUCE completion
            ((WHERE FROM -!) ; REDUCE(8) op
              (setq input (cons '<VAR-LIST> (apply #'(LAMBDA (A) (LIST A)) (reduce 1)))))
            (VAR (shift 'VAR-8.1-9.2)) ; SHIFT op
            (return (list 'SYNTAX-ERROR (caar stack) '(WHERE FROM -! VAR) (car input)))))
         (return 'INTERNAL-ERROR))))))
